let skafferi = ["Abborre (1)",
"Adzukibönor (8)",
"Aioli (5)",
"Ajvar (3)",
"Ale (2)",
"Alger (1)",
"Alkohol (64)",
"Almfrukt (1)",
"Ananas (28)",
"Ancho Chili (5)",
"Anis (3)",
"Ansjovis (22)",
"Apelsin (46)",
"Aprikoser (12)",
"Arborioris (1)",
"Aubergine (17)",
"Avocado (57)",
"Bacon (84)",
"Baguette (2)",
"Bakpotatis (5)",
"Bakpulver (21)",
"Baljväxter (5)",
"Bambuskott (1)",
"Banan (17)",
"Basilika (30)",
"Bearnaisesås (13)",
"Bechamelsås (1)",
"Belugalinser (16)",
"Biff (1)",
"Bikarbonat (2)",
"Björnbär (1)",
"Black Eye-bönor (1)",
"Blandfärs (7)",
"Blast och växter (38)",
"Blodapelsin (2)",
"Blodpudding (2)",
"Blomkrasse (6)",
"Blomkål (69)",
"Blåbär (8)",
"Blåklint (2)",
"Blå Potatis (1)",
"Bondbönor (8)",
"Borlottibönor (2)",
"Bourbon (2)",
"Bresaola (1)",
"Brieost (2)",
"Broccoli (73)",
"Brysselkål (9)",
"Brytbönor (3)",
"Bröd (10)",
"Bulgur (4)",
"Butternut (16)",
"Bär (8)",
"Böngroddar (2)",
"Bönor (122)",
"Cannellinibönor (7)",
"Cashewnötter (4)",
"Cashewnötter (2)",
"Caviar (11)",
"Champinjoner (85)",
"Cheddarost (5)",
"Chili (82)",
"Chipotle (17)",
"Choklad (15)",
"Chorizo (8)",
"Ciabatta (1)",
"Cider (3)",
"Citron (47)",
"Citrongräs (2)",
"Citronverbena (1)",
"Citrus (98)",
"Coca Cola (1)",
"Cognac (4)",
"Corn Flakes (2)",
"Couscous (8)",
"Crabsticks (1)",
"Creme Fraiche (23)",
"Crostini (1)",
"Cumberlandsås (1)",
"Curry (21)",
"Dadlar (4)",
"Digestivekex (4)",
"Dijonsenap (5)",
"Dill (67)",
"Dillfrö (3)",
"Dinkel (4)",
"Dragon (11)",
"Enbär (5)",
"Enokisvamp (1)",
"Entrecôte (4)",
"Falukorv (33)",
"Fetaost (116)",
"Fikon (19)",
"Filodeg (7)",
"Flankstek (7)",
"Flintastek (1)",
"Flundra (2)",
"Fläder (4)",
"Fläskfilé (19)",
"Fläskfärs (10)",
"Fläskkarré (12)",
"Fläskkotlett (8)",
"Fläsklägg (3)",
"Fläsksida (2)",
"Fläskytterfilé (7)",
"Fläskytterlår (1)",
"Fransyska (6)",
"Frukt (72)",
"Frön (83)",
"Fullkornsmjöl (5)",
"Fänkål (41)",
"Färskost (39)",
"Fårost (0)",
"Getost (60)",
"Gi (21)",
"Glass (5)",
"Glaze (2)",
"Glöggkryddor (2)",
"Grahamsmjöl (2)",
"Granatäpple (4)",
"Granskott (7)",
"Gravad Lax (2)",
"Groddar (1)",
"Grädde (43)",
"Gräddfil (2)",
"Gräslök (23)",
"Gräslöksblommor (6)",
"Gröna linser (1)",
"Grönkål (14)",
"Gröt (2)",
"Gulbetor (7)",
"Gurka (24)",
"Gurkört (1)",
"Gökärt (2)",
"Gös (2)",
"Habanero (3)",
"Hajmal/Pangasius (8)",
"Hallon (12)",
"Halloumi (34)",
"Halloweenpumpa (15)",
"Haricots Verts (34)",
"Harsyra (2)",
"Hasselnötter (14)",
"Havregryn (4)",
"Hickory (5)",
"Hirs (3)",
"Hjortron (1)",
"Hjärtsallad/Gemsallad (4)",
"Hollandaisesås (2)",
"Honung (35)",
"Hovmästarsås (1)",
"Hummer (1)",
"Högrev (19)",
"Höstsvamp (26)",
"Ingefära (14)",
"Isbergssallad (1)",
"Isterband (4)",
"Jalapeños (7)",
"Jordgubbar (20)",
"Jordnötssmör (1)",
"Jordnötter (1)",
"Jordärtskocka (14)",
"Julskinka (13)",
"Järpish (3)",
"Jäst (5)",
"Kaffe (4)",
"Kahlua (1)",
"Kakao (5)",
"Kako (1)",
"Kalkon (2)",
"Kallrökt lax (2)",
"Kalvfilé (2)",
"Kalvfärs (4)",
"Kalvribs (1)",
"Kalvstek (4)",
"Kalvsylta (1)",
"Kamben (1)",
"Kamomill (0)",
"Kanel (26)",
"Kantareller (32)",
"Kapris (49)",
"Kardemumma (5)",
"Karl Johansvamp (1)",
"Kassler (1)",
"Kavring (3)",
"Kesella (6)",
"Keso (8)",
"Ketchup (1)",
"Kidneybönor (49)",
"Kikärtor (103)",
"Kirskål (3)",
"Kivi (5)",
"Knipplök (1)",
"Kokos (11)",
"Kokosmjölk (7)",
"Kokossocker (1)",
"Koriander (64)",
"Korvish (2)",
"Krabba (2)",
"Kronärtskocka (9)",
"Krossade tomater (51)",
"Krustader (2)",
"Kryddig korv (25)",
"Kryddor och Salt (4)",
"Kryddpeppar (2)",
"Kräftor (7)",
"Kräftstjärtar (27)",
"Kummin (15)",
"Kungskrabba (2)",
"Kyckling (104)",
"Kycklingben (1)",
"Kycklingbröst (3)",
"Kycklingfilé (62)",
"Kycklingfärs (1)",
"Kyckling hel (12)",
"Kycklingklubba (3)",
"Kycklinglår (3)",
"Kycklinglårfilé (2)",
"Kål (108)",
"Kåldolmar (2)",
"Kålrabbi (0)",
"Kålrot (13)",
"Körsbär (6)",
"Körvel (2)",
"Lakrits (21)",
"Lammfilé (5)",
"Lammfärs (6)",
"Lammkorv (7)",
"Lammkotlett (1)",
"Lammlägg (3)",
"Lammracks (4)",
"Lammrostbiff (7)",
"Lammrygg (0)",
"Lammstek (8)",
"Lasagne (6)",
"Lavendel (1)",
"Lax (78)",
"Laxsida (5)",
"LCHF (19)",
"Lemon Curd (4)",
"Leverpastej (2)",
"Libbsticka (9)",
"Lime (36)",
"Linfrön (1)",
"Lingon (9)",
"Lingonpulver (1)",
"Linser (54)",
"Luffarbiff (1)",
"Lufttorkad skinka (23)",
"Läckökorv (2)",
"Löjrom (3)",
"Lök (134)",
"Löktrav (5)",
"Lövbiff (2)",
"Machésallad (6)",
"Majonnäs (37)",
"Majrova (1)",
"Majs (54)",
"Majskolvar (10)",
"Malva (1)",
"Mandel (53)",
"Mandelmassa (1)",
"Mandelmjöl (3)",
"Mango (36)",
"Mangold (5)",
"Mannagryn (3)",
"Maräng (3)",
"Mascarpone (2)",
"Mathavre (2)",
"Matjessill (7)",
"Matlagningsyoghurt (6)",
"Matvete (6)",
"Melon (7)",
"Merguez (1)",
"Milkshake (1)",
"Mjölk (1)",
"Mjölkört/Rallarros (1)",
"Morotsblast (6)",
"Morötter (252)",
"Mozzarella (37)",
"Muffins (7)",
"Mungbönor (7)",
"Muscatpumpa (25)",
"Muscovadosocker (18)",
"Muskot (7)",
"Musslor (6)",
"Mynta (18)",
"Märgben (2)",
"Nachochips (1)",
"Nate / Våtarv (6)",
"Nejlikor (5)",
"Nektarin (13)",
"Njurtapp / Slaktarbiff (2)",
"Nori (1)",
"Norsk Fjordörret (3)",
"Nudlar (3)",
"Nypon (1)",
"Nässlor (7)",
"Nätmelon (1)",
"Nötbog (2)",
"Nötfärs (62)",
"Nötstek (4)",
"Nötter (18)",
"Nötytterfilé (0)",
"Nötytterlår (1)",
"Ogräs (17)",
"Oliver (73)",
"Ost (65)",
"Ostron (1)",
"Ostronskivling (2)",
"Oxfilé (16)",
"Oxkind (2)",
"Pajdeg (8)",
"Pajskal utan mjöl och gluten (11)",
"Pak Choi (2)",
"Palsternacka (49)",
"Pankoströbröd (11)",
"Papaya (2)",
"Paprika (125)",
"Parmesanost (33)",
"Passerade tomater (2)",
"Passionsfrukt (2)",
"Paté (2)",
"Pecorino (2)",
"Penne Rigate (1)",
"Penséer (1)",
"Pepparkakskryddor (5)",
"Pepparrot (27)",
"Persika (4)",
"Persilja (31)",
"Pesto (9)",
"Physalis (2)",
"Pilgrimsmusslor (2)",
"Pimientos de Padron (2)",
"Pinjenötter (8)",
"Pitabröd (8)",
"Pizzadeg (2)",
"Plommon (10)",
"Polenta (2)",
"Polkabetor (3)",
"Porter (6)",
"Portobello (3)",
"Portvin (5)",
"Potatis (159)",
"Primörer (16)",
"Prinskorv (4)",
"Proteinpulver (5)",
"Pulled Pork (6)",
"Pumpa (48)",
"Pumpafrön (18)",
"Punsch (2)",
"Purjolök (52)",
"Puré (4)",
"Puylinser (22)",
"Päron (10)",
"Quinoa (19)",
"Quorn (12)",
"Quorn Bitar (1)",
"Quorn Burgare (1)",
"Quorn Filéer (2)",
"Quorn Färs (4)",
"Quorn Strimlor (0)",
"Rabar (1)",
"Rabarber (7)",
"Ramslök (17)",
"Red Snapper (1)",
"Red Stag (2)",
"Renfilé (1)",
"Reninnanlår (1)",
"Renkött (2)",
"Rensalami (1)",
"Renskav (2)",
"Ribs (11)",
"Ricotta (2)",
"Ris (11)",
"Rom (5)",
"Romanesco (4)",
"Romansallad (4)",
"Rosmarin (27)",
"Rosor (1)",
"Rostas (14)",
"Rostbiff (2)",
"Rosépeppar (1)",
"Rotsaker (42)",
"Rotselleri (42)",
"Rucola (60)",
"Russin (7)",
"Ryggbiff (4)",
"Ryssgubbe (1)",
"Rädisblast (2)",
"Rädisor (13)",
"Räkor (25)",
"Rättika (1)",
"Rådjur (2)",
"Rådjursfilé (1)",
"Rådjursytterfilé (1)",
"Rågmjöl (0)",
"Råkorv (1)",
"Röda linser (20)",
"Röda vinbär (1)",
"Rödbetor (65)",
"Rödbetsblast (3)",
"Röding (1)",
"Rödklöver (3)",
"Rödkål (13)",
"Rödlök (82)",
"Röd Oxalis (2)",
"Rödspätta (1)",
"Rödvin (5)",
"Rökt Paprikapulver (28)",
"Rölleka (1)",
"Röllika (2)",
"Rönnbär (1)",
"Rösti (5)",
"Saffran (17)",
"Salami (23)",
"Salladskål (3)",
"Salladslök (64)",
"Salsiccia (6)",
"Saltgurka (3)",
"Salvia (4)",
"Sardeller (5)",
"Savojkål (8)",
"Schalottenlök (15)",
"Scones (7)",
"Sej (3)",
"Selleri (50)",
"Senap (36)",
"Sesamfrön (32)",
"Sharonfrukt (3)",
"Shiitakesvamp (8)",
"Sidfläsk (1)",
"Silverlök (2)",
"Sirap (14)",
"Skinka (20)",
"Skinkbog (2)",
"Skinkschnitzel (1)",
"Skinkstek (5)",
"Smuldeg (1)",
"Småbladssallad (1)",
"Smör (6)",
"Smördeg (37)",
"Smörgåsgurka (7)",
"Smörgåskrasse (15)",
"Sockerkaka (1)",
"Sockerärtor (27)",
"Soja (8)",
"Sojabönor (31)",
"Solrosfrön (45)",
"Solrosskott (2)",
"Soltorkade tomater (103)",
"Spaghetti (10)",
"Sparris (47)",
"Spenat (28)",
"Spetskål (2)",
"Spiskummin (20)",
"Srirachasås (1)",
"Stekfläsk (4)",
"Steklök (8)",
"Stevia (0)",
"Strösocker (4)",
"Sugarsnaps (12)",
"Surdeg (7)",
"Surimisticks (3)",
"Svamp (103)",
"Svarta bönor (46)",
"Svarta Vinbär (4)",
"Svartkål (9)",
"Svartpeppar (3)",
"Svartrot (1)",
"Svart trumpetsvamp (12)",
"Svinmålla (7)",
"Sweet Chilisås (6)",
"Syltlök (1)",
"Syrad grädde (3)",
"Syren (2)",
"Sötpotatis (14)",
"Tabasco (3)",
"Tacoskal (2)",
"Tagetes (10)",
"Tagiatelle (1)",
"Temynta (1)",
"Tequila (2)",
"Teriyakisås (0)",
"Tilapia (1)",
"Timjan (24)",
"Tomat (100)",
"Tomatpuré (11)",
"Tonfisk (15)",
"Torsk (32)",
"Torskrygg (16)",
"Tortillabröd (14)",
"Tranbär (2)",
"Trattkantareller (21)",
"Tryffelolja (15)",
"Tunnbröd (6)",
"Valnötter (5)",
"Vanilj (15)",
"Vaniljglass (2)",
"Vaniljsås (3)",
"Varmrökt lax (0)",
"Vattenmelon (1)",
"Vaxbönor (10)",
"Vermouth (8)",
"Vetemjöl (24)",
"Vildris (1)",
"Vildsvin (1)",
"Vin (2)",
"Vita bönor (21)",
"Vit Choklad (12)",
"Vit fisk (14)",
"Vitkål (45)",
"Vitlök (86)",
"Vitt vin (10)",
"Vodka (1)",
"Västerbottensost (23)",
"Whisky / Whiskey (10)",
"Wokgrönsaker (1)",
"Zucchini (56)",
"Ädelost (1)",
"Ägg (38)",
"Äggröra (4)",
"Älg (1)",
"Älgfärs (2)",
"Äpple (127)",
"Ärtor (20)",
"Ärtskott (1)",
"Ätbara Blommor (20)",
"Ätbart grönt (59)",
"Ättika (3)",
"Öl (10)",
"Örter (26)"];