var Nightmare = require('nightmare');
var nightmare = Nightmare({
    openDevTools: false, show: false, webPreferences: {
        images: false,
    }
})

var fs = require('fs');


//ta fram urls genom att:
//1. Gå till en sida på ica.se/recept
//2. kör: var hrefs=[]; var interv=setInterval(function(){if(document.querySelector('.recipe-bottom-container .showMoreText')){document.querySelector('a.loadmore').click();}else{hrefs=Array.from(document.querySelectorAll('article.recipe header h2.title a')).map(a => a.href);console.log("done");clearInterval(interv);}},1500);
//IMPROVED var result = []; var interv=setInterval(function(){if(document.querySelector('.recipe-bottom-container .showMoreText')){result = result.concat(Array.from(document.querySelectorAll('article.recipe header h2.title a')).map(a => a.href));$('article.recipe').remove();document.querySelector('a.loadmore').click();}else{;console.log("done");clearInterval(interv);}},1500);
//med denna laggar inte sidan och result byggs på under körningen.
//kopiera result med copy([... new Set(result)])
//3. Vänta på att "done" har loggats i consolen.
//4. kopiera alla hrefs genom copy(hrefs) eller copy(Array.from(document.querySelectorAll('article.recipe header h2.title a')).map(a => a.href));
//5. paste in i urls
//6. Sätt filename enligt "ICA-RECEPTSRC-DATE.json"
//6. kör node set DEBUG=nightmare & node ica.js
//8. kör node createRecipes.js och ange namnet på filen som skapades här
let urls = [ "https://www.ica.se/recept/kycklingfile-med-broccoli-och-fullkornsris-559690/",
"https://www.ica.se/recept/renskavspanna-559675/",
"https://www.ica.se/recept/lax-med-bladspenat-och-pasta-559580/",
"https://www.ica.se/recept/chili-sin-carne-559566/",
"https://www.ica.se/recept/kassler-med-rodbetsfras-559546/",
"https://www.ica.se/recept/spattafileer-med-rakor-559523/",
"https://www.ica.se/recept/varm-potatissallad-558514/",
"https://www.ica.se/recept/elkes-och-mallas-kal-554288/",
"https://www.ica.se/recept/teriyakilax-551721/",
"https://www.ica.se/recept/skogens-svamp-med-rotfrukter-och-matvete-551592/",
"https://www.ica.se/recept/salsa-verde-med-rotfrukter-och-lamm-551553/",
"https://www.ica.se/recept/lovbiffwok-med-ris-550623/",
"https://www.ica.se/recept/potatis-och-morotsmos-med-kottkorv-550568/",
"https://www.ica.se/recept/green-currykyckling-med-fullkornsris-550420/",
"https://www.ica.se/recept/biffar-med-rotsaker-i-pitabrod-550405/",
"https://www.ica.se/recept/bonrora-med-kycklingkorv-550378/",
"https://www.ica.se/recept/rosti-med-morotter-och-kyckling-550339/",
"https://www.ica.se/recept/fisk-i-paprikasas-550290/",
"https://www.ica.se/recept/kycklinglever-med-fullkornsbulgur-550222/",
"https://www.ica.se/recept/kinesisk-kycklingwok-549478/",
"https://www.ica.se/recept/hui-guo-rou-549199/",
"https://www.ica.se/recept/ma-po-dou-fu-549172/",
"https://www.ica.se/recept/dagobertare-med-kyckling-mango-och-avokado-549103/",
"https://www.ica.se/recept/currylaksa-548785/",
"https://www.ica.se/recept/stekt-flask-i-mork-sojasas-548696/",
"https://www.ica.se/recept/rakor-och-stjalkselleri-548577/",
"https://www.ica.se/recept/pumpapasta-med-basilika-och-chorizo-717836/",
"https://www.ica.se/recept/stekt-karre-med-tomat-och-avokadosallad-717833/",
"https://www.ica.se/recept/nudelsoppa-med-kyckling-717829/",
"https://www.ica.se/recept/kycklingkorv-545244/",
"https://www.ica.se/recept/vild-cowboygryta-544729/",
"https://www.ica.se/recept/kottbullar-i-tomat-och-citronsas-543564/",
"https://www.ica.se/recept/pocherad-torsk-med-sparris-och-kaviaryoghurt-543470/",
"https://www.ica.se/recept/jespers-favoritkottbullar-543217/",
"https://www.ica.se/recept/stekt-hokifile-med-varm-morotssallad-542386/",
"https://www.ica.se/recept/potatis-och-morotsmos-med-varmkorv-542014/",
"https://www.ica.se/recept/kyckling-med-saffran-och-tomat-541935/",
"https://www.ica.se/recept/kalkongryta-med-rotfrukter-och-risotto-541422/",
"https://www.ica.se/recept/kycklingwok-med-grapefrukt-541400/",
"https://www.ica.se/recept/kyckling-med-citron-och-persilja-541370/",
"https://www.ica.se/recept/kyckling-med-asiatisk-smak-541299/",
"https://www.ica.se/recept/laxpytt-med-caviar-541152/",
"https://www.ica.se/recept/laxbiff-med-citrussallad-och-oliver-538661/",
"https://www.ica.se/recept/biff-med-farskost-och-champinjoner-538621/",
"https://www.ica.se/recept/appelkotlett-med-baconkrisp-537974/",
"https://www.ica.se/recept/fankalsfrittata-537944/",
"https://www.ica.se/recept/kycklingwok-med-potatis-537916/",
"https://www.ica.se/recept/angkokt-kolja-med-jordartskockor-och-svamp-537735/",
"https://www.ica.se/recept/kassler-och-gronsakswok-537431/",
"https://www.ica.se/recept/pepparhalstrad-gravlax-med-avokado-537392/",
"https://www.ica.se/recept/grillad-kyckling-med-gremolata-537329/",
"https://www.ica.se/recept/kycklingfileer-i-marinad-med-gron-sas-536629/",
"https://www.ica.se/recept/tomat-och-olivbiffar-534180/",
"https://www.ica.se/recept/asiatisk-kyckling-med-lime-533876/",
"https://www.ica.se/recept/kikartscurry-med-potatis-533839/",
"https://www.ica.se/recept/blommig-falukorv-532502/",
"https://www.ica.se/recept/klockargardens-knaperstekta-abborre-532428/",
"https://www.ica.se/recept/raltagardens-grillade-kassler-med-paprikasas-532379/",
"https://www.ica.se/recept/lammfarsbiffar-med-potatis-och-artmos-531570/",
"https://www.ica.se/recept/knaperstekt-roding-med-citron-honungsbrynt-farskpotatis-531322/",
"https://www.ica.se/recept/lammytterfile-med-getostrora-och-bulgursallad-528964/",
"https://www.ica.se/recept/snabbrimmad-lax-med-ruccola-och-persika-524888/",
"https://www.ica.se/recept/halstrad-gravlax-med-chevresallad-rodbetor-och-kronartskockskram-524656/",
"https://www.ica.se/recept/raggmunk-med-flask-och-lingon-524547/",
"https://www.ica.se/recept/texas-pit-beans-524457/",
"https://www.ica.se/recept/isterband-special-med-kapris-522059/",
"https://www.ica.se/recept/pasta-med-kyckling-och-grona-oliver-521998/",
"https://www.ica.se/recept/grillspett-med-rodbetsris-521911/",
"https://www.ica.se/recept/tacocrepes-520430/",
"https://www.ica.se/recept/tacokyckling-520064/",
"https://www.ica.se/recept/korv-stroganoff-med-farsk-pasta-516296/",
"https://www.ica.se/recept/fiskgryta-med-fankal-och-farsk-pasta-516256/",
"https://www.ica.se/recept/kokt-agg-512848/",
"https://www.ica.se/recept/rosastekt-kalvlever-med-farska-fikon-och-balsamvinager-510299/",
"https://www.ica.se/recept/pannbiff-med-apple-lok-och-champinjoner-510284/",
"https://www.ica.se/recept/frittata-med-bacon-och-purjo-510106/",
"https://www.ica.se/recept/stekt-stromming-med-potatisplattar-509666/",
"https://www.ica.se/recept/banana-pancake-509572/",
"https://www.ica.se/recept/torsk-med-smak-av-medelhavet-504817/",
"https://www.ica.se/recept/pollo-tonnato-504636/",
"https://www.ica.se/recept/pollo-alla-cacciatora-504482/",
"https://www.ica.se/recept/sugo-di-carne-504416/",
"https://www.ica.se/recept/kallarrokt-skinka-med-blomkalspure-504244/",
"https://www.ica.se/recept/russinkyckling-med-pasta-503938/",
"https://www.ica.se/recept/baskisk-panna-500229/",
"https://www.ica.se/recept/svensk-panna-499925/",
"https://www.ica.se/recept/vitello-tonnato-kalvkott-med-tonfisksas-497447/",
"https://www.ica.se/recept/pot-eu-feu-pa-kyckling-med-rotfrukter-496986/",
"https://www.ica.se/recept/lammbullar-med-spiskummin-och-rostade-gronsaker-496673/",
"https://www.ica.se/recept/grillad-chorizo-med-nudelwok-494353/",
"https://www.ica.se/recept/potatiskaka-med-getost-torkad-skinka-493894/",
"https://www.ica.se/recept/fisk-a-la-thai-493821/",
"https://www.ica.se/recept/farsdolmar-i-tomatsas-490956/",
"https://www.ica.se/recept/lammfile-med-kramig-polenta-och-kronartskockssalsa-488039/",
"https://www.ica.se/recept/sas-med-rokt-lax-och-sparris-487630/",
"https://www.ica.se/recept/kycklinggryta-med-chilikorv-487094/",
"https://www.ica.se/recept/biff-med-citronpotatis-och-vaniljkryddad-sas-461685/",
"https://www.ica.se/recept/laxfarserad-rodspattafile-i-vitvinssas-486387/",
"https://www.ica.se/recept/curryris-med-kassler-och-yoghurt-459041/",
"https://www.ica.se/recept/tomatfalukorv-med-palsternacksmos-454463/",
"https://www.ica.se/recept/flaskkotletter-med-ljummen-pastasallad-454449/",
"https://www.ica.se/recept/farswok-med-minimajs-454424/",
"https://www.ica.se/recept/korvpanna-med-couscous-454411/",
"https://www.ica.se/recept/laxpanna-453463/",
"https://www.ica.se/recept/fars-och-svamppanna-449208/",
"https://www.ica.se/recept/ananastoppade-skinkschnitzlar-med-paprika-och-lokfras-449176/",
"https://www.ica.se/recept/oreganokyckling-433508/",
"https://www.ica.se/recept/kebab-med-yoghurtsas-433440/",
"https://www.ica.se/recept/chili-con-carne-433075/",
"https://www.ica.se/recept/mosbricka-med-extra-av-allt-433020/",
"https://www.ica.se/recept/spattarullar-med-spenat-och-ost-429906/",
"https://www.ica.se/recept/kotlettpanna-med-farskost-429892/",
"https://www.ica.se/recept/kycklingwok-med-banan-429834/",
"https://www.ica.se/recept/kotlettskivor-i-fransk-senapssas-429795/",
"https://www.ica.se/recept/curryrakor-med-ris-429765/",
"https://www.ica.se/recept/italienska-farsbiffar-427130/",
"https://www.ica.se/recept/nordafrikansk-couscouspanna-med-fisk-427001/",
"https://www.ica.se/recept/tysk-fisk-med-surkal-och-applen-426948/",
"https://www.ica.se/recept/kinawok-med-woksas-och-cashewnotter-426892/",
"https://www.ica.se/recept/japansk-wasabibiff-med-soja-426863/",
"https://www.ica.se/recept/fransk-strimmelbiff-med-adelost-426823/",
"https://www.ica.se/recept/mexipanna-med-kyckling-och-bonor-426650/",
"https://www.ica.se/recept/indisk-kycklinggryta-426603/",
"https://www.ica.se/recept/pasta-med-rostbiff-och-squashrora-426313/",
"https://www.ica.se/recept/kycklingklubbor-med-gron-salsa-426295/",
"https://www.ica.se/recept/filewok-med-ortsas-och-couscous-426280/",
"https://www.ica.se/recept/fetafylld-biff-med-rodlok-426208/",
"https://www.ica.se/recept/stekt-kyckling-med-appel-potatissallad-426192/",
"https://www.ica.se/recept/kyckling-med-kokos-och-persikor-426143/",
"https://www.ica.se/recept/pestofyllda-schnitzlar-med-zucchininudlar-425584/",
"https://www.ica.se/recept/stekta-spattafileer-med-gurksallad-422526/",
"https://www.ica.se/recept/kycklingbrost-med-pikanta-champinjoner-418913/",
"https://www.ica.se/recept/hokifile-med-sallad-pa-avokado-och-grillad-paprika-418856/",
"https://www.ica.se/recept/fiskpinnar-med-mos-och-varm-bonsallad-417416/",
"https://www.ica.se/recept/katrinplommonfyllda-jarpar-416016/",
"https://www.ica.se/recept/kokta-strommingsrullar-med-dillris-415946/",
"https://www.ica.se/recept/laxfjaril-med-teriyakisas-och-wok-414972/",
"https://www.ica.se/recept/torsk-med-thaismak-414867/",
"https://www.ica.se/recept/sesamlax-med-sojasas-414779/",
"https://www.ica.se/recept/rimmad-oxbringa-med-jordartskockor-414281/",
"https://www.ica.se/recept/kryddad-lammfars-pa-spett-413576/",
"https://www.ica.se/recept/halloumi-och-tomatfyllda-kottfarsbiffar-413414/",
"https://www.ica.se/recept/skavwok-med-kiwi-410732/",
"https://www.ica.se/recept/spattafile-med-stekta-ananasringar-410719/",
"https://www.ica.se/recept/ost-och-sparristackt-kotlett-410707/",
"https://www.ica.se/recept/chutneystekta-kycklingbrost-med-kryddigt-matvete-408730/",
"https://www.ica.se/recept/kassler-med-varm-ananassalsa-406459/",
"https://www.ica.se/recept/basilikakyckling-406419/",
"https://www.ica.se/recept/korv-med-grekiskt-mos-406374/",
"https://www.ica.se/recept/mandelstekt-kycklingfile-med-rispilaff-406347/",
"https://www.ica.se/recept/frasig-fisk-med-franska-arter-403639/",
"https://www.ica.se/recept/gronsaksrora-med-kryddiga-kottbullar-403621/",
"https://www.ica.se/recept/kalvfile-i-marsalasas-399445/",
"https://www.ica.se/recept/gaddburgare-med-kaviardressing-399221/",
"https://www.ica.se/recept/farsbiffar-i-graddig-tomatsas-399148/",
"https://www.ica.se/recept/sparris-med-rokt-kalkonbrost-och-limevinagrett-389351/",
"https://www.ica.se/recept/kycklingpanna-med-gront-och-fullkornspasta-389176/",
"https://www.ica.se/recept/skinkschnitzel-med-majsrisotto-388848/",
"https://www.ica.se/recept/fisk-i-kaviarsas-388826/",
"https://www.ica.se/recept/korvpanna-allt-i-ett-388792/",
"https://www.ica.se/recept/rotfruktspytt-med-kyckling-388781/",
"https://www.ica.se/recept/kokt-torskfile-med-bacon-och-artpure-388457/",
"https://www.ica.se/recept/stekt-hoki-med-majsmos-388219/",
"https://www.ica.se/recept/dubbla-kasslerskivor-med-gronsakspasta-388209/",
"https://www.ica.se/recept/farsbiff-med-rodbetor-och-agg-388103/",
"https://www.ica.se/recept/oxrulader-med-graddsas-387835/",
"https://www.ica.se/recept/potatismoskrans-med-kycklingfras-386497/",
"https://www.ica.se/recept/grillade-kycklingspett-med-couscous-och-gronsaksrora-385514/",
"https://www.ica.se/recept/kotlettpanna-med-brysselkal-385501/",
"https://www.ica.se/recept/kyckling-i-kormasas-med-ris-384048/",
"https://www.ica.se/recept/stekt-torskfile-med-taboulesallad-383588/",
"https://www.ica.se/recept/torsk-med-frasch-gronsaksrora-381158/",
"https://www.ica.se/recept/festkotlett-med-bearnaisesmor-381132/",
"https://www.ica.se/recept/lovbiff-med-lok-och-chilisas-375691/",
"https://www.ica.se/recept/fiskpinnar-med-gronsakssas-375604/",
"https://www.ica.se/recept/kottbullar-med-prickigt-mos-och-lingonsylt-375548/",
"https://www.ica.se/recept/strommingspanna-med-medelhavssmak-375391/",
"https://www.ica.se/recept/kottfarspytt-375312/",
"https://www.ica.se/recept/kokta-kycklingfileer-med-ostrisotto-375202/",
"https://www.ica.se/recept/purjofylld-spatta-med-oliver-och-tomat-374936/",
"https://www.ica.se/recept/kottfarsbiffar-med-olivrora-374769/",
"https://www.ica.se/recept/fetafyllda-kycklingfileer-i-tomatsas-374733/",
"https://www.ica.se/recept/keftedes-372818/",
"https://www.ica.se/recept/laxwok-teriyaki-371454/",
"https://www.ica.se/recept/kramig-skinkrora-med-potatistoppar-368227/",
"https://www.ica.se/recept/sma-kottfarsbiffar-med-oliver-och-kapris-367872/",
"https://www.ica.se/recept/kokt-blomkal-med-aggfras-367314/",
"https://www.ica.se/recept/flaskkotletter-med-tomat-apelsin-och-oliver-367291/",
"https://www.ica.se/recept/grillkryddad-lax-med-avokado-och-rakor-365088/",
"https://www.ica.se/recept/lovbiff-med-potatispuckar-363956/",
"https://www.ica.se/recept/snabbrimmad-hoki-med-sparris-och-limesky-363043/",
"https://www.ica.se/recept/sparris-med-serranoskinka-och-ostvinagrett-363012/",
"https://www.ica.se/recept/halstrad-gos-med-braserad-salladslok-kapris-och-dragon-361548/",
"https://www.ica.se/recept/skinkrulader-med-svampmos-360225/",
"https://www.ica.se/recept/kotletter-med-fransk-bonsallad-360103/",
"https://www.ica.se/recept/pepparrotsfisk-360091/",
"https://www.ica.se/recept/kottbullar-i-mandelsas-albondigas-con-salsa-de-almendras-352834/",
"https://www.ica.se/recept/fiskpinnar-med-fullkornsris-352551/",
"https://www.ica.se/recept/fars-och-champinjonfrikadeller-352535/",
"https://www.ica.se/recept/korv-med-kramig-majsrisotto-352502/",
"https://www.ica.se/recept/lammkotletter-med-vitlokskram-och-lokpotatis-352480/",
"https://www.ica.se/recept/tomatspatta-med-oliver-352358/",
"https://www.ica.se/recept/skinkwok-med-ingefara-352251/",
"https://www.ica.se/recept/mexikalkon-i-wok-352216/",
"https://www.ica.se/recept/kycklingleverpytt-352119/",
"https://www.ica.se/recept/morots-och-cottage-cheeseplattar-352090/",
"https://www.ica.se/recept/stekt-portionsregnbage-med-citronsas-351927/",
"https://www.ica.se/recept/russinkyckling-349982/",
"https://www.ica.se/recept/spagetti-med-raksas-348588/",
"https://www.ica.se/recept/hoisinwokad-korv-344095/",
"https://www.ica.se/recept/kycklingbiffar-med-basilika-344063/",
"https://www.ica.se/recept/kassler-med-kal-och-chiliwok-344025/",
"https://www.ica.se/recept/kotletter-med-stuvad-potatis-343982/",
"https://www.ica.se/recept/stromming-med-lingonyoghurt-343969/",
"https://www.ica.se/recept/kalpudding-fran-pannan-343122/",
"https://www.ica.se/recept/kycklingpanna-pikant-342962/",
"https://www.ica.se/recept/nudelwok-med-kokosrakor-342063/",
"https://www.ica.se/recept/paronjarpar-med-julsmak-341191/",
"https://www.ica.se/recept/dubbelstekta-spattafileer-med-kraftost-341170/",
"https://www.ica.se/recept/wokad-rodkalssallad-med-kalvsylta-341118/",
"https://www.ica.se/recept/kycklingwok-med-rakor-och-cashewnotter-339038/",
"https://www.ica.se/recept/sotare-med-citronolja-338990/",
"https://www.ica.se/recept/gammelmormors-kottbullar-338364/",
"https://www.ica.se/recept/brasiliansk-hamburgare-med-rostad-majskram-717371/",
"https://www.ica.se/recept/kycklingspett-i-pita-med-mango-chutneydressing-717370/",
"https://www.ica.se/recept/raksallad-med-avokado-tomat-och-rod-peppar-717369/",
"https://www.ica.se/recept/provencalsk-potatissallad-717368/",
"https://www.ica.se/recept/sill-med-gurka-och-pepparrot-pa-knacke-717365/",
"https://www.ica.se/recept/fisk-med-agg-chili-och-dill-338102/",
"https://www.ica.se/recept/kokt-kycklingfile-med-ortsas-338058/",
"https://www.ica.se/recept/falukorv-med-kalrotsfras-337083/",
"https://www.ica.se/recept/nudlar-med-gronsaker-svamp-och-rakor-328525/",
"https://www.ica.se/recept/algkottbullar-fran-jamtland-327877/",
"https://www.ica.se/recept/kokt-lutfisk-pa-norskt-vis-med-flask-skirat-smor-och-artpure-327611/",
"https://www.ica.se/recept/stekt-ankbrost-med-rodkal-fran-danmark-327544/",
"https://www.ica.se/recept/lovbiff-med-rodloksmarmelad-327269/",
"https://www.ica.se/recept/korv-med-gront-mos-327225/",
"https://www.ica.se/recept/majs-och-potatisbullar-326987/",
"https://www.ica.se/recept/fjarilens-middag-pasta-med-fjarilskotlett-326959/",
"https://www.ica.se/recept/gula-fiskbiffar-326489/",
"https://www.ica.se/recept/kokosstekt-kycklingfile-326435/",
"https://www.ica.se/recept/appelfyllda-kottfarsjarpar-med-morotsmos-324115/",
"https://www.ica.se/recept/flaskfile-med-persiljerotsaker-324101/",
"https://www.ica.se/recept/flaskfile-med-lokrora-323476/",
"https://www.ica.se/recept/kyckling-och-paprika-i-tikkasas-323413/",
"https://www.ica.se/recept/sesamlax-med-currypotatis-323213/",
"https://www.ica.se/recept/tacobiffar-322254/",
"https://www.ica.se/recept/kalkonmedaljonger-med-tomatcouscous-322209/",
"https://www.ica.se/recept/rakfylld-spatta-i-citronsas-321399/",
"https://www.ica.se/recept/grillad-kassler-med-sommarsallad-pa-farskpotatis-320529/",
"https://www.ica.se/recept/kycklingwok-med-italiensk-smak-318701/",
"https://www.ica.se/recept/schnitzel-med-basilikapotatis-318509/",
"https://www.ica.se/recept/sommarpanna-med-kassler-318373/",
"https://www.ica.se/recept/tomat-och-ostfylld-lovbiff-318361/",
"https://www.ica.se/recept/kryddstekt-kycklingfile-och-gronsaker-318256/",
"https://www.ica.se/recept/kycklingfile-med-grillsas-317811/",
"https://www.ica.se/recept/chilitonfisk-317804/",
"https://www.ica.se/recept/hjortfile-med-tomatsalsa-314592/",
"https://www.ica.se/recept/alg-fran-woken-med-svampmarmelad-314376/",
"https://www.ica.se/recept/kottbullar-i-tomatsas-med-basilikasmak-309786/",
"https://www.ica.se/recept/skordepytt-309765/",
"https://www.ica.se/recept/chilistekt-spetskal-med-grillade-kycklinglar-305079/",
"https://www.ica.se/recept/stromming-med-lax-och-potatissallad-304541/",
"https://www.ica.se/recept/kottfarsjarpar-pa-mosbadd-302431/",
"https://www.ica.se/recept/kyckling-med-gron-curry-302396/",
"https://www.ica.se/recept/fiskpinnar-med-gremolatamos-302350/",
"https://www.ica.se/recept/asiatisk-slaw-med-kottbullar-302342/",
"https://www.ica.se/recept/het-biff-med-bambuskott-sambal-oelek-302319/",
"https://www.ica.se/recept/kottbullar-med-kryddig-tomatsas-302279/",
"https://www.ica.se/recept/hallefile-med-champinjoner-och-pepparrot-300412/",
"https://www.ica.se/recept/raraka-med-kycklingrora-300375/",
"https://www.ica.se/recept/kotlett-med-kiwisalsa-297017/",
"https://www.ica.se/recept/torsk-med-mexikansk-paprikasas-296982/",
"https://www.ica.se/recept/knaperstekt-kycklingfile-med-passionsrelish-296916/",
"https://www.ica.se/recept/currykyckling-med-kikarter-och-purjolok-296001/",
"https://www.ica.se/recept/kokt-blomkal-med-het-paprikasas-295980/",
"https://www.ica.se/recept/sesampanerad-stromming-med-haricots-verts-295744/",
"https://www.ica.se/recept/brysselkal-med-parmaskinka-och-pinjenotter-295703/",
"https://www.ica.se/recept/fetaburgare-med-gronsaksrora-295690/",
"https://www.ica.se/recept/buljongkokt-kycklingfile-med-mos-292815/",
"https://www.ica.se/recept/jordnotsmarinerade-kycklingfileer-panerade-med-kokos-292574/",
"https://www.ica.se/recept/tonfiskkakor-291446/",
"https://www.ica.se/recept/het-falukorv-med-gronsaksspagetti-288505/",
"https://www.ica.se/recept/currylax-med-koriander-288489/",
"https://www.ica.se/recept/pepparbiff-med-sotsur-lokkompott-286942/",
"https://www.ica.se/recept/stekt-ris-med-purjo-och-svamp-286824/",
"https://www.ica.se/recept/teriyakilax-med-wasabi-och-graslokssmor-286734/",
"https://www.ica.se/recept/viltbiffar-med-enbarsstekta-rotfrukter-284383/",
"https://www.ica.se/recept/heta-ingefarsrakor-med-salladslok-281196/",
"https://www.ica.se/recept/korv-med-lok-och-apple-281149/",
"https://www.ica.se/recept/frukostkorv-med-currylinser-277011/",
"https://www.ica.se/recept/kassler-med-spenat-och-paronfras-och-smulad-adelost-276832/",
"https://www.ica.se/recept/thaipocherad-fiskfile-275619/",
"https://www.ica.se/recept/kottfarsrullar-pa-spett-med-jordnotsdipp-273636/",
"https://www.ica.se/recept/hemlagad-kottkorv-268372/",
"https://www.ica.se/recept/kryddstekt-hallefile-med-aubergine-och-tzatsiki-267699/",
"https://www.ica.se/recept/kokt-torsk-med-mussel-och-chilistuffing-263816/",
"https://www.ica.se/recept/stekt-hallefile-med-kapris-rakor-och-citron-261560/",
"https://www.ica.se/recept/halstrad-rabiff-med-spenatyoghurt-261452/",
"https://www.ica.se/recept/ciderbraserad-flaskkarre-med-apple-och-pepparrot-260037/",
"https://www.ica.se/recept/flaskkotlett-med-ruccolatzatsiki-259932/",
"https://www.ica.se/recept/kyckling-med-hasselnotter-och-bonor-256449/",
"https://www.ica.se/recept/sojastekt-flaskkarre-med-chilikryddad-avokadosallad-256418/",
"https://www.ica.se/recept/sellerimos-med-kassler-och-svamp-256366/",
"https://www.ica.se/recept/rotfruktsrosti-med-renstek-256234/",
"https://www.ica.se/recept/chili-tomatmusslor-med-orter-247381/",
"https://www.ica.se/recept/kokt-fisk-med-avokado-citron-och-sardeller-237515/",
"https://www.ica.se/recept/bonchili-med-brackt-falukorv-237321/",
"https://www.ica.se/recept/kalkonwok-med-sockerarter-och-black-beansas-237229/",
"https://www.ica.se/recept/kasslerkotlett-med-champinjonkram-225390/",
"https://www.ica.se/recept/kotlettpanna-med-silverlok-och-soltorkade-tomater-173716/",
"https://www.ica.se/recept/friterade-lok-och-blackfiskringar-med-haftig-sas-172981/",
"https://www.ica.se/recept/biff-med-lok-171627/",
"https://www.ica.se/recept/kreolsk-fiskpanna-170719/",
"https://www.ica.se/recept/kryddiga-kottfarsbiffar-med-ost-och-tomat-170094/",
"https://www.ica.se/recept/kraftstromming-169568/",
"https://www.ica.se/recept/lax-med-bonor-och-tandooridressing-167463/",
"https://www.ica.se/recept/fisk-med-kall-rak-och-romsas-166852/",
"https://www.ica.se/recept/laxcrepes-med-ruccolassallad-166733/",
"https://www.ica.se/recept/flaskkotlett-med-olivsas-och-smorfrast-savoykal-166346/",
"https://www.ica.se/recept/stromming-med-lime-och-tomat-166005/",
"https://www.ica.se/recept/kyckling-med-kapris-och-rodbetor-165779/",
"https://www.ica.se/recept/halstrad-lax-med-vinagrett-164623/",
"https://www.ica.se/recept/senapsrakor-med-pepparrot-164275/",
"https://www.ica.se/recept/hallefile-med-vitlokschampinjoner-164064/",
"https://www.ica.se/recept/kycklingfile-i-panna-med-bacon-och-druvor-160791/",
"https://www.ica.se/recept/spattaborsar-med-banan-och-tomat-155448/",
"https://www.ica.se/recept/hoisinkyckling-med-risnudlar-130138/",
"https://www.ica.se/recept/kassler-med-varma-rodbetsklyftor-115479/",
"https://www.ica.se/recept/couscouspaella-115259/",
"https://www.ica.se/recept/kycklingkottbullar-med-sataysas-111989/",
"https://www.ica.se/recept/kyckling-i-ortdressing-76837/",
"https://www.ica.se/recept/kassler-med-citronrasp-50354/",
"https://www.ica.se/recept/skaldjurspanna-50326/",
"https://www.ica.se/recept/kycklingspett-med-purjolok-och-paprika-5565/",
"https://www.ica.se/recept/wokad-lax-5549/",
"https://www.ica.se/recept/cashew-wok-5538/",
"https://www.ica.se/recept/kassler-med-gronsaksfras-5458/",
"https://www.ica.se/recept/gron-och-gul-wok-5432/",
"https://www.ica.se/recept/lammkotletter-med-vitlokskram-och-rosmarinpotatis-5430/",
"https://www.ica.se/recept/rosens-spatta-5412/",
"https://www.ica.se/recept/flaskkorv-graddkokt-fankal-5397/",
"https://www.ica.se/recept/isterband-special-med-kapris-5396/",
"https://www.ica.se/recept/potatisplattar-med-skinka-5325/",
"https://www.ica.se/recept/sotare-med-ansjovispotatis-5307/",
"https://www.ica.se/recept/kokt-hummer-med-majonnas-a-la-oliv-5262/",
"https://www.ica.se/recept/kottbullar-med-kikartswok-5219/",
"https://www.ica.se/recept/ananas-med-kokostacke-901/",
"https://www.ica.se/recept/amerikansk-rokig-rub-714993/",
"https://www.ica.se/recept/alunbrukets-paprikamarmelad-302684/",
"https://www.ica.se/recept/aloo-jeera-664259/",
"https://www.ica.se/recept/allt-i-ett-wok-4096/",
"https://www.ica.se/recept/alexandras-enkla-matjessallad-618487/",
"https://www.ica.se/recept/alexandra-zazzis-basta-italienrecept-vitello-tonnato-686837/",
"https://www.ica.se/recept/aladab-pa-flasklagg-1724/",
"https://www.ica.se/recept/ajvarkryddade-farsbiffar-408350/",
"https://www.ica.se/recept/ajo-blanco-714363/",
"https://www.ica.se/recept/aioli-686990/",
"https://www.ica.se/recept/afrikansk-soppgryta-500207/",
"https://www.ica.se/recept/ljummen-sallad-i-smordressing-med-rokt-makrill-agg-och-farskpotatis-59/",
"https://www.ica.se/recept/vargryta-pa-indiavis-2899/",
"https://www.ica.se/recept/aioli-2359/",
"https://www.ica.se/recept/afroditiska-bar-i-kryddlag-574913/",
"https://www.ica.se/recept/afrikansk-kyckling-och-brysselkalsgryta-1068/",
"https://www.ica.se/recept/acar-awak-548935/",
"https://www.ica.se/recept/2-x-smaksatt-ris-664204/",
"https://www.ica.se/recept/1-2-3-lag-492762/",
"https://www.ica.se/recept/syrad-kinakalssallad-643781/",
"https://www.ica.se/recept/seafood-med-nudlar-och-pak-choy-i-ingefarsbuljong-714654/",
"https://www.ica.se/recept/plumepork-med-spenat-och-mandelsallad-715561/",
"https://www.ica.se/recept/boqerones-pa-ansjovis-716857/",
"https://www.ica.se/recept/limeonad-med-mynta-716525/",
"https://www.ica.se/recept/fagelmat-notblandning-376505/",
"https://www.ica.se/recept/nudelpanna-med-svamp-5089/",
"https://www.ica.se/recept/italienska-biffar-5088/",
"https://www.ica.se/recept/skomakarlada-om-hosten-5073/",
"https://www.ica.se/recept/paprikafisk-birgitte-4616/",
"https://www.ica.se/recept/kaprisfisk-4206/",
"https://www.ica.se/recept/stekt-flaskfile-med-pure-ragu-4189/",
"https://www.ica.se/recept/filemedaljong-med-lokchutney-4097/",
"https://www.ica.se/recept/rakbiffar-med-tomatsalsa-4094/",
"https://www.ica.se/recept/lunchpanna-pa-mitt-satt-4030/",
"https://www.ica.se/recept/laxbiffar-med-salsa-3973/",
"https://www.ica.se/recept/friterad-ansjovis-med-dill-och-ansjovisdressing-3965/",
"https://www.ica.se/recept/rosmarinspett-3920/",
"https://www.ica.se/recept/majspuffar-med-lax-3919/",
"https://www.ica.se/recept/saltimboca-3804/",
"https://www.ica.se/recept/kycklingsate-3739/",
"https://www.ica.se/recept/farsrullar-i-oreganosas-3738/",
"https://www.ica.se/recept/potatiskompott-med-kalvlever-och-salvia-3705/",
"https://www.ica.se/recept/sparrispotatis-i-tomatsas-med-serranoskinka-och-mozzarella-3697/",
"https://www.ica.se/recept/kroppkakor-av-kokt-potatis-3693/",
"https://www.ica.se/recept/mandelpotatis-med-balsamvinagerstekt-flask-3686/",
"https://www.ica.se/recept/bla-congo-med-gravad-lax-och-brynt-limesmor-3669/",
"https://www.ica.se/recept/dubbelstekta-spattafileer-med-sweet-chili-och-ost-3423/",
"https://www.ica.se/recept/spattarullar-med-pepparrot-och-rodbetor-3415/",
"https://www.ica.se/recept/surkal-med-flasklagg-och-bratwurst-3412/",
"https://www.ica.se/recept/kycklingfileer-i-kokossas-med-couscous-och-frasta-gronsaker-3366/",
"https://www.ica.se/recept/tapenadefyllda-spattafileer-3038/",
"https://www.ica.se/recept/strimmelbog-sweet-and-sour-2690/",
"https://www.ica.se/recept/potatispanna-med-sardiner-och-rodlok-2683/",
"https://www.ica.se/recept/mexikanska-fiskbullar-med-bonor-2671/",
"https://www.ica.se/recept/fiskbullewok-sweet-chili-2669/",
"https://www.ica.se/recept/panerade-stekta-fiskfileer-med-kaprisfras-2438/",
"https://www.ica.se/recept/mozzarellafyllda-kalkonschnitzlar-2408/",
"https://www.ica.se/recept/farsspett-2368/",
"https://www.ica.se/recept/laxkotletter-med-fruktig-salsa-2273/",
"https://www.ica.se/recept/vinbarskyckling-1994/",
"https://www.ica.se/recept/huli-hulisticks-1987/",
"https://www.ica.se/recept/stora-rakor-med-vitlok-och-curry-1801/",
"https://www.ica.se/recept/julkottbullar-1715/",
"https://www.ica.se/recept/friterad-flaskfile-med-persikochutney-1684/",
"https://www.ica.se/recept/stekt-flask-pepparrot-1556/",
"https://www.ica.se/recept/kycklingnudlar-1478/",
"https://www.ica.se/recept/roserullad-fisk-med-vitvinssas-1327/",
"https://www.ica.se/recept/stekt-lax-med-grapefruktsas-1293/",
"https://www.ica.se/recept/rimmad-ortkycklingfile-1241/",
"https://www.ica.se/recept/blakokt-regnbage-med-bladruvsas-1233/",
"https://www.ica.se/recept/shiitakefyllda-kycklingfileer-1202/",
"https://www.ica.se/recept/viltwok-med-rotsaker-1189/",
"https://www.ica.se/recept/oxrulader-med-graddsas-1146/",
"https://www.ica.se/recept/braserad-gos-med-brynt-flask-i-smorsas-och-rotmos-1139/",
"https://www.ica.se/recept/flaskkotletter-i-kiwisas-1131/",
"https://www.ica.se/recept/spattarullar-med-gron-sas-1130/",
"https://www.ica.se/recept/apelsinbiffar-olympus-1127/",
"https://www.ica.se/recept/rodbetspanna-med-kabanossenkorv-1107/",
"https://www.ica.se/recept/limekryddad-rakpasta-1014/",
"https://www.ica.se/recept/rodloksfyllda-kottfarsrullar-958/",
"https://www.ica.se/recept/tomat-och-mozzarellagratinerad-kassler-231982/",
"https://www.ica.se/recept/biffsteksrulle-655461/",
"https://www.ica.se/recept/stekt-ryggbiff-med-smetanabearnaise-och-klyftpotatis-717676/",
"https://www.ica.se/recept/rostad-majs-och-kyckling-med-avokadosalsa-717674/",
"https://www.ica.se/recept/stekt-kotlett-med-sockerartssallad-och-potatisgratang-717618/",
"https://www.ica.se/recept/sojawokad-kyckling-med-lime-717616/",
"https://www.ica.se/recept/kalrotswok-med-bacon-856/",
"https://www.ica.se/recept/vinkokt-skinka-med-orter-486/",
"https://www.ica.se/recept/renskavspanna-med-gronpepparsmak-425/",
"https://www.ica.se/recept/crepestarta-med-kyckling-och-aubergine-95/",
"https://www.ica.se/recept/pulled-pork-716155/",
"https://www.ica.se/recept/pestotorsk-och-minestrone-2058/",
"https://www.ica.se/recept/broccolipesto-med-hasselnotter-716812/",
"https://www.ica.se/recept/lamm-latino-570875/",
"https://www.ica.se/recept/pumpapesto-284219/",
"https://www.ica.se/recept/ugnsbakad-lax-med-pumpapesto-och-risonisallad-714114/",
"https://www.ica.se/recept/avokadopesto-a-la-mick-2228/",
"https://www.ica.se/recept/pestodipp-4012/",
"https://www.ica.se/recept/pestogratinerad-aubergine-med-parmesan-och-flingsalt-551461/",
"https://www.ica.se/recept/chili-och-sojamarinerad-flaskkarre-med-ortslungad-sparris-668034/",
"https://www.ica.se/recept/grillat-bondbrod-med-prosciutto-tomat-och-pestopotatis-56/",
"https://www.ica.se/recept/falsk-pesto-666339/",
"https://www.ica.se/recept/pesto-1821/",
"https://www.ica.se/recept/annas-pesto-53704/",
"https://www.ica.se/recept/klassisk-pesto-666350/",
"https://www.ica.se/recept/pasta-med-pesto-och-marinerade-soltorkade-tomater-2807/",
"https://www.ica.se/recept/tapenade-och-bonpesto-460859/",
"https://www.ica.se/recept/pesto-alla-genovese-638334/",
"https://www.ica.se/recept/frostekt-torsk-med-artpesto-och-roman-och-gurksallad-715120/",
"https://www.ica.se/recept/morotssoppa-med-jordnotspesto-682510/",
"https://www.ica.se/recept/gronkalspesto-393089/",
"https://www.ica.se/recept/svennis-italiarullar-4799/",
"https://www.ica.se/recept/korianderfyllda-kycklingfilerullar-413063/",
"https://www.ica.se/recept/brackt-lax-med-pestopotatis-119/",
"https://www.ica.se/recept/pasta-med-halloumi-rotfrukter-och-ruccolapesto-714516/",
"https://www.ica.se/recept/flaskfile-med-solrospesto-369459/",
"https://www.ica.se/recept/minestrone-med-tomatpesto-5132/",
"https://www.ica.se/recept/lattgravad-grillad-lax-med-dillpesto-715217/",
"https://www.ica.se/recept/spenat-och-solrospesto-716717/",
"https://www.ica.se/recept/stekt-torsk-med-artpesto-717639/",
"https://www.ica.se/recept/kantarellpesto-638013/",
"https://www.ica.se/recept/ugnsbakad-kalkon-med-chermoula-714679/",
"https://www.ica.se/recept/pestorisoni-525623/",
"https://www.ica.se/recept/helstekt-rostbiff-med-hemgjord-pestosas-713661/",
"https://www.ica.se/recept/hembakt-pizza-pa-italienskt-vis-713095/",
"https://www.ica.se/recept/smorrebrod-med-lax-pesto-och-rimmad-gurka-672711/",
"https://www.ica.se/recept/pesto-med-pasta-1284/",
"https://www.ica.se/recept/mias-pesto-297804/",
"https://www.ica.se/recept/skinkrullar-med-sparris-i-pesto-5422/",
"https://www.ica.se/recept/svensk-pesto-715168/",
"https://www.ica.se/recept/pesto-med-basilika-717599/",
"https://www.ica.se/recept/annikas-souvas-564102/",
"https://www.ica.se/recept/annas-potatissallad-531584/",
"https://www.ica.se/recept/annas-ostcrepes-566135/",
"https://www.ica.se/recept/annas-nubberora-581833/",
"https://www.ica.se/recept/ananastartelette-med-limefraiche-663550/",
"https://www.ica.se/recept/ananaspaj-3273/",
"https://www.ica.se/recept/amerikanska-blabarspannkakor-715324/",
"https://www.ica.se/recept/amerikansk-hamburgerdressing-714998/",
"https://www.ica.se/recept/adventssoppa-5327/",
"https://www.ica.se/recept/adventspeppisar-595892/",
"https://www.ica.se/recept/grillrokt-lax-med-kall-graslokssas-713007/",
"https://www.ica.se/recept/gumrora-pa-kavring-2433/",
"https://www.ica.se/recept/ortsas-med-wasabi-715021/",
"https://www.ica.se/recept/ortsill-712670/",
"https://www.ica.se/recept/ortpate-med-pistagenotter-1798/",
"https://www.ica.se/recept/ortkryddade-kottfarsbiffar-med-rostade-rotsaker-och-fetaost-och-tomatsas-717226/",
"https://www.ica.se/recept/ortfisk-med-hummersmak-2913/",
"https://www.ica.se/recept/ortdipp-2316/",
"https://www.ica.se/recept/ortbakat-kalkonbrost-med-potatis-och-brysselkal-618550/",
"https://www.ica.se/recept/ortbakad-lax-med-smorslungad-potatissallad-715075/",
"https://www.ica.se/recept/ortbakad-lammstek-med-vitlokscreme-och-parmesan-714684/",
"https://www.ica.se/recept/ortagardssill-393002/",
"https://www.ica.se/recept/ort-och-vitlokspaj-med-skinka-420226/",
"https://www.ica.se/recept/ort-och-vitloksgravad-stromming-515388/",
"https://www.ica.se/recept/ort-och-potatissoppa-5153/",
"https://www.ica.se/recept/glutenfria-vallmofrallor-717827/",
"https://www.ica.se/recept/curry-pulled-pork-i-naanbrod-714678/",
"https://www.ica.se/recept/oppenlasagne-84/",
"https://www.ica.se/recept/olandsk-chili-700219/",
"https://www.ica.se/recept/artig-soppa-med-skink-och-paprikatortilla-713104/",
"https://www.ica.se/recept/appelbraserade-rullader-pa-gardsgris-fyllda-med-apple-och-mesost-serverat-med-persiljekokt-potatis-656173/",
"https://www.ica.se/recept/art-och-pepparrotsdip-713175/",
"https://www.ica.se/recept/appelpiroger-med-citron-och-kardemumma-717086/",
"https://www.ica.se/recept/appelknyte-med-lakritssmak-338624/",
"https://www.ica.se/recept/appel-och-pepparrotssas-579100/",
"https://www.ica.se/recept/appel-och-blomkalssallad-669676/",
"https://www.ica.se/recept/algfarslimpa-702209/",
"https://www.ica.se/recept/aggsallad-med-salladslok-422080/",
"https://www.ica.se/recept/aggrora-pa-hampafron-647818/",
"https://www.ica.se/recept/agghalvor-med-lojrom-1706/",
"https://www.ica.se/recept/agghalvor-med-citron-rom-och-krispig-rodlok-715917/",
"https://www.ica.se/recept/agg-och-potatissallad-424557/",
"https://www.ica.se/recept/agg-och-bacon-510602/",
"https://www.ica.se/recept/adelrissoppa-3454/",
"https://www.ica.se/recept/adelostpaj-1926/",
"https://www.ica.se/recept/adelostbakad-knipplok-622354/",
"https://www.ica.se/recept/asas-luriga-olivsas-380892/",
"https://www.ica.se/recept/asas-bacon-och-tonfisksas-433868/",
"https://www.ica.se/recept/vasterbottensruta-med-lojrom-713640/",
"https://www.ica.se/recept/varrulle-med-bonsallad-och-sesamdipp-567226/",
"https://www.ica.se/recept/zucchinilax-med-ingefarsyoghurt-27/",
"https://www.ica.se/recept/yoghurtbearnaise-537843/",
"https://www.ica.se/recept/vasterbottensuffle-458920/",
"https://www.ica.se/recept/vasterbottenkex-med-rakor-lojrom-och-picklad-rodlok-712609/",
"https://www.ica.se/recept/vasterbottenfocaccia-med-kraftrora-619848/",
"https://www.ica.se/recept/varsallad-med-jordgubbar-och-skinka-161277/",
"https://www.ica.se/recept/varlig-kotlett-3867/",
"https://www.ica.se/recept/varig-alggryta-701209/",
"https://www.ica.se/recept/varig-kalkongryta-med-svartrot-och-dragon-713673/",
"https://www.ica.se/recept/svartvinbarssylt-med-nektarin-och-vanilj-714036/",
"https://www.ica.se/recept/syltad-ingefara-2782/",
"https://www.ica.se/recept/syltad-kal-641228/",
"https://www.ica.se/recept/syltad-lok-och-svamp-387976/",
"https://www.ica.se/recept/syltad-pumpa-321822/",
"https://www.ica.se/recept/syltad-pumpa-643717/",
"https://www.ica.se/recept/vaffla-special-utan-agg-292941/",
"https://www.ica.se/recept/syltad-svamp-och-rodlok-716901/",
"https://www.ica.se/recept/syltad-zucchini-1076/",
"https://www.ica.se/recept/syltade-clementiner-692213/",
"https://www.ica.se/recept/vaffla-med-kalkonmousse-och-soltorkade-tomater-292903/",
"https://www.ica.se/recept/syltade-grona-tomater-2017/",
"https://www.ica.se/recept/syltade-rosennypon-412142/",
"https://www.ica.se/recept/wrap-med-grillad-karre-520089/",
"https://www.ica.se/recept/yoghurt-och-kumminmarinerad-kyckling-med-syltad-gurka-713516/",
"https://www.ica.se/recept/svart-vinbarssylt-med-paron-och-kanel-712788/",
"https://www.ica.se/recept/sotad-syltad-lok-643815/",
"https://www.ica.se/recept/rovartarta-med-glass-och-blabarssylt-618667/",
"https://www.ica.se/recept/rarord-vinbarssylt-534920/",
"https://www.ica.se/recept/rulltarta-med-stjarnanis-och-rodvinbarssylt-683491/",
"https://www.ica.se/recept/rabarbersylt-med-jordgubbar-534893/",
"https://www.ica.se/recept/vivekas-snabba-heta-fisk-561832/",
"https://www.ica.se/recept/vitlokssill-med-orter-och-citron-716591/",
"https://www.ica.se/recept/vitlokssill-1380/",
"https://www.ica.se/recept/vitlokscreme-624624/",
"https://www.ica.se/recept/vitloks-och-parmesanmajonnas-712990/",
"https://www.ica.se/recept/peach-melbasylt-712784/",
"https://www.ica.se/recept/vitloks-och-broccolisoppa-454051/",
"https://www.ica.se/recept/vitkalsstuvning-med-stekt-flask-265157/",
"https://www.ica.se/recept/vitkalsknyten-med-kummin-3953/",
"https://www.ica.se/recept/korsbarssylt-med-choklad-712779/",
"https://www.ica.se/recept/vitkal-med-creme-fraiche-kummin-och-senap-4369/",
"https://www.ica.se/recept/kiwisylt-5562/",
"https://www.ica.se/recept/vintersoppa-med-skaldjur-326/",
"https://www.ica.se/recept/jordgubbssylt-med-stjarnanis-671515/",
"https://www.ica.se/recept/jordgubbssylt-med-lavendel-712781/",
"https://www.ica.se/recept/inlagda-syltade-grona-tomater-572138/",
"https://www.ica.se/recept/vinkokt-skinka-med-orter-tips-vid-tidsbrist-5426/",
"https://www.ica.se/recept/viltskavsgryta-med-linser-och-kapris-715700/",
"https://www.ica.se/recept/grundrecept-sylt-534879/",
"https://www.ica.se/recept/viltpanna-med-svamp-och-rarorda-lingon-713161/",
"https://www.ica.se/recept/viltkryddad-farslimpa-med-rostad-pumpa-och-apple-713986/",
"https://www.ica.se/recept/vilda-norrlandskotletter-4125/",
"https://www.ica.se/recept/vild-pastasallad-581590/",
"https://www.ica.se/recept/vild-korv-stroganoff-499901/",
"https://www.ica.se/recept/wiggo-jerk-chicken-wrap-713406/",
"https://www.ica.se/recept/falsk-hjortronsylt-3174/",
"https://www.ica.se/recept/eivors-syltade-squash-och-paprika-454258/",
"https://www.ica.se/recept/vermouthfisk-med-fankal-996/",
"https://www.ica.se/recept/vegolasagne-714301/",
"https://www.ica.se/recept/vegogryta-fran-medelhavet-369475/",
"https://www.ica.se/recept/bjornbarssylt-med-gin-712783/",
"https://www.ica.se/recept/bjornbarssylt-farskost-537611/",
"https://www.ica.se/recept/vegetarisk-lasagne-med-gronkal-och-majrova-655135/",
"https://www.ica.se/recept/bakelse-med-rabarber-och-jordgubbssylt-och-vaniljcreme-fraiche-717173/",
"https://www.ica.se/recept/veggo-lasagne-653499/",
"https://www.ica.se/recept/vegetarisk-lasagne-715781/",
"https://www.ica.se/recept/varmrokt-fisk-med-syrade-gronsaker-715136/",
"https://www.ica.se/recept/varm-tomatsoppa-med-kallrokt-lax-och-graddfilsdipp-712827/",
"https://www.ica.se/recept/varma-agg-i-glas-med-purjolok-ansjovis-och-dill-713760/",
"https://www.ica.se/recept/varma-ost-och-skinkklammor-685969/",
"https://www.ica.se/recept/varm-appeltarta-5177/",
"https://www.ica.se/recept/varm-fiskfars-3453/",
"https://www.ica.se/recept/varm-avokadosoppa-698054/",
"https://www.ica.se/recept/vardagslyxlax-630012/",
"https://www.ica.se/recept/vackra-roda-godsaker-555186/",
"https://www.ica.se/recept/ugnsstekt-karre-med-smalokar-och-vin-714611/",
"https://www.ica.se/recept/ugnskyckling-med-vitlok-och-broccoli-449153/",
"https://www.ica.se/recept/ugnsstekt-kyckling-med-klyftpotatis-717111/",
"https://www.ica.se/recept/ugnsstekt-falukorv-med-rostade-rotfrukter-713615/",
"https://www.ica.se/recept/ugnspytt-med-senapskram-och-krispig-krassesallad-714658/",
"https://www.ica.se/recept/ugnsomelett-med-rostad-lok-och-bacon-697629/",
"https://www.ica.se/recept/ugnskyckling-med-vitlok-och-broccoli-712868/",
"https://www.ica.se/recept/ugnsbakat-dillkott-med-syrliga-morotter-633662/",
"https://www.ica.se/recept/ugnsbakad-lax-med-rokt-smak-och-farskpotatissallad-668866/",
"https://www.ica.se/recept/ugnsbakad-lax-med-limecreme-fraiche-688127/",
"https://www.ica.se/recept/ugnsbakad-lax-med-lime-och-tomat-713976/",
"https://www.ica.se/recept/tva-tips-till-grillat-583303/",
"https://www.ica.se/recept/tunnbrodsrulle-med-tonfisk-715186/",
"https://www.ica.se/recept/tunnbrodsrulle-med-surstromming-676944/",
"https://www.ica.se/recept/tunnbrodsrulle-med-potatis-agg-och-kaviar-716216/",
"https://www.ica.se/recept/tunnbrodsrulle-med-krossad-potatis-och-skinka-714550/",
"https://www.ica.se/recept/tunnbrodsrulle-i-folie-med-vasterbottensost-och-ruccola-713533/",
"https://www.ica.se/recept/tunnbrodsrullar-med-tonfisk-och-spenat-713506/",
"https://www.ica.se/recept/tunnbrodsrullar-med-rostbiff-och-rotsakssallad-564079/",
"https://www.ica.se/recept/tryfferade-champinjoner-525442/",
"https://www.ica.se/recept/tranbarsglaserat-majskycklingbrost-med-svamp-och-artsas-600607/",
"https://www.ica.se/recept/tortillapizza-med-kyckling-403592/",
"https://www.ica.se/recept/tortilla-med-potatis-och-ostfyllning-621639/",
"https://www.ica.se/recept/tortilla-med-lammstek-och-pumpapure-715298/",
"https://www.ica.se/recept/tortellini-med-sparris-och-bacon-328509/",
"https://www.ica.se/recept/tortellini-med-kyckling-och-paprikasas-679709/",
"https://www.ica.se/recept/torskfile-med-pepparrotscreme-och-rakor-594249/",
"https://www.ica.se/recept/torsk-med-morot-och-apelsin-716877/",
"https://www.ica.se/recept/torsk-med-kramig-paprika-714280/",
"https://www.ica.se/recept/torsk-med-citron-och-dragonsas-ris-och-morotspure-717440/",
"https://www.ica.se/recept/tonfisktacos-3737/",
"https://www.ica.se/recept/tonfiskrora-713928/",
"https://www.ica.se/recept/tonfiskrulle-716490/",
"https://www.ica.se/recept/tonfisklasagne-675670/",
"https://www.ica.se/recept/tonfiskgratang-med-tomater-4876/",
"https://www.ica.se/recept/tonfiskdip-med-chili-3353/",
"https://www.ica.se/recept/tomatsoppa-med-pasta-och-bacon-679722/",
"https://www.ica.se/recept/tomatsoppa-med-lax-musslor-712715/",
"https://www.ica.se/recept/tomatsoppa-med-chili-och-aprikoser-555636/",
"https://www.ica.se/recept/tomatsoppa-med-cashewnotter-2589/",
"https://www.ica.se/recept/tomatsoppa-med-basilikacreme-1777/",
"https://www.ica.se/recept/tomat-och-saffranssill-716931/",
"https://www.ica.se/recept/tomat-och-potatisgratang-341/",
"https://www.ica.se/recept/tomat-och-dillpaj-med-rakor-5013/",
"https://www.ica.se/recept/tomat-och-baconpasta-717047/",
"https://www.ica.se/recept/tomat-och-avokadobruschetta-med-skaldjur-och-dragoncreme-690284/",
"https://www.ica.se/recept/toast-med-rokta-rakor-629131/",
"https://www.ica.se/recept/toast-med-rakor-avokado-och-chili-716125/",
"https://www.ica.se/recept/timjankyckling-med-ruccolasas-531364/",
"https://www.ica.se/recept/timjan-och-citronkyckling-i-ruccolacreme-616215/",
"https://www.ica.se/recept/timbal-pa-pilgrimsmusslor-276751/",
"https://www.ica.se/recept/thaifisk-med-koriander-556430/",
"https://www.ica.se/recept/texmexpajer-333440/",
"https://www.ica.se/recept/tex-mex-baguetter-400290/",
"https://www.ica.se/recept/tarte-aux-oignons-5115/",
"https://www.ica.se/recept/tapenadekrutonger-2545/",
"https://www.ica.se/recept/tapenadecigarr-med-getostdipp-458501/",
"https://www.ica.se/recept/tandooriburgare-304511/",
"https://www.ica.se/recept/tagliatelle-med-champinjoner-vitlok-arter-och-parmesan-713256/",
"https://www.ica.se/recept/tacos-pa-svenska-469141/",
"https://www.ica.se/recept/tacos-med-kryddstekt-lax-och-salsa-tricolore-713100/",
"https://www.ica.se/recept/tacopaj-714198/",
"https://www.ica.se/recept/tacopaj-713200/",
"https://www.ica.se/recept/tacokryddad-kycklinglasagne-659942/",
"https://www.ica.se/recept/tacobiff-med-salsasas-och-sallad-567269/",
"https://www.ica.se/recept/sotpotatissallad-med-kokos-och-lime-717489/",
"https://www.ica.se/recept/sot-drom-med-pistagekram-671193/",
"https://www.ica.se/recept/sas-till-inkokt-lax-1541/",
"https://www.ica.se/recept/sas-till-gravad-lax-5283/",
"https://www.ica.se/recept/syrlig-vaniljsas-med-citron-2951/",
"https://www.ica.se/recept/sydfranska-gronsaker-med-fisk-och-citron-668662/",
"https://www.ica.se/recept/sydafrikanska-soaties-med-koriandermos-och-grillad-mango-426765/",
"https://www.ica.se/recept/svenssons-kaviarsnurror-5372/",
"https://www.ica.se/recept/sweetchiliwok-med-pasta-2853/",
"https://www.ica.se/recept/sweet-chili-sas-till-ingefarsgravad-lax-1542/",
"https://www.ica.se/recept/sweet-chilikram-712650/",
"https://www.ica.se/recept/sweet-chilifisksoppa-1624/",
"https://www.ica.se/recept/svartpepparstekt-flaskytterfile-med-apelsinglacerade-morotter-och-dragoncreme-684660/",
"https://www.ica.se/recept/svamppizza-med-kyckling-timjan-och-schalottenlok-715303/",
"https://www.ica.se/recept/svamplasagne-med-tomat-och-mozzarella-714672/",
"https://www.ica.se/recept/svamp-och-selleribiffar-714242/",
"https://www.ica.se/recept/svamp-och-potatissoppa-4690/",
"https://www.ica.se/recept/rabarber-och-jordgubbsmarmelad-med-lime-612195/",
"https://www.ica.se/recept/svamp-och-parmesanoverbakad-file-med-potatisterrine-och-balsamicosky-714310/",
"https://www.ica.se/recept/svamp-och-farsbiffar-med-pasta-426158/",
"https://www.ica.se/recept/suveran-paj-2034/",
"https://www.ica.se/recept/sushi-pa-svenska-345202/",
"https://www.ica.se/recept/susannes-vilda-sas-714215/",
"https://www.ica.se/recept/supersnabb-korvcouscous-630042/",
"https://www.ica.se/recept/burgare-med-bonrora-716669/",
"https://www.ica.se/recept/buljongkokt-falukorv-med-tomat-och-basilikacreme-fraiche-113741/",
"https://www.ica.se/recept/brackt-rimmad-oxbringa-rostade-rotfrukter-och-senapscreme-1156/",
"https://www.ica.se/recept/brackt-oxbringa-med-rotfrukter-och-ortcreme-633484/",
"https://www.ica.se/recept/brackt-kassler-med-hostwok-och-basilikakram-3285/",
"https://www.ica.se/recept/broccolisoppa-med-italienska-smaker-711988/",
"https://www.ica.se/recept/broccolifylld-lovbiff-1074/",
"https://www.ica.se/recept/broccoli-och-ostsoppa-med-rakklamma-714572/",
"https://www.ica.se/recept/broccoli-och-mandelsoppa-717290/",
"https://www.ica.se/recept/britas-fisk-och-skaldjurssoppa-464923/",
"https://www.ica.se/recept/bratwurst-med-kalrabbi-4194/",
"https://www.ica.se/recept/bookmaker-toast-med-pepparrotskram-och-frasiga-lokringar-714152/",
"https://www.ica.se/recept/blomkalstimbal-med-radissallad-9/",
"https://www.ica.se/recept/ortig-blomkalssoppa-50360/",
"https://www.ica.se/recept/blomkalspure-557779/",
"https://www.ica.se/recept/blomkalsgratang-med-knaperstekt-bacon-713393/",
"https://www.ica.se/recept/blomkalsdipp-674239/",
"https://www.ica.se/recept/biffcrostini-357916/",
"https://www.ica.se/recept/biff-stroganoff-713113/",
"https://www.ica.se/recept/biff-oriental-715568/",
"https://www.ica.se/recept/biff-med-rotselleripure-picklad-rodlok-och-betor-714233/",
"https://www.ica.se/recept/biff-med-karljohancreme-och-rostade-mandelpotatisskivor-647326/",
"https://www.ica.se/recept/biff-med-cajunrubbing-pa-ljummen-potatisbadd-713526/",
"https://www.ica.se/recept/bellaverde-med-kramig-pasta-716386/",
"https://www.ica.se/recept/beer-can-chicken-med-coleslaw-716100/",
"https://www.ica.se/recept/beef-barbeque-713407/",
"https://www.ica.se/recept/bbq-marinerad-oxfile-med-vitlokskram-713707/",
"https://www.ica.se/recept/bbq-kyckling-med-appel-och-sellerisallad-524857/",
"https://www.ica.se/recept/bbq-griljerad-kassler-med-bluecheesesas-387579/",
"https://www.ica.se/recept/bbq-kyckling-med-gronkalscole-slaw-717122/",
"https://www.ica.se/recept/basilikagravad-stromming-1705/",
"https://www.ica.se/recept/basilikadoftande-kycklinggryta-med-potatis-och-broccolimos-717439/",
"https://www.ica.se/recept/basilikadoftande-kyckling-med-pressad-potatis-715703/",
"https://www.ica.se/recept/basilikadoftande-kyckling-i-ugn-med-tomatsallad-713625/",
"https://www.ica.se/recept/barbecueburgare-med-kalrotsslaw-714188/",
"https://www.ica.se/recept/banancheesecake-med-jordgubbar-713912/",
"https://www.ica.se/recept/balsamicorostad-kycklingfile-med-morotter-och-fetaostrora-715078/",
"https://www.ica.se/recept/bakpotatis-med-kryddig-skinkrora-611977/",
"https://www.ica.se/recept/baked-artichoke-varm-kronartsskocksdipp-714006/",
"https://www.ica.se/recept/bakad-sotpotatis-med-fetostkram-3619/",
"https://www.ica.se/recept/bakad-potatis-med-skagenrora-3707/",
"https://www.ica.se/recept/bakad-potatis-med-gront-265188/",
"https://www.ica.se/recept/baguette-med-rakrora-och-avokado-715105/",
"https://www.ica.se/recept/baconburgare-med-blue-cheesedressing-och-grillat-paron-714888/",
"https://www.ica.se/recept/baconburgare-i-baguette-med-paprikadipp-713727/",
"https://www.ica.se/recept/bacon-och-haricots-verts-sas-487712/",
"https://www.ica.se/recept/avokadosoppa-a-la-creme-224639/",
"https://www.ica.se/recept/avokadosoppa-retro-378633/",
"https://www.ica.se/recept/avokadosandwiches-459/",
"https://www.ica.se/recept/avokadosalsa-grill-520084/",
"https://www.ica.se/recept/avokadosalsa-2594/",
"https://www.ica.se/recept/avokadorisoni-med-persika-och-myntasas-369424/",
"https://www.ica.se/recept/avokadokram-306874/",
"https://www.ica.se/recept/avokadofylld-paj-med-rakor-914/",
"https://www.ica.se/recept/avokadoburgare-883/",
"https://www.ica.se/recept/avokado-och-rakrora-302846/",
"https://www.ica.se/recept/avokado-med-rakrora-716410/",
"https://www.ica.se/recept/augustisoppa-5028/",
"https://www.ica.se/recept/auberginekram-525522/",
"https://www.ica.se/recept/auberginedip-842/",
"https://www.ica.se/recept/asiatisk-sill-284609/",
"https://www.ica.se/recept/apelsinsoppa-499944/",
"https://www.ica.se/recept/apelsinsmakande-gronsaker-964/",
"https://www.ica.se/recept/apelsinkryddad-skinkgryta-454370/",
"https://www.ica.se/recept/apelsinbakad-fisk-med-kramiga-tomater-717316/",
"https://www.ica.se/recept/apelsin-och-spenatfisk-665430/",
"https://www.ica.se/recept/apelsin-och-pepparkakscheesecake-4425/",
"https://www.ica.se/recept/apelsin-och-nejlikespjall-med-appelcreme-716860/",
"https://www.ica.se/recept/anvandbara-roran-953/",
"https://www.ica.se/recept/ansjovissas-1990/",
"https://www.ica.se/recept/ansjovisrora-med-salladslok-437/",
"https://www.ica.se/recept/lokfyllda-enchiladas-171279/",
"https://www.ica.se/recept/spagetti-med-tomat-sardeller-kapris-och-oliver-169216/",
"https://www.ica.se/recept/enchiladas-a-la-mexiko-167776/",
"https://www.ica.se/recept/gratinerade-tortillaknyten-med-kyckling-och-spenat-165215/",
"https://www.ica.se/recept/langos-164027/",
"https://www.ica.se/recept/grillade-lammkotletter-med-honungsrostade-vitloksklyftor-163969/",
"https://www.ica.se/recept/fisk-i-form-med-apple-lok-och-curry-163645/",
"https://www.ica.se/recept/skarbonor-i-panna-med-tomat-och-vitlok-151040/",
"https://www.ica.se/recept/haricots-verts-med-vitlokskrutonger-och-nobissas-149599/",
"https://www.ica.se/recept/kall-soppa-pa-rostade-tomater-132972/",
"https://www.ica.se/recept/kyckling-och-rotfruktspajer-131801/",
"https://www.ica.se/recept/paprikapaj-131178/",
"https://www.ica.se/recept/laxrora-med-potatis-126769/",
"https://www.ica.se/recept/fisk-och-skaldjursgryta-124959/",
"https://www.ica.se/recept/sparris-och-ostpastejer-117190/",
"https://www.ica.se/recept/mostackt-skavgratang-50378/",
"https://www.ica.se/recept/het-avokadokram-med-notter-50117/",
"https://www.ica.se/recept/chiligrillade-kottspett-50025/",
"https://www.ica.se/recept/nonnas-jordgubbs-och-rabarbersaft-4022/",
"https://www.ica.se/recept/basilikabiff-4001/",
"https://www.ica.se/recept/spanska-fisken-3277/",
"https://www.ica.se/recept/risotto-pa-pumpa-2633/",
"https://www.ica.se/recept/kryddig-appelkaka-2523/",
"https://www.ica.se/recept/je-te-tiens-par-la-queue-jag-haller-dig-i-stjarten-1833/",
"https://www.ica.se/recept/pasta-med-sparris-och-rakor-1288/",
"https://www.ica.se/recept/ortsas-med-honung-1244/",
"https://www.ica.se/recept/tomatsas-1229/",
"https://www.ica.se/recept/palsternackssallad-med-russin-1194/",
"https://www.ica.se/recept/kottgryta-habanero-1022/",
"https://www.ica.se/recept/kyckling-diavolo-1021/",
"https://www.ica.se/recept/paj-med-papaya-och-kyckling-861/",
"https://www.ica.se/recept/nasselsoppa-408/",
"https://www.ica.se/recept/irlandsk-gryta-310/",
"https://www.ica.se/recept/potatissoppa-med-mangold-och-smulad-fetaost-31/",
"https://www.ica.se/recept/appelsallad-med-honungsvinagrett-2098/",
"https://www.ica.se/recept/appel-och-chevregravad-stromming-555064/",
"https://www.ica.se/recept/adelostfylld-kyckling-med-appel-och-sellerisallad-261485/",
"https://www.ica.se/recept/vietnamesisk-nudelwrap-i-sallad-716012/",
"https://www.ica.se/recept/ugnsbrasserade-revben-med-asiatisk-glaze-och-nudelsallad-714644/",
"https://www.ica.se/recept/tomatsallad-med-ruccola-567244/",
"https://www.ica.se/recept/tex-mex-dinner-714610/",
"https://www.ica.se/recept/sotsur-asiatisk-sojasas-50095/",
"https://www.ica.se/recept/stekt-korv-med-ratatouille-och-timjansenap-714537/",
"https://www.ica.se/recept/spenatsallad-med-adelost-och-aprikoser-712726/",
"https://www.ica.se/recept/senapssas-715797/",
"https://www.ica.se/recept/rodbetssallad-fran-nice-3052/",
"https://www.ica.se/recept/quornbiffar-712629/",
"https://www.ica.se/recept/picknick-piroger-418561/",
"https://www.ica.se/recept/melon-med-honungsyoghurt-712811/",
"https://www.ica.se/recept/matjessill-med-brynt-smor-424345/",
"https://www.ica.se/recept/lokdolmar-714377/",
"https://www.ica.se/recept/laxtartar-med-gurka-och-krasse-716149/",
"https://www.ica.se/recept/rosepeppargrillad-lax-med-ansjovisdipp-717448/",
"https://www.ica.se/recept/vit-chokladkram-med-lime-och-bar-717392/",
"https://www.ica.se/recept/kramig-polenta-med-vit-choklad-716322/",
"https://www.ica.se/recept/kryddiga-snacksnotter-713632/",
"https://www.ica.se/recept/kalvfarsbiffar-med-sotsyrlig-morotssallad-713292/",
"https://www.ica.se/recept/juniorburgare-med-grillad-falukorv-och-currycoleslaw-50256/",
"https://www.ica.se/recept/jordgubbar-med-knackig-pistage-630269/",
"https://www.ica.se/recept/ingefars-och-vaniljglass-668608/",
"https://www.ica.se/recept/hogrev-med-sojapicklad-svamp-och-wasabimajonas-717136/",
"https://www.ica.se/recept/honungsrostad-not-och-fromix-713468/",
"https://www.ica.se/recept/honungsglaserad-vildsvinsstek-700252/",
"https://www.ica.se/recept/hallon-och-blabarssmoothie-med-havregryn-715990/",
"https://www.ica.se/recept/lax-och-romtarta-713886/",
"https://www.ica.se/recept/langgrillade-oxspjall-717766/",
"https://www.ica.se/recept/ortsmorsfylld-lammburgare-717757/",
"https://www.ica.se/recept/ortslungad-farskpotatis-717747/",
"https://www.ica.se/recept/tre-laskande-sommardrinkar-717787/",
"https://www.ica.se/recept/skogssmoothie-med-lingon-och-kardemumma-717778/",
"https://www.ica.se/recept/variation-pa-morot-717755/",
"https://www.ica.se/recept/primorbetor-getyoghurt-och-smulat-isterband-717754/",
"https://www.ica.se/recept/ljumna-primorer-med-smulad-ost-och-rostade-notter-717749/",
"https://www.ica.se/recept/lyxig-chokladkaka-med-sommarbar-717753/",
"https://www.ica.se/recept/pannacotta-med-choklad-och-bar-717786/",
"https://www.ica.se/recept/lakritsbrownie-med-citronmousse-och-bar-717785/",
"https://www.ica.se/recept/strutar-med-lingongradde-717784/",
"https://www.ica.se/recept/barmuffins-med-frosting-och-notkrisp-717783/",
"https://www.ica.se/recept/glutenfri-sommarpaj-med-knacktacke-717781/",
"https://www.ica.se/recept/brytbrod-med-havre-och-rag-717780/",
"https://www.ica.se/recept/spenatsallad-med-adelost-och-tranbar-717779/",
"https://www.ica.se/recept/hemgjord-nyponsoppa-med-apelsin-717776/",
"https://www.ica.se/recept/sommarpasta-med-salsa-verde-och-lufttorkad-skinka-717775/",
"https://www.ica.se/recept/honungsstekt-halloumi-och-citronslungade-bonor-717774/",
"https://www.ica.se/recept/caponata-717773/",
"https://www.ica.se/recept/pizza-med-sparris-och-vasterbottenskram-717772/",
"https://www.ica.se/recept/aggsallad-med-tonfisk-pa-rostat-brod-717771/",
"https://www.ica.se/recept/barbecuegrillade-revbensspjall-717768/",
"https://www.ica.se/recept/paprika-och-chilirub-717765/",
"https://www.ica.se/recept/tikka-masala-716082/",
"https://www.ica.se/recept/pepparlax-717769/",
"https://www.ica.se/recept/ortmarinad-717764/",
"https://www.ica.se/recept/ingefars-och-sesammarinad-717763/",
"https://www.ica.se/recept/ortsmor-med-chili-717762/",
"https://www.ica.se/recept/pepparrotscreme-717761/",
"https://www.ica.se/recept/kaffe-och-konjaksglaze-717760/",
"https://www.ica.se/recept/bourbon-och-ananasglaze-717759/",
"https://www.ica.se/recept/ortmarinerad-grillkyckling-717758/",
"https://www.ica.se/recept/gos-med-brynt-matjessmor-717756/",
"https://www.ica.se/recept/sommarsparris-med-tryffelsmor-717752/",
"https://www.ica.se/recept/klassisk-gotlandslimpa-717751/",
"https://www.ica.se/recept/gubbrora-med-kapris-717750/",
"https://www.ica.se/recept/rosegravad-lax-med-dillkram-717748/",
"https://www.ica.se/recept/zetterstroms-favoritsill-717746/",
"https://www.ica.se/recept/sesamgrillade-morotter-med-lime-och-ingefara-717744/",
"https://www.ica.se/recept/smorfrasta-morotter-med-vitlok-och-chili-717743/",
"https://www.ica.se/recept/rahyvlad-morot-med-apelsin-russin-och-mynta-717742/",
"https://www.ica.se/recept/grillad-ananas-med-kokoshonung-713553/",
"https://www.ica.se/recept/getostsas-50273/",
"https://www.ica.se/recept/farskpotatissallad-med-pepparrot-citron-och-kapris-713868/",
"https://www.ica.se/recept/fetaspread-med-valnotter-714797/",
"https://www.ica.se/recept/feta-och-melonsallad-625017/",
"https://www.ica.se/recept/elenas-eleganta-efterratt-349116/",
"https://www.ica.se/recept/desserttallrik-715792/",
"https://www.ica.se/recept/cranachan-714367/",
"https://www.ica.se/recept/citron-och-vitloksmarinerad-kycklingfile-med-potatis-och-sparrissallad-712610/",
"https://www.ica.se/recept/ciabatta-med-rokt-skinka-citronrostad-fankal-fetaost-och-oliver-617829/",
"https://www.ica.se/recept/chorizosallad-607328/",
"https://www.ica.se/recept/choklad-och-notrora-med-frukt-714436/",
"https://www.ica.se/recept/chilikyckling-med-pak-soi-och-sesammajonnas-717121/",
"https://www.ica.se/recept/burgers-med-klyftisar-och-bluecheesesas-674354/",
"https://www.ica.se/recept/balsamicofile-med-tryffelkantareller-589180/",
"https://www.ica.se/recept/citronpaj-717251/",
"https://www.ica.se/recept/rabarber-med-vit-chokladgradde-och-grillad-sockerkaka-717647/",
"https://www.ica.se/recept/stekta-svampdumlings-med-dippsas-717824/",
"https://www.ica.se/recept/dubbelmarinerad-flaskfile-714796/",
"https://www.ica.se/recept/ortprickig-dijonsill-670795/",
"https://www.ica.se/recept/appelsenap-714453/",
"https://www.ica.se/recept/yoghurt-shake-med-jordgubbar-715246/",
"https://www.ica.se/recept/yoghurt-med-rarivet-paron-och-ingefarshonung-715823/",
"https://www.ica.se/recept/varprimorer-med-senapsdressing-714791/",
"https://www.ica.se/recept/vintersallad-med-rotfrukter-pumpa-och-honungsnotter-714738/",
"https://www.ica.se/recept/ugnsbakade-rotfrukter-med-rosmarinlamm-3290/",
"https://www.ica.se/recept/ugnsbakad-lax-med-pumpafrotacke-och-rodloksmarmelad-715901/",
"https://www.ica.se/recept/ugnsbakad-fisk-med-tomatsalsa-291640/",
"https://www.ica.se/recept/somriga-grillgronsaker-673089/",
"https://www.ica.se/recept/sommarbar-med-lime-och-myntakryddad-honungsyoghurt-418941/",
"https://www.ica.se/recept/sojafrast-broccolisallad-med-rodkal-bulgur-och-sesamkyckling-715893/",
"https://www.ica.se/recept/smorrebrod-med-rokt-kalkon-och-lokmarmelad-672747/",
"https://www.ica.se/recept/smoothie-med-avokado-och-hallon-715843/",
"https://www.ica.se/recept/signes-sota-chokladdryck-med-vanilj-och-kanel-714448/",
"https://www.ica.se/recept/sallad-pa-halstrad-fiskfile-dressing-399292/",
"https://www.ica.se/recept/saffransscones-716771/",
"https://www.ica.se/recept/rodbets-och-chevreknyten-713237/",
"https://www.ica.se/recept/rakspett-3468/",
"https://www.ica.se/recept/radiskimchi-med-kyckling-och-sesam-716621/",
"https://www.ica.se/recept/rotfrukter-med-ost-och-nottacke-714222/",
"https://www.ica.se/recept/rostbiff-i-marinad-med-farska-orter-536763/",
"https://www.ica.se/recept/rostade-gronsaker-med-spiskummin-och-sesamfron-551571/",
"https://www.ica.se/recept/rostad-kyckling-syrlig-gurka-och-sotpotatispure-715958/",
"https://www.ica.se/recept/rosmarinkyckling-med-rostad-potatis-715067/",
"https://www.ica.se/recept/rosmarindoftande-rodbetsvaffla-med-fetaost-701271/",
"https://www.ica.se/recept/risgrynsyoghurt-med-applen-och-valnotter-698337/",
"https://www.ica.se/recept/potatissallad-med-varprimorer-715023/",
"https://www.ica.se/recept/potatispannkaka-och-blabarscottage-cheese-714741/",
"https://www.ica.se/recept/potatis-och-ortspett-med-kyckling-3087/",
"https://www.ica.se/recept/plattbakelser-med-frukt-534346/",
"https://www.ica.se/recept/pepparkakssnittar-med-ost-och-fikon-717013/",
"https://www.ica.se/recept/ostrulle-med-valnotter-2333/",
"https://www.ica.se/recept/ostkaka-med-granatapple-jordgubbar-och-pistagenotter-620633/",
"https://www.ica.se/recept/musli-713871/",
"https://www.ica.se/recept/myntasas-717302/",
"https://www.ica.se/recept/morots-och-appelrutor-716949/",
"https://www.ica.se/recept/morots-och-palsternacksbrod-med-oliver-717117/",
"https://www.ica.se/recept/morgonkick-713464/",
"https://www.ica.se/recept/memphis-style-ribs-med-grillad-potatissallad-och-coleslaw-med-valnotter-716665/",
"https://www.ica.se/recept/melon-och-fetaostspett-712722/",
"https://www.ica.se/recept/matig-tradgardssallad-643964/",
"https://www.ica.se/recept/marangsviss-med-bar-714466/",
"https://www.ica.se/recept/marockansk-farsgryta-med-myntayoghurt-714663/",
"https://www.ica.se/recept/marinerade-bonor-537809/",
"https://www.ica.se/recept/marinerad-flaskkarre-365050/",
"https://www.ica.se/recept/mangosmoothie-med-clementin-och-kardemumma-717083/",
"https://www.ica.se/recept/mangoraja-621523/",
"https://www.ica.se/recept/mangoraja-715007/",
"https://www.ica.se/recept/mango-och-hallon-smoothie-med-havredryck-716143/",
"https://www.ica.se/recept/mandelpotatisvaffla-med-siksallad-701938/",
"https://www.ica.se/recept/mandelbiskviparfait-med-honungsrabarber-3070/",
"https://www.ica.se/recept/majsrelish-3388/",
"https://www.ica.se/recept/loksoppgryta-fran-ost-171137/",
"https://www.ica.se/recept/lattfrusen-appelyoghurt-716835/",
"https://www.ica.se/recept/latt-appeldessert-537565/",
"https://www.ica.se/recept/langbakad-grissida-med-morotspure-699567/",
"https://www.ica.se/recept/ljummen-varprimorssallad-med-halloumi-kalkon-och-dragonsas-617180/",
"https://www.ica.se/recept/ljummen-potatissallad-med-rakor-och-sparris-712636/",
"https://www.ica.se/recept/gyros-med-syrlig-paprikasallad-717798/",
"https://www.ica.se/recept/torsk-med-ljummen-tomat-och-sparrissallad-717797/",
"https://www.ica.se/recept/paella-717796/",
"https://www.ica.se/recept/lammfarsbiffar-med-fetaost-och-rosmarin-717795/",
"https://www.ica.se/recept/pasta-med-strimlad-ryggbiff-717794/",
"https://www.ica.se/recept/ugnsgrillad-kycklingklubba-med-coleslaw-717793/",
"https://www.ica.se/recept/stekt-bratwurst-med-grasloksstuvad-potatis-717792/",
"https://www.ica.se/recept/jarpar-med-tomat-och-olivsas-717791/",
"https://www.ica.se/recept/kassler-med-currystekt-blomkal-och-grasloksyoghurt-717790/",
"https://www.ica.se/recept/lovbiff-med-oliv-och-mandelpicada-717741/",
"https://www.ica.se/recept/spatta-med-rodloksgremolata-717740/",
"https://www.ica.se/recept/ljummen-potatissallad-med-brynt-smor-och-pepparlax-716219/",
"https://www.ica.se/recept/ljummen-ostsallad-med-bakad-broccoli-716895/",
"https://www.ica.se/recept/ljummen-farskpotatissallad-med-vinagrett-pa-bakad-vitlok-716508/",
"https://www.ica.se/recept/lingon-och-paronsmoothie-716566/",
"https://www.ica.se/recept/lime-och-honungssas-3470/",
"https://www.ica.se/recept/lime-och-blabarssmoothie-med-chiafron-och-havredryck-717082/",
"https://www.ica.se/recept/laxtallrik-715789/",
"https://www.ica.se/recept/laxspett-med-kimchi-och-sesamfron-716110/",
"https://www.ica.se/recept/laxcrostini-med-sojamajonnas-717178/",
"https://www.ica.se/recept/laxcarpaccio-med-pomelo-och-citrusvinagrett-714709/",
"https://www.ica.se/recept/laxbakelse-med-avokado-och-apple-713234/",
"https://www.ica.se/recept/lammstek-pa-skoglunds-vis-713046/",
"https://www.ica.se/recept/lammkorv-med-glaserade-rotfrukter-och-apple-695463/",
"https://www.ica.se/recept/korsbarstomat-med-tryffelcreme-och-timjan-651469/",
"https://www.ica.se/recept/kycklingwraps-med-fetacreme-713665/",
"https://www.ica.se/recept/kycklingsallad-med-hel-dinkel-716033/",
"https://www.ica.se/recept/kycklinglar-bbq-med-matvete-och-gronsaker-669736/",
"https://www.ica.se/recept/kyckling-pa-pinne-716280/",
"https://www.ica.se/recept/kyckling-och-angade-gronsaker-659762/",
"https://www.ica.se/recept/kramiga-sillar-668895/",
"https://www.ica.se/recept/kramig-julost-med-notter-4395/",
"https://www.ica.se/recept/kryddig-yoghurtpannacotta-med-hallon-651769/",
"https://www.ica.se/recept/kotlett-med-fankal-och-rispilaff-715345/",
"https://www.ica.se/recept/korv-med-potatissallad-i-senapsvinagrett-713604/",
"https://www.ica.se/recept/knaprig-musli-med-mandel-och-russin-422324/",
"https://www.ica.se/recept/kiwisalsa-med-mynta-421251/",
"https://www.ica.se/recept/kikartsfars-med-ruccolayoghurt-4472/",
"https://www.ica.se/recept/jordgubbstarta-531293/",
"https://www.ica.se/recept/hummer-naturell-med-tre-saser-3475/",
"https://www.ica.se/recept/honungssotad-mascarpone-med-frukt-och-amaretto-5554/",
"https://www.ica.se/recept/honungsrostad-havre-712694/",
"https://www.ica.se/recept/honungsgrillad-majskyckling-med-rostad-pumpa-714765/",
"https://www.ica.se/recept/honungsglacerat-kycklingbrost-med-solrospasta-617263/",
"https://www.ica.se/recept/honungs-sesamrostad-kyckling-589858/",
"https://www.ica.se/recept/couscoussallad-med-kyckling-och-pumpafron-716379/",
"https://www.ica.se/recept/lasagne-med-mozzarellasallad-717729/",
"https://www.ica.se/recept/timjansstekt-potatis-med-rostas-och-getost-717593/",
"https://www.ica.se/recept/ort-och-senapsfylld-kyckling-med-ratatouille-598573/",
"https://www.ica.se/recept/algfarssoppa-701743/",
"https://www.ica.se/recept/zucchinigratang-med-sallad-och-flaskstrimlor-714777/",
"https://www.ica.se/recept/viltgulasch-med-vitlokskram-715957/",
"https://www.ica.se/recept/vegobouillabaisse-715262/",
"https://www.ica.se/recept/veggosas-487786/",
"https://www.ica.se/recept/veggopizza-med-aubergine-och-paprika-712633/",
"https://www.ica.se/recept/veggochili-med-falafel-och-yoghurt-713403/",
"https://www.ica.se/recept/vegetarisk-stroganoff-716672/",
"https://www.ica.se/recept/vegetarisk-spaghetti-bolognese-716674/",
"https://www.ica.se/recept/vegetarisk-lasagne-med-kryddiga-rotfrukter-698538/",
"https://www.ica.se/recept/vegetarisk-lasagne-3805/",
"https://www.ica.se/recept/veenas-vindaloo-5450/",
"https://www.ica.se/recept/variant-pa-kottfarssas-med-chili-och-basilika-697092/",
"https://www.ica.se/recept/ungersk-kottgryta-med-korv-och-paprika-717383/",
"https://www.ica.se/recept/ungersk-kottgryta-426/",
"https://www.ica.se/recept/ugnsrostad-zucchini-med-godsaker-617246/",
"https://www.ica.se/recept/ugnsbraserad-margpipa-med-bonor-chili-och-bacon-713293/",
"https://www.ica.se/recept/ugnsbakad-sej-under-orttacke-med-ratatouille-714101/",
"https://www.ica.se/recept/ugnsbakad-fetaost-520278/",
"https://www.ica.se/recept/tunnbrodsenchiladas-med-ananassalsa-714170/",
"https://www.ica.se/recept/tortillapizza-med-parmaskinka-281365/",
"https://www.ica.se/recept/tortillagratang-715951/",
"https://www.ica.se/recept/tortellini-med-ricottaost-497410/",
"https://www.ica.se/recept/torsk-med-squash-och-tomater-550434/",
"https://www.ica.se/recept/torsk-med-musselsas-713000/",
"https://www.ica.se/recept/torsdagssoppan-pa-mitt-satt-225231/",
"https://www.ica.se/recept/tonfiskrora-med-tomat-och-kapris-541224/",
"https://www.ica.se/recept/tonfisk-och-tomatsas-487736/"];

let filename = "ica/updateAll9-2018-06-21.json";

nightmare
    .goto('https://www.ica.se/recept')
    .evaluate(function () {

    })
    .then(function (hrefs) {

        console.log("start");
        console.log("nr of urls: " + urls.length);
        uniqurls = [...new Set(urls)];
        console.log("uniq : " + uniqurls.length);
        return uniqurls.reduce(function (accumulator, href) {
            return accumulator.then(function (results) {
                return nightmare.goto(href)
                    .evaluate(function () {
                        if (!document.querySelector('.recipepage main.container--main')) {
                            return;
                        }
                        let recipe = {};
                        //title
                        recipe.title = document.querySelector('.recipepage header h1.recipepage__headline').innerHTML.trim();
                        //tags
                        let tags = {};
                        //cannot read property length of null
                        $('.related-recipes .related-recipe-tags__container a').each(function () {
                            let t = $(this).text();
                            if (t.match(/[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]/g)) {
                                t = t + "FAILEDTAG";
                            }
                            tags[t.charAt(0).toUpperCase() + t.slice(1).replace(/\s*\([^()]*\)/g, '').split(",")[0].replace(/([/.#$])/g, '').trim()] = true;

                        })
                        recipe.tags = tags;
                        //source
                        recipe.source = window.location.href;
                        recipe.source = recipe.source.substr(recipe.source.indexOf("ica.se"));
                        //rating
                        recipe.rating = document.querySelector('.recipepage header .recipe-header a.rating-stars').getAttribute("title");
                        //votes
                        recipe.votes = document.querySelector('.recipepage header .recipe-header a.rating-stars .recipe-meta .js-number-of-votes').innerHTML;
                        //author
                        recipe.author = "ICA";
                        //createdFor
                        if (document.querySelector('.recipepage .magazine-row a.magazine-row__link')) {
                            if (document.querySelector('.recipepage .magazine-row a.magazine-row__link').getAttribute("href") === "/buffe/") {
                                recipe.createdFor = "Buffé";
                            }
                        }
                        //portions  "4småpotioner" trattkantarellsoppan. replace alla bokstäver med ""?
                        if (document.querySelector('.recipepage .servings-picker')) {
                            recipe.portions = document.querySelector('.recipepage .servings-picker').getAttribute('data-default-portions');
                        }
                        //created

                        //description
                        if (document.querySelector('.recipepage p.recipe-preamble')) {
                            recipe.description = document.querySelector('.recipepage p.recipe-preamble').innerHTML.replace(/(\r\n|\n|\r|<[^>]*>)/gm, "").replace(/  +/g, ' ').trim();
                        }
                        //time and difficulty
                        if (document.querySelector('.recipepage .recipe-meta.recipe-meta--header')) {
                            let timeDiff = document.querySelector('.recipepage .recipe-meta.recipe-meta--header').innerHTML.replace(/(\r\n|\n|\r|<[^>]*>)/gm, "").trim().split(" | ");
                            let diff = timeDiff[1];
                            //diff
                            if (diff === "Enkel") {
                                recipe.level = 1;
                            } else if (diff === "Medel") {
                                recipe.level = 2;
                            } else if (diff === "Avancerad") {
                                recipe.level = 3;
                            } else {
                                recipe.level = "FAILEDLEVEL"
                            }
                            //time
                            let timeString = timeDiff[0];
                            if (timeString.indexOf("MIN") > -1) {
                                recipe.time = timeString.split(" ")[0] - 0;
                            } else if (timeString.indexOf("TIM")) {
                                let parts = timeString.split(" ")[0].split("-");
                                if (parts.length === 1) {
                                    recipe.time = (timeString.split(" ")[0] - 0) * 60;
                                } else {
                                    recipe.time = (((parts[0] - 0) + (parts[1] - 0)) / 2) * 60;
                                }
                            } else {
                                return;
                            }
                            if (recipe.time < 25) {
                                if (!tags.hasOwnProperty('Snabbt')) {
                                    tags["Snabbt"] = true;
                                }
                            }
                        }
                        //ingredients
                        if (document.querySelector('.recipepage #ingredients-section .ingredients__content .ingredients__list .ingredients__list__item')) {
                            let ingredientsDom = document.querySelector('.recipepage #ingredients-section .ingredients__content').getElementsByTagName("li");
                            let ingredients = [];
                            let ingredientNames = [];
                            for (let i = 0; i < ingredientsDom.length; ++i) {
                                let ingredient = {};
                                let innerHtml = ingredientsDom[i].innerHTML;
                                ingredient.amount = ingredientsDom[i].getElementsByTagName("span")[0].innerHTML.trim();
                                if (ingredient.amount.indexOf("\/")) {
                                    var y = ingredient.amount.split(' ');
                                    if (y.length > 1) {
                                        var z = y[1].split('/');
                                        ingredient.amount = +y[0] + (z[0] / z[1]) + "";
                                    }
                                    else {
                                        var z = y[0].split('/');
                                        if (z.length > 1) {
                                            ingredient.amount = z[0] / z[1] + "";
                                        }
                                        else {
                                            ingredient.amount = z[0] + "";
                                        }
                                    }
                                }



                                let parts = innerHtml.slice(innerHtml.indexOf("</span>") + 7).split(" ");
                                ingredient.unit = parts[1];

                                let namepart = innerHtml.slice(innerHtml.indexOf(parts[2] === "st" ? parts[3] : parts[2])).trim();

                                ingredient.name = namepart.charAt(0).toUpperCase() + namepart.slice(1).replace(/\s*\([^()]*\)/g, '').split(",")[0].replace(/([/.#$])/g, '').trim();
                                if (ingredientNames.indexOf(ingredient.name) > -1) {
                                    continue;
                                }

                                if(ingredient.amount.trim()==""){
                                    delete ingredient.amount;
                                }
                                if(ingredient.unit.trim()==""){
                                    delete ingredient.unit;
                                }
                                ingredientNames.push(ingredient.name);
                                ingredients.push(ingredient);



                                //måste göra om till innerHTML och ta ut det som ligger i spanet till amount 
                                //och det andra får först trimmas och sen splitas på " " och ta ut [0] till unit

                            }
                            recipe.ingredients = ingredients;
                        }
                        else if (document.querySelector('.recipepage #ingredients-section ul li span.ingredient')) {
                            let ingredientsDom = document.querySelector('.recipepage #ingredients-section').getElementsByClassName("ingredient");
                            let ingredients = [];
                            let ingredientNames = [];
                            for (let i = 0; i < ingredientsDom.length; ++i) {
                                let ingredient = {};
                                let ingredientDom = ingredientsDom[i];
                                let innerText = ingredientDom.innerText;
                                ingredient.amount = ingredientDom.getAttribute("data-amount");
                                if (ingredient.amount === "0") {
                                    ingredient.amount = "";
                                }
                                ingredient.unit = ingredientDom.getAttribute("data-type");
                                let extraSliceIndex = 0;
                                if (ingredient.unit.length > 0 && ingredient.amount.length > 0) {
                                    extraSliceIndex = 1;
                                }
                                let namepart = innerText.slice(ingredient.amount.length + ingredient.unit.length + extraSliceIndex).trim();


                                if (ingredient.unit.length > 0) {
                                    namepart = innerText.slice(innerText.indexOf(ingredient.unit) + ingredient.unit.length + 1).trim();
                                } else if (ingredient.amount.length > 0) {
                                    if (ingredient.amount % 1 != 0) {
                                        let parts = innerText.split(" ");
                                        if (ingredient.amount > 1) {
                                            namepart = innerText.slice(innerText.indexOf(parts[2])).trim();
                                        } else {
                                            namepart = innerText.slice(innerText.indexOf(parts[1])).trim();
                                        }

                                    } else {
                                        namepart = innerText.slice(innerText.indexOf(ingredient.amount) + ingredient.amount.length + 1).trim();

                                    }
                                } else {
                                    namepart = innerText.trim();
                                }



                                ingredient.name = namepart.charAt(0).toUpperCase() + namepart.slice(1).replace(/\s*\([^()]*\)/g, '').split(",")[0].replace(/([/.#$])/g, '').trim();
                                if (ingredientNames.indexOf(ingredient.name) > -1) {
                                    continue;
                                }


                                ingredientNames.push(ingredient.name);
                                ingredients.push(ingredient);
                            }
                            recipe.ingredients = ingredients;
                        }
                        //kan detta brytas ut till valideringsfunktion?
                        if (!recipe.ingredients || recipe.ingredients.length === 0 || (recipe.time && recipe.time < 1)) {
                            return;
                        }
                        return recipe;
                    })
                    .then(function (html) {
                        results.push(html);
                        return results;
                    })

            });
        }, Promise.resolve([]))
    })
    .then(function (resultArr) {
        console.log(resultArr.length);

        fs.writeFile("C:/react/" + filename, JSON.stringify(resultArr), function (err) {

            if (err) {
                return console.log(err);
            }

            console.log("The file was saved!");
        });
    });