var Nightmare = require('nightmare');
var nightmare = Nightmare({
  openDevTools: false, show: false, webPreferences: {
    images: false,
  }
})

var fs = require('fs');


//ta fram urls genom att:
//1. Gå till en sida på koket.se
//2. kör: var interv=setInterval(function(){if(document.querySelector('li.next').offsetParent!=null){document.querySelector('a[rel="next"]').click();}else{console.log("done");clearInterval(interv);}},600);
//3. Vänta på att "done" har loggats i consolen.
//4. kopiera alla hrefs genom copy(Array.from(document.querySelectorAll('article.list-item.recipe .info .top h2 a')).map(a => a.href));
//5. paste in i urls
//6. kör node night2.js
//7. resultatet sparas i react/test.txt
//8. kör node datachange.js här alla recept läses in till firebase från textfilen
let urls = [
  "https://www.koket.se/kramig-italiensk-gratang",
  "https://www.koket.se/per_morberg/varmratter/gronsaker__potatis_och_andra_rotfrukter/per_morbergs_raggmunk_med_flask/",
  "https://www.koket.se/stefano-catenacci/varmratter/pasta-och-nudlar/spaghetti-carbonara/",
  "https://www.koket.se/per-morberg/soppor-och-grytor/kott/boeuf-bourguignon-a-la-per-morberg/",
  "https://www.koket.se/per-morberg/varmratter/kott/per-morbergs-flasklagg-med-rotmos/",
  "https://www.koket.se/bowl-med-kyckling-i-rod-curry-savojkal-och-matvete",
  "https://www.koket.se/cottage-pie-pa-vegofars-siri-barjes-recept",
  "https://www.koket.se/tacos-med-strimlad-biff-kalsallad-och-avokadokram",
  "https://www.koket.se/filip-fasten/soppor-grytor/gronsaker-potatis-rotfrukter/potatis--och-purjolokssoppa/",
  "https://www.koket.se/gi-viktkoll/varmratter/flaskfile/helstekt-flaskfile-i-ugn/",
  "https://www.koket.se/hel-kyckling-i-ugn-med-timjan-och-citron",
  "https://www.koket.se/forkvall/pelle-johansson/kokt-torsk-med-aggsas/",
  "https://www.koket.se/mitt-kok/paolo-roberto/carbonara-paolo-robertos-recept",
  "https://www.koket.se/snabb-kantarellsoppa-jessica-frejs-recept",
  "https://www.koket.se/kramig-majssoppa-med-ostkrutonger",
  "https://www.koket.se/pannkaka-2",
  "https://www.koket.se/glasnudlar-med-edamame-cashewnotter-och-agg",
  "https://www.koket.se/vad-blir-det-for-mat/per-morberg/lasagne-bolognese--per-morbergs-recept/",
  "https://www.koket.se/graddig-fisksoppa-med-rakor-och-saffran",
  "https://www.koket.se/flankstek-med-rostade-morotter-dragon-och-brynt-smor",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/biff-stroganoff/",
  "https://www.koket.se/per-morberg/varmratter/pasta-och-nudlar/per-morbergs-hemlagade-pasta-med-svampsas/",
  "https://www.koket.se/morberg-lagar-husmanskost/per-morberg/falukorv-i-ugn-a-la-per-morberg/",
  "https://www.koket.se/monikas-vardagsmat/monika-ahlberg/mozzarella--och-spenatlasagne/",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/texas-chili/",
  "https://www.koket.se/per_morberg/varmratter/kott/per_morbergs_oxrullader_med_graddsas/",
  "https://www.koket.se/dragonkyckling-med-ris",
  "https://www.koket.se/halloumi-stroganoff-med-ris",
  "https://www.koket.se/morotssoppa-med-ingefara-och-chili",
  "https://www.koket.se/oxrullader-serveras-med-blomkalsris-och-rodvinssas",
  "https://www.koket.se/matgladje-hela-livet/leif-mannerstrom/leif-mannerstroms-kroppkakor/",
  "https://www.koket.se/kryddstekt-halloumi-med-avokadorora-och-quinoa",
  "https://www.koket.se/len-pumpasoppa-med-appelcider",
  "https://www.koket.se/kycklingkebab-med-pitabrod",
  "https://www.koket.se/rod-linssoppa-med-basilika-och-vitlok",
  "https://www.koket.se/spaghetti-carbonara-pa-riktigt",
  "https://www.koket.se/kobide-kebab-pa-lammkott",
  "https://www.koket.se/shrimp-n-sausage-gumbo",
  "https://www.koket.se/anna-hallen/soppor-och-grytor/kyckling-och-fagel/kycklinggryta-med-curry/",
  "https://www.koket.se/morberg-lagar-husmanskost/per-morberg/per-morbergs-makaronipudding/",
  "https://www.koket.se/italienska-kottbullar-i-tomatsas-med-spaghetti",
  "https://www.koket.se/halloumigryta-med-tomat-linser-och-chili",
  "https://www.koket.se/per_morberg/varmratter/vilt/per_morbergs_algstek_med_kantarellsas/",
  "https://www.koket.se/leif-mannerstrom/varmratter/kott/mannerstoms-pannbiff-med-lok/",
  "https://www.koket.se/allt-i-en-form-med-kyckling-chorizo-och-paprika",
  "https://www.koket.se/matgladje-hela-livet/leif-mannerstrom/kaldolmar/",
  "https://www.koket.se/rikard___stockholm/soppor_och_grytor/kott/mustig_kottgryta_som_heter_duga/",
  "https://www.koket.se/nyhetsmorgon/jennie-wallden/vietnamesiska-sommarrullar/",
  "https://www.koket.se/camilla_thulin_och_uluc_telmen/varmratter/kyckling_och_fagel/ugnsbakad_kyckling_med_klyftpotatis/",
  "https://www.koket.se/frasig-laxburgare-med-avokado-och-coleslaw",
  "https://www.koket.se/marinerad-kyckling-serveras-med-kokoscurrysas",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/boeuf-bourguignon/",
  "https://www.koket.se/pelle_johansson/huvudratter/kott/stekt_flask_med_loksas/",
  "https://www.koket.se/per_morberg/varmratter/kott/per_morbergs_plankstek_med_grillade_tomater/",
  "https://www.koket.se/per-morberg/varmratter/vilt/algfarsbiffar-med-mandelpotatis/",
  "https://www.koket.se/morberg/per-morberg/per-morbergs-viltgryta-med-skogssvamp/",
  "https://www.koket.se/laxlada-hela-middagen-i-en-form",
  "https://www.koket.se/per-morberg/varmratter/vilt/per-morbergs-algstek/",
  "https://www.koket.se/per-morbergs-korvstroganoff",
  "https://www.koket.se/matgladje-hela-livet/leif-mannerstrom/leif-mannerstroms-kalops/",
  "https://www.koket.se/per_morberg/varmratter/korv_och_chark/isterband_med_stuvad_potatis/",
  "https://www.koket.se/lchf-for-kvinnor/anna-hallen/kyckling-i-form/",
  "https://www.koket.se/leila-lindholm/varmratter/kott/leilas-godaste-revbensspjall/",
  "https://www.koket.se/per_morberg/varmratter/kott/per_morbergs_kaldolmar/",
  "https://www.koket.se/leila-lindholm/varmratter/fisk-och-skaldjur/smorstekt-torskrygg-med-stuvad-potatis/",
  "https://www.koket.se/fredrik_eriksson/soppor_och_grytor/svamp/trattkantarellsoppa/",
  "https://www.koket.se/pasta-med-rakor-paprika-och-vitt-vin",
  "https://www.koket.se/mitt-kok/jennie-wallden/flaskfile-i-kramig-dragon--och-senapssas/",
  "https://www.koket.se/pasta-salsiccia-classico",
  "https://www.koket.se/sa-gor-du-egen-sushi",
  "https://www.koket.se/skinkstek-fran-as",
  "https://www.koket.se/efter-tio/linda-skugge/cowboysoppa-med-kottfars/",
  "https://www.koket.se/gulaschsoppa-pa-notfars",
  "https://www.koket.se/new-orleans-gumbo",
  "https://www.koket.se/halloumitacos-med-avokadokram-och-inlagd-lok",
  "https://www.koket.se/one-pot-kyckling-alfredo",
  "https://www.koket.se/halloumi-tikka-masala-med-ris-och-cashewnotter",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/jordartskockssoppa-med-varm-toast/",
  "https://www.koket.se/mitt-kok/donal-skehan/italienska-kottbullar-i-tomatsas/",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/sojamarinerad-lax-med-sesambroccoli/",
  "https://www.koket.se/per_morberg/varmratter/vilt/per_morbergs_viltfarsbiffar/",
  "https://www.koket.se/falafel-med-myntasas",
  "https://www.koket.se/marcus_samuelsson/varmratter/fisk_och_skaldjur/fish_and_chips/",
  "https://www.koket.se/rostade-rotfrukter-med-halloumi-och-aioli",
  "https://www.koket.se/morbergs-dillkott-med-kokta-rotfrukter",
  "https://www.koket.se/chevrelasagne-med-kycklingfile",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/snabb-kottfarslimpa-pa-pizzavis/",
  "https://www.koket.se/wallenbergare-med-brynt-smor-och-artor",
  "https://www.koket.se/per_morberg/varmratter/kyckling_och_fagel/per_morbergs_coq_au_vin/",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/torskrygg-i-ugn/",
  "https://www.koket.se/frasig-piccata-pa-kalkonbrost-sandra-mastios-recept",
  "https://www.koket.se/aloo-gobi-indisk-gryta-med-blomkal-och-potatis",
  "https://www.koket.se/hemlagade-kottbullar-med-graddsas",
  "https://www.koket.se/ulrika-davidsson/varmratter/pasta-nudlar/mammas-goda-spagettigratang/",
  "https://www.koket.se/anette_rosvall_och_emma_hamberg/varmratter/kott/rasande_god_renskav/",
  "https://www.koket.se/enkel-sotpotatisgratang-med-lax-fetaost-och-tomat-ortsas",
  "https://www.koket.se/pasta-med-chorizo-och-paprika",
  "https://www.koket.se/kroppkakor-med-lingon-och-brynt-smor",
  "https://www.koket.se/lammfile-med-svamprisotto-serveras-med-hallon-och-chokladsas",
  "https://www.koket.se/karibisk-sotpotatisgryta-med-svarta-bonor",
  "https://www.koket.se/pulled-chicken-i-mjuk-tortilla",
  "https://www.koket.se/morberg-lagar-husmanskost/per-morberg/lammstek-med-potatisgratang/",
  "https://www.koket.se/mina-favoriter-fran-barcelona/markus-aujalay/kottbullar-i-tomatsas/",
  "https://www.koket.se/per_morberg/varmratter/kott/per_morbergs_pyttipanna/",
  "https://www.koket.se/penne-med-oxfile-och-gradde",
  "https://www.koket.se/siris-snabba-rotfruktssoppa",
  "https://www.koket.se/lchf-kokboken/sten-sture-skaldeman/ingerlises-tacogratang/",
  "https://www.koket.se/pastagratang-med-tacosmak",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/tommy-myllymakis-saftiga-cheeseburgare/",
  "https://www.koket.se/nyhetsmorgon/leif-mannerstrom/oxfile-med-pepparsas/",
  "https://www.koket.se/porterstek-pa-fransyska",
  "https://www.koket.se/liselotte-forslin/varmratter/kott/pulled-pork/",
  "https://www.koket.se/mitt-kok/filip-fasten/panerad-rodspatta-med-pressad-potatis/",
  "https://www.koket.se/jacob_wismar/varmratter/kyckling_och_fagel/hel_kyckling_i_ugn_med_paprikor/",
  "https://www.koket.se/per-morbergs-wienerschnitzel",
  "https://www.koket.se/linssoppa-med-kokosmjolk-tomat-och-halloumitarningar",
  "https://www.koket.se/kramig-trattkantarellsoppa-med-vitloksbrod",
  "https://www.koket.se/per_morberg/varmratter/kott/biff_rydberg_a_la_morberg/",
  "https://www.koket.se/lax---fran-vardag-till-lyx/paula-ahlsen-soder/ugnsbakad-lax-med-teriyakisas/",
  "https://www.koket.se/lchq/fredrik-paulun/citronkyckling-i-ugn-med-gronsaker-och-fetaostrora/",
  "https://www.koket.se/stekt-panerad-rodspatta-med-rotsakspytt",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/sa-lyckas-du-med-pommes-frites-hemma/",
  "https://www.koket.se/graddig-filegryta",
  "https://www.koket.se/mina-fastrars-mat/paolo-roberto/pasta-al-forno/",
  "https://www.koket.se/ortkryddad-fransyska-serveras-med-rostade-rotfrukter",
  "https://www.koket.se/myllymakis-kantarellpasta-med-kyckling",
  "https://www.koket.se/thai-kycklinggryta-med-kokosmjolk",
  "https://www.koket.se/helstekt-hogrev",
  "https://www.koket.se/torskrygg-med-vitvinsas-och-smorslungad-dillgurka",
  "https://www.koket.se/paolo-roberto/varmratter/pasta-och-nudlar/pappardelle-con-salsiccia/",
  "https://www.koket.se/morberg-lagar-husmanskost/per-morberg/plommonspackad-flaskkarre-med-graddsas/",
  "https://www.koket.se/pasta-med-kyckling-och-soltorkade-tomater",
  "https://www.koket.se/nyhetsmorgon/paolo-roberto/pasta-med-stora-kottbullar-i-tomatsas/",
  "https://www.koket.se/jamie_oliver/soppor_och_grytor/kott/jamie_olivers_grekiska_kottgryta/",
  "https://www.koket.se/varmande-gronsakssoppa-se-gor",
  "https://www.koket.se/vegetarisk-kalpudding-med-potatis",
  "https://www.koket.se/ernst_kirchsteiger/paj_och_pizza/mjol/ernsts_kantarellpaj/",
  "https://www.koket.se/mitt-kok/lisa-lemke/snabb-fisksoppa-med-saffran-och-fryst-lax/",
  "https://www.koket.se/currygryta-med-vitkal-chili-och-kokos",
  "https://www.koket.se/per-morbergs-fish-and-chips",
  "https://www.koket.se/per_morberg/varmratter/kott/morbergs_skanska_kalops/",
  "https://www.koket.se/per-morberg/varmratter/kott/klassiskt-dillkott/",
  "https://www.koket.se/per-morberg/varmratter/kott/slottsstek/",
  "https://www.koket.se/vietnamesisk-torsk-med-krispig-sallad",
  "https://www.koket.se/koket/pelle-johansson/wokade-nudlar-med-gronsaker/",
  "https://www.koket.se/husmorsorna/anette-rosvall-och-emma-hamberg/ugnspannkaka-med-flask/",
  "https://www.koket.se/naringsrik-och-naturlig-lchf/klara-desser/kycklinggryta-med-blomkalsris/",
  "https://www.koket.se/grekiska-lammfarsbiffar-med-fetaost",
  "https://www.koket.se/annika_wesslen/varmratter/kyckling_och_fagel/asiatisk_kycklingsoppa/",
  "https://www.koket.se/biff-a-la-lindstrom",
  "https://www.koket.se/vegetarisk-bolognese",
  "https://www.koket.se/krispig-spatta-med-curryremoulad",
  "https://www.koket.se/italiensk-flaskfile-med-parmesangratinerad-rotselleri",
  "https://www.koket.se/kalpudding",
  "https://www.koket.se/renskav-med-kantareller-och-potatisstomp",
  "https://www.koket.se/nyhetsmorgon/jennie-wallden/bibimbap-pa-entrecote-med-chilipicklad-gurka/",
  "https://www.koket.se/mitt-kok/jennie-wallden/laxsida-i-ugn-med-hollandaise",
  "https://www.koket.se/fritters-med-zucchini-och-halloumi",
  "https://www.koket.se/potatisbullar-med-bacon-och-lingon",
  "https://www.koket.se/hemgjord-gnocchi-se-gor",
  "https://www.koket.se/kottbullar-med-potatismos-och-graddig-loksas",
  "https://www.koket.se/vad-blir-det-for-mat/per-morberg/akta-sjomansbiff/",
  "https://www.koket.se/cathrine_schuck/varmratter/ris/trattkantarell_risotto_med_parmesan/",
  "https://www.koket.se/sotpotatis-med-getost-rodlok-och-spenat",
  "https://www.koket.se/vegansk-currygryta-med-kokos-och-kal",
  "https://www.koket.se/gulasch-med-syrad-gradde",
  "https://www.koket.se/smordegsinbakad-flaskfile-med-champinjonsas-och-potatisgratang",
  "https://www.koket.se/niclas_wahlgren/varmratter/mjol/akta_hemlagad_pizza/",
  "https://www.koket.se/johan_jureskog/huvudratter/kott/rodvinsbrasserade_oxkinder_med_tryffelpotatispure/",
  "https://www.koket.se/den-stora-matresan/per-morberg/hangmorad-biff-med-gronpepparsas/",
  "https://www.koket.se/pizza-margherita-sandra-mastios-recept",
  "https://www.koket.se/per-morberg/varmratter/pasta-och-nudlar/per-morbergs-pasta-vongole/",
  "https://www.koket.se/fisktacos-med-guacamole-och-mangosalsa",
  "https://www.koket.se/mitt-kok/jennie-wallden/klassisk-kottfarssas-med-spaghetti/",
  "https://www.koket.se/mannagrynsfisk-med-potatismos-och-romsas",
  "https://www.koket.se/klassisk-fiskgratang",
  "https://www.koket.se/paolos-porchetta-med-rostad-potatis",
  "https://www.koket.se/poke-bowl-med-lax-avokado-och-mango",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/tommys-traditionella-dillkott/",
  "https://www.koket.se/per-morberg/varmratter/kott/per-morbergs-hamburgare-med-hembakt-brod/",
  "https://www.koket.se/helstekt-oxfile",
  "https://www.koket.se/rodbraserat-flask",
  "https://www.koket.se/pernilla-wahlgren/varmratter/kott/kottbullar--jessicas-grymma-recept/",
  "https://www.koket.se/glutenfri-kantarellpaj",
  "https://www.koket.se/gi_viktkoll/huvudratter/kott/ugnsstekt_flaskfile/",
  "https://www.koket.se/bulgursallad-med-halloumi-och-sesam",
  "https://www.koket.se/jens_linder/varmratter/kott/vildsvinsstek_med_honung_och_citron/",
  "https://www.koket.se/per_morberg/varmratter/ris__couscous_och_andra_gryn/per_mobergs_paella/",
  "https://www.koket.se/brasilianska-fisktacos-med-mangosalsa",
  "https://www.koket.se/bao-bun-med-hoisinflask",
  "https://www.koket.se/nysaters-stek-i-lergryta",
  "https://www.koket.se/lasagne-med-zucchini-och-ricotta",
  "https://www.koket.se/ugnsbakad-lax-och-spetska-l-i-kra-mig-citronsa-s",
  "https://www.koket.se/vegetariska-kottbullar-med-graddsas-och-potatis",
  "https://www.koket.se/spagetthini-med-mozzarella-tomat-och-basilika",
  "https://www.koket.se/frasig-fiskburgare-med-tommys-dragonsas",
  "https://www.koket.se/tina-pa-besok/tina-nordstrom/hel-ugnsbakad-lax-med-smorsas--spritarter--vit-saltgurka-och-savoykalsallad/",
  "https://www.koket.se/tandoori-chicken-med-raita",
  "https://www.koket.se/vegetarisk-spaghetti-bolognese-pa-rotselleri-och-morotter",
  "https://www.koket.se/per-morberg/varmratter/kott/hangmorad-biff-med-bearnaise/",
  "https://www.koket.se/anders_leven/huvudratter/kott/wienerschnitzel/",
  "https://www.koket.se/nyhetsmorgon/jennie-wallden/sichuan-chicken-kung-pao/",
  "https://www.koket.se/red-curry-bowl-med-kyckling",
  "https://www.koket.se/laxpasta-med-citron-och-basilikasas",
  "https://www.koket.se/jens-linder/varmratter/kott/texas-chili-con-carne/",
  "https://www.koket.se/per_morberg/varmratter/vilt/radjurssadel_med_potatisgratang/",
  "https://www.koket.se/paolo_roberto/varmratter/pasta_och_nudlar/lasagne_al_forno/",
  "https://www.koket.se/kramig-potatisgratang",
  "https://www.koket.se/ortstekt-flaskfile-med-rotsaksgratang",
  "https://www.koket.se/gronkalspaj-med-getost-och-valnotter",
  "https://www.koket.se/kantarellasagne",
  "https://www.koket.se/kantarellpizza-med-lagrad-ost",
  "https://www.koket.se/paolo-roberto/varmratter/gronsaker--potatis-och-andra-rotfrukter/melanzane-alla-parmigiana/",
  "https://www.koket.se/morberg/per-morberg/morbergska-fisksoppan-med-saffran/",
  "https://www.koket.se/pauls-friterade-kyckling-med-tillbehor",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/tandoorikyckling-i-ugn/",
  "https://www.koket.se/mustig-hogrevsgryta-med-smak-av-hosten-serveras-med-betor-och-sotpotatis",
  "https://www.koket.se/leila-lindholm/varmratter/pasta-och-nudlar/farsk-pasta---grundrecept/",
  "https://www.koket.se/filip_fasten/varmratter/kott/storkok_pa_hogrev/",
  "https://www.koket.se/stekt-stromming-med-potatismos",
  "https://www.koket.se/ugnsstekt-flaskfile-med-lingonsas-och-potatisbakelse",
  "https://www.koket.se/ulrika-davidsson/varmratter/kyckling-och-fagel/thaikyckling-med-kokosmjolk-och-gront/",
  "https://www.koket.se/laskig-kottfarspaj-till-halloween",
  "https://www.koket.se/eggs-florentine-i-ugn",
  "https://www.koket.se/lisa-lemke/snabblagat/kyckling-och-fagel/snabblagad-kyckling-med-broccoli/",
  "https://www.koket.se/jens_linder/soppor_och_grytor/kott/boeuf_bourguignon_med_skogssvamp/",
  "https://www.koket.se/mitt-kok/jennie-wallden/kycklingfajitas/",
  "https://www.koket.se/du-ar-vad-du-ater/anna-skipper/tjalknol/",
  "https://www.koket.se/andre-wessman/klassisk-boeuf-bourguignon/",
  "https://www.koket.se/vegetarisk-lasagne-med-vegofars",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/pigg-laxpasta-med-syrlig-sas/",
  "https://www.koket.se/torskrygg-med-jordartskockspure",
  "https://www.koket.se/monikas-vardagsmat/monika-ahlberg/fiskpaket--all-in-one--med-couscous/",
  "https://www.koket.se/klassisk-curry-med-kyckling",
  "https://www.koket.se/lammlagg-med-rodvin-vitlok-och-kramigt-potatismos",
  "https://www.koket.se/pastagratang-a-la-carbonara",
  "https://www.koket.se/husmorsorna/anette-rosvall-och-emma-hamberg/kalsoppa-med-frikadeller/",
  "https://www.koket.se/mitt-kok/donal-skehan/donal-skehans-boeuf-bourguignon/",
  "https://www.koket.se/kycklinglada-med-kramig-sas-och-pressad-potatis",
  "https://www.koket.se/svampfyllda-kroppkakor-med-brynt-hasselnotssmor",
  "https://www.koket.se/rodvinskokt-hogrev-med-rosmarinspotatismos",
  "https://www.koket.se/grekisk-gratang-med-zucchini-fetaost-och-linser",
  "https://www.koket.se/smorstekt-torskrygg-med-potatispure-fankalsflarn-bacon-och-vitvinssas",
  "https://www.koket.se/per_morberg/varmratter/kott/kalvstek_med_hasselbackspotatis/",
  "https://www.koket.se/marinerad-tofu-med-stekta-nudlar-och-gronsaker",
  "https://www.koket.se/lasagne-med-aubergine-creme-fra-che-basilika-och-rott-vin",
  "https://www.koket.se/mange_schmidt/varmratter/kott/boeuf_bourguignon/",
  "https://www.koket.se/kramig-flaskfilegryta-med-rostade-rotfrukter",
  "https://www.koket.se/strimlad-lovbiff-i-senapssas-med-parmesan",
  "https://www.koket.se/mitt-kok/jennie-wallden/koreansk-bulgogi/",
  "https://www.koket.se/sallad-med-rostad-sotpotatis-halloumi-och-belugalinser",
  "https://www.koket.se/pasta-med-mangold-parmesan-och-valnotter",
  "https://www.koket.se/klockan-atta-hos-stjarnorna/steffo-tornquist/ankbrost-med--varldens-skitgodaste-sas-/",
  "https://www.koket.se/mitt-kok/donal-skehan/kramig-kycklingpasta",
  "https://www.koket.se/nyhetsmorgon/green-kitchen-stories/rodbetsbourguignon/",
  "https://www.koket.se/anders_strand/varmratter/pasta_och_nudlar/ravioli_med_ricotta_och_spenat/",
  "https://www.koket.se/per_morberg/varmratter/kott/per_morbergs_honungsglaserade_revbensspjall/",
  "https://www.koket.se/kalkonkorv-stroganoff",
  "https://www.koket.se/per-morberg/varmratter/vilt/helstekt-dovhjortfile-med-kraftig-rodvinssas/",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/ugnsbakad-lax-med-krispiga-gronsaker/",
  "https://www.koket.se/sa-har-kokar-du-pasta",
  "https://www.koket.se/torsk-i-ugn-med-tomater-raksas-och-rostade-solrosfron",
  "https://www.koket.se/bakad-jordartskocka",
  "https://www.koket.se/filip_fasten/varmratter/kott/stekt_entrecote/",
  "https://www.koket.se/fiskgryta-med-kokosgradde-gron-curry-och-limeyoghurt",
  "https://www.koket.se/toscansk-kycklinggryta",
  "https://www.koket.se/filodegspaj-med-fetaost-farsk-spenat-och-solrosfron",
  "https://www.koket.se/champinjonburgare-med-ramsloksmajonnas-ruccola-och-stark-ost",
  "https://www.koket.se/poke-bowl-med-marinerad-lax",
  "https://www.koket.se/vegetarisk-bourguignon-med-svartrotter-och-betor",
  "https://www.koket.se/gnocchi-med-sidflask-och-surkal",
  "https://www.koket.se/ortbakade-lammracks-med-ugnsrostade-rotfrukter",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/ugnsrostad-kyckling-med-gorgonzola/",
  "https://www.koket.se/jamies-matrevolution/jamie-oliver/jamie-olivers-chili-con-carne/",
  "https://www.koket.se/per_morberg/varmratter/kott/per_morbergs_oxbringa/",
  "https://www.koket.se/flaskfile-for-kung-och-fosterland-med-pesto-och-mozzarella",
  "https://www.koket.se/ravioli-med-svampkram-svampveloute-och-svampgarnityr",
  "https://www.koket.se/ugnsbakad-torskrygg-med-rotselleri-och-hostsvamp",
  "https://www.koket.se/per_morberg/varmratter/kott/pertans_hemlagade_kottsoppa/",
  "https://www.koket.se/laxplat-med-rodbetor-broccoli-och-fetaostkram",
  "https://www.koket.se/vit-pizza-med-lojrom",
  "https://www.koket.se/johan_jureskog/varmratter/kott/stekt_flask_med_loksas/",
  "https://www.koket.se/per-morberg/varmratter/kott/oxfile-wellington-med-madeirasas/",
  "https://www.koket.se/johnny-johansson/varmratter/kyckling-och-fagel/kyckling-med-kramig-appelpotatis-och-rodbetssas/",
  "https://www.koket.se/paolo_roberto/varmratter/pasta_och_nudlar/spaghetti_al_olio__aglio_e_peperoncino/",
  "https://www.koket.se/nyhetsmorgon/tommy-myllymaki/helstekt-rotselleri-med-valnotter--parmesan-och-tryffel/",
  "https://www.koket.se/kycklingfile-med-vitkalsgratang",
  "https://www.koket.se/anette-rosvall-och-emma-hamberg/varmratter/korv-och-chark/italiensk-kassler-i-kramig-sas/",
  "https://www.koket.se/vegetarisk-pizza-med-champinjoner-och-mozzarella",
  "https://www.koket.se/svarslagen-caesarsallad",
  "https://www.koket.se/pauls-friterade-fisk",
  "https://www.koket.se/mitt-kok---sverigeresan/tommy-myllymaki/musslor-med-gradde-och-vitt-vin/",
  "https://www.koket.se/akta-wallenbergare",
  "https://www.koket.se/chili-con-carne-a-la-myllymaki",
  "https://www.koket.se/monica-eisenmans-asiatiska-nudlar-och-smaratter/monica-eisenman/gyozas/",
  "https://www.koket.se/kyckling-i-ugn-3",
  "https://www.koket.se/havets-wallenbergare",
  "https://www.koket.se/italiensk-pytt-i-panna",
  "https://www.koket.se/hogrevsburgare-med-klyftpotatis-och-guacamole",
  "https://www.koket.se/mitt-kok/paolo-roberto/pasta-med-vitloksfrasta-rakor-och-vitt-vin/",
  "https://www.koket.se/bengt_sjostrom/varmratter/fisk/citron__och_ortbakad_lax/",
  "https://www.koket.se/louise-johansson/soppor-och-grytor/fisk-och-skaldjur/graddig-fiskgryta-med-fankal/",
  "https://www.koket.se/oxrullader-med-rotfrukter-och-baconinlindad-sparris",
  "https://www.koket.se/baconfyllda-lovbiffsrullader-med-ugnsbakad-potatis-och-fargglada-tillbehor",
  "https://www.koket.se/anette_rosvall_och_emma_hamberg/varmratter/kyckling_och_fagel/basta_kyllingen_ever/",
  "https://www.koket.se/nyhetsmorgon/sara-ask/farska-varrullar-med-jordnotsdipp/",
  "https://www.koket.se/kycklingfile-i-gorgonzolasas-med-klyftpotatis",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/pasta-al-tono/",
  "https://www.koket.se/thaicurry-med-kyckling",
  "https://www.koket.se/leifs-piggvar",
  "https://www.koket.se/charlotta-malhotra/varmratter/fisk-och-skaldjur/ugnsbakad-lax-med-sweet-chili/",
  "https://www.koket.se/pelle-johansson/varmratter/kyckling-och-fagel/kokoskyckling-med-ris/",
  "https://www.koket.se/kramig-laxpasta-med-vitvinssas-och-parmesan",
  "https://www.koket.se/green-and-truffle-mac-n-cheese",
  "https://www.koket.se/oxjarpar-med-graddsas-och-picklade-vinbar",
  "https://www.koket.se/kycklingpasta-med-brynt-smor-och-grapefrukt",
  "https://www.koket.se/ramen-med-flaskfars-och-sesam",
  "https://www.koket.se/wraps-med-fuskpanerad-torsk-och-avokadomajonnas",
  "https://www.koket.se/flaskfile-med-svampsas-och-rostad-potatis",
  "https://www.koket.se/ugnsgratinerad-kyckling-med-chimichurri-och-mozzarella",
  "https://www.koket.se/steamed-buns-med-halstrad-tonfisk",
  "https://www.koket.se/johan_jureskog/varmratter/korv_och_chark/stuvade_makaroner_med_falukorv/",
  "https://www.koket.se/risotto-funghi-paolo-robertos-recept",
  "https://www.koket.se/indiskt-kryddad-lax-med-ris-och-yoghurtsas",
  "https://www.koket.se/laxpudding-med-gravad-lax",
  "https://www.koket.se/kalvfarsbiffar-med-rodbetor-serveras-med-graddsas-och-potatisskivor",
  "https://www.koket.se/ugnsbakad-torsk-med-dillpotatis-brynt-smor-pepparrot-agg-och-rakor",
  "https://www.koket.se/pankofriterad-kycklingtaco-med-fruktsalsa-och-hemgjorda-tortillabrod",
  "https://www.koket.se/pizza-bianco-med-portabello-mozzarella-och-rodlok",
  "https://www.koket.se/tva-sorters-knackepizza",
  "https://www.koket.se/adez-och-zigni-afrikanska-grytor-med-bonor-och-linser",
  "https://www.koket.se/indisk-linssoppa-med-garam-masala",
  "https://www.koket.se/varldens-nast-basta-burgare",
  "https://www.koket.se/le-parfait/varmratter/kott/file-mignon-black-and-white/",
  "https://www.koket.se/morberg-lagar-husmanskost/per-morberg/janssons-frestelse-pa-per-morbergs-vis/",
  "https://www.koket.se/rodspattarullader-i-vitvinssas",
  "https://www.koket.se/kycklinggratang-med-mango-och-curry",
  "https://www.koket.se/panerad-rodspatta-med-remoulad",
  "https://www.koket.se/black-and-white-med-gronpepparsas-och-potatismos",
  "https://www.koket.se/monica-eisenmans-asiatiska-nudlar-och-smaratter/monica-eisenman/snabb-kyckling--och-gronsakswok/",
  "https://www.koket.se/din-matkasse/anette-rosvall-och-emma-hamberg/kyckling-med-citron--och-vitlokssmor/",
  "https://www.koket.se/vegansk-pasta-bolognese-siri-barjes-recept",
  "https://www.koket.se/mitt-kok/donal-skehan/gumbogryta/",
  "https://www.koket.se/nyhetsmorgon/johan-jureskog/ag-s-hamburgare/",
  "https://www.koket.se/lchf-kokboken/sten-sture-skaldeman/moussaka/",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/kraftpasta-med-dill-och-citron/",
  "https://www.koket.se/cannelloni-med-ricotta-och-arrabbiatasas",
  "https://www.koket.se/nyhetsmorgon/bianca-wahlgren-ingrosso/penne-zafferano/",
  "https://www.koket.se/hostgryta-med-pepparrotskram",
  "https://www.koket.se/bolognese-pa-svarta-linser",
  "https://www.koket.se/malin_soderstrom/huvudratter/fisk_och_skaldjur/spaghetti_med_rakor__vitlok_och_tomat/",
  "https://www.koket.se/per_morberg/varmratter/_/ingas_pepparrotskott/",
  "https://www.koket.se/one-pot-pasta",
  "https://www.koket.se/sverigesmasterkock/parmalindad-kycklingfile-med-ugnspotatis/",
  "https://www.koket.se/mat-for-liv-och-lust/margit-eliasson-och-gunilla-lindeberg/grekiska-farsbiffar/",
  "https://www.koket.se/kungens-slottsstek-tillsammans-med-hertiginnans-potatis",
  "https://www.koket.se/nudelwok-med-flaskfars-och-pak-choi",
  "https://www.koket.se/margit_eliasson_och_gunilla_lindeberg/varmratter/kott/sjomansgryta/",
  "https://www.koket.se/pasta-ricotta-med-tomat-vitlok-och-orter",
  "https://www.koket.se/per_morberg/varmratter/kott/oxfile_provencale/",
  "https://www.koket.se/mitt-kok/jennie-wallden/vegetariska-kottbullar/",
  "https://www.koket.se/morbergs-polsa",
  "https://www.koket.se/sesamramen-med-svamp-och-tofu",
  "https://www.koket.se/mitt-kok/lisa-lemke/mexikansk-tacos",
  "https://www.koket.se/sofia___mora/varmratter/kott/oxfile_med_potatis__och_jordartskockspure/",
  "https://www.koket.se/monica-eisenmans-asiatiska-nudlar-och-smaratter/monica-eisenman/vietnamesisk-nudelsallad-med-biff/",
  "https://www.koket.se/lchf-for-familjen/anna-hallen/tacopaj-enligt-lchf/",
  "https://www.koket.se/frasig-ortlax-med-potatisstomp",
  "https://www.koket.se/kyckling-med-marockansk-chermoula",
  "https://www.koket.se/du-ar-vad-du-ater/anna-skipper/helstekt-farsk-dragonkyckling-med-graddsas/",
  "https://www.koket.se/ugnsbakad-lax-med-ortig-linsragu",
  "https://www.koket.se/per-morbergs-heta-pasta-vongole",
  "https://www.koket.se/knaperstekt-ankbrost-a-l-orange",
  "https://www.koket.se/stefan_svensson/varmratter/kyckling_och_fagel/chicken_tikka_masala/",
  "https://www.koket.se/tacosoppa",
  "https://www.koket.se/laxwok-teriyaki",
  "https://www.koket.se/markus-aujalay/kottbullar-med-rarorda-lingon-och-potatismos/",
  "https://www.koket.se/pizza-med-langbakad-rotselleri",
  "https://www.koket.se/angamat-med-potatis-sockerarter-och-persilja",
  "https://www.koket.se/morberg-lagar-husmanskost/per-morberg/kalvfile-oscar-a-la-per-morberg/",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/vegetarisk-currygryta-med-paprika/",
  "https://www.koket.se/lagtempad-lax-med-glasnudelsallad",
  "https://www.koket.se/asiatisk-linsgryta-med-chili-och-ingefara",
  "https://www.koket.se/lchq/fredrik-paulun/lax-i-ugn-med-rotfrukter-och-fetaost/",
  "https://www.koket.se/boeuf-bourguignon-burgundisk-kottgryta",
  "https://www.koket.se/mitt-kok/filip-fasten/kantarellpaj-fran-mitt-kok/",
  "https://www.koket.se/pankofriterad-fish-taco-med-hot-mayo-mangosalsa-och-kokosflakes",
  "https://www.koket.se/pasta-med-spenat-och-bacon",
  "https://www.koket.se/tortellini-med-ricotta-och-basilika-i-tomatsas",
  "https://www.koket.se/nudelwok-med-lovbiff-och-sesam",
  "https://www.koket.se/greek-gyros",
  "https://www.koket.se/halloumirarakor-med-avokadosalsa",
  "https://www.koket.se/morotsbullar-med-yoghurtsas",
  "https://www.koket.se/langos-med-citronmarinerad-rodlok-rakor-vasterbottensost-och-lojrom",
  "https://www.koket.se/tina-nordstrom/varmratter/kott/biff-wellington-med-svampfyllning/",
  "https://www.koket.se/ugnsstekt-rostbiff-med-hasselbackspotatis",
  "https://www.koket.se/halloumi-bbq-wrap-med-gronkalslaw",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/tommy-myllymakis-kottfarssas/",
  "https://www.koket.se/senapsgratinerad-falukorv-med-rotfruktsmos",
  "https://www.koket.se/mitt-kok/jennie-wallden/flaskfile-africana/",
  "https://www.koket.se/fiskgratangen-to-die-for",
  "https://www.koket.se/forkvall/johan-jureskog/johan-jureskogs-kalpudding/",
  "https://www.koket.se/dubbelmarinerad-flaskfile",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/oxfile-med-svampsas-och-hasselbackspotatis/",
  "https://www.koket.se/klassisk-oxfile-proven-ale",
  "https://www.koket.se/mitt-kok/lisa-lemke/kyckling-med-rotfrukter-i-langpanna/",
  "https://www.koket.se/torsk-med-dillsas-citron-och-kalrabbi",
  "https://www.koket.se/mitt-kok/paolo-roberto/pasta-med-hemgjord-pesto",
  "https://www.koket.se/joel-wastgard/gratang/gronsaker--potatis-och-andra-rotfrukter/nyttig-broccoligratang/",
  "https://www.koket.se/kottfarsfyllda-cannelloni",
  "https://www.koket.se/fajitakryddad-lax-med-quinoasallad",
  "https://www.koket.se/vegetariska-vietnamesiska-varrullar",
  "https://www.koket.se/mitt-kok/jennie-wallden/fisktacos-pa-torsk-med-pankostrobrod/",
  "https://www.koket.se/spisvarme/sigrid-barany/bbq-hogrev-med--coleslaw/",
  "https://www.koket.se/halv-atta-hos-mig/britt-marie---falun/hjortfile-med-svampduchesse-och-rodvinssas/",
  "https://www.koket.se/spaghetti-med-italienska-kottbullar-i-tomatsas",
  "https://www.koket.se/halv-atta-hos-mig/victor---stockholm/hjortfarsbiffar-med-potatispure-deluxe/",
  "https://www.koket.se/mitt-kok/jennie-wallden/lyxig-pasta-med-oxfile-och-svamp/",
  "https://www.koket.se/mitt-kok/jennie-wallden/jennies-helstekta-kyckling/",
  "https://www.koket.se/varmrokt-lax-med-parlcouscous-och-chermola",
  "https://www.koket.se/mexikansk-pulled-pork-med-kramig-coleslaw",
  "https://www.koket.se/dumplings-med-tva-saser",
  "https://www.koket.se/algfarsbiffar-med-kantarellsas-och-lingoncoleslaw",
  "https://www.koket.se/stefan_persson/varmratter/kott/sjomansbiff/",
  "https://www.koket.se/paolo_roberto/varmratter/pasta_och_nudlar/penne_all__arrabbiata/",
  "https://www.koket.se/halv-atta-hos-mig/malin---linkoping/hostig-alggryta/",
  "https://www.koket.se/helstekt-hjortfile-i-portvinssky-serveras-med-blomkalstryffelpure-och-rotfrukter",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/kramig-paprikapasta-med-skinka/",
  "https://www.koket.se/mexikansk-linsgryta-med-avokado-och-nachochips",
  "https://www.koket.se/lisa-lemke/lisa-lemke/lax-med-sesamfron-och-hoisinsas/",
  "https://www.koket.se/forkvall/christian-campogiani/pasta-med-ostsas/",
  "https://www.koket.se/mitt-kok/jennie-wallden/paella-med-kyckling-och-rakor/",
  "https://www.koket.se/gratinerade-cannelloni-med-kottfars",
  "https://www.koket.se/mitt-kok/donal-skehan/tacos-med-pulled-pork/",
  "https://www.koket.se/johan_jureskog/varmratter/korv_och_chark/kalvlever_anglais/",
  "https://www.koket.se/gott-utan-gluten--soja--laktos--vete--mjolk--agg/annika-wesslen/glutenfria-piroger-med-kottfarsrora/",
  "https://www.koket.se/lax-och-kyckling/kristina-eriksson/helstekt-kyckling-med-dragonsmor/",
  "https://www.koket.se/algryggbiff-med-trattkantarellsas-serveras-med-potatis-och-palsternackspure",
  "https://www.koket.se/artsoppa-med-varm-punsch",
  "https://www.koket.se/kycklingrullader-med-sidflask-parmesan-och-basilika",
  "https://www.koket.se/kycklingpasta-med-pesto",
  "https://www.koket.se/penne-med-spenat-vitlok-och-karljohansvamp",
  "https://www.koket.se/glutenfri-tacopaj",
  "https://www.koket.se/vietnamesiska-sommarrullar",
  "https://www.koket.se/nyhetsmorgon/nils-emil-ahlin/ugnsbakad-lax-pa-spenatbadd/",
  "https://www.koket.se/le-parfait/le-parfait/ort--och-citronkyckling/",
  "https://www.koket.se/spaghetti-med-salviakyckling-och-parmesan",
  "https://www.koket.se/auberginegryta-med-hummus",
  "https://www.koket.se/bean-taco-med-gron-salsa",
  "https://www.koket.se/linsgryta-med-halloumi-och-sotpotatis",
  "https://www.koket.se/chorizorisotto-med-vitlok-och-timjanstekt-torsk",
  "https://www.koket.se/pestokyckling-med-zucchinipasta",
  "https://www.koket.se/du-ar-vad-du-ater/anna-skipper/bovetepannkakor-med-hemmagjord-sylt/",
  "https://www.koket.se/braserad-lammbog-i-vitt-vin-och-tomat-med-grillad-morot-grona-tomater-oliver-och-libbsticka",
  "https://www.koket.se/ugnsbakad-sej-i-dillsas-med-pepparrotsmos",
  "https://www.koket.se/indisk-korma-med-halloumi-och-kikarter",
  "https://www.koket.se/zucchinifritters-med-halloumi",
  "https://www.koket.se/mitt-kok/lisa-lemke/indisk-gryta-med-falukorv/",
  "https://www.koket.se/portabelloburgare-med-karamelliserad-lok-tryffelkram-och-gronkal",
  "https://www.koket.se/halv-atta-hos-mig/hanna---mariestad/hannas-helstekta-ryggbiff-med-potatismuffins-och-portvinssas/",
  "https://www.koket.se/flaskfile-i-rosa-sas",
  "https://www.koket.se/ugnsbakad-laxsida-med-gron-sas",
  "https://www.koket.se/forkvall/ulrika-davidsson/gi-lasagne/",
  "https://www.koket.se/mitt-kok/paolo-roberto/langkokt-hogrev-i-tomatsas/",
  "https://www.koket.se/nyhetsmorgon/monika-ahlberg/chicken-satay-a-la-monika-ahlberg/",
  "https://www.koket.se/ljummen-pumpasallad-med-parmesan",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/chili-con-carne/",
  "https://www.koket.se/anette_rosvall_och_emma_hamberg/varmratter/pasta_och_nudlar/gudfaderns_pasta/",
  "https://www.koket.se/pumpa-paron-getost-och-pumpakarnor",
  "https://www.koket.se/karamelliserad-kyckling-med-sotpotatis-och-jordnotter",
  "https://www.koket.se/italiensk-kycklinggryta-med-parmesanpolenta",
  "https://www.koket.se/lax-med-romsas",
  "https://www.koket.se/leila_lindholm/varmratter/pasta_och_nudlar/leilas_pasta_med_bacon/",
  "https://www.koket.se/lisa-lemkes-fiskgratang-med-rak-och-dillsas",
  "https://www.koket.se/niklas_ekstedt/huvudratter/_/libapizza/",
  "https://www.koket.se/halv-atta-hos-mig/simona---goteborg/torskrygg-med-sandefjordsas-och-pressad-potatis/",
  "https://www.koket.se/ljummen-potatissallad-med-agg-brynt-smor-dill-pepparrot-och-rakor",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/baconlindad-flaskfile-med-rosti/",
  "https://www.koket.se/lax-i-ugn-pa-smordegsbadd",
  "https://www.koket.se/mitt-kok/lisa-lemke/trattkantarellsoppa-med-toast/",
  "https://www.koket.se/timells-skargardskok/malin-soderstrom/smorstekt-abborre-med-graddiga-kantareller/",
  "https://www.koket.se/koket/pelle-johansson/moussaka/",
  "https://www.koket.se/anette_rosvall_och_emma_hamberg/varmratter/fisk_och_skaldjur/lax_med_tacke/",
  "https://www.koket.se/biff-rydberg-med-pepparrots-och-senapskram",
  "https://www.koket.se/halv-atta-hos-mig/emma---skelleftea/helstekt-algfile/",
  "https://www.koket.se/soja-och-ingefarsmarinerad-renfile-med-skogssvamp-spetskal-och-krispigt-hostapple",
  "https://www.koket.se/filips-kalpudding-med-lingon",
  "https://www.koket.se/se-och-gor/caroline-ahlqvist/hur-gor-man-pizzadeg-/",
  "https://www.koket.se/per_morberg/varmratter/fisk_och_skaldjur/kokt_torsk_med_pepparrot_och_skirat_smor/",
  "https://www.koket.se/glenn_stromberg/varmratter/pasta_och_nudlar/spaghetti_med_chili__vitlok_och_olivolja/",
  "https://www.koket.se/mitt-kok/paolo-roberto/kyckling-milanese/",
  "https://www.koket.se/sommar-med-ernst/ernst-kirchsteiger/mamma-traudes-oxrullader/",
  "https://www.koket.se/mitt-kok/paolo-roberto/paolos-spaghetti-all-amatriciana/",
  "https://www.koket.se/chili-pa-hogrev-med-jalapeno-creme-fraiche-picklad-rodlok-och-stark-ost",
  "https://www.koket.se/fish-cakes-med-hemgjord-sweet-chili",
  "https://www.koket.se/halv-atta-hos-mig/jonas---malmo/ankbrost-med-apelsinsas/",
  "https://www.koket.se/ulrika_davidsson/varmratter/_/fransk_omelett/",
  "https://www.koket.se/flaskytterfile-med-ugnsrostade-rotfrukter-och-pepparsas",
  "https://www.koket.se/halv-atta-hos-mig/karin---are/lattrimmad-torskrygg-med-blomkalspure/",
  "https://www.koket.se/per-morberg/varmratter/kott/wienerschnitzel-med-rosti/",
  "https://www.koket.se/svamppasta-med-svartkal",
  "https://www.koket.se/pasta-med-vegansk-sas",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/helstekt-entrecote-med-pepparpotatis-och-rodvinssmor/",
  "https://www.koket.se/kottfarspaj-shepherd-s-pie",
  "https://www.koket.se/tina-nordstrom/varmratter/kott/tinas-cordon-bleu-pa-lovbiff/",
  "https://www.koket.se/anne_bramsen/varmratter/kott/dansk_flaskstek_med_hemlagad_rodkal/",
  "https://www.koket.se/mitt-kok/lisa-lemke/flaskfilepasta-med-gorgonzolasas/",
  "https://www.koket.se/lina_geback/varmratter/kyckling_och_fagel/chicken_nuggets_med_ris_och_currysas/",
  "https://www.koket.se/josefine_haamer_von_hofsten/varmratter/kyckling_och_fagel/josses_kyckling_med_rotfrukter_och_timjan/",
  "https://www.koket.se/spaghetti-med-salsicciasas",
  "https://www.koket.se/medeltida-kyckling-med-hasselbackspotatis",
  "https://www.koket.se/michael_bjorklund/soppor_och_grytor/korv_och_chark/korv_stroganoff/",
  "https://www.koket.se/spaghetti-ragu-bianco",
  "https://www.koket.se/vit-pizza-med-sparris-och-parmesan",
  "https://www.koket.se/koket/alexandra-zazzi/panerad-schnitzel/",
  "https://www.koket.se/tove_nilsson/varmratter/kyckling_och_fagel/tandoorikyckling/",
  "https://www.koket.se/hoisinkyckling-med-pak-choi-och-ingefara",
  "https://www.koket.se/oxfile-med-cointreausas-och-duchessepotatis",
  "https://www.koket.se/sverigesmasterkock/indisk-kycklingcurry/",
  "https://www.koket.se/vegetarisk-gulasch",
  "https://www.koket.se/nyhetsmorgon/paolo-roberto/gnocchi-med-tomatsas/",
  "https://www.koket.se/per_morberg/varmratter/ris__couscous_och_andra_gryn/per_morbergs_saffranspannkaka_med_salmbarssylt/",
  "https://www.koket.se/ulrika_davidsson/varmratter/fisk_och_skaldjur/laxfile_i_foliepaket/",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/kyckling-i-langpanna-med-feta-och-oliver/",
  "https://www.koket.se/naringsrik-och-naturlig-lchf/klara-desser/kottfarslimpa-med-svampsas/",
  "https://www.koket.se/marinerad-kycklingfile-med-svampsas-och-smordegsinbakad-potatis",
  "https://www.koket.se/fiskgratang-med-rak-dillsas",
  "https://www.koket.se/vietnamesisk-raksallad-med-risnudlar",
  "https://www.koket.se/potatis-och-purjolokssoppa-med-kalkonbacon",
  "https://www.koket.se/jessicas-halloumiburgare-med-soltorkade-tomater",
  "https://www.koket.se/tina-pa-besok/tina-nordstrom/tinas-falafel-pa-okokta-kikartor/",
  "https://www.koket.se/per_morberg/varmratter/fisk_och_skaldjur/piggvar_med_skirat_smor_och_pepparrot/",
  "https://www.koket.se/vad-blir-det-for-mat/per-morberg/musslor--angade-i-vitt-vin/",
  "https://www.koket.se/jordartskocksgratang",
  "https://www.koket.se/leif_mannerstrom/varmratter/fisk_och_skaldjur/mannerstoms_goda_janssons_frestelse/",
  "https://www.koket.se/naringsrik-och-naturlig-lchf/klara-desser/kycklinggryta-med-orter/",
  "https://www.koket.se/paolos-pasta-med-hostragu-pa-oxkott-och-svamp",
  "https://www.koket.se/radjurssadel-med-potatispure-stekta-paron-och-rodvinssas",
  "https://www.koket.se/mexican-rice-bowl",
  "https://www.koket.se/snabblagad-yakiniku-med-ris",
  "https://www.koket.se/margit_eliasson_och_gunilla_lindeberg/varmratter/ris__couscous_och_andra_gryn/nasi_goreng/",
  "https://www.koket.se/louise_johansson/varmratter/vilt/portermarinerad_viltgryta_med_kantareller/",
  "https://www.koket.se/mitt-kok/jennie-wallden/svamppasta-med-tryffel-och-parmesan",
  "https://www.koket.se/andreas_nylen/varmratter/gronsaker/mozzarellagratinerad_bruschetta/",
  "https://www.koket.se/nyhetsmorgon/jennie-wallden/kyckling-cashew/",
  "https://www.koket.se/efter-tio/mattias-kristiansson/veganfarslimpa-med-kantarellsas/",
  "https://www.koket.se/markus-aujalay/varmratter/kott/kottfarslimpa/",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/potatisstomp-och-lyxig-potatis/",
  "https://www.koket.se/spaghetti-med-citronkyckling-och-parmesan",
  "https://www.koket.se/fest--mat-och-karlek/christian-hellberg/helstekt-oxfile-med-pommes-och-bearnaisesas/",
  "https://www.koket.se/per_morberg/varmratter/kyckling_och_fagel/vildand_med_graddsas/",
  "https://www.koket.se/supersnabb-tonfiskpasta-med-oliver-och-kapris",
  "https://www.koket.se/lchq/fredrik-paulun/gyllene-kalpudding/",
  "https://www.koket.se/knaprigt-flask-med-asiatisk-plommonsas",
  "https://www.koket.se/koreansk-bbq-med-flaskkarre-och-kimchislaw",
  "https://www.koket.se/fina-fisken-moter-skogens-guld-torskrygg-med-kantareller-och-bacon",
  "https://www.koket.se/gudomligt-god-porterstek-med-kramig-gratang-och-sommarsallad",
  "https://www.koket.se/klassiska-wallenbergare",
  "https://www.koket.se/algkottbullar-med-graddsas-och-syltade-kantareller",
  "https://www.koket.se/stekt-citronlax-med-yoghurtsas",
  "https://www.koket.se/fisksoppa-a-la-catarina",
  "https://www.koket.se/sverigesmasterkock/amir-kheirmand/hjortinnerfile-med-potatisfondant--goda-tillbehor-och-madeirasas/",
  "https://www.koket.se/koket/alexandra-zazzi/spaghetti-a-la-carbonara/",
  "https://www.koket.se/mitt-kok/lisa-lemke/sallad-pa-flankstek-med-dijondressing/",
  "https://www.koket.se/bonchili-med-choklad-avokado-och-graddig-majs",
  "https://www.koket.se/markus-aujalay/varmratter/kott/markus-aujalays-lammfarsbiffar/",
  "https://www.koket.se/risgrynsplattar-med-lingonyoghurt-och-paron",
  "https://www.koket.se/matgladje-hela-livet/leif-mannerstrom/dillkott-pa-mitt-vis/",
  "https://www.koket.se/halv-atta-hos-mig/jonas---karlstad/alginnanlar-med-jordartskockspure-och-kantareller/",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/kottbullar-med-potatismos-och-lingon/",
  "https://www.koket.se/sara-begner/varmratter/fisk-och-skaldjur/lax-i-thaikryddad-sas/",
  "https://www.koket.se/kyckling-och-baconrullar",
  "https://www.koket.se/sverigesmasterkock/dennis-johansson/spaghetti-bolognese/",
  "https://www.koket.se/halv-atta-hos-mig/mikael---karlshamn/file-mignon-black-and-white/",
  "https://www.koket.se/kott-a-sas-a-putater",
  "https://www.koket.se/skordelasagne-med-getostbechamel",
  "https://www.koket.se/kottsoppa-pa-alg-och-rotfrukter",
  "https://www.koket.se/nyhetsmorgon/jennie-wallden/torskrygg-med-brynt-lime-och-sojasmor-och-blomkalspure/",
  "https://www.koket.se/lchf---husmanskost/anna-hallen/chili-con-carne-med-svarta-bonor/",
  "https://www.koket.se/italiensk-tomatsoppa-med-mozzarella",
  "https://www.koket.se/chicken-larb-salad",
  "https://www.koket.se/dominika_peczynski/varmratter/kott/biff_stroganoff/",
  "https://www.koket.se/anette_rosvall_och_emma_hamberg/varmratter/gronsaker__potatis_och_andra_rotfrukter/squashbiffar/",
  "https://www.koket.se/lax-och-kyckling/kristina-eriksson/laxsida-med-honung-och-chili/",
  "https://www.koket.se/nyhetsmorgon/nils-emil-ahlin/graddig-flaskfilegryta/",
  "https://www.koket.se/italiensk-kycklinglasagne",
  "https://www.koket.se/penne-ala-norma",
  "https://www.koket.se/klara_desser/soppor/gronsaker/morotssoppa_med_ingefara_och_apelsin/",
  "https://www.koket.se/flaskgryta-fran-louisiana",
  "https://www.koket.se/margit_eliasson_och_gunilla_lindeberg/varmratter/kyckling_och_fagel/parmesanfylld_kyckling_le/",
  "https://www.koket.se/lyxig-sondagsstek-av-alg-med-klassiska-tillbehor-med-twist",
  "https://www.koket.se/ulrika_jisland/varmratter/pasta_och_nudlar/pasta_med_flaskfile__parmaskinka_och_pesto/",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/pasta-med-bacon-och-gronkal/",
  "https://www.koket.se/kyckling-med-basilika-och-citronolja-samt-mozzarellagratinerad-broccoli-och-tomat",
  "https://www.koket.se/friterade-varrullar-med-flaskfars-och-rakor",
  "https://www.koket.se/bakad-torsk-med-rodbeta-och-brynt-citronsmor",
  "https://www.koket.se/nicoles-morotssoppa-med-ingefara-och-koriander",
  "https://www.koket.se/pasta-med-salsiccia-och-ricotta",
  "https://www.koket.se/bakad-lax-med-inlagd-kronartskocka-inlagd-paprika-och-fetaost",
  "https://www.koket.se/halv-atta-hos-mig/gerd-stromstad/helstekt-oxfile-med-rodvinssas-och-tillbehor",
  "https://www.koket.se/sveriges_masterkock/varmratter/fisk_och_skaldjur/smorstekt_torskrygg_med_tillbehor/",
  "https://www.koket.se/graddig-pasta-med-lax-spenat-och-endive",
  "https://www.koket.se/paolos-pastagratang-med-kyckling",
  "https://www.koket.se/vegetariska-burritos",
  "https://www.koket.se/mina-fastrars-mat/paolo-roberto/lammstek-med-rosmarin-och-vitlok--italiensk-/",
  "https://www.koket.se/caesarsallad-pa-tom-sjostedts-vis",
  "https://www.koket.se/radjursentrec-te-och-potatisstubbar-med-whiskysas-och-smorstekta-gronsaker",
  "https://www.koket.se/anders_leven/varmratter/kott/kokt_rimmad_oxbringa_med_pepparrot/",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/oxfile-med-rostad-pumpa/",
  "https://www.koket.se/klassisk-fransk-fisksoppa-med-saffransaioli",
  "https://www.koket.se/bengt_sjostrom/varmratter/kott/helstekt_flaskytterfile_med_rostade_rotfrukter_och_farskostsmor/",
  "https://www.koket.se/paula_ahlsen_soder/varmratter/fisk_och_skaldjur/senapsgriljerad_lax_med_gurksas/",
  "https://www.koket.se/jessica-frejs-klassiska-kottbullar",
  "https://www.koket.se/gai-pad-prik-het-thailandsk-kycklingwok",
  "https://www.koket.se/fisk-och-raksoppa-med-orter-och-saffran",
  "https://www.koket.se/morberg-grillar/per-morberg/farish-kebab-med-tsatsiki/",
  "https://www.koket.se/halv-atta-hos-mig/per---are/klassiskt-flasklagg-med-rotmos-och-hemgjord-senap/",
  "https://www.koket.se/sticky-rice-med-broccoli-sparris-och-friterad-tofu",
  "https://www.koket.se/penne-carbonara-med-salsiccia",
  "https://www.koket.se/per_morberg/varmratter/kyckling_och_fagel/jerk_chicken/",
  "https://www.koket.se/klas-lindberg/varmratter/kyckling-och-fagel/stekt-kycklingbrost-med-graddstuvade-kantareller/",
  "https://www.koket.se/halv-atta-hos-mig/claes---umea/-sas-som-i-himmelen-/",
  "https://www.koket.se/caroline_hofberg/varmratter/vilt/vild_porterstek/",
  "https://www.koket.se/jamie_oliver/varmratter/ris__couscous_och_andra_gryn/risotto_med_rostad_svamp/",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/pepparstek/",
  "https://www.koket.se/halv-atta-hos-mig/mats---sodertalje/rodingfile-med-palsternackspure/",
  "https://www.koket.se/chicken-ramen-bowl",
  "https://www.koket.se/ljummen-nudelsallad-med-friterad-kyckling",
  "https://www.koket.se/koreansk-taco",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/kramig-pasta-med-sidflask-och-parmesan/",
  "https://www.koket.se/nyhetsmorgon/werner-vogeli/wallenbergare/",
  "https://www.koket.se/markus-aujalay/varmratter/pasta-och-nudlar/spaghetti-med-kantareller--trumpetsvamp--parmesan-och-rucola/",
  "https://www.koket.se/morberg-lagar-husmanskost/per-morberg/per-morbergs-skinkstek-med-kokt-rodkal/",
  "https://www.koket.se/kikartsbiffar-med-ratatouille-och-basilikacreme",
  "https://www.koket.se/catarina-konigs-lyxtacos",
  "https://www.koket.se/tommys-basta-pastasallad",
  "https://www.koket.se/filip_fasten/varmratter/kott/osso_buco/",
  "https://www.koket.se/ernst_kirchsteiger/varmratter/kott/ernsts_lammkotletter/",
  "https://www.koket.se/jattegod-laxburgare-med-ortaioli-och-picklad-gurka",
  "https://www.koket.se/jens_linder/varmratter/kott/helstekt_kotlett_som_i_florens/",
  "https://www.koket.se/mansoreh_asgari/varmratter/kyckling_och_fagel/salade_olivie/",
  "https://www.koket.se/mustafa-iskandarani/varmratter/artor-bonor-linser/falafel-fran-libanon/",
  "https://www.koket.se/per-morberg/varmratter/fisk-och-skaldjur/hummer--nykokt-och-gratinerad/",
  "https://www.koket.se/pankopanerad-plattfisk-med-rattika-sweet-chili",
  "https://www.koket.se/fredrik_och_matthias___stockholm/varmratter/_/tre_kinesiska_dumplings_med_tre_tillbehor/",
  "https://www.koket.se/smorstekt-kolja-med-klassiska-tillbehor",
  "https://www.koket.se/taco-madness",
  "https://www.koket.se/cheeseburgare-med-tva-sorters-lok",
  "https://www.koket.se/paolo-roberto/varmratter/kyckling/kycklingklubbor-i-ugn---pollo-al-forno/",
  "https://www.koket.se/ulrika_davidsson/varmratter/fisk_och_skaldjur/chevrelax_med_gronsallad/",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/halstrade-pilgrimsmusslor-med-rastekt-blomkal/",
  "https://www.koket.se/kalasgott/jennie-benjaminsson/gnocchigratang/",
  "https://www.koket.se/mitt-kok/paolo-roberto/pastagratang-med-bacon--svamp-och-ostsas/",
  "https://www.koket.se/sverigesmasterkock/sveriges-masterkock/helstekt-oxfile-med-rodvinssas--spada-gronsaker-och-hasselbackspotatis/",
  "https://www.koket.se/danyel_couet/varmratter/kyckling/gumbo___mustig_kycklinggryta/",
  "https://www.koket.se/kryddig-linsgryta-med-morotsbullar",
  "https://www.koket.se/per_morberg/varmratter/pasta_och_nudlar/per_morbergs_pasta_di_piero_moreno/",
  "https://www.koket.se/nyhetsmorgon/cecilia-vikbladh/seitan-pa-vetemjol-special/",
  "https://www.koket.se/ulrika-jisland/varmratter/pasta-och-nudlar/snabb-citronpasta/",
  "https://www.koket.se/per_morberg/varmratter/kraftor/per_morbergs_kokta_kraftor/",
  "https://www.koket.se/fredrik_eriksson/huvudratter/kott/viltskav_med_svamp/",
  "https://www.koket.se/mitt-kok/filip-fasten/flaskfile-med-hasselbackspotatis/",
  "https://www.koket.se/gnocchi-med-mamma-ancis-rosa-pastasas",
  "https://www.koket.se/ugnsstekt-kotlett-med-potatisgratang",
  "https://www.koket.se/tommy_myllymaki/varmratter/kott/stek/",
  "https://www.koket.se/mitt-kok/jennie-wallden/bbq-burritos-med-kyckling/",
  "https://www.koket.se/thaikryddad-kyckling-med-glasnudlar",
  "https://www.koket.se/bonniers_kokbok/varmratter/kott/serranolindad_oxfile_med_rosmarin/",
  "https://www.koket.se/tjalknol-med-appelchutney-och-kantarellsas",
  "https://www.koket.se/snabb-mandagspasta-med-tofusas-och-champinjoner",
  "https://www.koket.se/teriyakiwok-med-flaskfile-paprika-och-savojkal",
  "https://www.koket.se/paolos-tomat-och-tonfiskpasta",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/huevos-rancheros/",
  "https://www.koket.se/viktor_westerlind/varmratter/kott/rodvinskokt_lammlagg_med_persilja/",
  "https://www.koket.se/leilas-mat/leila-lindholm/helstekt-entrecote/",
  "https://www.koket.se/lchf-kokboken/sten-sture-skaldeman/gulaschsoppa/",
  "https://www.koket.se/halloumi-stroganoff-med-couscous",
  "https://www.koket.se/ola_lauritzson/varmratter/kyckling/citron__och_salviafylld_kycklingfile_och_medelhavssallad/",
  "https://www.koket.se/mitt-kok/paolo-roberto/pasta-med-snabb-paprikasas/",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/kycklingschnitzel-cordon-bleu/",
  "https://www.koket.se/koreanska-tacos-med-entrecote-och-chiliaioli",
  "https://www.koket.se/fiskgryta-med-saffran-2",
  "https://www.koket.se/anette_rosvall_och_emma_hamberg/varmratter/korv_och_chark/fylld_frukostkorv/",
  "https://www.koket.se/lisa_lemke/varmratter/laxfile/snabblagad_lax_med_mandeltacke/",
  "https://www.koket.se/lax-och-kyckling/kristina-eriksson/kycklinggryta-med-coca-cola/",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/svartpepparstekt-tonfisk/",
  "https://www.koket.se/italiensk-paj-med-mozzarella-tomat-och-basilika",
  "https://www.koket.se/gratang-med-potatis-jordartskocka-kantareller-och-rodbetsblast",
  "https://www.koket.se/barnens-basta-fest/anna-lind-lewin/kottfars-africana/",
  "https://www.koket.se/jamie-oliver/varmratter/pasta-och-nudlar/jamie-olivers-carbonara-med-zucchini/",
  "https://www.koket.se/per-morberg/varmratter/kott/per-morbergs-recept-pa-julskinka-med-griljering/",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/pulled-pork-sandwich-med-surkal/",
  "https://www.koket.se/ankbrost-med-sockerstekt-potatis-serveras-med-kantarellsas-och-pressgurka",
  "https://www.koket.se/oxfileplanka-med-duchessepotatis-och-bearnaise",
  "https://www.koket.se/hostcarbonara-med-kantareller",
  "https://www.koket.se/jens_linder/varmratter/kott/svensk_oxstek_med__morotter_och_lok/",
  "https://www.koket.se/mitt-kok/donal-skehan/phad-thai/",
  "https://www.koket.se/eja_nilsson/varmratter/agg_och_mejeri/socca___provensalsk_kikartspannkaka/",
  "https://www.koket.se/halv-atta-hos-mig/emil---mariestad/file--och-kantarelltackling-med-ett-stank-av-rott/",
  "https://www.koket.se/mikaela__stockholm/varmratter/vilt/helstekt_hjortytterfile_med_potatiskaka/",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/lammfarsbiffar-med-graddkokt-savoykal/",
  "https://www.koket.se/indisk-dosa-med-kryddig-potatis-och-blomkal",
  "https://www.koket.se/tunnbrodrulle-med-korv-och-raksallad",
  "https://www.koket.se/pannbiff-med-loksky-och-mosad-potatis",
  "https://www.koket.se/tommy-myllymakis-skomakarlada",
  "https://www.koket.se/ugnsgratinerad-falukorv-med-potatismos",
  "https://www.koket.se/okand/varmratter/kyckling_och_fagel/kycklinggryta/",
  "https://www.koket.se/hemma-hos-melker-andersson/melker-andersson/melkers-orientaliska-laxfile-i-ugnen/",
  "https://www.koket.se/kolgrillad-sosida-serveras-med-ugnsrostade-rotfrukter",
  "https://www.koket.se/fylld-prosciuttolindad-kycklingfile",
  "https://www.koket.se/morotsfalafel-med-appeltzatziki",
  "https://www.koket.se/anders_leven/varmratter/kott/yakiniku/",
  "https://www.koket.se/oxfile-med-vasterbottensduchesse-samt-flamberad-gronpepparsas",
  "https://www.koket.se/grekiska-kycklingspett-med-potatisgratang-med-fetaost-och-vitlok",
  "https://www.koket.se/halv-atta-hos-mig/ingvar---kungsbacka/ingvars-fiskgratang-med-rakor/",
  "https://www.koket.se/lennart___halmstad/varmratter/fisk_och_skaldjur/stickans_festspatta/",
  "https://www.koket.se/paolos-pasta-med-rostade-gronsaker",
  "https://www.koket.se/asian-egg-fried-rice",
  "https://www.koket.se/chicken-tikka-masala-med-rostade-cashewnotter-och-naanbrod",
  "https://www.koket.se/hemgjord-kebabpizza-lisa-lemkes-basta-recept",
  "https://www.koket.se/gronkalspaj-med-vasterbottenost",
  "https://www.koket.se/nyhetsmorgon/jennie-wallden/koreanska-dumplings-med-sotsur-dipp/",
  "https://www.koket.se/matgladje-hela-livet/leif-mannerstrom/laxpudding/",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/ciderkyckling-med-ris/",
  "https://www.koket.se/lyxiga-langos-med-kramig-kraftrora",
  "https://www.koket.se/nyhetsmorgon/yohan-adell/boeuf-a-la-bourguignonne/",
  "https://www.koket.se/johan___ostersund/varmratter/vilt/braserad_algbog_med_mandelpotatispure/",
  "https://www.koket.se/ugnspannkaka-med-kalkonbacon",
  "https://www.koket.se/risotto-med-trattkantareller-svart-trumpetsvamp-och-ostronskivling",
  "https://www.koket.se/hogrevsgryta-med-chorizo-paprika-tomat-och-spiskummin",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/tomatgratinerad-cannelloni-med-skinka/",
  "https://www.koket.se/koket/pelle-johansson/kalpudding-pa-blandfars/",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/torsk-med-vitvinssas-och-morotter/",
  "https://www.koket.se/markus_aujalay/varmratter/kott/flaskkotlett_med_svamp/",
  "https://www.koket.se/halv-atta-hos-mig/sara---stockholm/boeuf-bourgiugnon-med-mandelpotatispure/",
  "https://www.koket.se/lammkotlett-med-parmesan-och-timjanstuvad-spetskal",
  "https://www.koket.se/tarte-flambee-med-lok-och-ansjovis",
  "https://www.koket.se/coconut-bean-curry-med-vitkal-och-morotter",
  "https://www.koket.se/wallenbergare-med-klassiska-tillbehor",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/klassisk-coq-au-vin-med-vitloksfrasta-haricots-verts/",
  "https://www.koket.se/jens_linder/soppor_och_grytor/kyckling_och_fagel/murgh_makhani___indisk_smorkyckling/",
  "https://www.koket.se/koket/anders-leven/kottfarssoppa/",
  "https://www.koket.se/poulet-au-vin-serveras-med-blomkalspure",
  "https://www.koket.se/quinoabowl-med-sojastekt-tofu-avokado-och-paprikahummus",
  "https://www.koket.se/teriyakilax-med-sesamris",
  "https://www.koket.se/gratang-med-torsk",
  "https://www.koket.se/helstekt-rostasfile-med-balsamicosas",
  "https://www.koket.se/pastasallad-med-tonfisk-fetaost-och-frasiga-kajennsmulor",
  "https://www.koket.se/risotto-grundrecept",
  "https://www.koket.se/kycklingrullader-med-cidersas-och-pressad-potatis",
  "https://www.koket.se/mitt-kok/lisa-lemke/snabblasagne-med-ricotta-och-tomat",
  "https://www.koket.se/mitt-kok/jennie-wallden/pizza-bianca/",
  "https://www.koket.se/nyhetsmorgon/sigrid-barany/hamburgare/",
  "https://www.koket.se/osso-bucco-med-risotto-alla-milanese",
  "https://www.koket.se/boeuf-bourguignon-med-rostade-potatisar-och-rotsaker",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/dillkyckling/",
  "https://www.koket.se/leila-lindholm/varmratter/kott/helgrillad-entrecote/",
  "https://www.koket.se/nyhetsmorgon/tom-sjostedt/chili-med-guacamole/",
  "https://www.koket.se/le-parfait/le-parfait/pasta-med-smorfriterad-salvia/",
  "https://www.koket.se/het-jambalaya-serveras-med-ris",
  "https://www.koket.se/halstrad-rabiff-med-pommes-allumettes-och-kryddsmor",
  "https://www.koket.se/libanesiska-quinoabiffar-med-gron-linssallad",
  "https://www.koket.se/mitt-kok/lisa-lemke/kycklingenchiladas/",
  "https://www.koket.se/monica-eisenman/varmratter/kyckling-och-fagel/satay-med-jordnotssas/",
  "https://www.koket.se/kalasgott/jennie-benjaminsson/underbara-smordegspizzor/",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/tommys-dumplings-med-flaskfars/",
  "https://www.koket.se/nyhetsmorgon/sigrid-barany/ortstekt-lammsadel-med-portvinssas-och-getostduchesse/",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/skaldjurspaella-med-snabb-aioli/",
  "https://www.koket.se/skaldjursrisotto-med-blamusslor-och-saffran",
  "https://www.koket.se/svampravioli-med-kramig-vitvinssas-rostade-pinjenotter-ruccola-och-svart-tryffel-2",
  "https://www.koket.se/fylld-pasta-se-gor",
  "https://www.koket.se/mitt-kok/donal-skehan/kyckling-med-citrongras-och-chili/",
  "https://www.koket.se/barnens-basta-fest/anna-lind-lewin/supersnabb-kottfarsrora/",
  "https://www.koket.se/chili",
  "https://www.koket.se/szechuan-pork-tenderloin-salad",
  "https://www.koket.se/kottfarswok",
  "https://www.koket.se/halv-atta-hos-mig/jessica---soderhamn/ugnsgrillad-kycklingfile/",
  "https://www.koket.se/ulrika_hoffer/varmratter/fisk_och_skaldjur/citronlax_i_folie/",
  "https://www.koket.se/arrosto-con-patate-all-italiana",
  "https://www.koket.se/kramig-rotfruktssoppa-med-graslok",
  "https://www.koket.se/helstekt-kalvfile-grundrecept",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/kycklingtacos-med-rostad-tomatsalsa/",
  "https://www.koket.se/leila_lindholm/varmratter/pasta_och_nudlar/rigatoni_med_karljohansvamp/",
  "https://www.koket.se/nils_emil_ahlin/huvudratter/kott/kokt_rimmat_flasklagg_med_rotmos/",
  "https://www.koket.se/nyhetsmorgon/markus-aujalay/ris-i-ugn-med-flaskkarre--chorizo--paprika-och-lok/",
  "https://www.koket.se/le-parfait/liselotte-forslin/alggryta-med-rotfrukter-och-svamp/",
  "https://www.koket.se/allt-pa-en-plat-med-korv-pumpa-och-lok",
  "https://www.koket.se/kreolsk-kottgryta-med-hasselbackspotatis",
  "https://www.koket.se/fiskgratang-med-citronsas-och-fankalssallad",
  "https://www.koket.se/smorrebrod-med-rostbiff-dijonkram-pepparrot-och-karamelliserad-lok",
  "https://www.koket.se/mitt-kok/paolo-roberto/spaghetti-alla-puttanesca",
  "https://www.koket.se/naringsrik-och-naturlig-lchf/klara-desser/ugnsbakad-lax-med-pinje--och-orttacke/",
  "https://www.koket.se/torskrygg-med-vasterbottensost-rodvin-och-syrad-lok",
  "https://www.koket.se/gi_viktkoll/huvudratter/fisk_och_skaldjur/sejfile_med_citronsas_och_rakor/",
  "https://www.koket.se/le-parfait/le-parfait/saltbakad-lax-med-yoghurtsas/",
  "https://www.koket.se/indisk-gryta-tandoori-garam-masala",
  "https://www.koket.se/klassisk-lasagne-med-mexikanska-smaker",
  "https://www.koket.se/ugnsbakad-fetaost-med-citron-och-orter",
  "https://www.koket.se/jureskogs-basta-burgare",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/fransk-kalvgryta-med-vitt-vin--rotfrukter-och-svamp/",
  "https://www.koket.se/mitt-kok/jennie-wallden/saftig-flaskfile-med-bearnaise-och-ugnsrostade-rotsaker/",
  "https://www.koket.se/jacob_wismar/soppor_och_grytor/kyckling_och_fagel/indisk_kyckling/",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/honungsstekt-flaskkarre-med-salsa/",
  "https://www.koket.se/five-spice-auberginebowl-med-krispigt-agg",
  "https://www.koket.se/portabelloburgare-med-ostaioli-och-karamelliserad-rodlok",
  "https://www.koket.se/stekt-lax-med-rostad-pestopotatis",
  "https://www.koket.se/per_morberg/varmratter/fisk_och_skaldjur/per_morbergs_rodspatta_grenoble/",
  "https://www.koket.se/leif_mannerstrom/varmratter/agg_och_mejeri/omelett_med_rakstuvning/",
  "https://www.koket.se/fredrik_eriksson/varmratter/vilt/algfarsbiffar/",
  "https://www.koket.se/yakiniku-med-jasminris-och-sallad",
  "https://www.koket.se/paolos-pizza-med-salsiccia-rosmarin-och-tre-sorters-ost",
  "https://www.koket.se/allt-i-ett-kycklinggryta",
  "https://www.koket.se/snabb-kinesisk-gryta-med-tofu",
  "https://www.koket.se/renfile-och-syltade-trattkantareller",
  "https://www.koket.se/mitt-kok/donal-skehan/lasagne-med-tre-sorters-ost/",
  "https://www.koket.se/marinerad-helstekt-flaskfile",
  "https://www.koket.se/mitt-kok/jennie-wallden/pannbiff-med-lok-och-rastekt-potatis/",
  "https://www.koket.se/leif-mannerstrom/varmratter/fisk-och-skaldjur/gratinerad-slatvar-med-duchessepotatis/",
  "https://www.koket.se/filip_fasten/varmratter/kott/oxrullader/",
  "https://www.koket.se/halv-atta-hos-mig/sara---stockholm/rimmad-torskrygg-med-knaperstekt-bacon/",
  "https://www.koket.se/bakad-sotpotatis-med-het-spenat-och-kikartscurry",
  "https://www.koket.se/linsbolognese-med-pasta",
  "https://www.koket.se/mitt-kok/tom-sjostedt/ugnsbakad-kyckling-med-rosmarin",
  "https://www.koket.se/anders_vendel/varmratter/ris/rodvinsrisotto_med_svamp__manchego_och_krasse/",
  "https://www.koket.se/forkvall/johan-jureskog/pytt-bellman/",
  "https://www.koket.se/anders_leven/varmratter/kott/tournedos_rossini/",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/pasta-med-torsk/",
  "https://www.koket.se/kall-flaskfile-serveras-med-potatisbatar",
  "https://www.koket.se/chipotle-hongos-med-picklad-rodlok-och-pico-de-gallo",
  "https://www.koket.se/korean-fried-chicken",
  "https://www.koket.se/steak-minute-med-bearnaise-och-rosti",
  "https://www.koket.se/festlig-oxfile-med-potatisgratang-och-rodvinssas",
  "https://www.koket.se/anette_rosvall_och_emma_hamberg/varmratter/kyckling_och_fagel/mamsingens_kycklinglasagne/",
  "https://www.koket.se/mitt-kok/jennie-wallden/rostad-citronblomkal-med-frasig-torsk-och-remouladsas/",
  "https://www.koket.se/hemgjorda-fiskbullar-i-thaicurrysas",
  "https://www.koket.se/fisk-gratang-pa-kronartskocka-och-tofu",
  "https://www.koket.se/sesamtofu-med-rostade-rotfrukter-och-rostad-vitloksmajonnas",
  "https://www.koket.se/hemgjorda-dumplings-med-sotsyrlig-sojadipp",
  "https://www.koket.se/morotssoppa-med-ra-ingefara-och-avokado",
  "https://www.koket.se/asiatisk-sommarsallad-med-lax-och-sesamdressing",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/baconlindad-kottfarslimpa-med-anjovis/",
  "https://www.koket.se/torsk-med-aggsas",
  "https://www.koket.se/lattlagat/pelle-johansson/tacopaj/",
  "https://www.koket.se/mitt-kok/donal-skehan/thaigryta-med-kyckling/",
  "https://www.koket.se/lchf-kokboken/sten-sture-skaldeman/omelett-med-svampstuvning/",
  "https://www.koket.se/ugnsstekt-kyckling-med-farsk-pasta-och-vitloks-och-adelostsas",
  "https://www.koket.se/raggmunk-med-butternutpumpa-och-mandelmjol",
  "https://www.koket.se/pulled-pork-pa-rostat-surdegsbrod-med-mango-och-tomatsallad-smashed-avokado-och-ingefarspicklad-rodlok",
  "https://www.koket.se/torskrygg-pa-en-badd-av-juliennegronsaker",
  "https://www.koket.se/pasta-med-zucchini-vitlok-och-mozzarella",
  "https://www.koket.se/sverigesmasterkock/leif-mannerstrom/leif-mannerstroms-foralskade-havskraftor/",
  "https://www.koket.se/lchf---husmanskost/anna-hallen/kottbullar-med-brunsas/",
  "https://www.koket.se/klockan-nio-hos-stjarnorna/tobbe-blom/indonesisk-kycklinggratang/",
  "https://www.koket.se/tacogratang-med-paprika-och-salsa",
  "https://www.koket.se/supersnabb-japansk-kycklingbowl-se-gor",
  "https://www.koket.se/tonfisksallad-med-avokado-och-srirachamajonnas",
  "https://www.koket.se/chicken-tikka-mas-a-la-par",
  "https://www.koket.se/johan_jureskog/varmratter/kyckling_och_fagel/coq_au_vin/",
  "https://www.koket.se/byung_hi_och_byung_soon_lim/varmratter/kott/grillat_sidflask___samgyopsal/",
  "https://www.koket.se/nyhetsmorgon/louise-johansson/bakad-flasksida-med-mandelpotatispure",
  "https://www.koket.se/klockan-nio-hos-stjarnorna/josefin-crafoord/josefins-gottiga-cowboychili-pa-hogrev/",
  "https://www.koket.se/ingefarsgravad-lax-med-nudelsallad-och-wasabimajonnas",
  "https://www.koket.se/mammas-frasiga-kyckling-med-rotsaker-och-aioli",
  "https://www.koket.se/skargardssoppa-med-lax-vitt-vin-och-hummerfond",
  "https://www.koket.se/bovetegalette-med-spenat-och-skinka",
  "https://www.koket.se/asiatiska-salladsrullar-med-knaperstekt-flaskfars",
  "https://www.koket.se/bakad-potatis-med-cheddar-lok-och-bacon",
  "https://www.koket.se/noah_likhaya/varmratter/artor__bonor_och_linser/chapati_med_gryta_pa_mungbonor/",
  "https://www.koket.se/stefano_catenacci/soppor_och_grytor/rotfrukter/minestrone/",
  "https://www.koket.se/sara_begner/varmratter/kott/helstekt_rostbiff_med_fetagronsaker/",
  "https://www.koket.se/koket/anders-leven/moules-frites-med-aioli/",
  "https://www.koket.se/flaskkorv-med-kalrotskram-pa-brynt-smor",
  "https://www.koket.se/familjens-godaste-kalkonbolognese",
  "https://www.koket.se/citronstekt-kycklingklubba-med-spenat-rodbetssallad",
  "https://www.koket.se/mustig-svampsoppa-med-ostflarn",
  "https://www.koket.se/isabel_berggren/varmratter/kott/flaskkarre_i_lergryta/",
  "https://www.koket.se/mitt-kok/karin-andersson/pasta-med-tomat-och-sidflask/",
  "https://www.koket.se/farska-varrullar-med-sotsyrlig-dipp",
  "https://www.koket.se/laxburgare-med-mangoyoghurt",
  "https://www.koket.se/frasiga-kycklingbiffar-med-asiatisk-rakostsallad",
  "https://www.koket.se/zucchinibiffar-med-appelsallad-och-citronyoghurt",
  "https://www.koket.se/ingrid___ostersund/varmratter/fisk_och_skaldjur/marulk_och_potatispure_med_kantareller/",
  "https://www.koket.se/per_morberg/varmratter/kott/per_morbergs_biffstek_med_smorslungad_lok/",
  "https://www.koket.se/monikas-vardagsmat/monika-ahlberg/falukorv-med-rotfruktsgratang/",
  "https://www.koket.se/rodbetsgnocchi-med-zucchini-salvia-och-basilika",
  "https://www.koket.se/fisktacos-med-mangosallad",
  "https://www.koket.se/pizza-bianca-med-karamelliserad-lok",
  "https://www.koket.se/pumpa-och-getostpaj",
  "https://www.koket.se/zucchinibiffar-med-appelsallad-och-citronyoghurt",
  "https://www.koket.se/ingrid___ostersund/varmratter/fisk_och_skaldjur/marulk_och_potatispure_med_kantareller/",
  "https://www.koket.se/per_morberg/varmratter/kott/per_morbergs_biffstek_med_smorslungad_lok/",
  "https://www.koket.se/monikas-vardagsmat/monika-ahlberg/falukorv-med-rotfruktsgratang/",
  "https://www.koket.se/rodbetsgnocchi-med-zucchini-salvia-och-basilika",
  "https://www.koket.se/fisktacos-med-mangosallad",
  "https://www.koket.se/pizza-bianca-med-karamelliserad-lok",
  "https://www.koket.se/pumpa-och-getostpaj",
  "https://www.koket.se/cannelloni-med-kycklingfars-och-svamp",
  "https://www.koket.se/jessica-frejs-arribiata-med-mozzarella",
  "https://www.koket.se/torskrygg-med-pancetta-skaldjurssas-och-dillolja",
  "https://www.koket.se/pasta-italiano-med-extra-allt",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/krabbkakor-med-hemgjord-tartarsas/",
  "https://www.koket.se/mitt-kok/jennie-wallden/isterband-med-persiljestuvad-potatis/",
  "https://www.koket.se/ernst_kirchsteiger/varmratter/fisk_och_skaldjur/laxpudding/",
  "https://www.koket.se/caroline_hofberg/varmratter/pasta_och_nudlar/ugnsbakad_pasta_med_mozzarella/",
  "https://www.koket.se/cannelloni-med-kycklingfars-och-svamp",
  "https://www.koket.se/jessica-frejs-arribiata-med-mozzarella",
  "https://www.koket.se/torskrygg-med-pancetta-skaldjurssas-och-dillolja",
  "https://www.koket.se/pasta-italiano-med-extra-allt",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/krabbkakor-med-hemgjord-tartarsas/",
  "https://www.koket.se/mitt-kok/jennie-wallden/isterband-med-persiljestuvad-potatis/",
  "https://www.koket.se/ernst_kirchsteiger/varmratter/fisk_och_skaldjur/laxpudding/",
  "https://www.koket.se/caroline_hofberg/varmratter/pasta_och_nudlar/ugnsbakad_pasta_med_mozzarella/",
  "https://www.koket.se/marinerad-kycklingfile-serveras-med-potatis-duchesse-och-kramig-heta-drommar-sas",
  "https://www.koket.se/klassisk-carbonara-med-capresesallad",
  "https://www.koket.se/lasagne-med-svamp-och-rosmarin",
  "https://www.koket.se/zucchinifalafel-i-pitabrod",
  "https://www.koket.se/nyhetsmorgon/johan-hedberg/algfarsbiffar-med-graddsas/",
  "https://www.koket.se/sverigesmasterkock/per-jarn/smorstekt-kummelfile-med-palsternackspure-och-smorsas/",
  "https://www.koket.se/halv-atta-hos-mig/peter---gran-canaria/peters-specialare-med-flaskfile/",
  "https://www.koket.se/sveriges-skonaste-gardar/eskesta-gard/pasta-pesto-med-mozzarella/",
  "https://www.koket.se/marinerad-kycklingfile-serveras-med-potatis-duchesse-och-kramig-heta-drommar-sas",
  "https://www.koket.se/klassisk-carbonara-med-capresesallad",
  "https://www.koket.se/lasagne-med-svamp-och-rosmarin",
  "https://www.koket.se/zucchinifalafel-i-pitabrod",
  "https://www.koket.se/nyhetsmorgon/johan-hedberg/algfarsbiffar-med-graddsas/",
  "https://www.koket.se/sverigesmasterkock/per-jarn/smorstekt-kummelfile-med-palsternackspure-och-smorsas/",
  "https://www.koket.se/halv-atta-hos-mig/peter---gran-canaria/peters-specialare-med-flaskfile/",
  "https://www.koket.se/sveriges-skonaste-gardar/eskesta-gard/pasta-pesto-med-mozzarella/",
  "https://www.koket.se/vitloksspackad-lammstek-med-stuvad-purjolok-och-smashed-potato",
  "https://www.koket.se/torskrygg-med-krassesmor-och-artsallad",
  "https://www.koket.se/flankstek-med-potatispuck-och-rostade-minimorotter",
  "https://www.koket.se/helgrillad-kyckling-med-lok-och-chili",
  "https://www.koket.se/pumpapaj-med-bacon-och-purjolok",
  "https://www.koket.se/snabb-pasta-med-gravad-lax-och-pesto",
  "https://www.koket.se/johan_jureskog/varmratter/kott/dillkott_pa_lamm/",
  "https://www.koket.se/mitt-kok/jennie-wallden/helrostad-kyckling-med-rosesallad/",
  "https://www.koket.se/forkvall/christian-campogiani/cappellini-med-kottbullar-och-tomatsas/",
  "https://www.koket.se/per_morberg/varmratter/kott/honugsglaserade_revbensspjall/",
  "https://www.koket.se/fredrik_eriksson/huvudratter/gronsaker__potatis_och_andra_rotfrukter/fredrik_erikssons_rosti/",
  "https://www.koket.se/ola-lauritzson/varmratter/kott/fylld-lovbiff-med-blomkalspure/",
  "https://www.koket.se/kalasgott/jennie-benjaminsson/flaskfilegryta-med-rosepeppar/",
  "https://www.koket.se/jul-med-ernst/ernst-kirchsteiger/algkottbullar-med-havregryn/",
  "https://www.koket.se/fransk-pastasallad-med-vita-bonor-agg-och-grasloksdressing",
  "https://www.koket.se/gyoza-med-flaskfars-sesam-och-ingefara",
  "https://www.koket.se/renee-voltaires-vegobiffar",
  "https://www.koket.se/vietnamesiska-spring-rolls-med-dippsas",
  "https://www.koket.se/linsbiffar-med-kramig-sallad",
  "https://www.koket.se/vildsvinssadel-med-persika-och-timjan",
  "https://www.koket.se/nyhetsmorgon/annika-sjoo/morotsspaghetti-med-kottfarssas/",
  "https://www.koket.se/tasanee-lidstrom/pad-thai-pa-kyckling--biff-eller-rakor/",
  "https://www.koket.se/mitt-kok/jennie-wallden/kyckling-med-grillad-citron-och-timjansas/",
  "https://www.koket.se/mitt-kok/donal-skehan/cannelloni-med-spenat-och-svamp/",
  "https://www.koket.se/sesamkryddad-kyckling-pa-spett-med-jordnotssas",
  "https://www.koket.se/pasta-med-morotsbullar-och-tomatsas",
  "https://www.koket.se/kycklinggryta-med-potatis-och-ras-el-hanout",
  "https://www.koket.se/fransk-kycklinggryta-med-linser",
  "https://www.koket.se/rodbetspaj-med-feta-honung-och-timjan",
  "https://www.koket.se/gron-pizza-med-fetaost-avokado-vitlok-ruccola-och-zucchini",
  "https://www.koket.se/anette_rosvall_och_emma_hamberg/varmratter/kott/helstekt_rostbiff_med_goda_tillbehor/",
  "https://www.koket.se/pelle_johansson/varmratter/ris__couscous_och_andra_gryn/risotto_med_kycklingfile_och_karljohansvamp/",
  "https://www.koket.se/sara___vaxjo/varmratter/kott/helstekt_oxfile__gourmet_/",
  "https://www.koket.se/halv-atta-hos-mig/camilla---dalsland/porterstek-pa-alg-med-hasselbackspotatis/",
  "https://www.koket.se/forkvall/johan-jureskog/stekta-pilgrimsmusslor-med-primorer-och-beurre-blanc/",
  "https://www.koket.se/panerad-rotselleri-med-artpotatismos-och-tartarsas",
  "https://www.koket.se/paolos-pasta-med-kyckling-och-salvia",
  "https://www.koket.se/oxfile-med-rotsellerikram-ingefarsinlagda-svarta-vinbar-och-rivet-hasselnotsmor",
  "https://www.koket.se/vegetarisk-gryta-med-savoykal-svamp-linser-och-vitt-vin",
  "https://www.koket.se/sesamrostad-kyckling-med-kramig-coleslaw",
  "https://www.koket.se/ugnsbakad-lax-med-basilikakram",
  "https://www.koket.se/sjotunga-walewska-med-gratinerat-mos",
  "https://www.koket.se/leif_mannerstrom/varmratter/svamp/kantarellrisotto_med_patanegraskinka__basilika_och_hyvlad_parmesan/",
  "https://www.koket.se/paolo_roberto/varmratter/ris__couscous_och_andra_gryn/risotto_con_funghi/",
  "https://www.koket.se/johan_jureskog/varmratter/fisk_och_skaldjur/torsk_med_agg__och_persiljesas/",
  "https://www.koket.se/monika_ahlberg/varmratter/ris__couscous_och_andra_gryn/svamprisotto/",
  "https://www.koket.se/ulrika-davidsson/varmratter/korv-och-chark/mozzarellafylld-falukorv-med-ajvar/",
  "https://www.koket.se/mitt-kok/tommy-myllymaki/svampragu-med-gnocchi/",
  "https://www.koket.se/karamelliserad-flaskytterfile-med-mystisk-sas",
  "https://www.koket.se/chorizopytt-i-ugnen",
  "https://www.koket.se/bouillabaisse-med-rouille",
  "https://www.koket.se/kramig-flaskfilepasta-med-paprika",
  "https://www.koket.se/mitt-kok/jennie-wallden/saffransrisotto-med-rostad-mandel/",
  "https://www.koket.se/husmorsorna/anette-rosvall-och-emma-hamberg/fyllda-algfarsbiffar/",
  "https://www.koket.se/per_morberg/varmratter/kott/per_morbergs_lammgryta_med_curry/",
  "https://www.koket.se/matgladje-hela-livet/leif-mannerstrom/kycklingbrost-med-parmesan/",
  "https://www.koket.se/nyhetsmorgon/anette-rosvall-och-emma-hamberg/raksallad/",
  "https://www.koket.se/stekt-torsk-med-tacokryddad-tomatsas-och-nachos",
  "https://www.koket.se/karibisk-rice-n-beans-med-jerkmarinerad-tofu",
  "https://www.koket.se/grillad-kyckling-med-ugnsrostade-gronsaker-och-ramsloksdressing",
  "https://www.koket.se/mustig-kottfarssas-for-riktiga-karlar",
  "https://www.koket.se/fisksoppa-med-smak-av-saffran",
  "https://www.koket.se/vegetarisk-masala",
  "https://www.koket.se/sara_ask/varmratter/fisk_och_skaldjur/barnmat__hemmagjorda_fiskpinnar/",
  "https://www.koket.se/paolo_roberto/varmratter/gronsaker__potatis_och_andra_rotfrukter/gnocchi_di_patate_con_salsa_di_pomodoro__gratinati_al_forno/",
  "https://www.koket.se/tina-i-fjallen/tina-nordstrom/korv-stroganoff-med-rokt-flask--paprika-och-rosmarin/",
  "https://www.koket.se/mitt-kok/donal-skehan/vodka-penne/",
  "https://www.koket.se/pastasallad-med-grillad-citronkyckling",
  "https://www.koket.se/spaghetti-med-sparris-parmesan-och-farska-orter",
  "https://www.koket.se/kalvfile-med-potatisrosor-och-svampsas-lucky-biff-med-lukes-rosepotato",
  "https://www.koket.se/fettuccine-alla-contadina",
  "https://www.koket.se/mitt-kok/lisa-lemke/pasta-med-tonfisk-och-citron/",
  "https://www.koket.se/nyhetsmorgon/byung-hi-och-byung-soon-lim/glasnudlar-med-gronsaker---chapachae/",
  "https://www.koket.se/hakan-larsson/varmratter/fisk-och-skaldjur/lax-med-astrids-basilikasas/",
  "https://www.koket.se/per_morberg/varmratter/kott/per_morbergs_buljongbraserade_flaskkotletter/",
  "https://www.koket.se/halv-atta-hos-mig/andreas---malmo/vild-kalpudding/",
  "https://www.koket.se/grillad-pluma-de-iberico-med-aprikossallad-och-varm-getostcreme",
  "https://www.koket.se/vietnamesisk-nudelsoppa-med-kyckling",
  "https://www.koket.se/peters-kroppkakor",
  "https://www.koket.se/dragonkycklinggryta-med-palsternacksklyftor",
  "https://www.koket.se/spaghetti-e-fagioli",
  "https://www.koket.se/toms-fish-and-chips",
  "https://www.koket.se/halv-atta-hos-mig/helen---varberg/kyckling-cordon-bleu-med-hasselbackspotatis-och-champinjonsas/",
  "https://www.koket.se/halv-atta-hos-mig/sandra---helsingborg/lax-walewska-pa-planka/",
  "https://www.koket.se/sommar-med-ernst/ernst-kirchsteiger/ernsts-lyxpytt-med-rodbetstzatziki/",
  "https://www.koket.se/svart-ris-med-ingefarsmarinerad-lax-och-avokado",
  "https://www.koket.se/indisk-blomkalsgryta-med-naanbrod",
  "https://www.koket.se/chili-med-gron-salsa-och-nachos",
  "https://www.koket.se/asiatisk-nudelsallad-med-rakor",
  "https://www.koket.se/mitt-kok/paolo-roberto/spaghetti-med-stora-kottbullar-i-tomatsas/",
  "https://www.koket.se/plankstek",
  "https://www.koket.se/margit-eliasson-och-gunilla-lindeberg/varmratter/kott/solgryta-pa-flaskkott-med-ananas/",
  "https://www.koket.se/pernillas-jul---kokboken/pernilla-wahlgren/oxfile-med-rodvinssky/",
  "https://www.koket.se/pitabrod-fyllda-med-lammkottbullar-och-tzatziki",
  "https://www.koket.se/snabb-nasi-goreng-med-flaskkarre-och-agg",
  "https://www.koket.se/torsk-med-pepparrot-och-skirat-smor",
  "https://www.koket.se/megasnabb-mustig-tomatsoppa-med-grillad-paprika",
  "https://www.koket.se/tortillas-med-svamp-mozzarella-och-lingon",
  "https://www.koket.se/new-orleans-gumbo",
  "https://www.koket.se/kobide-kebab-pa-lammkott",
  "https://www.koket.se/ortkryddad-fransyska-serveras-med-rostade-rotfrukter",
  "https://www.koket.se/laskig-kottfarspaj-till-halloween",
  "https://www.koket.se/oxrullader-serveras-med-blomkalsris-och-rodvinssas",
  "https://www.koket.se/marinerad-kyckling-serveras-med-kokoscurrysas",
  "https://www.koket.se/glasnudlar-med-edamame-cashewnotter-och-agg",
  "https://www.koket.se/snabb-kantarellsoppa-jessica-frejs-recept",
  "https://www.koket.se/kramig-majssoppa-med-ostkrutonger",
  "https://www.koket.se/len-pumpasoppa-med-appelcider"
];

nightmare
  .goto('https://www.koket.se/mat/specialkost/raw-food')
  .wait(1000)
  .evaluate(function () {

  })
  .then(function (hrefs) {


    console.log("start");
    //här kan jag bygga vilken lista jag vill med hrefs...
    console.log("nr of urls: " + urls.length);
    uniqurls = [...new Set(urls)];
    console.log("uniq : " + uniqurls.length);
    //here, we're going to use the vanilla JS way of executing a series of promises in a sequence.
    //for every href in hrefs,
    return uniqurls.reduce(function (accumulator, href) {
      //return the accumulated promise results, followed by...
      return accumulator.then(function (results) {
        return nightmare.goto(href)
          //get the html
          .evaluate(function () {
            if (document.querySelector('.recipe-column-wrapper .endorsed-banner')) {
              return;
            }

            let recipe = {};
            //title
            recipe.title = document.querySelector('.recipe-content-wrapper h1').innerHTML;
            //tags
            let tags = {};
            $('.category-touch-scroll .btn.green-btn.category').each(function () {
              let t = $(this).text().split('/');
              for (let i = 0; i < t.length; i++) {
                tags[t[i].charAt(0).toUpperCase() + t[i].slice(1)] = true;
              }
            })
            recipe.tags = tags;
            //source
            recipe.source = window.location.href;
            //rating
            recipe.rating = document.querySelector('.recipe-content-wrapper .rating-container.rating').getAttribute("data-setrating");
            //votes
            recipe.votes = document.querySelector('.recipe-content-wrapper .rating-container.rating span.text').innerHTML.split(" ")[0];
            //author
            if (document.querySelector('.recipe-content-wrapper .author-chef a')) {
              recipe.author = document.querySelector('.recipe-content-wrapper .author-chef a').innerHTML;
            }
            //createdFor
            if (document.querySelector('.recipe-content-wrapper .author-source a')) {
              recipe.createdFor = document.querySelector('.recipe-content-wrapper .author-source a').innerHTML;
            }
            //portions  "4småpotioner" trattkantarellsoppan. replace alla bokstäver med ""?
            if (document.querySelector('.recipe-content-wrapper .recipe-info.portions span.amount')) {
              recipe.portions = document.querySelector('.recipe-content-wrapper .recipe-info.portions span.amount').innerHTML.replace(/(\r\n|\n|\r| )/gm, "").trim();
            }
            //created
            if (document.querySelector('.recipe-content-wrapper .description meta[itemprop="datePublished"]')) {
              recipe.created = document.querySelector('.recipe-content-wrapper .description meta[itemprop="datePublished"]').getAttribute("content");
            }
            //description
            if (document.querySelector('.recipe-content-wrapper .recipe-article .description p')) {
              recipe.description = document.querySelector('.recipe-content-wrapper .recipe-article .description p:first-child').innerHTML.replace(/(\r\n|\n|\r|<[^>]*>)/gm, "").replace(/  +/g, ' ');
            }
            //time
            if (document.querySelector('.recipe-content-wrapper .cooking-time')) {
              //koket.se använder flera olika format på tid så det är inte lätt att ta ut ett generellt värde
              recipe.time = document.querySelector('.recipe-content-wrapper .cooking-time .time').innerHTML.replace(/(\r\n|\n|\r|)/gm, "").trim();
            }
            //ingredients
            if (document.querySelector('.recipe-column-wrapper #ingredients-component')) {
              let ingredientsDom = document.querySelector('.recipe-column-wrapper #ingredients-component #ingredients').getElementsByTagName("li");
              let ingredients = [];
              for (var i = 0; i < ingredientsDom.length; ++i) {
                let ingredient = {};
                let parts = ingredientsDom[i].getElementsByTagName("span");
                let amount = parts[1].innerHTML;
                ingredient.name = parts[2].innerHTML.charAt(0).toUpperCase() + parts[2].innerHTML.slice(1).replace(/[.#$]/g,'');
                if (amount.length > 0) {
                  let amountParts = amount.split(" ");
                  ingredient.amount = amountParts[0];
                  if (amountParts.length > 1) {
                    ingredient.unit = amountParts[1];
                    if (!/\d/.test(ingredient.amount)) {
                      ingredient.amount = amountParts[1];
                      ingredient.unit = amountParts[0];
                    }
                  }
                }
                ingredients.push(ingredient);
              }
              recipe.ingredients = ingredients;
            }
            //difficulty
            let instructionsList = document.querySelector('.recipe-column-wrapper #step-by-step').getElementsByTagName("li");
            let nrOfIngredients = recipe.ingredients.length;
            let instructionLength = 0;
            for (let i = 0; i < instructionsList.length; i++) {
              instructionLength = instructionLength + instructionsList[i].getElementsByTagName("span")[0].innerHTML.replace(/(\r\n|\n|\r|)/gm, "").trim().length;
            }
            instructionLength = instructionLength - instructionsList.length * 10;

            let levelIndex = (nrOfIngredients * 8) + (instructionLength / 14);
            if (recipe.tags.hasOwnProperty('Enkelt') || recipe.tags.hasOwnProperty('Lättlagat')) {
              levelIndex = levelIndex - 100;
            }
            if (recipe.tags.hasOwnProperty('Snabbt')) {
              levelIndex = levelIndex - 20;
            }

            if (levelIndex < 100) {
              recipe.level = 1;
            } else if (levelIndex < 200) {
              recipe.level = 2;
            } else {
              recipe.level = 3;
            }

            //lägg logik för validering i inläsningen och inte här.. om vissa saker saknas så hoppa över. om urlen redan finns hoppa över..
            //automatisera denna inläsning. 
            //Alla recept som skrivs till filen ska se likadana ut oberoende av källa.
            return recipe;
          })
          //add the result to the results
          .then(function (html) {
            results.push(html);
            return results;
          })
        // .then(function(results){
        //   //click on the search result link to go back to the search result page
        //   return nightmare
        //     .click('a[id="propertyHeading_searchResults"]')
        //     .then(function() {
        //       //make sure the results are returned
        //       return results;
        //     });
        // })
      });
    }, Promise.resolve([])) //kick off the reduce with a promise that resolves an empty array
  })
  .then(function (resultArr) {
    //if I haven't made a mistake above with the `Array.reduce`, `resultArr` should now contain all of your links' results
    console.log(resultArr.length);


    fs.writeFile("C:/react/recipes.json", JSON.stringify(resultArr), function (err) {

      if (err) {
        return console.log(err);
      }

      console.log("The file was saved!");
    });
  });