var Nightmare = require('nightmare');
var nightmare = Nightmare({
  openDevTools: false, show: false, webPreferences: {
    images: false,
  }
})

var fs = require('fs');


//ta fram urls genom att:
//1. Gå till en sida på koket.se
//2. kör: var interv=setInterval(function(){if(document.querySelector('li.next').offsetParent!=null){document.querySelector('a[rel="next"]').click();}else{console.log("done");clearInterval(interv);}},600);
//3. Vänta på att "done" har loggats i consolen.
//4. kopiera alla hrefs genom copy(Array.from(document.querySelectorAll('article.list-item.recipe .info .top h2 a')).map(a => a.href));
//5. paste in i urls
//6. kör node night2.js
//7. resultatet sparas i react/test.txt
//8. kör node datachange.js här alla recept läses in till firebase från textfilen
let urls = [
  "https://www.koket.se/hostpasta-med-kantarellkram-viltkottbullar-graddsas-och-apple",
  "https://www.koket.se/russin-och-havtornsparon-med-salt-karamellmousse-och-kaksmulor",
  "https://www.koket.se/rak-och-flaskgyoza-med-yuzuponzu",
  "https://www.koket.se/olskola-med-maya-samuelsson",
  "https://www.koket.se/smorrostat-brod-med-vaniljfarskost-och-ortig-bjornbarskompott",
  "https://www.koket.se/megasnabb-mustig-tomatsoppa-med-grillad-paprika",
  "https://www.koket.se/kikartsrora-med-hostiga-citronmarinerade-gronsaker",
  "https://www.koket.se/tortillas-med-svamp-mozzarella-och-lingon",
  "https://www.koket.se/pop-tarts-med-appelfyllning-roy-fares-recept",
  "https://www.koket.se/new-orleans-gumbo",
  "https://www.koket.se/falode-frysta-risnudlar-med-saffransglass-och-rosenvatten",
  "https://www.koket.se/kobide-kebab-pa-lammkott",
  "https://www.koket.se/saladolvie-persisk-kycklingratt",
  "https://www.koket.se/varldens-godaste-grot",
  "https://www.koket.se/tacos-med-strimlad-biff-kalsallad-och-avokadokram",
  "https://www.koket.se/kall-vaniljkon-med-hallonsas",
  "https://www.koket.se/ortkryddad-fransyska-serveras-med-rostade-rotfrukter",
  "https://www.koket.se/explosiv-raksallad",
  "https://www.koket.se/chokladbollar-med-kikartor-lakrits-och-fikon",
  "https://www.koket.se/cookie-dough-chokladbollar",
  "https://www.koket.se/chokladbollar-fyllda-med-jordnotssmor",
  "https://www.koket.se/muffins-med-inbakade-chokladbollar",
  "https://www.koket.se/laskig-kottfarspaj-till-halloween",
  "https://www.koket.se/bowl-med-kyckling-i-rod-curry-savojkal-och-matvete",
  "https://www.koket.se/yazh-s-blomkalsparatha-med-hemgjord-mango-chutney",
  "https://www.koket.se/mjukt-tunnbrod-med-grahamsmjol",
  "https://www.koket.se/kuvertbrod-med-insekter",
  "https://www.koket.se/glutenfritt-knackebrod-med-insekter",
  "https://www.koket.se/hallon-och-chokladmousse-pa-browniebotten",
  "https://www.koket.se/oxrullader-serveras-med-blomkalsris-och-rodvinssas",
  "https://www.koket.se/champinjonsoppa-serveras-med-majsknacke",
  "https://www.koket.se/cottage-pie-pa-vegofars-siri-barjes-recept",
  "https://www.koket.se/ragsurdegsfriterat-ostron-med-primorer-och-ostronemulsion",
  "https://www.koket.se/chokladpannacotta-med-farska-hallon",
  "https://www.koket.se/marinerad-kyckling-serveras-med-kokoscurrysas",
  "https://www.koket.se/kantarelltoast-toppad-med-vasterbottensost",
  "https://www.koket.se/glasnudlar-med-edamame-cashewnotter-och-agg",
  "https://www.koket.se/frasiga-glutenfria-pannkakor",
  "https://www.koket.se/snabb-kantarellsoppa-jessica-frejs-recept",
  "https://www.koket.se/kramig-majssoppa-med-ostkrutonger",
  "https://www.koket.se/len-pumpasoppa-med-appelcider",
  "https://www.koket.se/glutenfria-valnotsfrallor-jessica-frejs-recept",
  "https://www.koket.se/salted-caramel-fruits-n-nuts",
  "https://www.koket.se/shrimp-n-sausage-gumbo",
  "https://www.koket.se/black-eyed-peas-soul-salad",
  "https://www.koket.se/hostig-appelpaj-med-lock-tea-malmegards-recept",
  "https://www.koket.se/sura-potatischips-med-lojrom",
  "https://www.koket.se/potatisplattar-med-lojrom-och-creme-fraiche",
  "https://www.koket.se/smorsas-med-lojrom",
  "https://www.koket.se/frasig-laxburgare-med-avokado-och-coleslaw",
  "https://www.koket.se/fondant-au-chocolat",
  "https://www.koket.se/lammfile-med-svamprisotto-serveras-med-hallon-och-chokladsas",
  "https://www.koket.se/pilgrimsmusslor-med-jordartskockspure",
  "https://www.koket.se/pulled-chicken-i-white-corn-tortilla",
  "https://www.koket.se/flankstek-med-rostade-morotter-dragon-och-brynt-smor",
  "https://www.koket.se/koket-tarta-med-hallonmousse-och-choklad",
  "https://www.koket.se/cheesecake-med-farska-jordgubbar",
  "https://www.koket.se/chevrelasagne-med-kycklingfile",
  "https://www.koket.se/crostini-med-avokadohummus-och-tapenade",
  "https://www.koket.se/red-curry-bowl-med-kyckling",
  "https://www.koket.se/chicken-ramen-bowl",
  "https://www.koket.se/varm-appelbovetegrot-med-bjornbar",
  "https://www.koket.se/apelsinriddare-med-blabarskompott-och-grekisk-yoghurt",
  "https://www.koket.se/tropisk-smoothie",
  "https://www.koket.se/allt-gront-smoothie",
  "https://www.koket.se/varma-applen-med-yoghurt-snabbgranola-och-appelsirap",
  "https://www.koket.se/pasta-med-rakor-paprika-och-vitt-vin",
  "https://www.koket.se/cookies-med-creme-brulee-frosting",
  "https://www.koket.se/fankals-och-rabarberkakor-med-vit-choklad",
  "https://www.koket.se/mammas-chocolate-chip-cookies",
  "https://www.koket.se/schackrutor-med-tacke",
  "https://www.koket.se/hemgjorda-vaniljhjartan",
  "https://www.koket.se/flamberade-applen-och-valnotter-serveras-med-lyxig-vaniljglass",
  "https://www.koket.se/helstekt-hjortfile-i-portvinssky-serveras-med-blomkalstryffelpure-och-rotfrukter",
  "https://www.koket.se/smordegsflarn-med-spenat-ro-dlo-k-och-getost",
  "https://www.koket.se/appelkaka-i-langpanna",
  "https://www.koket.se/bountykladdkaka",
  "https://www.koket.se/frasig-piccata-pa-kalkonbrost-sandra-mastios-recept",
  "https://www.koket.se/tarte-tatin-richard-wajes-recept",
  "https://www.koket.se/mintchokladkaka-med-en-burmesisk-touch",
  "https://www.koket.se/adez-och-zigni-afrikanska-grytor-med-bonor-och-linser",
  "https://www.koket.se/sydostasiatisk-couscoussallad-med-tropiska-inslag",
  "https://www.koket.se/kryddstekt-halloumi-med-avokadorora-och-quinoa",
  "https://www.koket.se/campogianis-tiramisu",
  "https://www.koket.se/arrosto-con-patate-all-italiana",
  "https://www.koket.se/cannelloni-med-ricotta-och-arrabbiatasas",
  "https://www.koket.se/appelpizza-med-salt-kolasas-och-vaniljglass",
  "https://www.koket.se/italienska-kottbullar-i-tomatsas-med-spaghetti",
  "https://www.koket.se/hallonskumtoppar-med-biskvibottnar-och-choklad",
  "https://www.koket.se/torsk-i-ugn-med-tomater-raksas-och-rostade-solrosfron",
  "https://www.koket.se/enkel-sotpotatisgratang-med-lax-fetaost-och-tomat-ortsas",
  "https://www.koket.se/soja-och-ingefarsmarinerad-renfile-med-skogssvamp-spetskal-och-krispigt-hostapple",
  "https://www.koket.se/ugnsbakad-lax-med-ortig-linsragu",
  "https://www.koket.se/rabarberpaj-med-smak-av-mandel",
  "https://www.koket.se/black-and-white-med-gronpepparsas-och-potatismos",
  "https://www.koket.se/crepes-med-rakor-och-krabba",
  "https://www.koket.se/apelsin-och-dragonbakat-kalkonbrost",
  "https://www.koket.se/allt-i-en-form-med-kyckling-chorizo-och-paprika",
  "https://www.koket.se/lingonparfait-med-knackigt-flarn",
  "https://www.koket.se/algryggbiff-med-trattkantarellsas-serveras-med-potatis-och-palsternackspure",
  "https://www.koket.se/rokt-andbrost-med-waldorfsallad",
  "https://www.koket.se/fruktig-sommarbal",
  "https://www.koket.se/gnocchi-med-sidflask-och-surkal",
  "https://www.koket.se/mutzel-en-kombination-av-muffins-och-bretzels",
  "https://www.koket.se/knastrande-blabarsdrom-vallmomuffins-med-blabarsfrosting",
  "https://www.koket.se/chocolate-goes-nuts-hasselnotsmuffins-med-chokladsmorkram",
  "https://www.koket.se/toscakaka-med-brynt-smor",
  "https://www.koket.se/toscakaka-med-mandel-birgitta-rasmussons-recept",
  "https://www.koket.se/creme-br-lee-med-en-sommartwist",
  "https://www.koket.se/kalvfarsbiffar-med-rodbetor-serveras-med-graddsas-och-potatisskivor",
  "https://www.koket.se/lantlig-smordegspaj-med-skogens-guld",
  "https://www.koket.se/eggs-florentine-i-ugn",
  "https://www.koket.se/ravioli-med-svampkram-svampveloute-och-svampgarnityr",
  "https://www.koket.se/parlor-at-svin-fudgekaka-med-gradde-och-parlor",
  "https://www.koket.se/flaskfile-for-kung-och-fosterland-med-pesto-och-mozzarella",
  "https://www.koket.se/skagenrora-pa-avokadobadd-serveras-med-smordegsuggla",
  "https://www.koket.se/proteinlatte-med-vanilj",
  "https://www.koket.se/vegowrap-med-avokado-fetaost-och-jordnotter",
  "https://www.koket.se/superenkel-isglass",
  "https://www.koket.se/snittar-med-oliver-mozzarella-och-prosciutto",
  "https://www.koket.se/overnights-oats-med-blabar-och-jordnotssmor",
  "https://www.koket.se/gor-ett-lyxigare-bordsvatten-med-fruktiga-isbitar",
  "https://www.koket.se/kladdkaka-med-smak-av-tiramisu",
  "https://www.koket.se/aloo-gobi-indisk-gryta-med-blomkal-och-potatis",
  "https://www.koket.se/vegoquesadillas-med-mangosas",
  "https://www.koket.se/tortillapizza-med-mozzarella-basilika-och-kronartskocka",
  "https://www.koket.se/sota-appelbrod-pa-pizzadeg",
  "https://www.koket.se/pizza-med-langbakad-rotselleri",
  "https://www.koket.se/pizza-margherita-sandra-mastios-recept",
  "https://www.koket.se/pizza-funginanza",
  "https://www.koket.se/kladdig-chokladkaka-med-mynta-och-chokladkola",
  "https://www.koket.se/gor-pizzadeg-som-proffsen",
  "https://www.koket.se/lyxigt-fikaknacke-med-keso-apple-och-kanel",
  "https://www.koket.se/chokladcupcakes-med-chokladpraliner-bjornbar-och-kringlor",
  "https://www.koket.se/iste-med-citron-och-mynta",
  "https://www.koket.se/frostad-tryfferad-parfait-med-vit-nougat",
  "https://www.koket.se/tryffelrisoni-med-parmesan",
  "https://www.koket.se/tryfferad-jordartskockspure-med-lattrokt-sillkaviar",
  "https://www.koket.se/tryfferade-minikroppkakor",
  "https://www.koket.se/mango-chutney-se-gor",
  "https://www.koket.se/tandoori-chicken-med-raita",
  "https://www.koket.se/cheesecake-med-grillade-jordgubbar",
  "https://www.koket.se/kolgrillad-sosida-serveras-med-ugnsrostade-rotfrukter",
  "https://www.koket.se/trekant-med-gomma",
  "https://www.koket.se/fyllda-rullar-med-plommonsas-och-sesamdressing-erik-videgards-recept",
  "https://www.koket.se/italiensk-flaskfile-med-parmesangratinerad-rotselleri",
  "https://www.koket.se/punschglass-serveras-med-blabar",
  "https://www.koket.se/vildsvinskarre-med-potatis-och-rotfruktsgratang",
  "https://www.koket.se/skaldjurstoast-med-fuskmajonnas",
  "https://www.koket.se/len-potatispure-se-gor",
  "https://www.koket.se/flaskkorv-med-kalrotskram-pa-brynt-smor",
  "https://www.koket.se/american-dream-tarta-med-marang-mjolkchoklad-och-farska-bar",
  "https://www.koket.se/tarte-tatin-med-ingefara-och-kanel",
  "https://www.koket.se/tarte-tatin-pa-grillen",
  "https://www.koket.se/parfait-pa-apelsinlikor-serveras-med-hjortrongradde-och-jordgubbar",
  "https://www.koket.se/poulet-au-vin-serveras-med-blomkalspure",
  "https://www.koket.se/lax-melange-i-endiveblad-serveras-med-pilgrimsmusslor",
  "https://www.koket.se/tildes-chokladtarta-pa-riktigt",
  "https://www.koket.se/varmrokt-lax-med-parlcouscous-och-chermola",
  "https://www.koket.se/rodbraserat-flask",
  "https://www.koket.se/qp-ostron",
  "https://www.koket.se/bra-vibrationer-hjortronparfait",
  "https://www.koket.se/kungens-slottsstek-tillsammans-med-hertiginnans-potatis",
  "https://www.koket.se/gron-soppa-med-pepparrotsgradde",
  "https://www.koket.se/karibisk-sotpotatisgryta-med-svarta-bonor",
  "https://www.koket.se/gt-med-grape",
  "https://www.koket.se/kaffe-med-glass-i-ett",
  "https://www.koket.se/svampburgare-med-picklade-vinbar-getostkram",
  "https://www.koket.se/fruktig-sommardrink-med-vattenmelonspett",
  "https://www.koket.se/alkoholfri-mojito",
  "https://www.koket.se/krustader-med-farskost-rokt-korv-svartkal",
  "https://www.koket.se/vegopizza-med-soltorkade-tomater-farska-orter-pesto-mozzarella",
  "https://www.koket.se/froknacke-med-avokado-tomater",
  "https://www.koket.se/rokig-kramig-bbq-sas",
  "https://www.koket.se/rostad-morot-med-sesam-koriander-chili-och-lime",
  "https://www.koket.se/rakostsallad-med-brynt-smor-honung-och-hasselnotter",
  "https://www.koket.se/ljummen-potatissallad-med-agg-brynt-smor-dill-pepparrot-och-rakor",
  "https://www.koket.se/pumpa-paron-getost-och-pumpakarnor",
  "https://www.koket.se/flammad-isbergssallad",
  "https://www.koket.se/gronsallad-med-vinagrett",
  "https://www.koket.se/roy-fares-parontarte",
  "https://www.koket.se/tennstopets-anglamat",
  "https://www.koket.se/tennstopets-filbunke",
  "https://www.koket.se/tennstopets-kottsoppa-med-klimp",
  "https://www.koket.se/tennstopets-kolbulle",
  "https://www.koket.se/tennstopets-lerpotta",
  "https://www.koket.se/tennstopets-doppsko",
  "https://www.koket.se/kalkonfrikadeller-i-tomatsas",
  "https://www.koket.se/lingonpannacotta",
  "https://www.koket.se/oxrullader-med-rotfrukter-och-baconinlindad-sparris",
  "https://www.koket.se/toast-orlen",
  "https://www.koket.se/kalvtartar-med-jalape-o-och-rarivet-apple",
  "https://www.koket.se/brodpudding-med-applen-och-vaniljgradde",
  "https://www.koket.se/sobanudlar-med-kycklingfars-pak-choy-och-shiitake",
  "https://www.koket.se/aggande-parfait",
  "https://www.koket.se/kott-a-sas-a-putater",
  "https://www.koket.se/trattsoppa",
  "https://www.koket.se/ingefars-och-vitlokskycklingspett-rodkal-broccoli-pinjenotter-och-aioli-med-gurkmeja",
  "https://www.koket.se/italiensk-pytt-i-panna",
  "https://www.koket.se/ugnstekta-applen-och-hallon-med-paronlikorgradde",
  "https://www.koket.se/signes-radjursfile-med-whiskeysas",
  "https://www.koket.se/kantarellsoppa-serveras-med-lchf-brod",
  "https://www.koket.se/stekt-torsk-med-tacokryddad-tomatsas-och-nachos",
  "https://www.koket.se/overnight-oates-pa-havregryn-och-chiafron",
  "https://www.koket.se/braserad-lammbog-i-vitt-vin-och-tomat-med-grillad-morot-grona-tomater-oliver-och-libbsticka",
  "https://www.koket.se/wrapsrullar-med-kycklingrora-i-vitkalsblad",
  "https://www.koket.se/kvargdipp-med-ortolja",
  "https://www.koket.se/proteinshake-med-jordgubbar",
  "https://www.koket.se/tigerpudding",
  "https://www.koket.se/viltburgare-med-hemgjorda-pommes",
  "https://www.koket.se/rokt-sik-med-romrora-pa-smorstekt-brod",
  "https://www.koket.se/etiopiska-pannkakor-med-linsgryta-och-vitkal",
  "https://www.koket.se/svamptoast-johan-backeus-recept",
  "https://www.koket.se/svampconsume",
  "https://www.koket.se/svampkroketter-med-syrad-lok-kal-och-sojamajonnas",
  "https://www.koket.se/kanelbulle-anno-2017",
  "https://www.koket.se/toscabulle-daniel-lindebergs-recept",
  "https://www.koket.se/briochepizza-med-apple-och-kanel",
  "https://www.koket.se/lammgryta-med-inspiration-fran-skane-och-provence",
  "https://www.koket.se/paolos-pasta-med-hostragu-pa-oxkott-och-svamp",
  "https://www.koket.se/exotisk-parfait-i-tre-smaker",
  "https://www.koket.se/kall-flaskfile-serveras-med-potatisbatar",
  "https://www.koket.se/svampsoppa-med-vitloksbaguette",
  "https://www.koket.se/sotad-lax-med-gari-och-wasabikram",
  "https://www.koket.se/ortstekt-flaskfile-med-rotsaksgratang",
  "https://www.koket.se/fredrik_eriksson/_/_/toast_skagen/",
  "https://www.koket.se/fredrik-eriksson/smaratter-och-tillbehor/fisk-och-skaldjur/langbrosill-anno-2009/",
  "https://www.koket.se/vit-kladdkaka-med-varma-hjortron",
  "https://www.koket.se/gnocchi-med-mamma-ancis-rosa-pastasas",
  "https://www.koket.se/skagentoast-med-egengjord-majonnas",
  "https://www.koket.se/fiskgryta-med-kokosgradde-gron-curry-och-limeyoghurt",
  "https://www.koket.se/citronmousse",
  "https://www.koket.se/ugnstekt-lammfile-med-risotto",
  "https://www.koket.se/gratinerade-pilgrimsmusslor-med-svarta-parlor",
  "https://www.koket.se/blt-tacosallad-med-kyckling",
  "https://www.koket.se/appelvafflor-med-kanel",
  "https://www.koket.se/fruktig-gronsaksjuice-med-morot-gurkmeja-selleri-och-timjan",
  "https://www.koket.se/varm-matchalemonad-med-mynta-och-citron",
  "https://www.koket.se/grekisk-yoghurtsmoothie-med-apelsin-mango-banan-och-hallon",
  "https://www.koket.se/exotisk-smoothiebowl-med-chiafron",
  "https://www.koket.se/apelsin-och-hallonshrub",
  "https://www.koket.se/vegetarisk-bourguignon-med-svartrotter-och-betor",
  "https://www.koket.se/hjortronpannacotta-serveras-med-varma-hjortron",
  "https://www.koket.se/gratinerad-sjotunga-med-musselsas",
  "https://www.koket.se/hummersoppa-med-whiskeytouch",
  "https://www.koket.se/smoothie-med-kvarg-tropiska-frukter-och-havre",
  "https://www.koket.se/overnight-oats-med-chia-och-kakao",
  "https://www.koket.se/frozen-smoothie-bowl",
  "https://www.koket.se/bakad-appelgrot",
  "https://www.koket.se/carrot-cake-pancakes",
  "https://www.koket.se/morgon-pa-sprang-frukost",
  "https://www.koket.se/spring-onion-pancakes-med-tofu",
  "https://www.koket.se/inkokt-gos-med-sallad-pa-gulbeta-fiskfond-och-rokt-olja",
  "https://www.koket.se/nypon-och-ronnbarsketchup",
  "https://www.koket.se/nypon-och-havtornssoppa-med-mandelbiskvier-och-vaniljglass",
  "https://www.koket.se/havrevafflor-med-kardemumma-och-appelkompott",
  "https://www.koket.se/lagtempad-lax-med-glasnudelsallad",
  "https://www.koket.se/vaniljparfait-serveras-med-farska-jordgubbar",
  "https://www.koket.se/kantarellasagne",
  "https://www.koket.se/havskraftor-serveras-med-citron-och-dragonsmor",
  "https://www.koket.se/kycklingsliders-med-tomatchutney",
  "https://www.koket.se/beikudochizukeki-japansk-cheesecake",
  "https://www.koket.se/yakiniku-med-jasminris-och-sallad",
  "https://www.koket.se/okonomiyaki-japansk-pannkaka",
  "https://www.koket.se/hemgjorda-fiskbullar-i-currysas",
  "https://www.koket.se/linssoppa-med-pumpafron-och-creme-fraiche",
  "https://www.koket.se/zucchiniplattar-med-fetaost",
  "https://www.koket.se/lammkotlett-med-parmesan-och-timjanstuvad-spetskal",
  "https://www.koket.se/leche-flan-filippinsk-creme-br-lee",
  "https://www.koket.se/filippinska-dumplings-siomai",
  "https://www.koket.se/strimlad-beef-steak-med-sweet-chili-sauce",
  "https://www.koket.se/spaghetti-med-salsicciasas",
  "https://www.koket.se/chokladfondant-med-kanderade-rodbetor",
  "https://www.koket.se/oxfile-med-vasterbottensduchesse-samt-flamberad-gronpepparsas",
  "https://www.koket.se/ostpaj-serveras-med-lojrom",
  "https://www.koket.se/rodbetsgnocchi-med-zucchini-salvia-och-basilika",
  "https://www.koket.se/kyckling-med-basilika-och-citronolja-samt-mozzarellagratinerad-broccoli-och-tomat",
  "https://www.koket.se/kikartsbiffar-med-ratatouille-och-basilikacreme",
  "https://www.koket.se/pasta-med-varmrokt-lax-fankal-pak-choi-aggula-och-pepparrot",
  "https://www.koket.se/hemgjord-vaniljglass-med-salt-kolasas",
  "https://www.koket.se/tjalknol-med-appelchutney-och-kantarellsas",
  "https://www.koket.se/tiramisurulltarta",
  "https://www.koket.se/juligt-kalkonbrost",
  "https://www.koket.se/kryddiga-kalkonkottbullar",
  "https://www.koket.se/notpanerat-kalkonbrost-med-kantarellsas",
  "https://www.koket.se/kalkonpiccata-med-farsk-pasta",
  "https://www.koket.se/het-ramensoppa-med-marinerad-biff-och-pak-choi",
  "https://www.koket.se/ramen-med-glasnudlar-och-marinerad-kyckling",
  "https://www.koket.se/currygryta-med-vitkal-chili-och-kokos",
  "https://www.koket.se/filodegspaj-med-fetaost-farsk-spenat-och-solrosfron",
  "https://www.koket.se/halloumigryta-med-tomat-linser-och-chili",
  "https://www.koket.se/champinjonburgare-med-ramsloksmajonnas-ruccola-och-stark-ost",
  "https://www.koket.se/morotsbollar-med-ortyoghurt-och-rodkalssallad",
  "https://www.koket.se/angamat-med-potatis-sockerarter-och-persilja",
  "https://www.koket.se/ra-biff-med-ostronmajonnas-riven-rattika-och-vattenkrasse",
  "https://www.koket.se/eldat-ostron-med-syrlig-sallad-och-musselskum",
  "https://www.koket.se/friterade-ostron",
  "https://www.koket.se/pocherade-ostron",
  "https://www.koket.se/ostron-med-en-variant-pa-escabeche",
  "https://www.koket.se/ostron-med-variant-pa-ponzu",
  "https://www.koket.se/ugnsbakad-torskrygg-med-rotselleri-och-hostsvamp",
  "https://www.koket.se/vinbladsdolmar-med-myntayoghurt",
  "https://www.koket.se/hemgjord-hallonglass-med-lakritskolasas",
  "https://www.koket.se/indisk-gryta-tandoori-garam-masala",
  "https://www.koket.se/whiskeyrokta-chili-och-vitloksrakor-med-farskt-brod-och-citrusaioli",
  "https://www.koket.se/red-chicken-curry-med-sojastekt-tofu",
  "https://www.koket.se/bolognese-pa-rodbetor",
  "https://www.koket.se/halstrad-roding-med-betcarpaccio-basilika-och-sardellvinagrette",
  "https://www.koket.se/chicken-tikka-masala-med-rostade-cashewnotter-och-naanbrod",
  "https://www.koket.se/knaprigt-flask-med-asiatisk-plommonsas",
  "https://www.koket.se/chokladsuffle-med-mangosorbet",
  "https://www.koket.se/karamelliserad-flaskytterfile-med-mystisk-sas",
  "https://www.koket.se/kycklingragusoppa",
  "https://www.koket.se/kramig-polenta-med-parmesan-och-bonor",
  "https://www.koket.se/delikat-chokladgrotta",
  "https://www.koket.se/pasta-a-la-spinachi-med-rakor-och-champinjoner",
  "https://www.koket.se/albins-vasterbottenspaj-med-kantareller",
  "https://www.koket.se/ugnsbakad-sej-i-dillsas-med-pepparrotsmos",
  "https://www.koket.se/parmalindad-rodspatta-med-vitvinssas-rostade-rotfrukter-och-parmesancreme",
  "https://www.koket.se/pitabrod-med-kryddig-fars-och-kalsallad",
  "https://www.koket.se/mangosalsa-med-koriander",
  "https://www.koket.se/farsk-tomatsalsa",
  "https://www.koket.se/guacamole-med-jalapenos",
  "https://www.koket.se/grillspett-med-sotsur-salsa",
  "https://www.koket.se/minitacos-med-frukt-och-honung",
  "https://www.koket.se/quesadillas-med-vit-choklad-jordgubbar-och-basilika",
  "https://www.koket.se/minichurrotacos",
  "https://www.koket.se/ananastortillas",
  "https://www.koket.se/minitacos-med-svarta-bonor-och-mango-pico-de-gallo",
  "https://www.koket.se/quesadillas-med-fetaost-och-mandelspan",
  "https://www.koket.se/chipotle-hongos-med-picklad-rodlok-och-pico-de-gallo",
  "https://www.koket.se/mac-n-cheese-ballz-med-kramig-pepparrotsdipp",
  "https://www.koket.se/vegetarisk-bbq-burgare-med-coleslaw-och-potatischips",
  "https://www.koket.se/cheesecake-a-la-amerikat-med-svensk-twist",
  "https://www.koket.se/spicy-garbanzos-med-guacamole-koriander-och-fetaost",
  "https://www.koket.se/fajitakryddad-lax-med-quinoasallad",
  "https://www.koket.se/pulled-chicken-i-mjuk-tortilla",
  "https://www.koket.se/pastagratang-med-tacosmak",
  "https://www.koket.se/chili-pa-hogrev-med-jalapeno-creme-fraiche-picklad-rodlok-och-stark-ost",
  "https://www.koket.se/mexikansk-pulled-pork-med-kramig-coleslaw",
  "https://www.koket.se/tacosoppa",
  "https://www.koket.se/pankofriterad-fish-taco-med-hot-mayo-mangosalsa-och-kokosflakes",
  "https://www.koket.se/vegetarisk-kalpudding-med-potatis",
  "https://www.koket.se/hallon-och-vanilj-den-godaste-treminutersdesserten",
  "https://www.koket.se/5-minuters-lasagne",
  "https://www.koket.se/grillad-paprikasallad-med-fetaost",
  "https://www.koket.se/enkel-pastagratang-med-fisk-rakor-i-vitvinssas",
  "https://www.koket.se/mild-kramig-laxbolognese",
  "https://www.koket.se/ugnsbakad-lax-med-sweet-chili-citronsas",
  "https://www.koket.se/frisk-artsoppa-med-mynta-och-basilika",
  "https://www.koket.se/ortrostade-tomater-pa-surdegsbrod-med-pumpafropesto",
  "https://www.koket.se/caprese-pa-mastios-vis",
  "https://www.koket.se/angade-grona-bonor-med-brynt-notsmor-och-salsicciastrossel",
  "https://www.koket.se/brownie-med-kolatacke-marshmallows-och-jordnotter",
  "https://www.koket.se/eldad-fjallroding-med-sesammarinerad-bok-choy-och-spenat",
  "https://www.koket.se/risotto-funghi-paolo-robertos-recept",
  "https://www.koket.se/smorgas-med-gotlandskt-lamm-kantareller-och-kramig-kalsallad",
  "https://www.koket.se/exotisk-fruktsallad-med-vit-chokladvisp",
  "https://www.koket.se/gastvanlig-latmanslax-med-kramig-chilisas",
  "https://www.koket.se/chicken-satay-pa-risbadd-med-jordnotssmor",
  "https://www.koket.se/fiskgryta-fran-hav-sjo-och-land-med-dillpesto",
  "https://www.koket.se/karibisk-fishtacos",
  "https://www.koket.se/grillad-karibisk-fruktdrink",
  "https://www.koket.se/grillade-kraftor-med-hembakat-majsbrod",
  "https://www.koket.se/spatzle-med-lax-och-spenat",
  "https://www.koket.se/hemslungad-vaniljglass-med-hallonsky",
  "https://www.koket.se/klassisk-kraftsoppa-med-plankbrod",
  "https://www.koket.se/vitloksgratinerade-gronmusslor",
  "https://www.koket.se/wrap-med-vegetariska-morotsbullar",
  "https://www.koket.se/ostpaj-i-filodeg-med-smetana-rom-och-lok",
  "https://www.koket.se/grillad-vegoburgare-med-avokadosalsa",
  "https://www.koket.se/klassisk-svampmacka-med-portabellosvamp-och-ostronskivling",
  "https://www.koket.se/kroppkakor-med-lingon-och-brynt-smor",
  "https://www.koket.se/grona-crepes-med-kokosfyllning",
  "https://www.koket.se/ayam-masak-merah-kryddig-kyckling-i-tomatsas",
  "https://www.koket.se/notfarsfyllda-piroger-fran-malaysia",
  "https://www.koket.se/vegetarisk-blt-med-portabellosvamp-och-avokado",
  "https://www.koket.se/vit-chokladmousse-med-skogens-guld",
  "https://www.koket.se/helstekt-rostasfile-med-balsamicosas",
  "https://www.koket.se/norrlandstoast-med-gula-kantareller",
  "https://www.koket.se/indisk-dosa-med-kryddig-potatis-och-blomkal",
  "https://www.koket.se/sgroppino-for-tva",
  "https://www.koket.se/smorstekt-fasanbrost-med-gorgonzola-och-karljohansvamp",
  "https://www.koket.se/pappardelle-med-vildsvinsragu",
  "https://www.koket.se/pork-tenderloin-sliders",
  "https://www.koket.se/mexican-drunken-pork-tenderloin",
  "https://www.koket.se/szechuan-pork-tenderloin-salad",
  "https://www.koket.se/hjortron-och-citrongrottor",
  "https://www.koket.se/mandelpannacotta-med-hjortron-och-karamelliserad-mandel",
  "https://www.koket.se/orchiette-med-kantareller-smor-och-salvia",
  "https://www.koket.se/bruschetta-med-bondbonor-fetaost-dill-och-citron",
  "https://www.koket.se/chilimarinerad-biff-med-asiatiska-betor",
  "https://www.koket.se/ernsts-kraftbrod-med-tomat-och-ost",
  "https://www.koket.se/hjalmarenpudding-med-gos-lax-och-kraftor",
  "https://www.koket.se/graddig-soppa-eller-sas-pa-kraftfondskok",
  "https://www.koket.se/malin-soderstrom/smaratter-tillbehor/fisk-skaldjur/klassisk-klamma-med-surstromming/",
  "https://www.koket.se/surstrommingslada-malin-soderstroms-recept",
  "https://www.koket.se/kantarellpizza-med-lagrad-ost",
  "https://www.koket.se/stekta-flaskkotletter-med-gardspommes-och-hett-appelmos",
  "https://www.koket.se/yakiniku-jonas-crambys-recept",
  "https://www.koket.se/kummel-med-chorizo-och-tomat",
  "https://www.koket.se/blabarssorbet-my-feldts-recept",
  "https://www.koket.se/blabarskaka-med-solrosfron-och-karamelliserade-valnotter",
  "https://www.koket.se/paolos-pasta-med-kalkon-och-svartkal",
  "https://www.koket.se/sticky-rice-med-broccoli-sparris-och-friterad-tofu",
  "https://www.koket.se/harligt-frasigt-tomatflarn",
  "https://www.koket.se/klar-tomatbuljong-med-marinerade-tomater",
  "https://www.koket.se/bakade-tomater-med-mozzarella-och-citronmarinerad-fankal",
  "https://www.koket.se/tomat-och-basilikaketchup",
  "https://www.koket.se/gron-tomatmarmelad",
  "https://www.koket.se/jordgubbssallad-med-halloumi-tomater-notter-och-honung",
  "https://www.koket.se/halloumirarakor-med-avokadosalsa",
  "https://www.koket.se/halloumi-tikka-masala-med-ris-och-cashewnotter",
  "https://www.koket.se/lakritspannacotta-med-hallonkompott",
  "https://www.koket.se/bowl-med-chiliris-gronsaker-och-tofudressing",
  "https://www.koket.se/grillad-entrecote-med-pepprig-rotsellerigratang",
  "https://www.koket.se/heta-asiatiska-musslor-i-gron-curry",
  "https://www.koket.se/polentapanerad-torsk-med-bonsallad-och-burrata",
  "https://www.koket.se/kantarellcrepes-med-betsallad-krondill-och-kryddost",
  "https://www.koket.se/spaghetti-med-salviakyckling-och-parmesan",
  "https://www.koket.se/sushi-med-gronsaker-och-quinoa",
  "https://www.koket.se/birra-limone",
  "https://www.koket.se/notter-med-honung-och-salt",
  "https://www.koket.se/mandel-och-tomatsas",
  "https://www.koket.se/jessica-frejs-pan-con-tomat",
  "https://www.koket.se/farskostdipp-med-orter-och-brod",
  "https://www.koket.se/sallad-med-getost-bacon-och-valnotter",
  "https://www.koket.se/patatas-bravas-med-stekt-agg-och-aioli",
  "https://www.koket.se/jessica-frejs-pimentos-padron",
  "https://www.koket.se/smulpaj-med-lime-och-bjornbar",
  "https://www.koket.se/pride-spett-med-regnbagslax",
  "https://www.koket.se/te-kryddad-kycklingklubba-pa-gronsaksbadd",
  "https://www.koket.se/svartvinbarspaj-med-knackig-smuldeg",
  "https://www.koket.se/lyxiga-langos-med-smorstekta-kantareller-och-comtemousse",
  "https://www.koket.se/lyxiga-langos-med-pulled-chicken-och-guacamole",
  "https://www.koket.se/lyxiga-langos-med-kramig-kraftrora",
  "https://www.koket.se/paolos-porchetta-med-rostad-potatis",
  "https://www.koket.se/somrig-primorpytt-med-flankstek-och-kantareller",
  "https://www.koket.se/ernsts-ortsas-pa-bonor",
  "https://www.koket.se/tomat-och-sardellketchup",
  "https://www.koket.se/skordelasagne-med-getostbechamel",
  "https://www.koket.se/grillad-hummer-med-misosmor",
  "https://www.koket.se/tunnbrodrulle-med-korv-och-raksallad",
  "https://www.koket.se/halloumitacos-med-avokadokram-och-inlagd-lok",
  "https://www.koket.se/five-spice-auberginebowl-med-krispigt-agg",
  "https://www.koket.se/saft-pa-rallarros",
  "https://www.koket.se/ostkaka-fran-grunden-med-hemgjord-svartvinbarssylt",
  "https://www.koket.se/quesadillas-med-adelost-honung-och-valnotter-2",
  "https://www.koket.se/french-toast-med-ricottayoghurt-bar-och-citronhonung",
  "https://www.koket.se/toast-med-betor-aprikoser-och-mozzarella",
  "https://www.koket.se/aggrora-med-mangold-och-sesam",
  "https://www.koket.se/sable-med-lemon-curd-spritsad-marang-och-farska-hallon",
  "https://www.koket.se/kantarelltoast-med-prastost-persilja-och-syrad-lok",
  "https://www.koket.se/loksoppa-filip-fastens-recept",
  "https://www.koket.se/brioche-med-blabar-och-hemgjord-ricotta",
  "https://www.koket.se/friterade-varrullar-med-flaskfars-och-rakor",
  "https://www.koket.se/ernsts-notiga-sotarmurrar",
  "https://www.koket.se/choklad-och-timjanskorpor",
  "https://www.koket.se/somrig-bartarta-med-apelsin-och-fladerfyllning",
  "https://www.koket.se/baguette-fylld-med-ortmarinerad-kyckling-och-grillade-gronsaker",
  "https://www.koket.se/johan-hedbergs-grillade-sommarsallad",
  "https://www.koket.se/stekt-abborre-med-graddig-spetskal",
  "https://www.koket.se/gron-smoothie-anna-ottossons-recept",
  "https://www.koket.se/blabarssmoothie-pa-mandelmjolk",
  "https://www.koket.se/smoothie-pa-mango-och-citrus",
  "https://www.koket.se/italiensk-frittata-med-citronkokt-lok",
  "https://www.koket.se/fransk-pastasallad-med-vita-bonor-agg-och-grasloksdressing",
  "https://www.koket.se/somrig-fruktsallad-med-vit-chokladkram-och-karamelliserade-havregryn",
  "https://www.koket.se/jam-n-serrano-med-jordgubbar-och-basilika",
  "https://www.koket.se/seabreamfileer-med-passionsfruktssmorsas-smorslungade-potatisar-gronsaker",
  "https://www.koket.se/jessicas-goda-rub-till-grillat",
  "https://www.koket.se/bonor-artor-gurka-och-lagrad-svensk-hardost",
  "https://www.koket.se/svenska-tomater-med-nygjord-ricotta",
  "https://www.koket.se/friterade-potatisstrimlor-med-smetana-och-persilja",
  "https://www.koket.se/hummus-pa-gula-artor-yoghurt-blomkal",
  "https://www.koket.se/vetelangd-med-hallon-och-choklad",
  "https://www.koket.se/koreansk-bbq-bulgogi",
  "https://www.koket.se/caesarsallad-pa-tom-sjostedts-vis",
  "https://www.koket.se/egg-coddler",
  "https://www.koket.se/rabarbermarmelad-med-timjan-och-valnotter",
  "https://www.koket.se/tomat-och-morotsmarmelad",
  "https://www.koket.se/ernsts-scones-med-enkorn-och-fruktm-sli",
  "https://www.koket.se/grillad-flaskkotlett-med-rabarberketchup",
  "https://www.koket.se/lammfarsbiffar-med-oliver-citronbulgur-och-salsa-verde",
  "https://www.koket.se/vietnamesisk-raksallad-med-risnudlar",
  "https://www.koket.se/vegansk-pasta-bolognese-siri-barjes-recept",
  "https://www.koket.se/kryddiga-lammburgare-med-aubergine-och-fetaost",
  "https://www.koket.se/maffig-portabelloburgare-med-gruyereost-och-karamelliserad-lok",
  "https://www.koket.se/jattegod-laxburgare-med-ortaioli-och-picklad-gurka",
  "https://www.koket.se/grillad-svartkal-med-vitlok-fetaost-och-chiliflakes",
  "https://www.koket.se/citron-och-hallontartelette-my-feldts-recept",
  "https://www.koket.se/gron-artsoppa-med-mynta-och-lime",
  "https://www.koket.se/briochebullar-med-vaniljkram-och-farska-bar-roy-fares-recept",
  "https://www.koket.se/hummersallad-med-lime-chili-och-ingefara",
  "https://www.koket.se/smorstekt-piggvarsfile-med-sommarprimorer-och-champagnesas",
  "https://www.koket.se/gratinerad-gnocchi-med-tomatsas-paolo-robertos-recept",
  "https://www.koket.se/gosravioli-med-brynt-smor-rostade-hasselnotter-och-primorsallad",
  "https://www.koket.se/grillad-majstortilla-med-chorizo-och-kalsallad",
  "https://www.koket.se/smart-nudelsoppa-med-kyckling-perfekt-pa-picknicken",
  "https://www.koket.se/limpa-fylld-med-mozzarella-paprika-och-salami",
  "https://www.koket.se/koreansk-sushi-gimbap",
  "https://www.koket.se/frasig-ortlax-med-potatisstomp",
  "https://www.koket.se/karibisk-rice-n-beans-med-jerkmarinerad-tofu",
  "https://www.koket.se/tomatsallad-pa-hogsommartomater",
  "https://www.koket.se/tomatsallad-pa-sasongens-forsta-tomater",
  "https://www.koket.se/fruktsoppa-med-vaniljsockerlag",
  "https://www.koket.se/grillad-paprikarora-med-vitlok-och-ramslok",
  "https://www.koket.se/vegansk-caesarsallad-med-avokado-och-fron",
  "https://www.koket.se/vegansk-yoghurt-pa-cashewnotter",
  "https://www.koket.se/purple-rain-kokossmoothie-med-roda-bar",
  "https://www.koket.se/yellow-sunshine-mangosmoothie-med-banan-apelsin-och-ingefara",
  "https://www.koket.se/fattiga-riddare-med-hemgjord-hasselnotskram-och-hallon",
  "https://www.koket.se/halloumiburgare-med-rodbetor-och-jalape-omajonnas",
  "https://www.koket.se/grovt-brod-med-bockling-betor-och-picklad-lok",
  "https://www.koket.se/grillad-kalkonpastrami-med-kramig-potatissallad",
  "https://www.koket.se/ernsts-optimala-flaskmacka-med-apple-ingefara-och-chili",
  "https://www.koket.se/barley-water-ernsts-recept",
  "https://www.koket.se/koreansk-bbq-med-flaskkarre-och-kimchislaw",
  "https://www.koket.se/hemgjord-hasselnotskram-tea-malmegards-goda-recept",
  "https://www.koket.se/portabelloburgare-med-ostaioli-och-karamelliserad-rodlok",
  "https://www.koket.se/graddig-pasta-med-lax-spenat-och-endive",
  "https://www.koket.se/farrosallad-med-tomatpesto-och-mozzarella",
  "https://www.koket.se/sommardessert-med-bar-kola-maranger-och-fladersirap",
  "https://www.koket.se/sallad-med-knaperstekt-rokt-sidflask-brynta-kantareller-och-pressgurka",
  "https://www.koket.se/lax-med-sallad-pa-farsk-vitkal-gulbetor-och-fankal-i-sot-senapsdressing",
  "https://www.koket.se/enkla-frallor-med-fetaost-och-valnotter",
  "https://www.koket.se/hemgjord-farskost-med-persilja-graslok-och-dragon",
  "https://www.koket.se/pork-roast-bbq-med-cabbage-slaw-och-cheddar-sour-cream",
  "https://www.koket.se/grillad-picanha-med-sjograsnudelsallad-och-het-sojasas",
  "https://www.koket.se/helgrillad-entrec-te-med-krispig-rakostsallad-och-mandelpesto",
  "https://www.koket.se/roy-fares-galette-med-mandelfyllning-och-sommarbar",
  "https://www.koket.se/rostad-farskpotatis-med-graslok",
  "https://www.koket.se/grillad-broccoli-aubergine-zucchini-och-farsk-lok-med-gremolataolja",
  "https://www.koket.se/grillad-halloumi-med-honung-och-sesamfron",
  "https://www.koket.se/tzatziki-med-mynta-och-dill",
  "https://www.koket.se/tomat-och-fetaostsallad-med-dill",
  "https://www.koket.se/grillad-paella-med-kyckling-och-chorizo-lisa-lemkes-recept",
  "https://www.koket.se/fisk-och-skaldjursragu-med-citrus-och-forsommarprimorer",
  "https://www.koket.se/citruscurd-till-tartor",
  "https://www.koket.se/mattias-barkompott-till-tartor",
  "https://www.koket.se/gnocchi-med-sidflask-och-salvia",
  "https://www.koket.se/grillad-sallad-med-halloumi",
  "https://www.koket.se/tva-sorters-rub-till-grillat-johan-hedbergs-recept",
  "https://www.koket.se/grekisk-gratang-med-zucchini-fetaost-och-linser",
  "https://www.koket.se/matjesmaki",
  "https://www.koket.se/ingefarsgravad-lax-med-nudelsallad-och-wasabimajonnas",
  "https://www.koket.se/indisk-korma-med-halloumi-och-kikarter",
  "https://www.koket.se/jessica-frejs-melonsallad-med-fetaost",
  "https://www.koket.se/halloumi-med-gremolata",
  "https://www.koket.se/dilltsatsiki-med-kyckling",
  "https://www.koket.se/frittata-med-chorizo",
  "https://www.koket.se/varmrokt-lax-med-basilikasallad",
  "https://www.koket.se/friggin-s-morespaj-pa-grillen",
  "https://www.koket.se/creamed-corn-med-chili-och-koriander",
  "https://www.koket.se/friggin-ribs",
  "https://www.koket.se/hemgjord-glaze-till-grillat",
  "https://www.koket.se/grillad-hasselbackspotatis-med-lojrom-och-creme-fraiche",
  "https://www.koket.se/krispig-smordeg-med-farska-jordgubbar-limegradde-och-florsocker",
  "https://www.koket.se/burgare-fyllda-med-vasterbottensost",
  "https://www.koket.se/sallad-pa-senapssill-radisor-sparris-och-kryddkrasse",
  "https://www.koket.se/pistagefinancier-med-rabarber",
  "https://www.koket.se/langbakad-och-grillad-rostbiff-med-kryddrubb",
  "https://www.koket.se/rostad-kalsallad-med-grillad-spetspaprika-och-pak-soi",
  "https://www.koket.se/grillad-gemsallad-med-ort-och-tomatpesto",
  "https://www.koket.se/gubbrora-pa-lax-ansjovis-rodlok-och-dill",
  "https://www.koket.se/grillspett-med-kramig-fladerpotatissallad-och-grillad-chilisalsa",
  "https://www.koket.se/inlagd-lok-med-rosmarin-ernsts-recept",
  "https://www.koket.se/grillad-kycklingfile-med-vattenmelonsallad",
  "https://www.koket.se/sill-med-salsa-verde-loskokt-agg-och-ragbrod",
  "https://www.koket.se/sillbowl-med-pressad-potatis-och-wasabikram",
  "https://www.koket.se/snabb-tonfiskpizza-med-sparris-och-vasterbottensost",
  "https://www.koket.se/alkoholfri-torstslackare-med-ol-ananas-och-apple",
  "https://www.koket.se/sommarklassikern-pi-a-colada",
  "https://www.koket.se/sommarbal-pa-naked-grouse-och-apple",
  "https://www.koket.se/tarte-flambee-med-lok-och-ansjovis",
  "https://www.koket.se/jordgubbs-och-myntatartar-med-persiko-och-champagnegranite",
  "https://www.koket.se/pitabrod-fyllda-med-lammkottbullar-och-tzatziki",
  "https://www.koket.se/champagneplattar-med-sota-jordgubbar-och-lattvispad-gradde",
  "https://www.koket.se/angamat-med-krondillsskum",
  "https://www.koket.se/inkokt-vit-sparris-med-brynt-smor-sas",
  "https://www.koket.se/raggmunkar-serverade-med-aggrora-och-picklade-gronsaker",
  "https://www.koket.se/campogianis-jordgubbsdessert-med-vitt-vin",
  "https://www.koket.se/flamberad-kalvlever",
  "https://www.koket.se/pappardelle-med-kycklinghjarta-i-vitvinssas",
  "https://www.koket.se/crostini-med-kycklinglever-och-citronmajonnas",
  "https://www.koket.se/sliders-med-parmesancreme-och-gremolata",
  "https://www.koket.se/frederik-zalls-skargardssill",
  "https://www.koket.se/frederik-zalls-apelsinsill",
  "https://www.koket.se/frederik-zalls-laxburgare-deluxe",
  "https://www.koket.se/fisk-i-paket-med-dill-och-citron",
  "https://www.koket.se/roys-midsommartarta-med-jordgubbsmousse-rabarberkram-och-italiensk-marang",
  "https://www.koket.se/fisk-i-folie-med-kramig-raksas",
  "https://www.koket.se/ajvarfyllda-kycklingfileer-i-kramig-vitvinssas-2",
  "https://www.koket.se/pistage-och-vegetapanerad-kyckling",
  "https://www.koket.se/sichuanstekta-radisor-med-flask-och-koriander",
  "https://www.koket.se/gurksallad-med-mynta-och-miso-och-sesamdressing",
  "https://www.koket.se/stracciatella-med-gron-tomat-och-koreansk-sojavinagrett",
  "https://www.koket.se/paolos-pizza-med-salsiccia-rosmarin-och-tre-sorters-ost",
  "https://www.koket.se/brollopstarta-med-passionsfrukt-och-mascarponekram",
  "https://www.koket.se/pion-i-sockerpasta-se-gor",
  "https://www.koket.se/detaljerad-sockerros-se-gor",
  "https://www.koket.se/marsipanros-se-gor",
  "https://www.koket.se/planksallad-med-gardspommes-och-halloumi",
  "https://www.koket.se/overraskande-sommarpaj-3",
  "https://www.koket.se/spritsa-blommor-pa-cupcakes-se-gor",
  "https://www.koket.se/snabb-barbequesas",
  "https://www.koket.se/snabba-jordgubbstartan",
  "https://www.koket.se/himmelska-sill-sticks",
  "https://www.koket.se/biffmacka-a-la-lindstrom",
  "https://www.koket.se/tomatpaj-2",
  "https://www.koket.se/latt-potatissallad",
  "https://www.koket.se/skaldjurstarta",
  "https://www.koket.se/sill-och-potatispaj",
  "https://www.koket.se/viktvaktarnas-smorgastarta",
  "https://www.koket.se/chokladbrownies-med-butternutpumpa",
  "https://www.koket.se/mandel-och-rabarberkaka",
  "https://www.koket.se/smulpaj-med-rabarber-och-apple",
  "https://www.koket.se/pavlova-med-jordgubbar-och-pistagenotter",
  "https://www.koket.se/cheesecake-med-hallon-och-ingefara",
  "https://www.koket.se/viktvaktarnas-jordgubbstarta",
  "https://www.koket.se/viktvaktarnas-chimichurri",
  "https://www.koket.se/tre-varianter-av-tzatziki",
  "https://www.koket.se/asiatisk-majjo",
  "https://www.koket.se/ramensoppa-med-shiitakesvamp-och-miso",
  "https://www.koket.se/fish-cakes-med-hemgjord-sweet-chili",
  "https://www.koket.se/eco-echo-champagnedrink-med-flader-ananas-och-mandel",
  "https://www.koket.se/pannkakstarta-med-vaniljmousse-yuzumarinerade-jordgubbar-och-saltrostade-mandlar",
  "https://www.koket.se/rahyvlad-zucchini-och-sparris-med-curry-och-rostade-mandlar",
  "https://www.koket.se/eldad-rodbeta-kallrokt-graddfil-rarorda-svartvinbar-och-misomajonnas",
  "https://www.koket.se/pastasallad-med-grillad-citronkyckling",
  "https://www.koket.se/quinoabowl-med-sojastekt-tofu-avokado-och-paprikahummus",
  "https://www.koket.se/tartelette-med-vaniljkram-och-sasongens-bar",
  "https://www.koket.se/pizza-pa-grillen-med-chevre-sparris-och-vitlok",
  "https://www.koket.se/slatvarsfile-med-musslor-jatterakor-och-vitvinssas",
  "https://www.koket.se/vit-sparrisveloute",
  "https://www.koket.se/budapestbakelser-med-mandel-och-jordgubbar",
  "https://www.koket.se/rub-till-flaskkott",
  "https://www.koket.se/marinad-till-lammracks-niklas-ekstedts-recept",
  "https://www.koket.se/texas-ribs-med-coleslaw-och-picklad-jalapeno",
  "https://www.koket.se/tarta-med-kokosmousse-lemon-curd-och-vit-choklad",
  "https://www.koket.se/korgspritsning-pa-tarta-se-gor",
  "https://www.koket.se/sotpotatischips-superenkelt-recept",
  "https://www.koket.se/yakitorispett-med-ponzudressing-och-ris",
  "https://www.koket.se/risotto-pa-raris-med-shiitakesvamp",
  "https://www.koket.se/fritters-med-zucchini-och-halloumi",
  "https://www.koket.se/strassburgare-med-chokladganache",
  "https://www.koket.se/teas-chokladsnittar-med-parlsocker",
  "https://www.koket.se/drommar-utan-hjorthornssalt",
  "https://www.koket.se/teas-notkakor",
  "https://www.koket.se/stockholmskakor-med-dinkel-mandel-och-hallonsylt",
  "https://www.koket.se/enkla-macarons-svarmormors-biskvier",
  "https://www.koket.se/teas-kolasnittar-med-rasocker-och-vanilj",
  "https://www.koket.se/matjessill-med-dillslungad-potatis-och-pepparrotskram",
  "https://www.koket.se/varmlandstarta-med-jordgubbar-och-flader",
  "https://www.koket.se/chokladmedaljonger-fyllda-dadlar-och-m-slibars",
  "https://www.koket.se/vegetarisk-spaghetti-bolognese-pa-rotselleri-och-morotter",
  "https://www.koket.se/rabarber-och-halloncheesecake-med-dromkross",
  "https://www.koket.se/oxfilecarpaccio-med-snabb-kimchi-halstrad-kammussla-och-sesammajonnas",
  "https://www.koket.se/torsk-och-rakceviche-med-avokodocreme-och-forellrom",
  "https://www.koket.se/dessertpizza-med-jordgubbar-salta-mandlar-och-glass",
  "https://www.koket.se/sparrispizza-med-bovete-och-citron",
  "https://www.koket.se/rokig-margherita-med-scamorza",
  "https://www.koket.se/hemkokt-jordgubbskram-med-biskvisticks-och-vaniljglass",
  "https://www.koket.se/apelsintarta-med-tonkabonspannacotta-chokladmousse-och-kolasmorkram",
  "https://www.koket.se/thornstroms-toast-skagen",
  "https://www.koket.se/kalvfrikadeller-med-senap-och-persilja",
  "https://www.koket.se/buffalo-chicken-thighs-med-blue-cheese-dip",
  "https://www.koket.se/black-derby-fruit-cake",
  "https://www.koket.se/chokladcappuccino",
  "https://www.koket.se/rodtunga-i-skaldjurssas-med-finbesok-av-hummer-och-krafta",
  "https://www.koket.se/skon-gron-artsoppa-med-parmesanchips-och-pilgrimsmussla",
  "https://www.koket.se/frusen-mojito-myntasorbet-med-ljus-rom",
  "https://www.koket.se/pi-a-colada-glassdrink-med-kokosmjolk-malibu-och-ananas",
  "https://www.koket.se/roding-med-vit-sparris-och-hollandaisesas",
  "https://www.koket.se/semifreddo-med-notchoklad",
  "https://www.koket.se/majskyckling-med-syrlig-sas-serveras-med-sotpotatisfries",
  "https://www.koket.se/gron-artsoppa-med-pepparrotsfraiche",
  "https://www.koket.se/ugnsstekt-kung-ingels-med-fetaost-och-oliver",
  "https://www.koket.se/jordartskockssoppa-med-rokt-kalkon-och-timjan",
  "https://www.koket.se/adelostfylld-kalkonfile-med-hasselbackspotatis-och-blabarssas",
  "https://www.koket.se/marias-tortillalasagne",
  "https://www.koket.se/tandoorigryta-pa-kalkon-med-ris-och-naanbrod",
  "https://www.koket.se/grand-a-oli-marseillais",
  "https://www.koket.se/gron-papayasallad-i-rodkalsblad",
  "https://www.koket.se/kikartsfras-med-couscous-och-chimichurri",
  "https://www.koket.se/bleskiver-en-dansk-klassiker",
  "https://www.koket.se/ankbrost-med-sockerstekt-potatis-serveras-med-kantarellsas-och-pressgurka",
  "https://www.koket.se/tva-sma-sm-rrebr-d",
  "https://www.koket.se/frasig-currytorsk-med-hemgjord-mangochutney",
  "https://www.koket.se/klassiska-kanelbullar-och-parondrommar",
  "https://www.koket.se/flarn-till-smorgastarta",
  "https://www.koket.se/blabarsfrojd",
  "https://www.koket.se/fisksoppa-med-dillkram-serveras-med-smordegsflarn",
  "https://www.koket.se/toast-med-getost",
  "https://www.koket.se/rosti-med-svarta-linser-och-graddfil",
  "https://www.koket.se/sebastien-boudets-gronsakslasagne",
  "https://www.koket.se/paris-brest-med-pralinsmorkram",
  "https://www.koket.se/lattstekt-tonfisk-med-en-ljummen-sparrissallad-och-rouille",
  "https://www.koket.se/pinchos-med-getostrora-ramarinerad-polkabeta-och-oliv",
  "https://www.koket.se/pinchos-med-kallrokt-lax-dillinkokt-apple-keso-och-pepparrot",
  "https://www.koket.se/pinchos-med-kaprisfarskost-rodbeta-och-sardell",
  "https://www.koket.se/bakad-citronpaj-med-italiensk-marang",
  "https://www.koket.se/somrig-matjeswrap-med-krispig-pak-choi-lingonchutney",
  "https://www.koket.se/matjesklamma-med-het-rakrora",
  "https://www.koket.se/pho-vietnamesisk-soppa",
  "https://www.koket.se/drip-cake-med-choklad-marang-och-jordgubbar",
  "https://www.koket.se/blomsterarrangemang-som-tartdekoration-se-gor",
  "https://www.koket.se/rabarbersoppa-och-jordgubbstiramisu",
  "https://www.koket.se/fina-fisken-moter-skogens-guld-torskrygg-med-kantareller-och-bacon",
  "https://www.koket.se/skargardsstarter-med-finess-pa-gubben",
  "https://www.koket.se/varldens-enklaste-creme-fraiche-sas",
  "https://www.koket.se/smorsas-med-farska-orter",
  "https://www.koket.se/ansjovisdressing-med-dill",
  "https://www.koket.se/grekiska-kycklingspett-med-potatisgratang-med-fetaost-och-vitlok",
  "https://www.koket.se/smorrebrod-med-sparris-lax-och-pocherat-agg",
  "https://www.koket.se/smorrebrod-stjerneskud",
  "https://www.koket.se/smorrebrod-dyrlaegens-nattmad",
  "https://www.koket.se/minichokladkaka-toppad-med-roda-bar-och-vit-choklad",
  "https://www.koket.se/grillad-entrec-te-serveras-med-fransk-sas-och-farsk-pasta",
  "https://www.koket.se/baconinlindad-halloumi-med-grillade-gronsaker",
  "https://www.koket.se/lyxig-macka-med-cashewnotsdipp-och-gron-topping",
  "https://www.koket.se/senapsgratinerad-falukorv-med-rotfruktsmos",
  "https://www.koket.se/cheesecake-med-mandel-och-vanilj-serveras-med-bjornbar-fran-sodero",
  "https://www.koket.se/hel-abborre-i-paket",
  "https://www.koket.se/gubbrora-med-batbakat-knacke",
  "https://www.koket.se/helstekt-kalkon-pa-klassiskt-vis",
  "https://www.koket.se/kalkonkottbullar-med-salvia-och-vitlok",
  "https://www.koket.se/torsk-med-dillsas-citron-och-kalrabbi",
  "https://www.koket.se/johans-kokostoppar-saffransbiscotti-och-chokladsnurror",
  "https://www.koket.se/cecilias-kolakakor-minicookies-och-vanilj-och-chokladkakor",
  "https://www.koket.se/johan-sorbergs-flarnrullar",
  "https://www.koket.se/prinsessornas-hallonparfait",
  "https://www.koket.se/ugnsbakad-lax-med-fetaost-serveras-med-varm-potatissallad",
  "https://www.koket.se/parmainlindad-sparris-med-mozzarella-och-basilika",
  "https://www.koket.se/linsburgare-med-grillade-gronsaker-och-chipotlemajonnas",
  "https://www.koket.se/sommartarta-i-glas-med-jordgubbar-och-brynt-smor",
  "https://www.koket.se/koka-farskpotatis-jessica-frejs-recept",
  "https://www.koket.se/3-roror-till-buffebordet",
  "https://www.koket.se/lax-med-dragonsmor",
  "https://www.koket.se/kyckling-med-citron-och-basilikasas",
  "https://www.koket.se/sa-gor-du-swirls-pa-en-cheesecake-se-gor",
  "https://www.koket.se/cheesecake-med-vit-choklad-och-hallonswirl-roy-fares-recept",
  "https://www.koket.se/rabarberkompott-med-vispad-graddyoghurt-och-karamelliserad-mandel",
  "https://www.koket.se/levain-med-lojrom-och-farskost-med-ogras",
  "https://www.koket.se/pesto-pa-kirskal",
  "https://www.koket.se/pasta-primavera-med-sparris-svartkal-och-ricotta",
  "https://www.koket.se/tuttifruttitarta-med-jordgubbar-och-vit-choklad",
  "https://www.koket.se/spritsa-snackor-och-parlband-se-gor",
  "https://www.koket.se/gino-serveras-med-vaniljglass",
  "https://www.koket.se/helstekt-kronhjortfile-serveras-med-trattkantareller-och-rodvinssas",
  "https://www.koket.se/rokt-vildandsbrost-serveras-med-lojrom-och-creme-fraiche",
  "https://www.koket.se/somriga-tonfiskburgare",
  "https://www.koket.se/krispig-tonfisktaco-med-mango-chilisas",
  "https://www.koket.se/fyllda-laxfileer-med-varprimorer-i-vitvinssas",
  "https://www.koket.se/tonfiskwrap-med-mangodressing-picklad-rodkal",
  "https://www.koket.se/rostad-kyckling-med-primorsallad-och-sesamsas",
  "https://www.koket.se/passion-pavlova-toppad-med-bar",
  "https://www.koket.se/fisktacos-med-mangosallad",
  "https://www.koket.se/pulled-beef-med-asiatisk-touch",
  "https://www.koket.se/grillade-ajvarquesadillas",
  "https://www.koket.se/halloumiburgare-med-ajvar-och-rostad-lok",
  "https://www.koket.se/vegoburgare-med-parmesanrostad-gardspommes",
  "https://www.koket.se/bananglass-med-matcha-och-kokos",
  "https://www.koket.se/mitt-kok/jennie-wallden/thailandsk-biffsallad/",
  "https://www.koket.se/chokladmums-serveras-med-gradde-o-hallon",
  "https://www.koket.se/oxfile-tournedos-med-gronmogelost-serveras-med-rodvinssas-och-palsternackspure",
  "https://www.koket.se/slat-broccolisoppa-med-sting-toppad-med-knaperstekt-bacon",
  "https://www.koket.se/glutenfria-pannkakor-med-rakor-och-spenat",
  "https://www.koket.se/jordgubbssoppa-med-mandelbiskvier-och-mascarponekram",
  "https://www.koket.se/bakelse-pa-varmvispad-rulltarta",
  "https://www.koket.se/vit-chokladmousse-pa-mandelbotten-sheriffcake-med-chokladmousse",
  "https://www.koket.se/kalvfile-med-potatisrosor-och-svampsas-lucky-biff-med-lukes-rosepotato",
  "https://www.koket.se/fyllda-avokadoskal-med-rakor-och-kaviar-ranchens-rakado",
  "https://www.koket.se/filodegspaj-med-greve-och-vasterbottensost",
  "https://www.koket.se/kryddig-linsgryta-med-morotsbullar",
  "https://www.koket.se/pasta-med-morotsbullar-och-tomatsas",
  "https://www.koket.se/vegobullar-med-morot-och-linser",
  "https://www.koket.se/morotsbullar-med-yoghurtsas",
  "https://www.koket.se/sebastien-boudets-hemgjorda-smor",
  "https://www.koket.se/rabarber-och-apelsinsylt",
  "https://www.koket.se/baguette-med-poolish",
  "https://www.koket.se/pastasallad-med-notchorizo",
  "https://www.koket.se/the-chicago-dog",
  "https://www.koket.se/lammkorv-med-rotsakspytt-och-rosmarinmajonnas",
  "https://www.koket.se/flader-och-citronmarangpaj-roy-fares-recept",
  "https://www.koket.se/kycklinggryta-med-potatis-och-ras-el-hanout",
  "https://www.koket.se/pan-con-chocolat",
  "https://www.koket.se/spicy-beef-taco",
  "https://www.koket.se/jordgubbspaj-med-vaniljsas",
  "https://www.koket.se/sukiyaki-med-ris",
  "https://www.koket.se/sashimi-pa-lax-och-tonfisk",
  "https://www.koket.se/hemgjorda-fiskbullar-i-thaicurrysas",
  "https://www.koket.se/paolos-burrata-med-prosciutto-och-sota-tomater",
  "https://www.koket.se/rawchokladtryfflar-med-varma-hallon",
  "https://www.koket.se/gratinerad-rotselleri-med-ljunghonung-och-vildappelkompott",
  "https://www.koket.se/varm-jordgubbssoppa-serveras-med-saffransmandelgradde",
  "https://www.koket.se/hasselnotskaka-med-svartvinbarskram-och-vaniljmousse",
  "https://www.koket.se/graddtarta-med-vaniljkram-och-jordgubbar",
  "https://www.koket.se/glaserad-moussetarta-med-smak-av-lakrits-och-viol",
  "https://www.koket.se/avokadobakade-agg-med-chorizo",
  "https://www.koket.se/flader-och-kardemummatarta",
  "https://www.koket.se/wraps-med-stekt-agg-aubergine-och-chermoula",
  "https://www.koket.se/mammas-appelkaka-serveras-med-blabarsglass",
  "https://www.koket.se/angande-fiskgomma-serveras-med-rykande-gratang",
  "https://www.koket.se/vasterbottensbr-lee-med-lojrom",
  "https://www.koket.se/teriyakilax-med-sesamris",
  "https://www.koket.se/mork-chokladmousse-med-hallon-och-lakritsrostade-pecannotter",
  "https://www.koket.se/panerad-lubb-serveras-med-cool-kalsallad",
  "https://www.koket.se/brynt-tonfisk-med-kryddig-vinagrett-syrlig-avokadorora-och-sticklok",
  "https://www.koket.se/chokladbollsrulltarta-med-havrebollsfyllning",
  "https://www.koket.se/friterade-och-ostfyllda-risottobollar-med-bonsallad",
  "https://www.koket.se/mini-swirl-cheesecake",
  "https://www.koket.se/roy-fares-hemgjorda-chokladkex",
  "https://www.koket.se/mazamen",
  "https://www.koket.se/gyoza-med-flaskfars-sesam-och-ingefara",
  "https://www.koket.se/tempura-friterade-gronsaker-och-skaldjur",
  "https://www.koket.se/eclairer-med-jordgubbskram-och-mynta",
  "https://www.koket.se/vit-sparris-med-rostad-aggkram-vilda-orter-och-torkat-viltkott",
  "https://www.koket.se/hemgjord-kebabpizza-lisa-lemkes-basta-recept",
  "https://www.koket.se/red-velvet-cake-med-kolasmorkram-och-karamellpopcorn",
  "https://www.koket.se/cirkustarta-med-chokladgradde-och-chokladganache",
  "https://www.koket.se/atbar-spets-till-tarta-se-gor",
  "https://www.koket.se/sotsalt-cheesecake",
  "https://www.koket.se/marinerad-kycklingfile-serveras-med-potatis-duchesse-och-kramig-heta-drommar-sas",
  "https://www.koket.se/kraft-och-rakrora-pa-vitloksstekt-brod",
  "https://www.koket.se/tacos-med-kalkon-och-guacamole",
  "https://www.koket.se/familjens-godaste-kalkonbolognese",
  "https://www.koket.se/carbonara-med-skogschampinjon-och-kalkonbacon",
  "https://www.koket.se/kalkonspett-med-srirachaglaze-kokosdipp-och-smakrik-nudelsallad",
  "https://www.koket.se/caesarsallad-med-kalkon-och-kalkonbacon",
  "https://www.koket.se/kalkonkorv-stroganoff",
  "https://www.koket.se/chili-con-carne-med-kalkonfars",
  "https://www.koket.se/kalkonbourguignon-med-skogschampinjoner-savojkal-och-smorstekt-rodlok",
  "https://www.koket.se/kycklingrullader-med-sidflask-parmesan-och-basilika",
  "https://www.koket.se/parlhona-med-senapsveloute-och-smorkokt-majrova",
  "https://www.koket.se/crepes-med-camembert-och-hjortronsylt",
  "https://www.koket.se/vraas-vilda-biffar-med-rostade-gronsaker-och-svampsas",
  "https://www.koket.se/vraas-vilda-toast",
  "https://www.koket.se/spaghetti-med-rakor-bacon-ajvar",
  "https://www.koket.se/choklad-och-avokadomousse-med-bar-och-kokos",
  "https://www.koket.se/flader-och-kardemummatarta",
  "https://www.koket.se/wraps-med-stekt-agg-aubergine-och-chermoula",
  "https://www.koket.se/mammas-appelkaka-serveras-med-blabarsglass",
  "https://www.koket.se/angande-fiskgomma-serveras-med-rykande-gratang",
  "https://www.koket.se/vasterbottensbr-lee-med-lojrom",
  "https://www.koket.se/teriyakilax-med-sesamris",
  "https://www.koket.se/mork-chokladmousse-med-hallon-och-lakritsrostade-pecannotter",
  "https://www.koket.se/panerad-lubb-serveras-med-cool-kalsallad",
  "https://www.koket.se/brynt-tonfisk-med-kryddig-vinagrett-syrlig-avokadorora-och-sticklok",
  "https://www.koket.se/chokladbollsrulltarta-med-havrebollsfyllning",
  "https://www.koket.se/friterade-och-ostfyllda-risottobollar-med-bonsallad",
  "https://www.koket.se/mini-swirl-cheesecake",
  "https://www.koket.se/roy-fares-hemgjorda-chokladkex",
  "https://www.koket.se/mazamen",
  "https://www.koket.se/gyoza-med-flaskfars-sesam-och-ingefara",
  "https://www.koket.se/tempura-friterade-gronsaker-och-skaldjur",
  "https://www.koket.se/eclairer-med-jordgubbskram-och-mynta",
  "https://www.koket.se/vit-sparris-med-rostad-aggkram-vilda-orter-och-torkat-viltkott",
  "https://www.koket.se/hemgjord-kebabpizza-lisa-lemkes-basta-recept",
  "https://www.koket.se/red-velvet-cake-med-kolasmorkram-och-karamellpopcorn",
  "https://www.koket.se/cirkustarta-med-chokladgradde-och-chokladganache",
  "https://www.koket.se/atbar-spets-till-tarta-se-gor",
  "https://www.koket.se/sotsalt-cheesecake",
  "https://www.koket.se/marinerad-kycklingfile-serveras-med-potatis-duchesse-och-kramig-heta-drommar-sas",
  "https://www.koket.se/kraft-och-rakrora-pa-vitloksstekt-brod",
  "https://www.koket.se/tacos-med-kalkon-och-guacamole",
  "https://www.koket.se/familjens-godaste-kalkonbolognese",
  "https://www.koket.se/carbonara-med-skogschampinjon-och-kalkonbacon",
  "https://www.koket.se/kalkonspett-med-srirachaglaze-kokosdipp-och-smakrik-nudelsallad",
  "https://www.koket.se/caesarsallad-med-kalkon-och-kalkonbacon",
  "https://www.koket.se/kalkonkorv-stroganoff",
  "https://www.koket.se/chili-con-carne-med-kalkonfars",
  "https://www.koket.se/kalkonbourguignon-med-skogschampinjoner-savojkal-och-smorstekt-rodlok",
  "https://www.koket.se/kycklingrullader-med-sidflask-parmesan-och-basilika",
  "https://www.koket.se/parlhona-med-senapsveloute-och-smorkokt-majrova",
  "https://www.koket.se/crepes-med-camembert-och-hjortronsylt",
  "https://www.koket.se/vraas-vilda-biffar-med-rostade-gronsaker-och-svampsas",
  "https://www.koket.se/vraas-vilda-toast",
  "https://www.koket.se/spaghetti-med-rakor-bacon-ajvar",
  "https://www.koket.se/choklad-och-avokadomousse-med-bar-och-kokos",
  "https://www.koket.se/coconut-bean-curry-med-vitkal-och-morotter",
  "https://www.koket.se/grillad-ananas-med-frozen-yoghurt",
  "https://www.koket.se/grillad-kotlett-med-gronsaksspett",
  "https://www.koket.se/vit-chokladmousse-med-hallon",
  "https://www.koket.se/mammas-frasiga-kyckling-med-rotsaker-och-aioli",
  "https://www.koket.se/grillad-ryggbiff-med-nudelsallad",
  "https://www.koket.se/raksoppa-med-hummerfond",
  "https://www.koket.se/grillade-farsbiffar-med-het-coleslaw",
  "https://www.koket.se/grillad-kotlett-med-krispig-potatissallad",
  "https://www.koket.se/grillad-flaskfile-med-rabarberchutney",
  "https://www.koket.se/grillad-halloumi-med-paronsallad",
  "https://www.koket.se/grillad-portobelloburgare-med-parmesancreme",
  "https://www.koket.se/grillad-kyckling-med-pasta-och-paprikapesto",
  "https://www.koket.se/grillad-limekyckling-med-rostad-sotpotatis-och-fetaostkram",
  "https://www.koket.se/grillad-kyckling-med-ugnsrostade-gronsaker-och-ramsloksdressing",
  "https://www.koket.se/grillad-lax-med-fransk-potatissallad",
  "https://www.koket.se/vietnamesisk-torsk-med-krispig-sallad",
  "https://www.koket.se/bakad-rabarber-med-farskostmousse-och-kaksmulor",
  "https://www.koket.se/risotto-med-kirskal-farsklok-och-honungsglaserad-vit-sparris",
  "https://www.koket.se/saltstekt-gron-sparris-med-rostad-mandel-och-vasterbottensost",
  "https://www.koket.se/vit-sparris-marinerad-i-flader-och-rabarbervinagrett",
  "https://www.koket.se/pesto-av-nasslor-och-loktrav",
  "https://www.koket.se/ramsloksmajonnas",
  "https://www.koket.se/sa-kokar-du-den-perfekta-farskpotatisen",
  "https://www.koket.se/angssyrasmor",
  "https://www.koket.se/spaghetti-med-sparris-parmesan-och-farska-orter",
  "https://www.koket.se/valborgs-brinnande-glasstarta",
  "https://www.koket.se/nyhetsmorgon/sebastien-boudet/marshmallows-med-fruktpure/",
  "https://www.koket.se/dessert-med-farskostkram-svartvinbarskompott-och-grahamssmulor",
  "https://www.koket.se/salladsbuketter-och-musseldippa",
  "https://www.koket.se/nygraddat-tunnbrod-med-creme-fraiche-och-musseltopping",
  "https://www.koket.se/musslor-med-tomatsas",
  "https://www.koket.se/chokladtarta-med-hallon-och-vanilj",
  "https://www.koket.se/bao-bun-med-hoisinflask",
  "https://www.koket.se/pistagetarta-med-lingon-och-vit-choklad",
  "https://www.koket.se/zebramonstrad-tarta-se-gor",
  "https://www.koket.se/fransk-kycklinggryta-med-linser",
  "https://www.koket.se/kolja-i-kramig-dill-raksas",
  "https://www.koket.se/whiskeymarinerat-kalkonbrost",
  "https://www.koket.se/farska-varrullar-med-sotsyrlig-dipp",
  "https://www.koket.se/flat-bread-pizza-med-lammfars-och-mynta",
  "https://www.koket.se/lisas-fattoush-med-stekt-libabrod",
  "https://www.koket.se/christians-kyckling-med-picklade-gronsaker-och-hummus",
  "https://www.koket.se/krispig-spatta-med-curryremoulad",
  "https://www.koket.se/cashewnotsdipp-med-tomat-och-paprika",
  "https://www.koket.se/renee-voltaires-vegobiffar",
  "https://www.koket.se/farsk-sorbet-pa-kokosmjolk-och-sesamfron",
  "https://www.koket.se/perfekt-smulpaj-pa-rabarber",
  "https://www.koket.se/stekta-nasselskott-med-bondbonspure-och-forlorat-agg",
  "https://www.koket.se/vegetariska-samosas-med-morotssallad",
  "https://www.koket.se/jessicas-frejs-grundrecept-pa-risotto",
  "https://www.koket.se/chorizopytt-i-ugnen",
  "https://www.koket.se/knackig-glutenfri-rabarberpaj",
  "https://www.koket.se/nicoles-morotssoppa-med-ingefara-och-koriander",
  "https://www.koket.se/lobster-rolls-a-la-catarina",
  "https://www.koket.se/skumtoppar-med-blabar-och-vit-choklad",
  "https://www.koket.se/creme-brulee-med-stjarnanis-rabarber-och-lakrits",
  "https://www.koket.se/tonfisksallad-med-kokos-vit-sparris-och-ramslok",
  "https://www.koket.se/syditaliensk-kyckling-med-bonstomp",
  "https://www.koket.se/ananastarta-med-honungsrostade-valnotter-och-yoghurtfrosting",
  "https://www.koket.se/volangbard-till-tarta-se-gor",
  "https://www.koket.se/grillat-gronsaksknyte-med-myntahummus",
  "https://www.koket.se/grillade-potatiskroketter-med-ortsmor",
  "https://www.koket.se/tom-sjostedts-biff-rydberg-med-senapsyoghurt",
  "https://www.koket.se/friterad-avokado-med-citrondipp",
  "https://www.koket.se/taco-fiesta-med-ryggbiff",
  "https://www.koket.se/kyckling-ramen-med-pekingagg-sobanudlar-och-svampbuljong",
  "https://www.koket.se/ugnsbakade-tomater-med-halloumi-hotpot",
  "https://www.koket.se/ortfyllda-kycklingrullader-med-tomat-och-spenatsallad",
  "https://www.koket.se/kramig-italiensk-gratang",
  "https://www.koket.se/ljummen-nudelsallad-med-friterad-kyckling",
  "https://www.koket.se/jerk-chicken-tareq-taylors-recept",
  "https://www.koket.se/kycklingcurry-fran-seychellerna",
  "https://www.koket.se/aggrora-med-keso-och-rostade-notter-2",
  "https://www.koket.se/lisa-lemkes-fiskgratang-med-rak-och-dillsas",
  "https://www.koket.se/ramen-med-flaskfars-och-sesam",
  "https://www.koket.se/knackiga-flarnkorgar-med-glass-och-hallon",
  "https://www.koket.se/algrullader-med-bacon-serveras-med-ris",
  "https://www.koket.se/saljheas-kramiga-fisksoppa",
  "https://www.koket.se/snoagg-i-vaniljsas-magnus-johanssons-recept",
  "https://www.koket.se/flat-bread-pizza-med-lammfars-och-mynta",
  "https://www.koket.se/lisas-fattoush-med-stekt-libabrod",
  "https://www.koket.se/christians-kyckling-med-picklade-gronsaker-och-hummus",
  "https://www.koket.se/krispig-spatta-med-curryremoulad",
  "https://www.koket.se/cashewnotsdipp-med-tomat-och-paprika",
  "https://www.koket.se/renee-voltaires-vegobiffar",
  "https://www.koket.se/farsk-sorbet-pa-kokosmjolk-och-sesamfron",
  "https://www.koket.se/perfekt-smulpaj-pa-rabarber",
  "https://www.koket.se/stekta-nasselskott-med-bondbonspure-och-forlorat-agg",
  "https://www.koket.se/vegetariska-samosas-med-morotssallad",
  "https://www.koket.se/jessicas-frejs-grundrecept-pa-risotto",
  "https://www.koket.se/chorizopytt-i-ugnen",
  "https://www.koket.se/knackig-glutenfri-rabarberpaj",
  "https://www.koket.se/nicoles-morotssoppa-med-ingefara-och-koriander",
  "https://www.koket.se/lobster-rolls-a-la-catarina",
  "https://www.koket.se/skumtoppar-med-blabar-och-vit-choklad",
  "https://www.koket.se/creme-brulee-med-stjarnanis-rabarber-och-lakrits",
  "https://www.koket.se/tonfisksallad-med-kokos-vit-sparris-och-ramslok",
  "https://www.koket.se/syditaliensk-kyckling-med-bonstomp",
  "https://www.koket.se/ananastarta-med-honungsrostade-valnotter-och-yoghurtfrosting",
  "https://www.koket.se/volangbard-till-tarta-se-gor",
  "https://www.koket.se/grillat-gronsaksknyte-med-myntahummus",
  "https://www.koket.se/grillade-potatiskroketter-med-ortsmor",
  "https://www.koket.se/tom-sjostedts-biff-rydberg-med-senapsyoghurt",
  "https://www.koket.se/friterad-avokado-med-citrondipp",
  "https://www.koket.se/taco-fiesta-med-ryggbiff",
  "https://www.koket.se/kyckling-ramen-med-pekingagg-sobanudlar-och-svampbuljong",
  "https://www.koket.se/ugnsbakade-tomater-med-halloumi-hotpot",
  "https://www.koket.se/ortfyllda-kycklingrullader-med-tomat-och-spenatsallad",
  "https://www.koket.se/kramig-italiensk-gratang",
  "https://www.koket.se/ljummen-nudelsallad-med-friterad-kyckling",
  "https://www.koket.se/jerk-chicken-tareq-taylors-recept",
  "https://www.koket.se/kycklingcurry-fran-seychellerna",
  "https://www.koket.se/aggrora-med-keso-och-rostade-notter-2",
  "https://www.koket.se/lisa-lemkes-fiskgratang-med-rak-och-dillsas",
  "https://www.koket.se/ramen-med-flaskfars-och-sesam",
  "https://www.koket.se/knackiga-flarnkorgar-med-glass-och-hallon",
  "https://www.koket.se/algrullader-med-bacon-serveras-med-ris",
  "https://www.koket.se/saljheas-kramiga-fisksoppa",
  "https://www.koket.se/snoagg-i-vaniljsas-magnus-johanssons-recept",
  "https://www.koket.se/aggrora-med-kal-hasselnotter-och-sesamfron",
  "https://www.koket.se/red-suedill",
  "https://www.koket.se/porkolt-pa-mammas-vis",
  "https://www.koket.se/karpatka",
  "https://www.koket.se/tartar-pa-oxfile-med-misomajaonnas-och-lotusrotchips",
  "https://www.koket.se/snabb-varpaj-med-bakade-rabarber-och-applen",
  "https://www.koket.se/sallad-pa-rostade-morotter-med-varmrokt-lax-persiljedressing-pumpafron-och-fetaost",
  "https://www.koket.se/krossade-sma-parmesanpotatisar-med-brynt-ansjovissmor-med-dill-och-graslok",
  "https://www.koket.se/matjessnittar-av-surdegsbrod-med-ramsloks-och-aggrora",
  "https://www.koket.se/fryst-cheesecake-med-passionsfruktsspegel",
  "https://www.koket.se/smorstekt-lammrostbiff-med-gron-sparris",
  "https://www.koket.se/inkokt-vit-sparris-i-surol-med-kram-pa-aggula-krispigt-surdeg-och-libbsticka",
  "https://www.koket.se/lammkotletter-med-tomat-fetaost-och-rosmarin",
  "https://www.koket.se/macarons-med-mintfyllning-serveras-med-citronglass",
  "https://www.koket.se/adelostbakad-kyckling-med-ugnsstekta-paron-och-rodbetor",
  "https://www.koket.se/tomatsoppa-med-sting",
  "https://www.koket.se/grillad-toast-med-lagrad-ost-kallskuret-och-sallad",
  "https://www.koket.se/pastagratang-a-la-carbonara",
  "https://www.koket.se/hjortrondelikatess-vit-chokladkram-varvad-med-kaksmulor",
  "https://www.koket.se/lapplandsk-hamburgare-med-lingondressing-toppad-med-suovas",
  "https://www.koket.se/viltcarpaccio-pa-paronbadd-med-pepparrotskram-och-valnotter",
  "https://www.koket.se/proteingrot-med-notter-och-banan",
  "https://www.koket.se/paskkakor-med-dulce-de-leche-och-mork-choklad",
  "https://www.koket.se/thai-chicken-patties-med-krispig-kalsallad",
  "https://www.koket.se/lingonglass-med-blabar-och-hjortronsylt-bierna-muorje",
  "https://www.koket.se/boatso-med-mandelpotatiscrunch-och-blabarssky",
  "https://www.koket.se/smorgasbakelse-ravddo",
  "https://www.koket.se/sillmacka-med-basilika-och-kokt-agg",
  "https://www.koket.se/pannacotta-med-hjortron",
  "https://www.koket.se/ripa-med-ugnspotatis-och-vasterbottenflarn",
  "https://www.koket.se/toast-med-gravad-fjallsik-och-lojromsrora",
  "https://www.koket.se/spritsa-marang-se-gor",
  "https://www.koket.se/forforiska-vegobullar",
  "https://www.koket.se/bruschetta-pa-ajvar",
  "https://www.koket.se/klassiska-hamburgare",
  "https://www.koket.se/grillspett-av-tartariska-bullar-med-grillade-gronsaker",
  "https://www.koket.se/panko-och-sesamfrittad-kalkon-med-rotfruktspickels-och-sojamajjo",
  "https://www.koket.se/aprikosfylld-kalkonfile-med-farskostgremolata",
  "https://www.koket.se/rodvinsmarinerad-kalkonbrostfile",
  "https://www.koket.se/kalkonkottbullar",
  "https://www.koket.se/aggrora-med-kal-hasselnotter-och-sesamfron",
  "https://www.koket.se/red-suedill",
  "https://www.koket.se/porkolt-pa-mammas-vis",
  "https://www.koket.se/karpatka",
  "https://www.koket.se/tartar-pa-oxfile-med-misomajaonnas-och-lotusrotchips",
  "https://www.koket.se/snabb-varpaj-med-bakade-rabarber-och-applen",
  "https://www.koket.se/sallad-pa-rostade-morotter-med-varmrokt-lax-persiljedressing-pumpafron-och-fetaost",
  "https://www.koket.se/krossade-sma-parmesanpotatisar-med-brynt-ansjovissmor-med-dill-och-graslok",
  "https://www.koket.se/matjessnittar-av-surdegsbrod-med-ramsloks-och-aggrora",
  "https://www.koket.se/fryst-cheesecake-med-passionsfruktsspegel",
  "https://www.koket.se/smorstekt-lammrostbiff-med-gron-sparris",
  "https://www.koket.se/inkokt-vit-sparris-i-surol-med-kram-pa-aggula-krispigt-surdeg-och-libbsticka",
  "https://www.koket.se/lammkotletter-med-tomat-fetaost-och-rosmarin",
  "https://www.koket.se/macarons-med-mintfyllning-serveras-med-citronglass",
  "https://www.koket.se/adelostbakad-kyckling-med-ugnsstekta-paron-och-rodbetor",
  "https://www.koket.se/tomatsoppa-med-sting",
  "https://www.koket.se/grillad-toast-med-lagrad-ost-kallskuret-och-sallad",
  "https://www.koket.se/pastagratang-a-la-carbonara",
  "https://www.koket.se/hjortrondelikatess-vit-chokladkram-varvad-med-kaksmulor",
  "https://www.koket.se/lapplandsk-hamburgare-med-lingondressing-toppad-med-suovas",
  "https://www.koket.se/viltcarpaccio-pa-paronbadd-med-pepparrotskram-och-valnotter",
  "https://www.koket.se/proteingrot-med-notter-och-banan",
  "https://www.koket.se/paskkakor-med-dulce-de-leche-och-mork-choklad",
  "https://www.koket.se/thai-chicken-patties-med-krispig-kalsallad",
  "https://www.koket.se/lingonglass-med-blabar-och-hjortronsylt-bierna-muorje",
  "https://www.koket.se/boatso-med-mandelpotatiscrunch-och-blabarssky",
  "https://www.koket.se/smorgasbakelse-ravddo",
  "https://www.koket.se/sillmacka-med-basilika-och-kokt-agg",
  "https://www.koket.se/pannacotta-med-hjortron",
  "https://www.koket.se/ripa-med-ugnspotatis-och-vasterbottenflarn",
  "https://www.koket.se/toast-med-gravad-fjallsik-och-lojromsrora",
  "https://www.koket.se/spritsa-marang-se-gor",
  "https://www.koket.se/forforiska-vegobullar",
  "https://www.koket.se/bruschetta-pa-ajvar",
  "https://www.koket.se/klassiska-hamburgare",
  "https://www.koket.se/grillspett-av-tartariska-bullar-med-grillade-gronsaker",
  "https://www.koket.se/panko-och-sesamfrittad-kalkon-med-rotfruktspickels-och-sojamajjo",
  "https://www.koket.se/aprikosfylld-kalkonfile-med-farskostgremolata",
  "https://www.koket.se/rodvinsmarinerad-kalkonbrostfile",
  "https://www.koket.se/kalkonkottbullar",
  "https://www.koket.se/helstekt-kalkon-fylld-med-paron-och-rosmarin",
  "https://www.koket.se/helgrillad-kalkon-med-senap-och-vitlok",
  "https://www.koket.se/basilikamarinerad-kalkonfile-fylld-med-mozzarella-och-soltorkade-tomater",
  "https://www.koket.se/rostad-paprikasoppa-med-kalkonbacon",
  "https://www.koket.se/pulled-kalkon-med-coleslaw-och-syrad-rodlok",
  "https://www.koket.se/grekisk-filodegspaj-med-spenat-och-agg",
  "https://www.koket.se/saltstensrimmad-lax-med-dillstuvad-potatis",
  "https://www.koket.se/stekt-och-lattrokt-rodingfile-med-varsallad",
  "https://www.koket.se/frederik-zalls-loksill",
  "https://www.koket.se/curry-och-appelsill",
  "https://www.koket.se/husfrusill",
  "https://www.koket.se/blabar-och-citroncheesecake",
  "https://www.koket.se/jordgubbssmoothie",
  "https://www.koket.se/somrig-kornsallad",
  "https://www.koket.se/toskansk-farrosoppa",
  "https://www.koket.se/kryddgrillad-entrec-te-med-potatis-och-fankalsgratang",
  "https://www.koket.se/lammytterfile-med-tomater-kramiga-mannagryn-vitlok-och-orter",
  "https://www.koket.se/musslor-med-gurka-fankal-vitt-vin-och-gradde",
  "https://www.koket.se/spaghetti-ragu-bianco",
  "https://www.koket.se/minicheesecakes-med-jordgubbar-och-lime",
  "https://www.koket.se/laxpastrami-med-saffranscouscous",
  "https://www.koket.se/kall-kokosgazpacho-med-rakor-och-mynta",
  "https://www.koket.se/lantlig-galette-med-tomat-och-getost",
  "https://www.koket.se/hemlagad-krusbarskompott-med-vispgradde",
  "https://www.koket.se/morbergs-dillkott-med-kokta-rotfrukter",
  "https://www.koket.se/gubbrora-a-la-per-morberg",
  "https://www.koket.se/melvin",
  "https://www.koket.se/saffransdoftande-fisk-och-skaldjursgryta",
  "https://www.koket.se/avokadosallad-med-lime-och-basilikadressing",
  "https://www.koket.se/jordgubbslemonad-med-rosmarin",
  "https://www.koket.se/mimosa-med-apelsin-och-blodapelsin",
  "https://www.koket.se/3-x-smoothiebowls",
  "https://www.koket.se/hallonmargarita-med-smak-av-ros",
  "https://www.koket.se/torskflakes-med-aggkram-tryffelskum-och-variation-pa-gron-sparris",
  "https://www.koket.se/gronsakspanna-med-gryn-och-ricottakram",
  "https://www.koket.se/skaldjurs-och-sparrisrisotto",
  "https://www.koket.se/skaldjursrisotto-med-blamusslor-och-saffran",
  "https://www.koket.se/kokospannkakor-med-limesyrup",
  "https://www.koket.se/klassiska-men-snabba-empanadas",
  "https://www.koket.se/ceviche-pa-pilgrimsmussla-och-avokado"
];

nightmare
  .goto('https://www.koket.se/mat/specialkost/raw-food')
  .wait(1000)
  .evaluate(function () {

  })
  .then(function (hrefs) {


    console.log("start");
    //här kan jag bygga vilken lista jag vill med hrefs...
    console.log("nr of urls: " + urls.length);
    uniqurls = [...new Set(urls)];
    console.log("uniq : " + uniqurls.length);
    //here, we're going to use the vanilla JS way of executing a series of promises in a sequence.
    //for every href in hrefs,
    return uniqurls.reduce(function (accumulator, href) {
      //return the accumulated promise results, followed by...
      return accumulator.then(function (results) {
        return nightmare.goto(href)
          //get the html
          .evaluate(function () {
            if (document.querySelector('.recipe-column-wrapper .endorsed-banner')) {
              return;
            }
            //l sep är ett problem. replace &#8232; funkar inte
            //får överväga att kanske ta bort allt inom paranteser och efter andra specialtecken (,:."") och "eller (dela i två?)" ta bort plural "er,ar,or"
            //splita på mellanslag, om första delen innehåller en siffra /\d/.test lägg det i amount
            //problemet blir vissa som har skrivit amount och unit i samma span som namnet^

            //ha koll på om denna fix gör så att namnet blir lika med existerande food, isåfall plusa på uses
            //om jag fixar detta i efterhand så måste jag köra igenom alla foods/ och alla recipes/ingredients/

            //Bygg ett jobb som rensar bort dåliga recept? alt. validerar i detta jobb
            //recept med många konstiga ingredienser (långa namn, siffror i namn, specialtecken i namn,)
            let recipe = {};
            //title
            recipe.title = document.querySelector('.recipe-content-wrapper h1').innerHTML;
            //tags
            let tags = {};
            $('.category-touch-scroll .btn.green-btn.category').each(function () {
              let t = $(this).text().split('/');
              for (let i = 0; i < t.length; i++) {
                tags[t[i].charAt(0).toUpperCase() + t[i].slice(1)] = true;
              }
            })
            recipe.tags = tags;
            //source
            recipe.source = window.location.href;
            //rating
            recipe.rating = document.querySelector('.recipe-content-wrapper .rating-container.rating').getAttribute("data-setrating");
            //votes
            recipe.votes = document.querySelector('.recipe-content-wrapper .rating-container.rating span.text').innerHTML.split(" ")[0];
            //author
            if (document.querySelector('.recipe-content-wrapper .author-chef a')) {
              recipe.author = document.querySelector('.recipe-content-wrapper .author-chef a').innerHTML;
            }
            //createdFor
            if (document.querySelector('.recipe-content-wrapper .author-source a')) {
              recipe.createdFor = document.querySelector('.recipe-content-wrapper .author-source a').innerHTML;
            }
            //portions  "4småpotioner" trattkantarellsoppan. replace alla bokstäver med ""?
            if (document.querySelector('.recipe-content-wrapper .recipe-info.portions span.amount')) {
              recipe.portions = document.querySelector('.recipe-content-wrapper .recipe-info.portions span.amount').innerHTML.replace(/(\r\n|\n|\r| )/gm, "").trim();
            }
            //created
            if (document.querySelector('.recipe-content-wrapper .description meta[itemprop="datePublished"]')) {
              recipe.created = document.querySelector('.recipe-content-wrapper .description meta[itemprop="datePublished"]').getAttribute("content");
            }
            //description
            if (document.querySelector('.recipe-content-wrapper .recipe-article .description p')) {
              recipe.description = document.querySelector('.recipe-content-wrapper .recipe-article .description p:first-child').innerHTML.replace(/(\r\n|\n|\r|<[^>]*>)/gm, "").replace(/  +/g, ' ');
            }
            //time
            if (document.querySelector('.recipe-content-wrapper .cooking-time')) {
              //koket.se använder flera olika format på tid så det är inte lätt att ta ut ett generellt värde
              recipe.time = document.querySelector('.recipe-content-wrapper .cooking-time .time').innerHTML.replace(/(\r\n|\n|\r|)/gm, "").trim();
            }
            //ingredients
            if (document.querySelector('.recipe-column-wrapper #ingredients-component')) {
              let ingredientsDom = document.querySelector('.recipe-column-wrapper #ingredients-component #ingredients').getElementsByTagName("li");
              let ingredients = [];
              for (var i = 0; i < ingredientsDom.length; ++i) {
                let ingredient = {};
                let parts = ingredientsDom[i].getElementsByTagName("span");
                let amount = parts[1].innerHTML;
                ingredient.name = parts[2].innerHTML.charAt(0).toUpperCase() + parts[2].innerHTML.slice(1).replace(/\s*\([^()]*\)$/, '').split(",")[0].replace(/([/.#$])/g,'');
                if (amount.length > 0) {
                  let amountParts = amount.split(" ");
                  ingredient.amount = amountParts[0];
                  if (amountParts.length > 1) {
                    ingredient.unit = amountParts[1];
                    if (!/\d/.test(ingredient.amount)) {
                      ingredient.amount = amountParts[1];
                      ingredient.unit = amountParts[0];
                    }
                  }
                }
                ingredients.push(ingredient);
              }
              recipe.ingredients = ingredients;
            }
            //difficulty
            let instructionsList = document.querySelector('.recipe-column-wrapper #step-by-step').getElementsByTagName("li");
            let nrOfIngredients = recipe.ingredients.length;
            let instructionLength = 0;
            for (let i = 0; i < instructionsList.length; i++) {
              instructionLength = instructionLength + instructionsList[i].getElementsByTagName("span")[0].innerHTML.replace(/(\r\n|\n|\r|)/gm, "").trim().length;
            }
            instructionLength = instructionLength - instructionsList.length * 10;

            let levelIndex = (nrOfIngredients * 8) + (instructionLength / 14);
            if (recipe.tags.hasOwnProperty('Enkelt') || recipe.tags.hasOwnProperty('Lättlagat')) {
              levelIndex = levelIndex - 100;
            }
            if (recipe.tags.hasOwnProperty('Snabbt')) {
              levelIndex = levelIndex - 20;
            }

            if (levelIndex < 100) {
              recipe.level = 1;
            } else if (levelIndex < 200) {
              recipe.level = 2;
            } else {
              recipe.level = 3;
            }

            //lägg logik för validering i inläsningen och inte här.. om vissa saker saknas så hoppa över. om urlen redan finns hoppa över..
            //automatisera denna inläsning. 
            //Alla recept som skrivs till filen ska se likadana ut oberoende av källa.
            if(recipe.ingredients.length === 0){
              return;
            }
            return recipe;
          })
          //add the result to the results
          .then(function (html) {
            results.push(html);
            return results;
          })
        // .then(function(results){
        //   //click on the search result link to go back to the search result page
        //   return nightmare
        //     .click('a[id="propertyHeading_searchResults"]')
        //     .then(function() {
        //       //make sure the results are returned
        //       return results;
        //     });
        // })
      });
    }, Promise.resolve([])) //kick off the reduce with a promise that resolves an empty array
  })
  .then(function (resultArr) {
    //if I haven't made a mistake above with the `Array.reduce`, `resultArr` should now contain all of your links' results
    console.log(resultArr.length);


    fs.writeFile("C:/react/senaste2017-10-22.json", JSON.stringify(resultArr), function (err) {

      if (err) {
        return console.log(err);
      }

      console.log("The file was saved!");
    });
  });