var Nightmare = require('nightmare');
var nightmare = Nightmare({
    openDevTools: false, show: false, webPreferences: {
        images: false,
    }
})

var fs = require('fs');


//ta fram urls genom att:
//1. skapa ett script för att gå igenom alla http://www.tasteline.com/recept/?sida=2#sok där sida ökas på. Spara ner href från varje sida till en fil
//2. paste in i urls
//3. Sätt filename enligt "TASTELINE-RECEPTSRC-DATE.json"
//4. kör node set DEBUG=nightmare && node tasteline.js
//5. kör node createRecipes.js och ange namnet på filen som skapades här


let urls = [
    "http://www.tasteline.com/recept/romantisk-glass/",
    "http://www.tasteline.com/recept/kall-gurksoppa/",
    "http://www.tasteline.com/recept/frikadeller/",
    "http://www.tasteline.com/recept/vitello-tonnato-kalv/",
    "http://www.tasteline.com/recept/lasagne-2/",
    "http://www.tasteline.com/recept/hel-kyckling/",
    "http://www.tasteline.com/recept/paella-3/",
    "http://www.tasteline.com/recept/roding/",
    "http://www.tasteline.com/recept/bagels-2/",
    "http://www.tasteline.com/recept/sej/",
    "http://www.tasteline.com/recept/smordegspinnar/",
    "http://www.tasteline.com/recept/lax-2/",
    "http://www.tasteline.com/recept/frallor-i-angugn/",
    "http://www.tasteline.com/recept/inkokta-plommon/",
    "http://www.tasteline.com/recept/rodtunga/",
    "http://www.tasteline.com/recept/creme-brule/",
    "http://www.tasteline.com/recept/var-blomkal-med-kapris-och-russin/",
    "http://www.tasteline.com/recept/flamberade-mandariner/",
    "http://www.tasteline.com/recept/inlagda-paron/",
    "http://www.tasteline.com/recept/tomater/",
    "http://www.tasteline.com/recept/kronartskockor/",
    "http://www.tasteline.com/recept/rodbetor-2/",
    "http://www.tasteline.com/recept/vietnamesisk-nudelsopppa-med-helstekt-biff/",
    "http://www.tasteline.com/recept/fiskfars/",
    "http://www.tasteline.com/recept/mandelpotatis/",
    "http://www.tasteline.com/recept/pilgrimsmusslor-2/",
    "http://www.tasteline.com/recept/jappes-farska-varrullar/",
    "http://www.tasteline.com/recept/seglingspaella/",
    "http://www.tasteline.com/recept/pasta-med-spenat-och-bacon/",
    "http://www.tasteline.com/recept/batbakad-pizza/",
    "http://www.tasteline.com/recept/alandsk-stark-korvgryta/",
    "http://www.tasteline.com/recept/britas-batbruschetta/",
    "http://www.tasteline.com/recept/tomatsoppa-med-fetaost/",
    "http://www.tasteline.com/recept/fladerblomssaft/",
    "http://www.tasteline.com/recept/knaprig-musli/",
    "http://www.tasteline.com/recept/caesarsallad-med-knackebrod/",
    "http://www.tasteline.com/recept/knackesnacks/",
    "http://www.tasteline.com/recept/frittata-med-parmaskinka/",
    "http://www.tasteline.com/recept/knackepizzor/",
    "http://www.tasteline.com/recept/kokos-och-chokladtartelett/",
    "http://www.tasteline.com/recept/tikkamarinerade-tonfiskspett-med-gurk-och-kokossallad/",
    "http://www.tasteline.com/recept/kinondoris/",
    "http://www.tasteline.com/recept/vattenmelonslush-med-lime-och-mynta/",
    "http://www.tasteline.com/recept/grillad-ananas-med-ingefara-och-mascarponekram/",
    "http://www.tasteline.com/recept/farskpotatis-i-folie/",
    "http://www.tasteline.com/recept/vargardaristarta-med-bar/",
    "http://www.tasteline.com/recept/kladdkaka-7/",
    "http://www.tasteline.com/recept/cole-slaw/",
    "http://www.tasteline.com/recept/grissinipinnar-med-oliver/",
    "http://www.tasteline.com/recept/matjessillcheesecake-med-spada-skott/",
    "http://www.tasteline.com/recept/smaken-av-svensk-sommar/",
    "http://www.tasteline.com/recept/grillad-fjordlax-med-vispat-limesmor-och-ortpotatis/",
    "http://www.tasteline.com/recept/rakcocktail-med-mango-och-lime/",
    "http://www.tasteline.com/recept/muslikakor/",
    "http://www.tasteline.com/recept/steeplertarta/",
    "http://www.tasteline.com/recept/hallonsoppa-med-sesamfras/",
    "http://www.tasteline.com/recept/appelbulgur-med-blandade-bar/",
    "http://www.tasteline.com/recept/laxspett-med-shiitake-2/",
    "http://www.tasteline.com/recept/strommings-och-zucchinispett-med-jungfrusas-2/",
    "http://www.tasteline.com/recept/oxfilespett-med-vitlok-bacon-och-tomat-2/",
    "http://www.tasteline.com/recept/tigerungemuffins/",
    "http://www.tasteline.com/recept/valnotskakor/",
    "http://www.tasteline.com/recept/fladerblomsaft/",
    "http://www.tasteline.com/recept/jordgubbsdessert-med-pinjenotter/",
    "http://www.tasteline.com/recept/vasterbottensostpaj-med-lojrom/",
    "http://www.tasteline.com/recept/roding-med-fankalssmak/",
    "http://www.tasteline.com/recept/ortgravad-stromming/",
    "http://www.tasteline.com/recept/emmatartan/",
    "http://www.tasteline.com/recept/schackrutor/",
    "http://www.tasteline.com/recept/onskedrommar/",
    "http://www.tasteline.com/recept/nottoppar/",
    "http://www.tasteline.com/recept/fladerjello/",
    "http://www.tasteline.com/recept/fladerrulltarta/",
    "http://www.tasteline.com/recept/fladerbloms-och-myntaparfait-med-jordgubbsoppa/",
    "http://www.tasteline.com/recept/fladerchampagne/",
    "http://www.tasteline.com/recept/keylime-pie-med-flader/",
    "http://www.tasteline.com/recept/oxfilespett-med-vitlok-bacon-och-tomat/",
    "http://www.tasteline.com/recept/ort-och-senapsmarinerat-lammspett-med-aubergine-och-citron/",
    "http://www.tasteline.com/recept/laxspett-med-shiitake/",
    "http://www.tasteline.com/recept/tant-margits-likorglass/",
    "http://www.tasteline.com/recept/rokt-makrill-med-rodbetstzatziki/",
    "http://www.tasteline.com/recept/lattrimmad-kolja-med-brynt-smor-och-pepparrot/",
    "http://www.tasteline.com/recept/surlax-i-burk/",
    "http://www.tasteline.com/recept/gravad-stromming-med-kramig-ort-citronsas/",
    "http://www.tasteline.com/recept/rabarbersoppa-med-jordgubbar/",
    "http://www.tasteline.com/recept/gazpacho-4/",
    "http://www.tasteline.com/recept/angamat-2/",
    "http://www.tasteline.com/recept/rucolasoppa-med-getost/",
    "http://www.tasteline.com/recept/meatfeast/",
    "http://www.tasteline.com/recept/matjeswrap/",
    "http://www.tasteline.com/recept/kalkontrianglar/",
    "http://www.tasteline.com/recept/briebaguette-2/",
    "http://www.tasteline.com/recept/sega-chokladmuffins-varldens-godaste/",
    "http://www.tasteline.com/recept/ceviche-pa-pilgrimsmusslor/",
    "http://www.tasteline.com/recept/blinier-med-sting/",
    "http://www.tasteline.com/recept/asiatisk-quinoasallad-med-soyabonor/",
    "http://www.tasteline.com/recept/tabbouleh-med-mynta-aubergine-och-tomater/",
    "http://www.tasteline.com/recept/svenskt-dinkelris-med-skansk-senap-och-apple/",
    "http://www.tasteline.com/recept/ragbrod-med-rokta-rakor-i-farskost/",
    "http://www.tasteline.com/recept/rostad-blomkalssoppa/",
    "http://www.tasteline.com/recept/pytt-med-svenska-smaker/",
    "http://www.tasteline.com/recept/primorsallad-med-sparris-morotter-och-sockerartor/",
    "http://www.tasteline.com/recept/pannkakstarta-4/",
    "http://www.tasteline.com/recept/kanelbullar-4/",
    "http://www.tasteline.com/recept/basta-fladersaften/",
    "http://www.tasteline.com/recept/paj-med-prastost-vanernlojrom-och-lantagg/",
    "http://www.tasteline.com/recept/paj-med-currylok-och-heta-farsbullar/",
    "http://www.tasteline.com/recept/ljummen-sockersaltad-lax-med-cocktailtomater-och-orter-i-vanilj-och-vitt-vin/",
    "http://www.tasteline.com/recept/saftig-barkaka/",
    "http://www.tasteline.com/recept/laxburgare-med-couscous/",
    "http://www.tasteline.com/recept/lax-i-lergryta-med-bonor-salvia-och-majs/",
    "http://www.tasteline.com/recept/nutella-och-bananmacka/",
    "http://www.tasteline.com/recept/vegetarianens-medelhavsdrom/",
    "http://www.tasteline.com/recept/lyxmacka-meatfeast/",
    "http://www.tasteline.com/recept/kikarts-och-rotfruktscurry-med-cashewnotter/",
    "http://www.tasteline.com/recept/italiensk-nakenhavre-med-parmesan-och-basilika/",
    "http://www.tasteline.com/recept/iskall-gazpacho/",
    "http://www.tasteline.com/recept/grillad-ingefarskyckling-med-limesvangda-primorer/",
    "http://www.tasteline.com/recept/grillade-pilgrimsmusslor-och-ananas-smaksatt-med-koriander-och-sesamfron/",
    "http://www.tasteline.com/recept/grillad-lammrygg-med-sallad-pa-sotpotatis-smaksatt-med-apelsin/",
    "http://www.tasteline.com/recept/grillad-chorizo-med-gronsaker/",
    "http://www.tasteline.com/recept/getost-med-honung-och-mangosallad/",
    "http://www.tasteline.com/recept/frisk-rodbetssallad/",
    "http://www.tasteline.com/recept/fladergravad-lax/",
    "http://www.tasteline.com/recept/varma-empanadas-med-getost-och-chorizo/",
    "http://www.tasteline.com/recept/zlatans-favoritpyttipanna/",
    "http://www.tasteline.com/recept/lyxig-potatissallad/",
    "http://www.tasteline.com/recept/potatisbullar-3/",
    "http://www.tasteline.com/recept/skinka-farskostfyllda-champinjoner/",
    "http://www.tasteline.com/recept/christers-jordgubbstarta/",
    "http://www.tasteline.com/recept/inkokt-lax-med-skarpsas/",
    "http://www.tasteline.com/recept/toast-skagen-3/",
    "http://www.tasteline.com/recept/lax-pa-norska/",
    "http://www.tasteline.com/recept/picklade-gronsaker-3/",
    "http://www.tasteline.com/recept/vitloksmarinerade-lammracks-med-citron-och-mynta-2/",
    "http://www.tasteline.com/recept/kryddgrillad-snabbrimmad-lax-2/",
    "http://www.tasteline.com/recept/pannbiffar/",
    "http://www.tasteline.com/recept/potatisbullar-2/",
    "http://www.tasteline.com/recept/stekt-kalvlever/",
    "http://www.tasteline.com/recept/grodans-clubsandwich/",
    "http://www.tasteline.com/recept/fylld-sommarmelon-med-likormarinerade-bar/",
    "http://www.tasteline.com/recept/fyra-i-rad-kaka/",
    "http://www.tasteline.com/recept/picklade-gronsaker-2/",
    "http://www.tasteline.com/recept/vitloksmarinerade-lammracks-med-citron-och-mynta/",
    "http://www.tasteline.com/recept/kryddgrillad-snabbrimmad-lax/",
    "http://www.tasteline.com/recept/helgrillad-flaskkarre-rub-och-glaze-med-aprikos/",
    "http://www.tasteline.com/recept/mangokavaljer/",
    "http://www.tasteline.com/recept/chokladmoussetarta-med-banan/",
    "http://www.tasteline.com/recept/rabarbermoussetarta/",
    "http://www.tasteline.com/recept/kryddiga-kottbullar-med-pastagratang/",
    "http://www.tasteline.com/recept/kycklingkorv-med-energibulgur/",
    "http://www.tasteline.com/recept/ingefarswokade-gronsaker-med-marinerad-biff/",
    "http://www.tasteline.com/recept/gnocchi-med-paprikasas-och-lammfarsbiffar/",
    "http://www.tasteline.com/recept/pasta-med-tomatsas-2/",
    "http://www.tasteline.com/recept/att-gora-egen-pasta/",
    "http://www.tasteline.com/recept/vinkokt-hoki-med-aioli-och-sparris/",
    "http://www.tasteline.com/recept/havskattfile-i-folie-med-gron-sas-och-vitkalssallad/",
    "http://www.tasteline.com/recept/rotsaksgratang-med-mustig-kottgryta/",
    "http://www.tasteline.com/recept/laxburgare-med-limedressing-och-sallad/",
    "http://www.tasteline.com/recept/ankbrost-med-appelsky-och-fondantpotatis/",
    "http://www.tasteline.com/recept/paprikafylld-spatta-med-korianderolja-och-linssallad/",
    "http://www.tasteline.com/recept/halleflundra-med-pestotacke-och-bonsallad/",
    "http://www.tasteline.com/recept/rodbetssoppa-med-ortig-ostkram/",
    "http://www.tasteline.com/recept/miniostpaj-med-pinjenotter-och-ugnsbakade-cocktailtomater/",
    "http://www.tasteline.com/recept/rastekta-potatisplattar-med-lojrom/",
    "http://www.tasteline.com/recept/bonsoppa-med-rostad-paprika/",
    "http://www.tasteline.com/recept/gazpacho-med-ostpinnar/",
    "http://www.tasteline.com/recept/halstrade-pilgrimsmusslor-med-dillolja-pa-salladsbadd/",
    "http://www.tasteline.com/recept/jordartskockssoppa-med-citronrakor/",
    "http://www.tasteline.com/recept/zucchini-och-fetaostpudding-med-salami-och-parmaskinka/",
    "http://www.tasteline.com/recept/sotpotatissoppa-med-kryddig-korv/",
    "http://www.tasteline.com/recept/gron-artsoppa-med-riven-pepparrot-och-brodtarningar/",
    "http://www.tasteline.com/recept/broccolisoppa-med-pumpafron/",
    "http://www.tasteline.com/recept/pannkaka-med-bar-och-vaniljkram/",
    "http://www.tasteline.com/recept/apelsinsoppa-med-exotiska-frukter/",
    "http://www.tasteline.com/recept/gino-frukt-gratinerad-med-vit-choklad/",
    "http://www.tasteline.com/recept/cheesecake-med-frukt/",
    "http://www.tasteline.com/recept/marangtarta-med-gradde-och-frukt/",
    "http://www.tasteline.com/recept/citronfluff-med-apelsinklyftor-och-mandelfras/",
    "http://www.tasteline.com/recept/jordgubbs-och-yoghurtglass-med-myntasocker/",
    "http://www.tasteline.com/recept/vit-chokladmousse-med-apelsinsallad/",
    "http://www.tasteline.com/recept/chokladparfait-med-bar-och-notter/",
    "http://www.tasteline.com/recept/chokladmousse-med-kardemumma/",
    "http://www.tasteline.com/recept/chokladmuffins-med-chokladbitar/",
    "http://www.tasteline.com/recept/mandeltarta-med-smorkram-och-rostad-mandel/",
    "http://www.tasteline.com/recept/chokladtarta-med-gradde-och-riven-choklad/",
    "http://www.tasteline.com/recept/morotskaka-med-glasyr/",
    "http://www.tasteline.com/recept/parontartelett-med-ingefarsglasyr/",
    "http://www.tasteline.com/recept/appelkaka-med-sott-nottacke/",
    "http://www.tasteline.com/recept/smoothie-med-banan-och-blabar/",
    "http://www.tasteline.com/recept/appelsoppa-med-mandelskorpa/",
    "http://www.tasteline.com/recept/vattenmelon-och-jordgubbssoppa/",
    "http://www.tasteline.com/recept/olivrora/",
    "http://www.tasteline.com/recept/avokadorora-4/",
    "http://www.tasteline.com/recept/soltorkade-tomater-och-kesella/",
    "http://www.tasteline.com/recept/hummus-8/",
    "http://www.tasteline.com/recept/sockerkaka-med-citron-och-vallmofron/",
    "http://www.tasteline.com/recept/rulltarta-med-smorkram/",
    "http://www.tasteline.com/recept/vaniljbullar-3/",
    "http://www.tasteline.com/recept/hamburgerbrod-3/",
    "http://www.tasteline.com/recept/skallade-limpor/",
    "http://www.tasteline.com/recept/valnotsbrod-7/",
    "http://www.tasteline.com/recept/grissini/",
    "http://www.tasteline.com/recept/lantbrod/",
    "http://www.tasteline.com/recept/fullkornsbaguetter-med-oliver-tomater-och-basilika/",
    "http://www.tasteline.com/recept/sega-baguetter/",
    "http://www.tasteline.com/recept/focaccia-2/",
    "http://www.tasteline.com/recept/rivig-appelkaka-2/",
    "http://www.tasteline.com/recept/rabarberkompott/",
    "http://www.tasteline.com/recept/pavlova-4/",
    "http://www.tasteline.com/recept/rabarbermarinerade-spjall-med-nudelsallad/",
    "http://www.tasteline.com/recept/rabarbersylt-med-kardemumma/",
    "http://www.tasteline.com/recept/valfangare/",
    "http://www.tasteline.com/recept/frukostgrot-2-2/",
    "http://www.tasteline.com/recept/frukostgrot-2/",
    "http://www.tasteline.com/recept/laxpytt-med-romsas/",
    "http://www.tasteline.com/recept/dumplings/",
    "http://www.tasteline.com/recept/tekokade-agg/",
    "http://www.tasteline.com/recept/cous-cous-sallad/",
    "http://www.tasteline.com/recept/thaibiffar/",
    "http://www.tasteline.com/recept/varldens-snabbaste-kladdkaka/",
    "http://www.tasteline.com/recept/helstekt-ryggbiff-med-krispig-potatissallad/",
    "http://www.tasteline.com/recept/melonmums/",
    "http://www.tasteline.com/recept/artig-dipp/",
    "http://www.tasteline.com/recept/te-som-i-kashmir-2/",
    "http://www.tasteline.com/recept/kycklinggryta-serverad-med-matkorn/",
    "http://www.tasteline.com/recept/frittata-med-matkorn/",
    "http://www.tasteline.com/recept/kottgryta-med-matkorn/",
    "http://www.tasteline.com/recept/kottfarsrora-med-matkorn-och-senap-i-wrap/",
    "http://www.tasteline.com/recept/asiatisk-fisksoppa-med-matkorn/",
    "http://www.tasteline.com/recept/svampsoppa-med-matkorn/",
    "http://www.tasteline.com/recept/tisdagssoppa-med-rotfrukter/",
    "http://www.tasteline.com/recept/sufflerade-matkornsplattar-med-bjornbar/",
    "http://www.tasteline.com/recept/matkornsrolls-med-het-mangosalsa/",
    "http://www.tasteline.com/recept/ljummen-matkornssallad-grillade-kycklingkorvspett-och-kikartsrora/",
    "http://www.tasteline.com/recept/rabarber-och-jordgubbscobbler/",
    "http://www.tasteline.com/recept/varkyckling-i-gryta-med-ortaioli/",
    "http://www.tasteline.com/recept/raksallad-med-avokadorelish/",
    "http://www.tasteline.com/recept/pastasallad-med-artpesto/",
    "http://www.tasteline.com/recept/fusilli-med-lax-och-pepparrot/",
    "http://www.tasteline.com/recept/chokladglaserad-chokladkaka-med-knackebrod/",
    "http://www.tasteline.com/recept/lax-med-krispigt-orttacke/",
    "http://www.tasteline.com/recept/frasiga-krabbkakor-med-currymajonnas/",
    "http://www.tasteline.com/recept/bondomelett-med-lasagnette-och-mozzarella/",
    "http://www.tasteline.com/recept/fusilli-med-svamp-och-skinka/",
    "http://www.tasteline.com/recept/marinerad-pasta-med-halstrade-rakor/",
    "http://www.tasteline.com/recept/dinkelpastasallad-med-fetaost-oliver-och-lufttorkad-skinka/",
    "http://www.tasteline.com/recept/het-morotssoppa-med-fullkornspasta/",
    "http://www.tasteline.com/recept/tagliatelle-med-marinerad-kycklingfile-och-sesamfron/",
    "http://www.tasteline.com/recept/ljummen-sallad-med-cotelli-bonor-och-korv/",
    "http://www.tasteline.com/recept/passionsfruktssmoothie-med-ingefara-och-lime/",
    "http://www.tasteline.com/recept/jordgubbar-och-bjornbar-med-citronkram-i-krispigt-pajskal/",
    "http://www.tasteline.com/recept/kycklingar-i-ugn-med-quinoa-och-kornsallad/",
    "http://www.tasteline.com/recept/angade-skaldjur-med-aioli/",
    "http://www.tasteline.com/recept/malvapudding/",
    "http://www.tasteline.com/recept/african-passion/",
    "http://www.tasteline.com/recept/samosas-med-gronsaker/",
    "http://www.tasteline.com/recept/god-tortellinigratang/",
    "http://www.tasteline.com/recept/piggelinjuice-med-ingefara/",
    "http://www.tasteline.com/recept/snabb-blabarsglass/",
    "http://www.tasteline.com/recept/supersallad/",
    "http://www.tasteline.com/recept/avokadosoppa-med-sting/",
    "http://www.tasteline.com/recept/linnea/",
    "http://www.tasteline.com/recept/cafferinha/",
    "http://www.tasteline.com/recept/makaronpudding-med-gronsaker/",
    "http://www.tasteline.com/recept/pasta-med-gronsaker-rotfrukter-och-kryddig-korv/",
    "http://www.tasteline.com/recept/pastasas-med-sting/",
    "http://www.tasteline.com/recept/kladdig-chokladfrestelse-med-smak-av-apelsin/",
    "http://www.tasteline.com/recept/sarah-bernhardt-biskvier/",
    "http://www.tasteline.com/recept/tinas-brownie/",
    "http://www.tasteline.com/recept/satay-med-frasch-jordnotssas/",
    "http://www.tasteline.com/recept/stefans-sesam-kammusslor/",
    "http://www.tasteline.com/recept/ugnsgrillade-sparris/",
    "http://www.tasteline.com/recept/lakrits-gt/",
    "http://www.tasteline.com/recept/chocolate-chip-cookie/",
    "http://www.tasteline.com/recept/rodgron-pastasallad/",
    "http://www.tasteline.com/recept/svarta-bonor-i-tomatsas-med-parmesan/",
    "http://www.tasteline.com/recept/lammfarsbiffar-med-myntasas/",
    "http://www.tasteline.com/recept/enkel-men-god-rattatuille/",
    "http://www.tasteline.com/recept/svart-bonrora/",
    "http://www.tasteline.com/recept/spanskt-plock-tapas/",
    "http://www.tasteline.com/recept/keylime-pie/",
    "http://www.tasteline.com/recept/chilistuvad-majs/",
    "http://www.tasteline.com/recept/akta-chiligryta/",
    "http://www.tasteline.com/recept/mexikansk-flaskfilegryta-i-ugn/",
    "http://www.tasteline.com/recept/gi-mojito-royale/",
    "http://www.tasteline.com/recept/zero-passion/",
    "http://www.tasteline.com/recept/gi-cosmo/",
    "http://www.tasteline.com/recept/gi-caiprinoska/",
    "http://www.tasteline.com/recept/laxsandwich-med-senapsfarskost/",
    "http://www.tasteline.com/recept/pask-pascha-paskefterratt/",
    "http://www.tasteline.com/recept/majsbrod-4/",
    "http://www.tasteline.com/recept/cassata/",
    "http://www.tasteline.com/recept/hemgjord-sojamjolk-och-tofu/",
    "http://www.tasteline.com/recept/ajvar-bulgur-med-halstrad-torsk-och-senapssas/",
    "http://www.tasteline.com/recept/rod-quinoafylld-kalkonfile/",
    "http://www.tasteline.com/recept/paella-pa-grovsiktad-couscous/",
    "http://www.tasteline.com/recept/filodegsrulle-med-hel-bulgur-och-kycklingfile/",
    "http://www.tasteline.com/recept/quinoa-fullkornscouscous-med-svamp-och-fetaost/",
    "http://www.tasteline.com/recept/revben-med-stark-ajvar-relish-och-grovsiktad-couscoussallad/",
    "http://www.tasteline.com/recept/fullkornsbulgurkaka-med-rotfrukter/",
    "http://www.tasteline.com/recept/bulgurotto-med-grillad-lax/",
    "http://www.tasteline.com/recept/kokos-couscous-med-ugnsbakad-korv-eller-flaskfile/",
    "http://www.tasteline.com/recept/grynberg-med-lax-och-avokado/",
    "http://www.tasteline.com/recept/mjuk-mandelkaka-med-couscous/",
    "http://www.tasteline.com/recept/varm-bulgursallad-med-kantareller-och-rostade-kikartor/",
    "http://www.tasteline.com/recept/varm-bulgursallad-med-kryddstark-korv/",
    "http://www.tasteline.com/recept/mustig-hostsoppa-med-fullkornsbulgur/",
    "http://www.tasteline.com/recept/varm-hostwrap-med-fullkornscouscous/",
    "http://www.tasteline.com/recept/sommarsallad-2/",
    "http://www.tasteline.com/recept/latt-paj-med-fullkornscoucous/",
    "http://www.tasteline.com/recept/fullkornscouscous-med-rodbetor-och-chorizo/",
    "http://www.tasteline.com/recept/gnocchi-med-pesto-och-inlagda-kronartskockor/",
    "http://www.tasteline.com/recept/olivoljepotatis-med-pepparstekt-flaskkarre/",
    "http://www.tasteline.com/recept/blomkalspure-med-hasselnotssmor-och-varmrokt-lax/",
    "http://www.tasteline.com/recept/aggsallad-med-sparris-och-rakor/",
    "http://www.tasteline.com/recept/ingefarsvafflor-med-varma-applen/",
    "http://www.tasteline.com/recept/frasiga-chokladvafflor-med-kokosglass/",
    "http://www.tasteline.com/recept/spenatvafflor-med-knaperstekt-bacon-och-avokadodipp/",
    "http://www.tasteline.com/recept/ortvafflor-med-farskostkram/",
    "http://www.tasteline.com/recept/suffle-pa-rabarber-och-vaniljsas/",
    "http://www.tasteline.com/recept/frasig-sparris-och-potatispaj/",
    "http://www.tasteline.com/recept/farsk-tagliatelle-med-broccoli-och-ostsas/",
    "http://www.tasteline.com/recept/omelettstrimlor-med-bresaola-krispig-fankal-och-varsallad/",
    "http://www.tasteline.com/recept/wraps-med-grillad-lamkebab-och-kryddig-sallad/",
    "http://www.tasteline.com/recept/paskprinsesstarta/",
    "http://www.tasteline.com/recept/fyllda-agg-med-kapris-och-citron/",
    "http://www.tasteline.com/recept/snabbgravad-stekt-lax-pa-spenatbadd/",
    "http://www.tasteline.com/recept/marys-ansjovisrulle/",
    "http://www.tasteline.com/recept/varldens-godaste-chokladmuffins/",
    "http://www.tasteline.com/recept/halstrad-roding-med-rostad-mandelpotatis-romcreme-och-citronmarinerad-salladslok/",
    "http://www.tasteline.com/recept/gaddqueneller-med-vildris/",
    "http://www.tasteline.com/recept/rokt-sik-med-sauce-verte-och-potatissallad-med-hasselnot-och-salladslok/",
    "http://www.tasteline.com/recept/stekt-makrill-med-graddkokt-spenat-och-agghalvor/",
    "http://www.tasteline.com/recept/karleksmums-6/",
    "http://www.tasteline.com/recept/toscakaka-6/",
    "http://www.tasteline.com/recept/tigerkaksbrownie/",
    "http://www.tasteline.com/recept/svensk-tigerkaka/",
    "http://www.tasteline.com/recept/randig-cirkuskaka/",
    "http://www.tasteline.com/recept/ugnsbakad-kyckling-med-soja-och-chutney/",
    "http://www.tasteline.com/recept/kycklingbollar-med-citron-och-salvia/",
    "http://www.tasteline.com/recept/het-kycklingfarssallad-med-lime-och-koriander/",
    "http://www.tasteline.com/recept/asiatisk-barbecuekyckling/",
    "http://www.tasteline.com/recept/cupcakes-med-nougat-och-citron/",
    "http://www.tasteline.com/recept/kycklingrullader-med-dragonyoghurt-och-aprikoscouscous/",
    "http://www.tasteline.com/recept/chocolate-fudge/",
    "http://www.tasteline.com/recept/lattgravad-ugnsbakad-lax-med-fankalsremoulad/",
    "http://www.tasteline.com/recept/piripirigratinerde-rakor-med-ort-och-vitloksbrod/",
    "http://www.tasteline.com/recept/dinkelknackebrod/",
    "http://www.tasteline.com/recept/saffranssill-med-lokrora/",
    "http://www.tasteline.com/recept/sallad-med-marinerad-fetaost-och-crostini-med-morotshummus/",
    "http://www.tasteline.com/recept/chokladsuffle-4/",
    "http://www.tasteline.com/recept/zabaione-med-rod-frukt/",
    "http://www.tasteline.com/recept/smoothie-bananblabar-smoothie/",
    "http://www.tasteline.com/recept/chokladmoussetarta-3/",
    "http://www.tasteline.com/recept/fortune-cookies-onskekaka/",
    "http://www.tasteline.com/recept/pannkakstarta-med-blabar/",
    "http://www.tasteline.com/recept/ugnsbakade-cocktailtomater/",
    "http://www.tasteline.com/recept/fattiga-riddare-med-citrussallad/",
    "http://www.tasteline.com/recept/perfekt-aggrora-med-rokt-lax/",
    "http://www.tasteline.com/recept/lyxmusli/",
    "http://www.tasteline.com/recept/trillingnotsbrownie/",
    "http://www.tasteline.com/recept/korianderalskarens-musselsoppa/",
    "http://www.tasteline.com/recept/potatis-och-getostminipizza/",
    "http://www.tasteline.com/recept/midsommartarta-luuv-it/",
    "http://www.tasteline.com/recept/kycklingenchilada/",
    "http://www.tasteline.com/recept/moo-thad-kratiem-prick-tai-stir-fried-grisfillet-med-peppar-och-vitlok/",
    "http://www.tasteline.com/recept/kopparriga-karringens-tofu-ma-po-doufu/",
    "http://www.tasteline.com/recept/chilikyckling-fran-chongqing-chongqing/",
    "http://www.tasteline.com/recept/drakkallans-rakor-longjing-xiaren/",
    "http://www.tasteline.com/recept/revbensspjall-i-zhenjiangvinager-zhenjiang-paigu/",
    "http://www.tasteline.com/recept/bangbangkyckling-bangbang-jisi/",
    "http://www.tasteline.com/recept/jordnotsbars-med-mangomilkshake/",
    "http://www.tasteline.com/recept/fruktsallad-med-apelsin-och-knaprig-musli/",
    "http://www.tasteline.com/recept/matildas-kycklingsallad-med-avokado-mozzarella-och-ortdressing/",
    "http://www.tasteline.com/recept/sticky-toffee-pudding-2/",
    "http://www.tasteline.com/recept/chokladkronor/",
    "http://www.tasteline.com/recept/chef-pauls-kottfarslimpa/",
    "http://www.tasteline.com/recept/thaicurry-med-skinkspett-och-wokade-gronsaker/",
    "http://www.tasteline.com/recept/chef-paul-prudhommes-kottfarssas/",
    "http://www.tasteline.com/recept/enkel-fiskgryta-med-sej-lime-och-coctailtomater/",
    "http://www.tasteline.com/recept/borek/",
    "http://www.tasteline.com/recept/salata/",
    "http://www.tasteline.com/recept/vaffelmackor-med-pesto-ost-och-skinka/",
    "http://www.tasteline.com/recept/tunnbrodsrullar-med-potatis-surkal-och-lammkorv/",
    "http://www.tasteline.com/recept/argentinska-empanadas/",
    "http://www.tasteline.com/recept/american-pancakes/",
    "http://www.tasteline.com/recept/nerimans-fyllda-squash/",
    "http://www.tasteline.com/recept/aggcurry-fran-goa-baida-vindalu/",
    "http://www.tasteline.com/recept/7-up-salad/",
    "http://www.tasteline.com/recept/godaste-kolakakorna/",
    "http://www.tasteline.com/recept/ingefara-och-mjolk-som-krockar-jiang-zhuang-nai/",
    "http://www.tasteline.com/recept/tofu-i-spenat-bocai-doufu/",
    "http://www.tasteline.com/recept/varrullar-chunjuan/",
    "http://www.tasteline.com/recept/quorn-oriental/",
    "http://www.tasteline.com/recept/baka-semlor-med-drottningfyllning/",
    "http://www.tasteline.com/recept/tomat-och-kokosoppa/",
    "http://www.tasteline.com/recept/chocolate-chip-cookies-3/",
    "http://www.tasteline.com/recept/efterratt-finsk-ostbrod-brodostmed-hjortronsylt-och-gradde/",
    "http://www.tasteline.com/recept/sotsur-flaskfile-tangcu-liji/",
    "http://www.tasteline.com/recept/stekt-ris-shijin-chaofan/",
    "http://www.tasteline.com/recept/ma-la-kyckling-ma-la-ziji/",
    "http://www.tasteline.com/recept/skinkstek-med-rostade-rodbetor-rotfruktspure-och-ingefarssky/",
    "http://www.tasteline.com/recept/underbart-kramig-och-smakrik-medelhavsgratang/",
    "http://www.tasteline.com/recept/lammfile-med-rodbetsbulgur-och-getost/",
    "http://www.tasteline.com/recept/ullas-citronmarmelad/",
    "http://www.tasteline.com/recept/citronkaka/",
    "http://www.tasteline.com/recept/apelsinfromage/",
    "http://www.tasteline.com/recept/kycklingsymfoni/",
    "http://www.tasteline.com/recept/matig-kraftsoppa/",
    "http://www.tasteline.com/recept/minisemlor-2/",
    "http://www.tasteline.com/recept/chokladkyss-som-shot-eller-mousse/",
    "http://www.tasteline.com/recept/lammracks-med-rodvinsbraserade-puylinser/",
    "http://www.tasteline.com/recept/korv-rotfrukter-och-squash-pa-plat/",
    "http://www.tasteline.com/recept/basta-burgaren/",
    "http://www.tasteline.com/recept/enkla-fisksoppan/",
    "http://www.tasteline.com/recept/chipotle-beef-chili-med-limekram/",
    "http://www.tasteline.com/recept/het-vinterfrukt/",
    "http://www.tasteline.com/recept/focaccia-4/",
    "http://www.tasteline.com/recept/philadelphia-choklad-virvel-cheesecake/",
    "http://www.tasteline.com/recept/gronsakschips/",
    "http://www.tasteline.com/recept/sill-i-kapprock-rysk-delikatess/",
    "http://www.tasteline.com/recept/pasta-med-pesto-och-tonfisk/",
    "http://www.tasteline.com/recept/microknack/",
    "http://www.tasteline.com/recept/balsamicofile-med-tryffelkantareller-2/",
    "http://www.tasteline.com/recept/grovt-brod-med-havre-no-hands/",
    "http://www.tasteline.com/recept/mustig-fruktjuice/",
    "http://www.tasteline.com/recept/blabarsfromage/",
    "http://www.tasteline.com/recept/aioli-5/",
    "http://www.tasteline.com/recept/kokt-kyckling-med-purjolok-och-aioli/",
    "http://www.tasteline.com/recept/marinerade-rotsaker-och-musslor-kokta-i-appelcider/",
    "http://www.tasteline.com/recept/fruktsallad-i-glas/",
    "http://www.tasteline.com/recept/fetaostkyckling-med-rucola/",
    "http://www.tasteline.com/recept/lax-och-basilikaplattar-med-god-spenatsas/",
    "http://www.tasteline.com/recept/banan-kokossmoothie/",
    "http://www.tasteline.com/recept/skinka-satay/",
    "http://www.tasteline.com/recept/thailandska-fiskkakor-med-limedip/",
    "http://www.tasteline.com/recept/oxkinder-med-gremolata/",
    "http://www.tasteline.com/recept/oxfile-marinerad/",
    "http://www.tasteline.com/recept/jul-gammelmormors-kottbullar/",
    "http://www.tasteline.com/recept/hallonglasstarta/",
    "http://www.tasteline.com/recept/lammytterfile-med-getostgratang/",
    "http://www.tasteline.com/recept/mandelpotatismos-med-lojrom/",
    "http://www.tasteline.com/recept/ljummen-hummerhalva/",
    "http://www.tasteline.com/recept/jul-ljusa-julpepparkakor/",
    "http://www.tasteline.com/recept/the-mumminators-ultimate-untraditional-mumma/",
    "http://www.tasteline.com/recept/jul-sotpotatislada/",
    "http://www.tasteline.com/recept/creme-brulee-med-mango-och-appelsalsa/",
    "http://www.tasteline.com/recept/parmesanoverbakad-kyckling/",
    "http://www.tasteline.com/recept/flaskfile-med-ramslok-rotfruktspytt-och-granatapple/",
    "http://www.tasteline.com/recept/suovascarpaccio-med-lingonchutney/",
    "http://www.tasteline.com/recept/lakritsmaranger/",
    "http://www.tasteline.com/recept/lakritspannacotta-2/",
    "http://www.tasteline.com/recept/snabbpicklad-rodkal/",
    "http://www.tasteline.com/recept/kryddiga-clementiner/",
    "http://www.tasteline.com/recept/pumpa-och-morotsgryta-med-juliga-kryddor/",
    "http://www.tasteline.com/recept/gronkalsallad-med-frukttoast/",
    "http://www.tasteline.com/recept/kaneldoftande-apelsindryck/",
    "http://www.tasteline.com/recept/ingefarspepparkaka/",
    "http://www.tasteline.com/recept/lakrits-och-hallonkaka/",
    "http://www.tasteline.com/recept/magnus-franska-kola/",
    "http://www.tasteline.com/recept/apelsinsallad-med-fikon/",
    "http://www.tasteline.com/recept/favoritkottbullarna/",
    "http://www.tasteline.com/recept/langkokta-arter/",
    "http://www.tasteline.com/recept/rodbetssallad-3/",
    "http://www.tasteline.com/recept/chili-och-limesill/",
    "http://www.tasteline.com/recept/3-korvspanna-med-rotsaksrosti/",
    "http://www.tasteline.com/recept/supergod-pekingsoppa/",
    "http://www.tasteline.com/recept/jul-teskedskakor/",
    "http://www.tasteline.com/recept/citrus-stjarnanis-och-ingefarsgravad-lax/",
    "http://www.tasteline.com/recept/pannacotta-med-hjortrongele/",
    "http://www.tasteline.com/recept/lussebullar-med-fullkorn/",
    "http://www.tasteline.com/recept/amarula-springbock-coffee/",
    "http://www.tasteline.com/recept/amarula-southern-cream/",
    "http://www.tasteline.com/recept/tacogratang-med-quornfars/",
    "http://www.tasteline.com/recept/jul-min-basta-dadelkaka/",
    "http://www.tasteline.com/recept/vit-chokladmousse-med-hallon-2/",
    "http://www.tasteline.com/recept/helstekt-oxfile-med-svampsky-och-italiensk-potatispure/",
    "http://www.tasteline.com/recept/ostron-med-bloody-mary-vinagrett/",
    "http://www.tasteline.com/recept/flaskfilegryta-med-adelostsas/",
    "http://www.tasteline.com/recept/britmaris-engelska-pepparkakor/",
    "http://www.tasteline.com/recept/pepparkaksdeg-for-den-byggnadsglade/",
    "http://www.tasteline.com/recept/mintkysscupcakes/",
    "http://www.tasteline.com/recept/citrus-och-saffranspraliner/",
    "http://www.tasteline.com/recept/pepparkaksdrommar/",
    "http://www.tasteline.com/recept/brantevikssill-3/",
    "http://www.tasteline.com/recept/kottbullar-med-kanel-och-apelsin/",
    "http://www.tasteline.com/recept/agg-med-laxrora/",
    "http://www.tasteline.com/recept/mini-jansson-med-gravad-lax/",
    "http://www.tasteline.com/recept/gronkalssoppa-med-cheddartoast/",
    "http://www.tasteline.com/recept/julknackebrod/",
    "http://www.tasteline.com/recept/dill-och-vitlokssill/",
    "http://www.tasteline.com/recept/russinmuffins/",
    "http://www.tasteline.com/recept/sharonklyftor-med-kallrokt-skinka/",
    "http://www.tasteline.com/recept/saffransmazariner-2/",
    "http://www.tasteline.com/recept/vasterbottenpaj-med-sikrom/",
    "http://www.tasteline.com/recept/peppriga-kottfars-leverbiffar/",
    "http://www.tasteline.com/recept/coq-au-vin-3/",
    "http://www.tasteline.com/recept/rodvinsbraserad-lammrygg-med-tva-sorters-bonor/",
    "http://www.tasteline.com/recept/marmelad-sguash-och-appelmarmelad/",
    "http://www.tasteline.com/recept/marmelad-fikonmarmelad/",
    "http://www.tasteline.com/recept/ugnsstekt-flasklagg-med-surkal/",
    "http://www.tasteline.com/recept/rimmad-oxbringa-med-rotfrukter-och-pepparrotssas/",
    "http://www.tasteline.com/recept/apelsinlackat-sidflask-med-hasselnotsrosti-och-rodkalssallad/",
    "http://www.tasteline.com/recept/roding-med-gronkal-och-appel-och-kapriskram/",
    "http://www.tasteline.com/recept/flaskkorv-med-stuvad-brysselkal/",
    "http://www.tasteline.com/recept/kumminjarpar-med-kryddost-och-purjolok/",
    "http://www.tasteline.com/recept/grekisk-pytt-i-langpanna/",
    "http://www.tasteline.com/recept/valnotsscones-med-lax-och-pepparrotsost/",
    "http://www.tasteline.com/recept/lacker-smorgastarta-8-bitar/",
    "http://www.tasteline.com/recept/friterad-mars-bar/",
    "http://www.tasteline.com/recept/saffranssockerkaka-med-applen/",
    "http://www.tasteline.com/recept/leverpastej-med-konjak-och-katrinplommon/",
    "http://www.tasteline.com/recept/handgjorda-klubbor/",
    "http://www.tasteline.com/recept/superenkla-nougatnotter/",
    "http://www.tasteline.com/recept/hallon-och-lakritskola/",
    "http://www.tasteline.com/recept/victors-brod-no-hands/",
    "http://www.tasteline.com/recept/vasterbottenssmor/",
    "http://www.tasteline.com/recept/lammgryta-med-vita-bonor-och-sugar-snap-peas/",
    "http://www.tasteline.com/recept/boeuf-bourguignon-3/",
    "http://www.tasteline.com/recept/leilas-chokladkaka/",
    "http://www.tasteline.com/recept/nigiri-sushi-ris/",
    "http://www.tasteline.com/recept/ananaspaj-7/",
    "http://www.tasteline.com/recept/tonfiskrora-3/",
    "http://www.tasteline.com/recept/kycklinggryta-med-bonor/",
    "http://www.tasteline.com/recept/tacougnsomelett/",
    "http://www.tasteline.com/recept/paltbrod/",
    "http://www.tasteline.com/recept/sticky-rice-med-mango/",
    "http://www.tasteline.com/recept/kardemummakaka-2/",
    "http://www.tasteline.com/recept/polsa/",
    "http://www.tasteline.com/recept/apelsindessert-med-doft-av-kanel-och-pepparmynta/",
    "http://www.tasteline.com/recept/fruktfylld-kyckling-i-lergryta/",
    "http://www.tasteline.com/recept/kyckling-hyderabad-indisk-kyckling-med-mint-och-koriander/",
    "http://www.tasteline.com/recept/palak-paneer-indisk-spenatcurry-med-ostmassa/",
    "http://www.tasteline.com/recept/skink-broccolipaj/",
    "http://www.tasteline.com/recept/kycklingrora-med-mango/",
    "http://www.tasteline.com/recept/rodbets-och-granatapplesallad-fran-mellanostern/",
    "http://www.tasteline.com/recept/orientkryddade-majs-och-baljvaxter/",
    "http://www.tasteline.com/recept/rod-risotto-med-rispasta-och-bulgur/",
    "http://www.tasteline.com/recept/lax-med-wasabiyoghurt/",
    "http://www.tasteline.com/recept/paj-god-pajbotten/",
    "http://www.tasteline.com/recept/barolobraserad-dilammbog/",
    "http://www.tasteline.com/recept/baka-pannkaka-i-ugn-jattegod/",
    "http://www.tasteline.com/recept/chokladkolasnittar/",
    "http://www.tasteline.com/recept/chokladdessert/",
    "http://www.tasteline.com/recept/avokadosoppa/",
    "http://www.tasteline.com/recept/kasslergratang-5/",
    "http://www.tasteline.com/recept/finlandia-lime-ghost/",
    "http://www.tasteline.com/recept/chokladpaj-med-pekannotter/",
    "http://www.tasteline.com/recept/fyllt-kalkonlar-med-apple-och-graddsas/",
    "http://www.tasteline.com/recept/sotpotatissoppa-med-oliver/",
    "http://www.tasteline.com/recept/sivans-algfarsbiffar/",
    "http://www.tasteline.com/recept/graddig-suovaspanna/",
    "http://www.tasteline.com/recept/alggryta-med-kaffe-och-stjarnanis/",
    "http://www.tasteline.com/recept/svartsoppa/",
    "http://www.tasteline.com/recept/grova-baguetter/",
    "http://www.tasteline.com/recept/beurre-blancsas-for-lata/",
    "http://www.tasteline.com/recept/sallad-lyonnaise/",
    "http://www.tasteline.com/recept/apelsinspackad-flaskkarre/",
    "http://www.tasteline.com/recept/musslor-a-la-paolo/",
    "http://www.tasteline.com/recept/chokladmousse-a-le-train-bleu/",
    "http://www.tasteline.com/recept/sesamstekt-kycklingbrostfile-med-bulgur/",
    "http://www.tasteline.com/recept/grillad-kycklinginnerfile-med-karljohansravioli/",
    "http://www.tasteline.com/recept/pastasallad-med-stekta-kycklingben-tomat-mozzarella-och-basilika/",
    "http://www.tasteline.com/recept/miyagis-asiatiska-sallad/",
    "http://www.tasteline.com/recept/kycklingspett-med-jordnotssas-4/",
    "http://www.tasteline.com/recept/miyagis-asiatiska-soppa/",
    "http://www.tasteline.com/recept/julbal-2/",
    "http://www.tasteline.com/recept/bonsalsa-med-rostad-majs/",
    "http://www.tasteline.com/recept/corn-fritters-med-queso-fresco/",
    "http://www.tasteline.com/recept/kyckling-med-molesas/",
    "http://www.tasteline.com/recept/liselottes-ceviche/",
    "http://www.tasteline.com/recept/glasstarta-2/",
    "http://www.tasteline.com/recept/appeldricka-med-mynta/",
    "http://www.tasteline.com/recept/schweizisk-appelkaka/",
    "http://www.tasteline.com/recept/appelchutney-3/",
    "http://www.tasteline.com/recept/ingrids-waldorfsallad/",
    "http://www.tasteline.com/recept/kladdkakemuffins-med-kinapuffar-2/",
    "http://www.tasteline.com/recept/inkokt-sjotunga-med-citrusartpure/",
    "http://www.tasteline.com/recept/camillas-chokladkladdkaka-med-hallon/",
    "http://www.tasteline.com/recept/butternut-squash-soppa-med-kokosmjolk/",
    "http://www.tasteline.com/recept/pastalada-med-gronsaker-och-korv/",
    "http://www.tasteline.com/recept/korintkakor-3/",
    "http://www.tasteline.com/recept/champagnedrink-amore/",
    "http://www.tasteline.com/recept/mellanmalsbullar/",
    "http://www.tasteline.com/recept/het-lumumba/",
    "http://www.tasteline.com/recept/fudge-brownies-2/",
    "http://www.tasteline.com/recept/lulea-pasta/",
    "http://www.tasteline.com/recept/yakitori-japanskt-grillspett/",
    "http://www.tasteline.com/recept/basta-potatisen/",
    "http://www.tasteline.com/recept/citronbrod-med-ost-skinka/",
    "http://www.tasteline.com/recept/varrullar-med-dipsas-hanoi-style/",
    "http://www.tasteline.com/recept/soppa-med-gron-curry-kokos-och-kyckling/",
    "http://www.tasteline.com/recept/snabb-chokladkaka-med-sorbet-2/",
    "http://www.tasteline.com/recept/fisksoppa-med-kokt-potatis/",
    "http://www.tasteline.com/recept/gul-gazpacho-2/",
    "http://www.tasteline.com/recept/lavendeldrommar/",
    "http://www.tasteline.com/recept/pasta-med-gremolatakyckling/",
    "http://www.tasteline.com/recept/cheesecake-utan-ugn/",
    "http://www.tasteline.com/recept/julkorv/",
    "http://www.tasteline.com/recept/ugnsbakad-lax-med-couscous-basilikasas/",
    "http://www.tasteline.com/recept/skaldjursfylld-rodspattefile-med-musselsaffransas/",
    "http://www.tasteline.com/recept/ugnsbakat-kalkonbrost-med-klyftpotatis-och-fikonsas/",
    "http://www.tasteline.com/recept/alggryta-med-rotgronsaker/",
    "http://www.tasteline.com/recept/gratinerad-hajmal-pangasius-hypopthalmus/",
    "http://www.tasteline.com/recept/sichuankryddade-revbensspjall/",
    "http://www.tasteline.com/recept/vintergryta-med-kokos-och-rod-curry/",
    "http://www.tasteline.com/recept/svart-risgrot-med-ingefara-och-frukt/",
    "http://www.tasteline.com/recept/black-pepper-beef/",
    "http://www.tasteline.com/recept/quinoa-med-anisdoftande-ragu-pa-svamp-och-linser/",
    "http://www.tasteline.com/recept/saltbakade-kastanjer-med-smor/",
    "http://www.tasteline.com/recept/marias-knackiga-kanelbullar-i-form/",
    "http://www.tasteline.com/recept/morotsbrod-10/",
    "http://www.tasteline.com/recept/knackebrod-2/",
    "http://www.tasteline.com/recept/kirskalsbrod/",
    "http://www.tasteline.com/recept/frukt-och-notbrod-2/",
    "http://www.tasteline.com/recept/rodbetsbrod-med-fankal/",
    "http://www.tasteline.com/recept/mustig-valnotskaka/",
    "http://www.tasteline.com/recept/moule-frites-med-rokig-aioli/",
    "http://www.tasteline.com/recept/fikonsallad-med-hasselnotsdressing/",
    "http://www.tasteline.com/recept/kantarellpasta-med-sidflask/",
    "http://www.tasteline.com/recept/sotpotatisgratang/",
    "http://www.tasteline.com/recept/agg-benedict/",
    "http://www.tasteline.com/recept/smal-potatisgratang/",
    "http://www.tasteline.com/recept/shepherds-pie-3/",
    "http://www.tasteline.com/recept/provencalsk-gronsaksgratang/",
    "http://www.tasteline.com/recept/fankalsgratang-med-parmesan/",
    "http://www.tasteline.com/recept/rotfruktsgratang-med-kantareller-och-sidflask/",
    "http://www.tasteline.com/recept/faraos-kottfarscigarrer/",
    "http://www.tasteline.com/recept/asiatisk-rabiff/",
    "http://www.tasteline.com/recept/kycklingbullar-med-gomda-gronsaker/",
    "http://www.tasteline.com/recept/miso-soppa-med-tofu/",
    "http://www.tasteline.com/recept/reninnanlar-och-kantarellpytt-med-matvete/",
    "http://www.tasteline.com/recept/rodingfile-med-orttapenade/",
    "http://www.tasteline.com/recept/cowboygryta/",
    "http://www.tasteline.com/recept/familjegryta/",
    "http://www.tasteline.com/recept/sparris-i-ugn/",
    "http://www.tasteline.com/recept/baka-fromagetarta-med-jordgubbar/",
    "http://www.tasteline.com/recept/jattegod-kottgryta-2/",
    "http://www.tasteline.com/recept/ugnsstekt-kotlettrad-med-rotfruktsrosti/",
    "http://www.tasteline.com/recept/supergott-zucchinibrod/",
    "http://www.tasteline.com/recept/kyckling-gron-curry/",
    "http://www.tasteline.com/recept/confusion/",
    "http://www.tasteline.com/recept/jamaica-me-crazy/",
    "http://www.tasteline.com/recept/above-and-below/",
    "http://www.tasteline.com/recept/eye-for-fusion/",
    "http://www.tasteline.com/recept/herbal-jigger/",
    "http://www.tasteline.com/recept/mad-mex/",
    "http://www.tasteline.com/recept/chili-con-carne-5/",
    "http://www.tasteline.com/recept/brod-havregryn-tekakor/",
    "http://www.tasteline.com/recept/kycklinggryta-med-farskost/",
    "http://www.tasteline.com/recept/mammas-chokladkaka/",
    "http://www.tasteline.com/recept/skaldjursrisoni/",
    "http://www.tasteline.com/recept/hummer-med-smorsas-och-pepparrot/",
    "http://www.tasteline.com/recept/bondomelett-med-kraftor/",
    "http://www.tasteline.com/recept/red-light-delight/",
    "http://www.tasteline.com/recept/sallad-kythira-med-pilgrimsmusslor/",
    "http://www.tasteline.com/recept/ostron-med-lime-gurka-och-forellrom/",
    "http://www.tasteline.com/recept/pasta-med-ortgronsaker/",
    "http://www.tasteline.com/recept/kottfarsspett-med-ugnsbakade-gronsaker/",
    "http://www.tasteline.com/recept/finsk-korngrynbrod/",
    "http://www.tasteline.com/recept/pesche-ripiene/",
    "http://www.tasteline.com/recept/bracioli-con-salsa-di-pomodoro/",
    "http://www.tasteline.com/recept/polpette-di-ricotta/",
    "http://www.tasteline.com/recept/spaghetti-con-cozze-o-vongole/",
    "http://www.tasteline.com/recept/koesisters-med-mango-och-papayakulfi/",
    "http://www.tasteline.com/recept/kofta-med-okrasas/",
    "http://www.tasteline.com/recept/ljummen-tonfisktartar-med-plantainchips/",
    "http://www.tasteline.com/recept/kyckling-kyckling-med-kramig-tacke/",
    "http://www.tasteline.com/recept/kyckling-med-currystekt-vitkal/",
    "http://www.tasteline.com/recept/raktoast-smogen/",
    "http://www.tasteline.com/recept/skogstoast/",
    "http://www.tasteline.com/recept/bingospett/",
    "http://www.tasteline.com/recept/kantarelltoast-2/",
    "http://www.tasteline.com/recept/skogshuggarmacka/",
    "http://www.tasteline.com/recept/carpaccio-pa-stensopp/",
    "http://www.tasteline.com/recept/rynkad-tofsskivling-med-frikadeller-i-buljong/",
    "http://www.tasteline.com/recept/stekt-gos-med-citrongul-slemskivling/",
    "http://www.tasteline.com/recept/svart-trumpetsvamp-med-vita-bonor/",
    "http://www.tasteline.com/recept/sallad-pa-kremlor-endiver-och-blekselleri/",
    "http://www.tasteline.com/recept/dubbelmacka-pa-fjallskivling/",
    "http://www.tasteline.com/recept/fylld-melon/",
    "http://www.tasteline.com/recept/barnens-favorit-2/",
    "http://www.tasteline.com/recept/scones-2/",
    "http://www.tasteline.com/recept/varmt-kryddigt-appelvin/",
    "http://www.tasteline.com/recept/sydamerikansk-karleksdryck/",
    "http://www.tasteline.com/recept/lingondricka/",
    "http://www.tasteline.com/recept/tid-for-te-med-adla-muffins/",
    "http://www.tasteline.com/recept/kokoschoklad/",
    "http://www.tasteline.com/recept/chokladmums/",
    "http://www.tasteline.com/recept/ljuvligt-god-smorgastarta/",
    "http://www.tasteline.com/recept/laxpaj-tarta/",
    "http://www.tasteline.com/recept/kramig-och-lyxig-smorgastarta/",
    "http://www.tasteline.com/recept/smorgastarta-med-skaldjur/",
    "http://www.tasteline.com/recept/forratt-lojromsmousse/",
    "http://www.tasteline.com/recept/godis-falska-mozartkulor/",
    "http://www.tasteline.com/recept/frusen-moccatarta/",
    "http://www.tasteline.com/recept/sallad-avocadosallad/",
    "http://www.tasteline.com/recept/biffstroganoff/",
    "http://www.tasteline.com/recept/tortillapizza-2/",
    "http://www.tasteline.com/recept/morotsbrod-i-langpanna-4/",
    "http://www.tasteline.com/recept/auberginetorn-med-mozzarella-och-pesto/",
    "http://www.tasteline.com/recept/kikartsbiffar-och-apelsinmorotter/",
    "http://www.tasteline.com/recept/baka-gifflar-med-fyllning/",
    "http://www.tasteline.com/recept/kottfars-medelhavsbiffar/",
    "http://www.tasteline.com/recept/angelas-whiskydoftande-appelpaj-med-whiskyglass-angelas-share/",
    "http://www.tasteline.com/recept/bargrottor/",
    "http://www.tasteline.com/recept/dajmbrack/",
    "http://www.tasteline.com/recept/godmorgonbullar/",
    "http://www.tasteline.com/recept/fylld-paprika/",
    "http://www.tasteline.com/recept/rakwok/",
    "http://www.tasteline.com/recept/hallon-och-graddfil-2/",
    "http://www.tasteline.com/recept/vitloksstekta-kantareller/",
    "http://www.tasteline.com/recept/primormorotter/",
    "http://www.tasteline.com/recept/sallad-med-graddvinagrett/",
    "http://www.tasteline.com/recept/agg-i-ugn-med-spenat-och-bacon/",
    "http://www.tasteline.com/recept/sotsura-gronsaker-2/",
    "http://www.tasteline.com/recept/rakspett-med-currydippa/",
    "http://www.tasteline.com/recept/drink-pina-colada/",
    "http://www.tasteline.com/recept/blabarspannkakor-2/",
    "http://www.tasteline.com/recept/blabarssirap-med-vanilj/",
    "http://www.tasteline.com/recept/blabarsglaze-med-pepparrot/",
    "http://www.tasteline.com/recept/mormor-siris-blabarskaka/",
    "http://www.tasteline.com/recept/fusk-cheesecake-i-glas/",
    "http://www.tasteline.com/recept/ljummen-potatissallad-med-ruccola-och-valnotter/",
    "http://www.tasteline.com/recept/smorgastarta-lyxig-smorgastarta/",
    "http://www.tasteline.com/recept/forratt-kraftsallad-i-glas/",
    "http://www.tasteline.com/recept/vitlokschampinjoner/",
    "http://www.tasteline.com/recept/kantarellpaj-med-smak-av-timjan/",
    "http://www.tasteline.com/recept/god-fisksoppa/",
    "http://www.tasteline.com/recept/hasselbackspotatis/",
    "http://www.tasteline.com/recept/sataysas-2/",
    "http://www.tasteline.com/recept/havrekakor-2/",
    "http://www.tasteline.com/recept/appel-kanel-muffins-light/",
    "http://www.tasteline.com/recept/passion-med-vit-choklad/",
    "http://www.tasteline.com/recept/vasterbottensmos-med-kantareller-och-torkad-oxfile/",
    "http://www.tasteline.com/recept/rod-linsgryta-med-stark-korv/",
    "http://www.tasteline.com/recept/vaniljpannkakor/",
    "http://www.tasteline.com/recept/jordnotskraft/",
    "http://www.tasteline.com/recept/morotskaka-3/",
    "http://www.tasteline.com/recept/snickerskaka/",
    "http://www.tasteline.com/recept/mynta-och-citronmeliss-cooler/",
    "http://www.tasteline.com/recept/iste-av-mynta/",
    "http://www.tasteline.com/recept/rosmarinkokta-vita-bonor-med-rucola-och-parmesan/",
    "http://www.tasteline.com/recept/salviabrod/",
    "http://www.tasteline.com/recept/timjan-och-citronstekt-flaskkotlett/",
    "http://www.tasteline.com/recept/rosepepparstekt-lax-med-citrontimjanquinoa/",
    "http://www.tasteline.com/recept/kokta-rodbetor-med-vitloksgrassas/",
    "http://www.tasteline.com/recept/kycklingmacka-med-thaibasilika-och-mangosalsa/",
    "http://www.tasteline.com/recept/avokado-och-tomatsallad-med-koriander-och-mynta/",
    "http://www.tasteline.com/recept/potatisgryta-med-kyckling-och-curry/",
    "http://www.tasteline.com/recept/citronstekt-klyftpotatis/",
    "http://www.tasteline.com/recept/potatisgratang-med-graslok-och-jalapeno/",
    "http://www.tasteline.com/recept/rostbiffmacka/",
    "http://www.tasteline.com/recept/fyllig-potatis-och-dragonsoppa/",
    "http://www.tasteline.com/recept/kaskadsallad-med-aprikoser-rokt-flask-och-pepparrotsyoghurt/",
    "http://www.tasteline.com/recept/sesampanerade-potatis-och-halloumibullar/",
    "http://www.tasteline.com/recept/bladspenat-och-kycklingburgare-med-grasloksyoghurt-2/",
    "http://www.tasteline.com/recept/lax-och-mizunasallat-i-folie-med-vitloksgras-och-ingefara/",
    "http://www.tasteline.com/recept/halloumi-och-paprikaspett-med-rucolapesto/",
    "http://www.tasteline.com/recept/sallatsmix-med-grillad-biff-och-myntadressing/",
    "http://www.tasteline.com/recept/sesamnudlar-med-mizunasallat-och-grillad-flaskkarre/",
    "http://www.tasteline.com/recept/grillade-gronsaker-med-rod-mangold-och-marinerad-fetaost/",
    "http://www.tasteline.com/recept/rosmarinmuffins-med-basilikafarskost/",
    "http://www.tasteline.com/recept/dill-kapris-och-zucchinisallad/",
    "http://www.tasteline.com/recept/grapefrukt-med-fankalssallad/",
    "http://www.tasteline.com/recept/rucola-och-citronris/",
    "http://www.tasteline.com/recept/quesadilla-med-rosmarin-och-chevre/",
    "http://www.tasteline.com/recept/hallonmuffins-2/",
    "http://www.tasteline.com/recept/skradda-kakor/",
    "http://www.tasteline.com/recept/superenkel-hallonkaka-2/",
    "http://www.tasteline.com/recept/pink-swing/",
    "http://www.tasteline.com/recept/farmor-ruts-mogelkakor/",
    "http://www.tasteline.com/recept/farmor-sigrids-sockerringar/",
    "http://www.tasteline.com/recept/faster-harriets-gaffelkakor/",
    "http://www.tasteline.com/recept/citrontimjanstekta-tomater-med-avokado-och-rucolasallat/",
    "http://www.tasteline.com/recept/jennys-rabarberchutney/",
    "http://www.tasteline.com/recept/rieska-finskt-kornbrod/",
    "http://www.tasteline.com/recept/enkel-limpa-utan-jast/",
    "http://www.tasteline.com/recept/kottgryta-4/",
    "http://www.tasteline.com/recept/grillade-gronsaker-med-ansjovishollandaise/",
    "http://www.tasteline.com/recept/petras-tacoburgare-med-fruktig-champinjon-och-pinjenotssallad/",
    "http://www.tasteline.com/recept/toulouse-lautrecs-potatissallad/",
    "http://www.tasteline.com/recept/flintastek/",
    "http://www.tasteline.com/recept/cookies/",
    "http://www.tasteline.com/recept/grillad-lax-med-lime-och-chili/",
    "http://www.tasteline.com/recept/kycklingspett-i-mias-marinad-med-mango-chutney-sas/",
    "http://www.tasteline.com/recept/idas-apelsin-stjarnanis-snaps/",
    "http://www.tasteline.com/recept/idas-sommar-snaps/",
    "http://www.tasteline.com/recept/lyxiga-lussebullar/",
    "http://www.tasteline.com/recept/hajmal-med-graslok-och-citron/",
    "http://www.tasteline.com/recept/salviamarinerade-skinkskivor-med-pp-sallad/",
    "http://www.tasteline.com/recept/indonesisk-tomatsalsa/",
    "http://www.tasteline.com/recept/kryddiga-revbensspjall/",
    "http://www.tasteline.com/recept/apelsingratinerade-jordgubbar/",
    "http://www.tasteline.com/recept/kallarfranska-2/",
    "http://www.tasteline.com/recept/lime-cheesecake-2/",
    "http://www.tasteline.com/recept/grova-tekakor-med-havregryn/",
    "http://www.tasteline.com/recept/portionspajer-med-chevre-persika-och-honung/",
    "http://www.tasteline.com/recept/lax-och-kraftpaj/",
    "http://www.tasteline.com/recept/traditionell-smorgastarta/",
    "http://www.tasteline.com/recept/italiensk-paj-med-salami/",
    "http://www.tasteline.com/recept/tomattarte-med-sardeller/",
    "http://www.tasteline.com/recept/ostquiche-med-fikon-och-paron/",
    "http://www.tasteline.com/recept/bruschetta-med-getbrie/",
    "http://www.tasteline.com/recept/varm-sallad-med-kronartskockor/",
    "http://www.tasteline.com/recept/jordgubbssallad-med-fetaost-haricots-verts-och-mynta/",
    "http://www.tasteline.com/recept/filbunke-2/",
    "http://www.tasteline.com/recept/fetaostknyten-med-aprikoser/",
    "http://www.tasteline.com/recept/syrrans-squash-med-pasta/",
    "http://www.tasteline.com/recept/citronprimorer-med-kalkonkassler/",
    "http://www.tasteline.com/recept/ortkryddad-rot-och-gronsaksmos-med-creme-fraiche-for-bebisar/",
    "http://www.tasteline.com/recept/dillkryddad-lax-och-potatispure-for-bebisar/",
    "http://www.tasteline.com/recept/mazarintarta/",
    "http://www.tasteline.com/recept/avokadosoppa-med-rakor/",
    "http://www.tasteline.com/recept/varma-jordgubbar-med-gronpeppar-2/",
    "http://www.tasteline.com/recept/choklad-och-hasselnotstarta-glutenfri/",
    "http://www.tasteline.com/recept/fruktsoppa/",
    "http://www.tasteline.com/recept/matjesill-med-brynt-smor-och-hackat-agg/",
    "http://www.tasteline.com/recept/rabarberkompott-med-kardemumma/",
    "http://www.tasteline.com/recept/krusbarskram-2/",
    "http://www.tasteline.com/recept/klappkram/",
    "http://www.tasteline.com/recept/gazpacho-8/",
    "http://www.tasteline.com/recept/spansk-aioli/",
    "http://www.tasteline.com/recept/dessert-frasiga-vafflor/",
    "http://www.tasteline.com/recept/tarta-med-vit-chokladmousse/",
    "http://www.tasteline.com/recept/dessert-ljuvlig-hallonmousse/",
    "http://www.tasteline.com/recept/grillad-baguette-med-prosciutto-och-grillad-halloumi/",
    "http://www.tasteline.com/recept/kryddig-thai-kyckling/",
    "http://www.tasteline.com/recept/fetaostfylld-oxfile-med-timjanpotatis-2/",
    "http://www.tasteline.com/recept/lefkos-med-paprika-och-zucchini/",
    "http://www.tasteline.com/recept/ernst-stompa/",
    "http://www.tasteline.com/recept/jordgubbskompott-med-limemousse/",
    "http://www.tasteline.com/recept/matjestarta/",
    "http://www.tasteline.com/recept/laxfile-med-skagensas/",
    "http://www.tasteline.com/recept/midsommarsallad-2/",
    "http://www.tasteline.com/recept/nubbesallad-8/",
    "http://www.tasteline.com/recept/heta-mandelrakor/",
    "http://www.tasteline.com/recept/laxrulle-3/",
    "http://www.tasteline.com/recept/rokt-stenbit-fattigmansal-pa-macka-med-aggrora/",
    "http://www.tasteline.com/recept/potatisoverbakad-skrubba/",
    "http://www.tasteline.com/recept/kraftsill/",
    "http://www.tasteline.com/recept/gratinerade-musslor-2/",
    "http://www.tasteline.com/recept/gravlaxsallad-i-tunnbrodskorgar/",
    "http://www.tasteline.com/recept/citronsill-3/",
    "http://www.tasteline.com/recept/heta-vitloksrakor/",
    "http://www.tasteline.com/recept/bocadillas-med-rostad-paprika-och-sardeller/",
    "http://www.tasteline.com/recept/tortilla-espanola/",
    "http://www.tasteline.com/recept/rora-vit-rora-till-midsommarfisken-med-keso/",
    "http://www.tasteline.com/recept/banankaka-med-dinkel/",
    "http://www.tasteline.com/recept/finsk-midsommarostsoppa-eller-sotost/",
    "http://www.tasteline.com/recept/sallad-mozzarellasallad/",
    "http://www.tasteline.com/recept/sallad-coleslaw-kalsallad/",
    "http://www.tasteline.com/recept/chistorra-pa-brod/",
    "http://www.tasteline.com/recept/rostade-sommargronsaker/",
    "http://www.tasteline.com/recept/grillad-kotlett-och-squash-med-varm-vitloks-och-sardellolja/",
    "http://www.tasteline.com/recept/vattenmelon-i-glas/",
    "http://www.tasteline.com/recept/gronsaltad-gurka/",
    "http://www.tasteline.com/recept/ugnstorkade-tomater/",
    "http://www.tasteline.com/recept/den-optimala-tomatsasen/",
    "http://www.tasteline.com/recept/tomat-och-citrusmarmelad/",
    "http://www.tasteline.com/recept/tomatsmorgas-med-farskost/",
    "http://www.tasteline.com/recept/tomatsallad-med-getost/",
    "http://www.tasteline.com/recept/tomat-och-bonsalsa/",
    "http://www.tasteline.com/recept/dessert-jordgubbsmousse-pa-italienska/",
    "http://www.tasteline.com/recept/dessert-glass-med-jordgubbar-med-marangtopp/",
    "http://www.tasteline.com/recept/sommardrinken-domino/",
    "http://www.tasteline.com/recept/klyftpotatis-2/",
    "http://www.tasteline.com/recept/blabarsbullar-4/",
    "http://www.tasteline.com/recept/dinkelbullar-2/",
    "http://www.tasteline.com/recept/mustig-korvsoppa/",
    "http://www.tasteline.com/recept/smakakor-grundrecept/",
    "http://www.tasteline.com/recept/sojayoghurt-med-rostad-halsomusli-och-smorgas/",
    "http://www.tasteline.com/recept/finsk-jordgubbs-och-rabarberkaka/",
    "http://www.tasteline.com/recept/thai-panaeng-curry-med-fisk/",
    "http://www.tasteline.com/recept/tomatsas-som-ar-god-till-nastan-allt/",
    "http://www.tasteline.com/recept/finsk-anitas-havtorns-cheesecake/",
    "http://www.tasteline.com/recept/adelostgratinerad-flaskkotlett/",
    "http://www.tasteline.com/recept/finsk-akta-romanov-jordgubbar/",
    "http://www.tasteline.com/recept/finsk-ragbrod-av-surdeg/",
    "http://www.tasteline.com/recept/finsk-muslibrod/",
    "http://www.tasteline.com/recept/finsk-skargardsbrod/",
    "http://www.tasteline.com/recept/asiatisk-rissallad-med-mango/",
    "http://www.tasteline.com/recept/gong-bao-chicken-kung-pao/",
    "http://www.tasteline.com/recept/jordgubbssalsa/",
    "http://www.tasteline.com/recept/finsk-goda-kottpiroger/",
    "http://www.tasteline.com/recept/pasta-med-tonfisk-och-chilisas/",
    "http://www.tasteline.com/recept/blabarssmoothie-3/",
    "http://www.tasteline.com/recept/supergott-filmjolksbrod/",
    "http://www.tasteline.com/recept/dallasbullar/",
    "http://www.tasteline.com/recept/biscotti-3/",
    "http://www.tasteline.com/recept/karleksmums-2/",
    "http://www.tasteline.com/recept/engelska-scones/",
    "http://www.tasteline.com/recept/finsk-gravlaxrullar-med-varmrok-sik-fyllning/",
    "http://www.tasteline.com/recept/finsk-chokladkaka/",
    "http://www.tasteline.com/recept/bacon-och-farslada-gi/",
    "http://www.tasteline.com/recept/bias-roda-gi-appelpaj/",
    "http://www.tasteline.com/recept/gi-chokladtarta/",
    "http://www.tasteline.com/recept/gi-varrullar/",
    "http://www.tasteline.com/recept/gi-toppar/"
];
let filename = "tasteline/tasteline-10.1-2017-11-13.json";

nightmare
    .goto('http://www.tasteline.com/recept/')
    .evaluate(function () {

    })
    .then(function (hrefs) {

        console.log("start");
        console.log("nr of urls: " + urls.length);
        uniqurls = [...new Set(urls)];
        console.log("uniq : " + uniqurls.length);
        return uniqurls.reduce(function (accumulator, href) {
            return accumulator.then(function (results) {
                return nightmare.goto(href)
                    .evaluate(function () {
                        if (!document.querySelector('.page-content .recipe-content')) {
                            return;
                        }
                        let recipe = {};
                        //title
                        recipe.title = document.querySelector('.page-content .recipe-description h1').innerHTML.trim();
                        //tags
                        let tags = {};
                        //cannot read property length of null
                        $('.page-content .recipe-description .category-list a').each(function () {
                            let t = $(this).text();
                            if (t.match(/^[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]*$/)) {
                                t = t + "FAILEDTAG";
                            }
                            tags[t.charAt(0).toUpperCase() + t.slice(1).replace(/\s*\([^()]*\)$/, '').split(",")[0].replace(/([/.#$])/g, '').trim()] = true;

                        })
                        recipe.tags = tags;
                        //source
                        recipe.source = window.location.href;

                        //votes rating
                        if (document.querySelector('.page-content .recipe-description .recipe-rating.voting-enabled i')) {
                            let ratingLine = document.querySelector('.page-content .recipe-description .recipe-rating.voting-enabled').getAttribute("title");
                            let parts = ratingLine.split("Antal röster:");
                            recipe.votes = parts[1].trim();
                            recipe.rating = parts[0].split(":")[1].trim();
                        }
                        //author
                        if (document.querySelector('.page-content .recipe-author-text-inner span')) {
                            recipe.author = document.querySelector('.page-content .recipe-author-text-inner span').innerText.trim();
                        } else {
                            recipe.author = "tasteline.com";
                        }

                        //createdFor

                        //portions
                        if (document.querySelector('.page-content .recipe-content .portions')) {
                            recipe.portions = document.querySelector('.page-content .recipe-content .portions').getAttribute('data-portions');
                        }
                        //created

                        //description
                        if (document.querySelector('.page-content .recipe-ingress')) {
                            recipe.description = document.querySelector('.page-content .recipe-ingress').innerHTML.replace(/(\r\n|\n|\r|<[^>]*>)/gm, "").replace(/  +/g, ' ').trim();
                        }

                        //time
                        if (document.querySelector('.page-content .recipe-description .fa-clock-o')) {
                            recipe.time = document.querySelector('.page-content .recipe-description .fa-clock-o').nextSibling.nodeValue.trim();
                            let parts = recipe.time.split(" ");
                            if (parts.length === 2 && (parts[1] === "min" || parts[1] === "minuter") && parts[0] < 30) {
                                if (!tags.hasOwnProperty('Snabbt')) {
                                    tags["Snabbt"] = true;
                                }
                            }
                        }
                        //denna är kvar att fixa till
                        //ingredients
                        if (document.querySelector('.page-content .ingredient-group li')) {
                            let ingredientgroups = document.querySelector('.page-content').getElementsByClassName('ingredient-group');
                            let ingredients = [];
                            let ingredientNames = [];
                            for (let i = 0; i < ingredientgroups.length; i++) {
                                let ingredientsDom = ingredientgroups[i].getElementsByTagName("li");
                                for (let j = 0; j < ingredientsDom.length; ++j) {
                                    let ingredient = {};
                                    ingredient.amount = ingredientsDom[j].getElementsByClassName("quantity")[0].getAttribute('data-quantity');
                                    ingredient.unit = ingredientsDom[j].getElementsByClassName("unit")[0].getAttribute('data-unit-name');
                                    if (!ingredientsDom[j].getElementsByClassName("ingredient")[0]) {
                                        return;
                                    }
                                    let namepart = ingredientsDom[j].getElementsByClassName("ingredient")[0].getElementsByTagName("span")[0].innerHTML.trim();
                                    ingredient.name = namepart.charAt(0).toUpperCase() + namepart.slice(1).replace(/\s*\([^()]*\)$/, '').split(",")[0].replace(/([/.#$])/g, '').trim();
                                    if (ingredientNames.indexOf(ingredient.name) > -1) {
                                        continue;
                                    }
                                    ingredientNames.push(ingredient.name);
                                    ingredients.push(ingredient);
                                    //måste göra om till innerHTML och ta ut det som ligger i spanet till amount 
                                    //och det andra får först trimmas och sen splitas på " " och ta ut [0] till unit

                                }
                            }
                            recipe.ingredients = ingredients;
                        }

                        if (!recipe.ingredients || recipe.ingredients.length === 0) {
                            return;
                        }

                        //difficulty
                        let instructionsList = document.querySelector('.page-content .recipe-content .steps').getElementsByTagName("li");
                        let nrOfIngredients = recipe.ingredients.length;
                        let instructionLength = 0;
                        for (let i = 0; i < instructionsList.length; i++) {
                            instructionLength = instructionLength + instructionsList[i].innerHTML.replace(/(\r\n|\n|\r|)/gm, "").trim().length;
                        }
                        instructionLength = instructionLength - instructionsList.length * 10;

                        let levelIndex = (nrOfIngredients * 8) + (instructionLength / 14);
                        if (recipe.tags.hasOwnProperty('Enkelt') || recipe.tags.hasOwnProperty('Lättlagat')) {
                            levelIndex = levelIndex - 100;
                        }
                        if (recipe.tags.hasOwnProperty('Snabbt')) {
                            levelIndex = levelIndex - 20;
                        }

                        if (levelIndex < 100) {
                            recipe.level = 1;
                        } else if (levelIndex < 200) {
                            recipe.level = 2;
                        } else {
                            recipe.level = 3;
                        }


                        return recipe;
                    })
                    .then(function (html) {
                        results.push(html);
                        return results;
                    })

            });
        }, Promise.resolve([]))
    })
    .then(function (resultArr) {
        console.log(resultArr.length);

        fs.writeFile("C:/react/" + filename, JSON.stringify(resultArr), function (err) {

            if (err) {
                return console.log(err);
            }

            console.log("The file was saved!");
        });
    });