var Nightmare = require('nightmare');
var nightmare = Nightmare({
    openDevTools: false, show: false, webPreferences: {
        images: false,
    }
})

var fs = require('fs');


//ta fram urls genom att:
//1. skapa ett script för att gå igenom alla http://www.tasteline.com/recept/?sida=2#sok där sida ökas på. Spara ner href från varje sida till en fil
//2. paste in i urls
//3. Sätt filename enligt "TASTELINE-RECEPTSRC-DATE.json"
//4. kör node set DEBUG=nightmare & node tasteline.js
//5. kör node createRecipes.js och ange namnet på filen som skapades här


let urls = [
    "http://www.tasteline.com/recept/matjessilltarta/",
    "http://www.tasteline.com/recept/iste-med-roibos-eller-gront-te/",
    "http://www.tasteline.com/recept/saftiga-kanel-applemuffins/",
    "http://www.tasteline.com/recept/superfluffig-vegansk-chokladmousse-med-hemlig-agent/",
    "http://www.tasteline.com/recept/fantastiskt-froknacke/",
    "http://www.tasteline.com/recept/mjolkfria-kladdkakemuffins/",
    "http://www.tasteline.com/recept/alices-och-axels-pizzadeg/",
    "http://www.tasteline.com/recept/prinsesstarta-6/",
    "http://www.tasteline.com/recept/havrekakor-med-choklad-3/",
    "http://www.tasteline.com/recept/churros-med-chokladsas-2/",
    "http://www.tasteline.com/recept/snabba-empanadas/",
    "http://www.tasteline.com/recept/tortillabrod-4/",
    "http://www.tasteline.com/recept/tres-leches/",
    "http://www.tasteline.com/recept/vit-chokladpannacotta-med-muscovadomarinerade-jordgubbar/",
    "http://www.tasteline.com/recept/en-blabarsdrom/",
    "http://www.tasteline.com/recept/biskvi-med-hallonkram/",
    "http://www.tasteline.com/recept/jordgubbsshrub/",
    "http://www.tasteline.com/recept/bubbelsangria-med-shrub/",
    "http://www.tasteline.com/recept/fladerblomssaft-med-muscovado/",
    "http://www.tasteline.com/recept/fankal-och-paronmarmelad/",
    "http://www.tasteline.com/recept/jordgubbsylt-med-citron-och-mynta/",
    "http://www.tasteline.com/recept/drottningsylt-med-en-touch-av-lime/",
    "http://www.tasteline.com/recept/minibrioche-med-vaniljkram-och-farska-bar/",
    "http://www.tasteline.com/recept/jordgubbstarta-med-passionscurd/",
    "http://www.tasteline.com/recept/minirabarberpajer-med-varmvispad-marang/",
    "http://www.tasteline.com/recept/varldens-brod/",
    "http://www.tasteline.com/recept/surdegsbrod-2/",
    "http://www.tasteline.com/recept/potkas/",
    "http://www.tasteline.com/recept/kycklinglever-med-vaxbonor-och-salvia/",
    "http://www.tasteline.com/recept/grillrokta-pilgrimsmusslor-pa-blomkalsbadd/",
    "http://www.tasteline.com/recept/hush-puppies/",
    "http://www.tasteline.com/recept/blabarscheesecake/",
    "http://www.tasteline.com/recept/gron-bonwrap/",
    "http://www.tasteline.com/recept/mjuk-appelkaka/",
    "http://www.tasteline.com/recept/brollopstarta-med-smultron-och-flader/",
    "http://www.tasteline.com/recept/pinocchiotarta/",
    "http://www.tasteline.com/recept/saftig-chokladtarta/",
    "http://www.tasteline.com/recept/ostron-grillade-med-tomat-och-olivvinagrett/",
    "http://www.tasteline.com/recept/medelhavsgronsaker-pa-spett-med-timjan-och-rostad-lok/",
    "http://www.tasteline.com/recept/gadda-med-smak-av-sommarkrafta/",
    "http://www.tasteline.com/recept/avokado-med-grillad-lime-och-koriander/",
    "http://www.tasteline.com/recept/lingontarta/",
    "http://www.tasteline.com/recept/mattande-sallad-med-mango-kyckling-och-mango-currydip/",
    "http://www.tasteline.com/recept/lchf-brod-med-linfron-och-mandel/",
    "http://www.tasteline.com/recept/chokladmoussetarta-med-apelsinsmak-2/",
    "http://www.tasteline.com/recept/indisk-lammgryta-med-frast-spenat/",
    "http://www.tasteline.com/recept/paj-med-broccoli-svarta-oliver-och-adelost/",
    "http://www.tasteline.com/recept/kantarell-och-ostpaj/",
    "http://www.tasteline.com/recept/paskchokladtarta/",
    "http://www.tasteline.com/recept/kapten-haddock-ugnsrostad-kyckling/",
    "http://www.tasteline.com/recept/helgrillad-ryggbiff-med-rucola-och-parmesan/",
    "http://www.tasteline.com/recept/sensuella-rawfoodbollar/",
    "http://www.tasteline.com/recept/avokadosoppa-a-green-choice/",
    "http://www.tasteline.com/recept/norirullar-med-papaya/",
    "http://www.tasteline.com/recept/golden-milk-ayurvedisk-dryck/",
    "http://www.tasteline.com/recept/ananas-och-mangosorbet/",
    "http://www.tasteline.com/recept/appelpannkakor/",
    "http://www.tasteline.com/recept/morotskaksbollar/",
    "http://www.tasteline.com/recept/jordnotsnudlar/",
    "http://www.tasteline.com/recept/galet-god-chokladtarta/",
    "http://www.tasteline.com/recept/rawfoodtarta-med-blabarsmousse/",
    "http://www.tasteline.com/recept/picklade-rotfrukter/",
    "http://www.tasteline.com/recept/notpanerad-rotselleri/",
    "http://www.tasteline.com/recept/krispiga-vietnamesiska-varrullar/",
    "http://www.tasteline.com/recept/vitloksbakade-majrovor/",
    "http://www.tasteline.com/recept/vegoskinka-2-0/",
    "http://www.tasteline.com/recept/ugnsrostade-rotfrukter/",
    "http://www.tasteline.com/recept/mjolksyrade-morotter/",
    "http://www.tasteline.com/recept/sweet-potatoe-pie-med-kanel-och-muskot/",
    "http://www.tasteline.com/recept/finsk-kalrotslada-3/",
    "http://www.tasteline.com/recept/pommes-frites-pa-persiljerot/",
    "http://www.tasteline.com/recept/brioche-burger-bun-2/",
    "http://www.tasteline.com/recept/ninas-nyttiga-bananpaj-med-knackiga-tacke/",
    "http://www.tasteline.com/recept/varm-skagensmorgas-med-laxromsnaps/",
    "http://www.tasteline.com/recept/dillkott-pa-kyckling/",
    "http://www.tasteline.com/recept/gulasch-pa-kycklinglarfile/",
    "http://www.tasteline.com/recept/pankofriterade-kycklingbollar-i-en-het-sotsur-sas/",
    "http://www.tasteline.com/recept/fyllda-oxrullader/",
    "http://www.tasteline.com/recept/laxwallenbergare-med-dijonsenapssas-4/",
    "http://www.tasteline.com/recept/grillad-avokadoburgare-med-marinerade-bonor-creme-fraiche-och-farska-orter/",
    "http://www.tasteline.com/recept/svart-bonburgare-med-gruyereost-och-karamelliserad-lok/",
    "http://www.tasteline.com/recept/snurrad-zucchini-och-sotpotatisburgare-med-chipotlemajonnas/",
    "http://www.tasteline.com/recept/zucchinikimchi/",
    "http://www.tasteline.com/recept/kolbrod/",
    "http://www.tasteline.com/recept/kimchibas/",
    "http://www.tasteline.com/recept/zucchinisallad-med-citron-och-dill/",
    "http://www.tasteline.com/recept/katalanska-kottbullar/",
    "http://www.tasteline.com/recept/het-paprikarora-2/",
    "http://www.tasteline.com/recept/bonsallad-med-rostad-mandel/",
    "http://www.tasteline.com/recept/rosesangria/",
    "http://www.tasteline.com/recept/kramig-chokladgrot/",
    "http://www.tasteline.com/recept/bananbrod-gluten-mjolkfritt/",
    "http://www.tasteline.com/recept/lchf-bacon-och-adelostpaj/",
    "http://www.tasteline.com/recept/kottfarslimpa-de-luxe/",
    "http://www.tasteline.com/recept/gron-temainspirerad-marsipantarta/",
    "http://www.tasteline.com/recept/superenkla-bonbiffar/",
    "http://www.tasteline.com/recept/avokado-smoothie-bowl/",
    "http://www.tasteline.com/recept/jordnotssmor-och-banan-grot/",
    "http://www.tasteline.com/recept/smakrika-kikartsbullar-med-couscous/",
    "http://www.tasteline.com/recept/glutenfria-fluffiga-plattars-2/",
    "http://www.tasteline.com/recept/pizza-pa-broccoli-och-blomkalsbotten/",
    "http://www.tasteline.com/recept/marias-choklad-chili-kyckling/",
    "http://www.tasteline.com/recept/marias-thaiwok-med-marinerad-flask/",
    "http://www.tasteline.com/recept/tonfiskpotatissallad-427-kalorier-per-portion/",
    "http://www.tasteline.com/recept/veggie-eggie/",
    "http://www.tasteline.com/recept/trolldeg/",
    "http://www.tasteline.com/recept/en-jattegod-kalrotslada/",
    "http://www.tasteline.com/recept/saftigt-julbrod/",
    "http://www.tasteline.com/recept/maries-musli/",
    "http://www.tasteline.com/recept/champagnegele-med-vit-chokladgradde/",
    "http://www.tasteline.com/recept/tryffelblinier-med-valnotskroketter/",
    "http://www.tasteline.com/recept/tomattartar/",
    "http://www.tasteline.com/recept/pimientos-de-padron/",
    "http://www.tasteline.com/recept/gratinerade-tomater/",
    "http://www.tasteline.com/recept/svampkroketter/",
    "http://www.tasteline.com/recept/brysselkalsgratang-med-timjan/",
    "http://www.tasteline.com/recept/smordegsflarn-med-valnotskram-och-paron/",
    "http://www.tasteline.com/recept/fankalssallad-med-saffran/",
    "http://www.tasteline.com/recept/sticky-tofu/",
    "http://www.tasteline.com/recept/svarta-bonbollar-med-valnotter/",
    "http://www.tasteline.com/recept/kaxig-rodbetssallad/",
    "http://www.tasteline.com/recept/senaps-sill/",
    "http://www.tasteline.com/recept/crostini-med-zucchini-getost-och-valnot/",
    "http://www.tasteline.com/recept/lussebullar-med-mustig-rom/",
    "http://www.tasteline.com/recept/finsk-leverlada-2/",
    "http://www.tasteline.com/recept/nyttig-frusen-snickerskaka/",
    "http://www.tasteline.com/recept/borgmastarns-glogg/",
    "http://www.tasteline.com/recept/pepparkakscrostini-med-gorgonzola-mascarpone-farska-fikon-och-pistasch/",
    "http://www.tasteline.com/recept/minimackor-till-gloggen/",
    "http://www.tasteline.com/recept/vitk/",
    "http://www.tasteline.com/recept/lchf-limpa/",
    "http://www.tasteline.com/recept/figges-vortbrod/",
    "http://www.tasteline.com/recept/gravad-lax-4/",
    "http://www.tasteline.com/recept/figges-julfruktkaka/",
    "http://www.tasteline.com/recept/figges-godaste-lussebulle/",
    "http://www.tasteline.com/recept/supergoda-kebabspett/",
    "http://www.tasteline.com/recept/schwarzwaldtarta-av-jon-hansson-schwarzwalder-kirschtorte/",
    "http://www.tasteline.com/recept/chipsgratang/",
    "http://www.tasteline.com/recept/the-franska-lchf/",
    "http://www.tasteline.com/recept/raw-pepparkaksbollar-glutenfria/",
    "http://www.tasteline.com/recept/senapsgriljerad-quorn-med-rod-coleslaw/",
    "http://www.tasteline.com/recept/sesampanerad-tonfisk-chilimajonnas-och-sojamarinerad-sallad/",
    "http://www.tasteline.com/recept/aperol-spritz/",
    "http://www.tasteline.com/recept/banoffee-pie/",
    "http://www.tasteline.com/recept/mac-n-cheese/",
    "http://www.tasteline.com/recept/croque-monsieur-2/",
    "http://www.tasteline.com/recept/renskav-med-rotfrukter-messmorssas/",
    "http://www.tasteline.com/recept/kalvlever-med-applen-och-rokt-flask/",
    "http://www.tasteline.com/recept/ossobuco/",
    "http://www.tasteline.com/recept/sauerbraten-med-semmelknodel/",
    "http://www.tasteline.com/recept/gratinerade-havskraftor-med-kantarellsmor/",
    "http://www.tasteline.com/recept/hastbullar-med-kanelhjarta/",
    "http://www.tasteline.com/recept/nyttiga-energibars-med-jordnotter/",
    "http://www.tasteline.com/recept/chokladgodis-med-notter/",
    "http://www.tasteline.com/recept/lchf-snickers-med-flingsalt/",
    "http://www.tasteline.com/recept/basta-falafel-med-ugnsgratinerade-tomater-och-rakost/",
    "http://www.tasteline.com/recept/elvis-presleys-cupcakes/",
    "http://www.tasteline.com/recept/het-paprika-bon-och-linsgryta/",
    "http://www.tasteline.com/recept/lchf-chokladmousse/",
    "http://www.tasteline.com/recept/tonfiskrora-9/",
    "http://www.tasteline.com/recept/eriks-jordnots-och-chokladmuffins/",
    "http://www.tasteline.com/recept/yoghurt-limesas/",
    "http://www.tasteline.com/recept/kryddiga-quinoacrackers/",
    "http://www.tasteline.com/recept/gron-smoothiebowl/",
    "http://www.tasteline.com/recept/groddade-bovete-och-vallmoplattar/",
    "http://www.tasteline.com/recept/farska-varrullar-med-rodkal-notter-och-mango/",
    "http://www.tasteline.com/recept/groddat-frobrod/",
    "http://www.tasteline.com/recept/kolafudge/",
    "http://www.tasteline.com/recept/randig-godispannacotta/",
    "http://www.tasteline.com/recept/chokladtarta-med-malteserkulor/",
    "http://www.tasteline.com/recept/marshmallowtarta/",
    "http://www.tasteline.com/recept/mug-cakes-med-chokladkola/",
    "http://www.tasteline.com/recept/aggrora-med-purjolok-spenat-och-krasse/",
    "http://www.tasteline.com/recept/bonchili-med-choklad-ol-koriander-och-graddkokt-majs/",
    "http://www.tasteline.com/recept/portabelloburgare-med-gronkal-tryffelkram-och-karamelliserad-lok/",
    "http://www.tasteline.com/recept/sushifest-med-quinoa/",
    "http://www.tasteline.com/recept/grillad-purjolok-med-timjan-och-citronsmor/",
    "http://www.tasteline.com/recept/toast-skagen-5/",
    "http://www.tasteline.com/recept/hamburgare-med-sotpotatisstrips/",
    "http://www.tasteline.com/recept/saftig-banan-och-blabarskaka/",
    "http://www.tasteline.com/recept/lchf-kesoplattar-med-kall-baconrora/",
    "http://www.tasteline.com/recept/kottbullar-med-brunsas-och-lingon/",
    "http://www.tasteline.com/recept/vaniljpannkakor-2/",
    "http://www.tasteline.com/recept/ostron-med-lojrom-och-brynt-smor/",
    "http://www.tasteline.com/recept/egna-egga-vegobiffar/",
    "http://www.tasteline.com/recept/rakpaj-med-chili-och-paprika/",
    "http://www.tasteline.com/recept/sotpotatisstrips-2/",
    "http://www.tasteline.com/recept/banan-och-kesoplattar/",
    "http://www.tasteline.com/recept/froknacke-med-bovete/",
    "http://www.tasteline.com/recept/svartkals-och-spenatchips-med-chili-lime-och-sesam/",
    "http://www.tasteline.com/recept/godisremmar/",
    "http://www.tasteline.com/recept/len-potatissallad/",
    "http://www.tasteline.com/recept/vasterbottenkex-med-timjan-och-vallmo/",
    "http://www.tasteline.com/recept/klassisk-turkisk-omelett/",
    "http://www.tasteline.com/recept/pitepalt-traditionell-husmanskost/",
    "http://www.tasteline.com/recept/smalandska-kroppkakor/",
    "http://www.tasteline.com/recept/bakad-potatis-med-skagenrora-2/",
    "http://www.tasteline.com/recept/kramig-potatisgratang-2/",
    "http://www.tasteline.com/recept/ugnsbakad-hasselbackspotatis/",
    "http://www.tasteline.com/recept/knackig-appelblabarspaj/",
    "http://www.tasteline.com/recept/lchf-ostbrod/",
    "http://www.tasteline.com/recept/lchf-kottfarspaj-med-adelost/",
    "http://www.tasteline.com/recept/lax-och-avokadorullar/",
    "http://www.tasteline.com/recept/over-natten-grot-med-banan-och-blabar/",
    "http://www.tasteline.com/recept/musslor-i-kokosmjolk/",
    "http://www.tasteline.com/recept/nyttiga-peanut-butter-snickers/",
    "http://www.tasteline.com/recept/fiskcurry-fran-goa/",
    "http://www.tasteline.com/recept/tekakor-mamma-rigmor/",
    "http://www.tasteline.com/recept/hostig-appelkaka/",
    "http://www.tasteline.com/recept/banancupcakes-med-pekannotter/",
    "http://www.tasteline.com/recept/graddsas-med-kalvfond/",
    "http://www.tasteline.com/recept/surstrommingsklamma-med-hart-tunnbrod/",
    "http://www.tasteline.com/recept/appel-och-kanelrutor-med-mandeltosca/",
    "http://www.tasteline.com/recept/fluffiga-vaniljrutor/",
    "http://www.tasteline.com/recept/chocolate-chip-cookies-6/",
    "http://www.tasteline.com/recept/chokladpavlova-med-bjornbar/",
    "http://www.tasteline.com/recept/vit-kladdkaka-med-philadelphiafrosting-och-hallon/",
    "http://www.tasteline.com/recept/blomkalsbrod-lchf/",
    "http://www.tasteline.com/recept/mammas-oktoberkaka/",
    "http://www.tasteline.com/recept/lauras-pasta-de-cecco-conchigliette-rigate-nr-51/",
    "http://www.tasteline.com/recept/biskvitarta-2/",
    "http://www.tasteline.com/recept/laxpudding-variation-fran-gammalt-hallandskt-recept/",
    "http://www.tasteline.com/recept/asiatisk-supersmal-kycklingsoppa-med-lagt-gi/",
    "http://www.tasteline.com/recept/quinoabiffar-quinoaplattar-quinoabrod-glutenfria/",
    "http://www.tasteline.com/recept/twin-peaks-korsbarspaj/",
    "http://www.tasteline.com/recept/pevre-chiliensk-kall-sas-med-kopriander/",
    "http://www.tasteline.com/recept/familjens-gubbrora/",
    "http://www.tasteline.com/recept/blabarssylt/",
    "http://www.tasteline.com/recept/hallonsylt-2/",
    "http://www.tasteline.com/recept/jordgubbssaft/",
    "http://www.tasteline.com/recept/svart-vinbarssaft/",
    "http://www.tasteline.com/recept/jordgubbssylt-2/",
    "http://www.tasteline.com/recept/pogaca-turkiska-piroger/",
    "http://www.tasteline.com/recept/sojakryddad-kycklinggryta/",
    "http://www.tasteline.com/recept/kottgryta-5/",
    "http://www.tasteline.com/recept/quans-pho/",
    "http://www.tasteline.com/recept/sotpotatisbiffar-med-ingefara-och-notter/",
    "http://www.tasteline.com/recept/nyttig-rawfoodbakelse-med-chokladmousse/",
    "http://www.tasteline.com/recept/grillad-majs-och-quinosallad/",
    "http://www.tasteline.com/recept/texas-sweet-potato-chili/",
    "http://www.tasteline.com/recept/snittar-med-kikartstrora-och-grillad-paprika/",
    "http://www.tasteline.com/recept/snittar-med-champinjonkram-och-friterad-kapris/",
    "http://www.tasteline.com/recept/snittar-med-citronkram-och-rokt-lax/",
    "http://www.tasteline.com/recept/minismorgastarta-sommar/",
    "http://www.tasteline.com/recept/norrlandsk-smorgastarta-med-roding/",
    "http://www.tasteline.com/recept/smorgastarta-fruktig/",
    "http://www.tasteline.com/recept/smorgastarta-havet/",
    "http://www.tasteline.com/recept/mini-smorgastarta/",
    "http://www.tasteline.com/recept/claras-rakbomb/",
    "http://www.tasteline.com/recept/claras-klassiska-smorgastarta/",
    "http://www.tasteline.com/recept/smorgastarta-med-mozzarella-och-tomat/",
    "http://www.tasteline.com/recept/smorgastarta-med-tva-sorters-lax/",
    "http://www.tasteline.com/recept/smorgastarta-vegetarisk/",
    "http://www.tasteline.com/recept/underbara-claras-silltarta/",
    "http://www.tasteline.com/recept/tunnbrodsnittar-med-matjesill-och-brynt-smor/",
    "http://www.tasteline.com/recept/mjukt-tunnbrod-med-grillad-sparris-och-vasterbottensost/",
    "http://www.tasteline.com/recept/tunnbrodsnittar-med-farskpotatis-och-groddar/",
    "http://www.tasteline.com/recept/midsommartarta-4/",
    "http://www.tasteline.com/recept/gorgonzolasnittar/",
    "http://www.tasteline.com/recept/kraftsnittar-med-chiliaioli/",
    "http://www.tasteline.com/recept/njallastrutar/",
    "http://www.tasteline.com/recept/snittar-med-vasterbottenskram-och-farskt-fikon/",
    "http://www.tasteline.com/recept/eriks-lada-2/",
    "http://www.tasteline.com/recept/dolma/",
    "http://www.tasteline.com/recept/smorgastarta-med-rokt-renkott-och-fetaost/",
    "http://www.tasteline.com/recept/schweizer-potatismosgratang/",
    "http://www.tasteline.com/recept/saftiga-saffransbullar-utan-kesella/",
    "http://www.tasteline.com/recept/tiramisu-a-la-pepparkakor/",
    "http://www.tasteline.com/recept/kung-pao-gong-bao/",
    "http://www.tasteline.com/recept/sanaz-nyttiga-chokladbollar/",
    "http://www.tasteline.com/recept/reninnerfile-med-potatiskaka-vinsky-och-paprikacreme/",
    "http://www.tasteline.com/recept/flaskkotlett-med-ugnsgrillade-rotsaker-och-tomat-och-ananassalsa/",
    "http://www.tasteline.com/recept/julens-aptitretare/",
    "http://www.tasteline.com/recept/kottfarsbollar-i-mumsig-tomtsas-och-pasta/",
    "http://www.tasteline.com/recept/bananchoklad-milkshakedrink/",
    "http://www.tasteline.com/recept/mangosalsa-och-mango-chutney-dipp-till-grillad-kyckling/",
    "http://www.tasteline.com/recept/stekpannepizza-med-makrill/",
    "http://www.tasteline.com/recept/barbecueanka-och-soppa-med-ramennudlar/",
    "http://www.tasteline.com/recept/tjingeling/",
    "http://www.tasteline.com/recept/flan/",
    "http://www.tasteline.com/recept/fyllda-agghalvor/",
    "http://www.tasteline.com/recept/gravlaxrullar-med-varmrokt-sik-fyllning/",
    "http://www.tasteline.com/recept/skaldjurssallad-i-sallatsblad/",
    "http://www.tasteline.com/recept/tabbens-latta-semlor/",
    "http://www.tasteline.com/recept/julen-i-marsipan/",
    "http://www.tasteline.com/recept/fetaostgratinerad-quornfile-med-rodbetsrisotto/",
    "http://www.tasteline.com/recept/rawfoodgodis-glutenfria-mint-och-chokladrutor/",
    "http://www.tasteline.com/recept/sockerfri-glasstarta/",
    "http://www.tasteline.com/recept/den-optimala-omeletten-2/",
    "http://www.tasteline.com/recept/steamed-buns-med-halstrad-tonfisk/",
    "http://www.tasteline.com/recept/catarinatarta-med-hallonmousse-passionscurd-och-vit-chokladfrosting/",
    "http://www.tasteline.com/recept/laxtataki/",
    "http://www.tasteline.com/recept/chevrefylld-ravioli/",
    "http://www.tasteline.com/recept/varldens-basta-raw-food-paj/",
    "http://www.tasteline.com/recept/nyttig-pizza-med-rawfoodbotten/",
    "http://www.tasteline.com/recept/glutenfri-himmelsk-raw-food-kladdkaka/",
    "http://www.tasteline.com/recept/honungskakor-utan-tillsatt-socker/",
    "http://www.tasteline.com/recept/nyttiga-bananmuffins/",
    "http://www.tasteline.com/recept/farmargryta-med-rotfrukter/",
    "http://www.tasteline.com/recept/lax-och-potatisratt/",
    "http://www.tasteline.com/recept/johanna-westmans-blomkalspure/",
    "http://www.tasteline.com/recept/fikon-och-farskosttartletter/",
    "http://www.tasteline.com/recept/dumplings-med-lime-koriander-och-chilidip/",
    "http://www.tasteline.com/recept/kikartsmarangtarta-med-syrlig-bargradde/",
    "http://www.tasteline.com/recept/mr-king-en-gron-smoothie/",
    "http://www.tasteline.com/recept/veganbuljong/",
    "http://www.tasteline.com/recept/matcha-te-latte/",
    "http://www.tasteline.com/recept/chocolate-heaven-smoothie/",
    "http://www.tasteline.com/recept/gron-stracci-med-farsk-tomat-och-basilika/",
    "http://www.tasteline.com/recept/apelsinmarmelad-med-earl-grey/",
    "http://www.tasteline.com/recept/chokladtryffel-med-stjarnanis/",
    "http://www.tasteline.com/recept/rombollar-2/",
    "http://www.tasteline.com/recept/blueberry-pie-cookies/",
    "http://www.tasteline.com/recept/kanelbullar-7/",
    "http://www.tasteline.com/recept/krabbelurer-2/",
    "http://www.tasteline.com/recept/sockerkaka-6/",
    "http://www.tasteline.com/recept/pannkakor-med-applekompott-och-citrongradde/",
    "http://www.tasteline.com/recept/svartkal-i-agg/",
    "http://www.tasteline.com/recept/miia-s-egen-gronsakssoppa-med-lax/",
    "http://www.tasteline.com/recept/paron-cheesecake/",
    "http://www.tasteline.com/recept/flaskfile-med-chevre-rodbetor-potatis-sallad-3/",
    "http://www.tasteline.com/recept/pasta-med-bacon-2-2/",
    "http://www.tasteline.com/recept/kasslersoppa/",
    "http://www.tasteline.com/recept/t-sas/",
    "http://www.tasteline.com/recept/halstrade-pilgrimsmusslor-i-kall-gron-salsa-med-pistage-och-sockerartor/",
    "http://www.tasteline.com/recept/saffranskokos-med-apelsinsmak/",
    "http://www.tasteline.com/recept/julegris/",
    "http://www.tasteline.com/recept/baklava-3/",
    "http://www.tasteline.com/recept/kycklingrillette-med-apple-och-schalottenlok-2/",
    "http://www.tasteline.com/recept/gyldene-fredens-klassiska-kottbullar/",
    "http://www.tasteline.com/recept/mormors-tomtegrot/",
    "http://www.tasteline.com/recept/mormor-lillys-sillsallad/",
    "http://www.tasteline.com/recept/filodegstrianglar/",
    "http://www.tasteline.com/recept/ostgifflar/",
    "http://www.tasteline.com/recept/julskinka-4/",
    "http://www.tasteline.com/recept/snobollar-med-smak-av-polka/",
    "http://www.tasteline.com/recept/after-eight-muffins-2/",
    "http://www.tasteline.com/recept/paron-after-eight-2/",
    "http://www.tasteline.com/recept/barbakelse-med-after-eight-och-vanilj/",
    "http://www.tasteline.com/recept/glass-med-varm-after-eight-sas/",
    "http://www.tasteline.com/recept/cheesecake-after-eight/",
    "http://www.tasteline.com/recept/after-eight-brownie/",
    "http://www.tasteline.com/recept/after-eight-fluff-2/",
    "http://www.tasteline.com/recept/after-eight-parfait-2/",
    "http://www.tasteline.com/recept/kladdkaka-after-eight-aret-runt-till-julen-pasken-eller-festen/",
    "http://www.tasteline.com/recept/senapssill-3/",
    "http://www.tasteline.com/recept/claras-juliga-smorgastarta/",
    "http://www.tasteline.com/recept/sugar-cookies-3/",
    "http://www.tasteline.com/recept/sugar-cookies-2/",
    "http://www.tasteline.com/recept/sugar-cookies/",
    "http://www.tasteline.com/recept/mint-kyssar/",
    "http://www.tasteline.com/recept/applerulltarta/",
    "http://www.tasteline.com/recept/fyllt-picknickbrod/",
    "http://www.tasteline.com/recept/linus-randiga-bakelser/",
    "http://www.tasteline.com/recept/portvinssill/",
    "http://www.tasteline.com/recept/devils-on-horseback-baconlindade-dadlar/",
    "http://www.tasteline.com/recept/mjall-flaskkarre-med-katrinplommonsky-och-rotfruktspure/",
    "http://www.tasteline.com/recept/rawfood-morotskaka/",
    "http://www.tasteline.com/recept/lammstek-med-chiliglaze-sotpotatis-och-bonor/",
    "http://www.tasteline.com/recept/kristins-algchili/",
    "http://www.tasteline.com/recept/algburgare-med-karamelliserad-rodlok-med-coleslaw/",
    "http://www.tasteline.com/recept/lyxiga-hamburgare-med-svamp-adelost-och-coleslaw/",
    "http://www.tasteline.com/recept/asiatisk-kyckling-i-salladswrap/",
    "http://www.tasteline.com/recept/louise-johanssons-sandefjordsgryta/",
    "http://www.tasteline.com/recept/mattias-kikartsgryta-med-saffran-och-rispapperssamosas/",
    "http://www.tasteline.com/recept/panerad-schnitzel-med-persiljestompad-potatis-och-kaprissallad/",
    "http://www.tasteline.com/recept/stekt-lax-med-avokadodipp-och-haricots-verts/",
    "http://www.tasteline.com/recept/haggans-vegetariska-pastej/",
    "http://www.tasteline.com/recept/fargglad-hostgryta/",
    "http://www.tasteline.com/recept/stromming-nastan-som-krafta/",
    "http://www.tasteline.com/recept/matig-laxsallad/",
    "http://www.tasteline.com/recept/kallrokt-laxsallad/",
    "http://www.tasteline.com/recept/grytstekt-flaskkarre-med-appelsas/",
    "http://www.tasteline.com/recept/mattias-majsplattar-med-avokado-och-chimichurrirora/",
    "http://www.tasteline.com/recept/alggulasch-med-timjan-och-kummin/",
    "http://www.tasteline.com/recept/thaicurrygryta-med-falukorv-och-gronsaker/",
    "http://www.tasteline.com/recept/bonnsupen/",
    "http://www.tasteline.com/recept/baba-gannough-aubergine-yoghurtrora-med-vitlok-citron/",
    "http://www.tasteline.com/recept/tonfiskfile-med-en-anis-och-shitakerisotto/",
    "http://www.tasteline.com/recept/magiskt-goda-chokladmuffins/",
    "http://www.tasteline.com/recept/vinpocherad-torsk-med-pepparrot-och-kokt-potatis/",
    "http://www.tasteline.com/recept/god-kramig-kycklinggryta/",
    "http://www.tasteline.com/recept/pannkakor-7/",
    "http://www.tasteline.com/recept/dragonkyckling-3/",
    "http://www.tasteline.com/recept/ugnsgratinerade-champinjoner/",
    "http://www.tasteline.com/recept/sweet-chili-lax/",
    "http://www.tasteline.com/recept/panerad-gaddfile-med-citron/",
    "http://www.tasteline.com/recept/piri-piri-sas/",
    "http://www.tasteline.com/recept/orientalisk-pizza/",
    "http://www.tasteline.com/recept/korsbarssylt-fran-sorby/",
    "http://www.tasteline.com/recept/torsk-med-parmesanpesto-och-karamelliserade-tomater/",
    "http://www.tasteline.com/recept/lojrom-med-mandelpotatisbakelse/",
    "http://www.tasteline.com/recept/erikas-goda-kokoskyckling/",
    "http://www.tasteline.com/recept/sommartarta-fran-nittsjo/",
    "http://www.tasteline.com/recept/muggkaka-2/",
    "http://www.tasteline.com/recept/cinderella-2/",
    "http://www.tasteline.com/recept/prosciuttosallad-med-granatapple-fikon-och-getost/",
    "http://www.tasteline.com/recept/kryddig-korvgryta-2/",
    "http://www.tasteline.com/recept/lasagne-al-forno/",
    "http://www.tasteline.com/recept/erwings-lax-med-pesto-och-pinjenotter/",
    "http://www.tasteline.com/recept/spaghetti-med-vegetarisk-kottfarssas/",
    "http://www.tasteline.com/recept/tomattarte-med-ugnssbakad-fetaost/",
    "http://www.tasteline.com/recept/majs-och-kikartsplattar-med-sesamfron/",
    "http://www.tasteline.com/recept/spaghetti-limone-parmigiano/",
    "http://www.tasteline.com/recept/spaghetti-alla-puttanesca-2/",
    "http://www.tasteline.com/recept/avokado-och-applesmoothie/",
    "http://www.tasteline.com/recept/midsommaragg/",
    "http://www.tasteline.com/recept/falafelwraps-med-hummus-och-myntayoghurt/",
    "http://www.tasteline.com/recept/vegetariska-kottbullar-med-blomkalsmos-och-rarorda-lingon/",
    "http://www.tasteline.com/recept/knapriga-bananbitar/",
    "http://www.tasteline.com/recept/midsommarmat/",
    "http://www.tasteline.com/recept/erwings-tomatsoppa-med-risoni/",
    "http://www.tasteline.com/recept/moussaka-med-sotpotatis-aubergine/",
    "http://www.tasteline.com/recept/kramig-polenta-med-svamp-kronartskocka/",
    "http://www.tasteline.com/recept/kall-avokadosoppa/",
    "http://www.tasteline.com/recept/glaserade-flaskkotletter-med-matvetesallad-och-fetaostkram/",
    "http://www.tasteline.com/recept/torskrygg-med-brynt-smor-hollandaise-och-fankalssallad/",
    "http://www.tasteline.com/recept/grillad-sparris-med-tryffelhollandaise-och-rostade-mandlar/",
    "http://www.tasteline.com/recept/edamamepasta-med-vitloksfrasta-gronsaker/",
    "http://www.tasteline.com/recept/halloncheesecake-med-havrebotten-och-kolasas/",
    "http://www.tasteline.com/recept/grape-cosmo/",
    "http://www.tasteline.com/recept/saffranspasta-med-zucchini-och-morot/",
    "http://www.tasteline.com/recept/cointreau-fizz-med-jordgubb/",
    "http://www.tasteline.com/recept/cointreau-fizz-med-mynta/",
    "http://www.tasteline.com/recept/rotfruktsplattar-med-keso-bacon-och-rarorda-lingon/",
    "http://www.tasteline.com/recept/grillade-rotfrukter-med-saganaki-och-basilikadipp/",
    "http://www.tasteline.com/recept/erwings-cevapcici/",
    "http://www.tasteline.com/recept/nyttiga-frukostmuffins-med-kesella-och-pumpakarnor/",
    "http://www.tasteline.com/recept/ugnsgrillad-flaskfile-med-bacon-och-kaprisvinagrett/",
    "http://www.tasteline.com/recept/nikkaluoktasoppa-2/",
    "http://www.tasteline.com/recept/cajunkraftor-2/",
    "http://www.tasteline.com/recept/grundrecept-for-ny-kraftlag/",
    "http://www.tasteline.com/recept/eton-mess-3/",
    "http://www.tasteline.com/recept/salami-e-ricotta-con-rucola/",
    "http://www.tasteline.com/recept/hellman-s-hamburgare-med-hemmagjort-brod/",
    "http://www.tasteline.com/recept/cole-slaw-2/",
    "http://www.tasteline.com/recept/lollipopcorn-2/",
    "http://www.tasteline.com/recept/lakritsdrommar/",
    "http://www.tasteline.com/recept/fladermoussetarta-med-jordgubbar/",
    "http://www.tasteline.com/recept/hel-saltbakad-havsabborre-med-pepparrot-och-rakor/",
    "http://www.tasteline.com/recept/snabbpizza-2/",
    "http://www.tasteline.com/recept/panzerotti-med-salmalax/",
    "http://www.tasteline.com/recept/bratwurst-med-syrad-vitkal-2/",
    "http://www.tasteline.com/recept/pastatarta-2/",
    "http://www.tasteline.com/recept/smulpajdeg-med-agg-och-bakpulver/",
    "http://www.tasteline.com/recept/afrikansk-kikartsgryta/",
    "http://www.tasteline.com/recept/ljuvlig-chokladfondant-glutenfri-och-sockerfri/",
    "http://www.tasteline.com/recept/renande-ananas-smoothie/",
    "http://www.tasteline.com/recept/superenkla-bountys/",
    "http://www.tasteline.com/recept/kokoskokt-quinoagrot/",
    "http://www.tasteline.com/recept/tobbes-snabba-kottfarssas/",
    "http://www.tasteline.com/recept/masklex-s-grogg/",
    "http://www.tasteline.com/recept/quinoabiffar-med-sotstark-paprikasas/",
    "http://www.tasteline.com/recept/bacon-och-adelostsoppa/",
    "http://www.tasteline.com/recept/bullar-basta-bullen-glutenfri/",
    "http://www.tasteline.com/recept/ungkarlslapskojs/",
    "http://www.tasteline.com/recept/falukorv-med-ratatouillesas-och-spaghetti/",
    "http://www.tasteline.com/recept/lokdolmar-med-ugnsbakad-potatis-anna/",
    "http://www.tasteline.com/recept/rapsgrisdumplings-med-plommonsas-2/",
    "http://www.tasteline.com/recept/honungsstekt-karre-med-artpure-och-sesamrostad-potatis-med-getost/",
    "http://www.tasteline.com/recept/timjanstekt-kotlett-med-svartvinbarslok-och-samt-jordartskockstomp/",
    "http://www.tasteline.com/recept/rapsgrisschnitzel-med-kapris-citron-och-rodbetstzatziki/",
    "http://www.tasteline.com/recept/lagtemperaturstekt-flaskkarre-med-blomkalskram-och-en-rostad-sallad-pa-morotter-och-salladslok/",
    "http://www.tasteline.com/recept/kryddstekt-skinka-med-bulgursallad-aprikoser-och-hasselnotter/",
    "http://www.tasteline.com/recept/rapsgris-bacon-lokpaj-med-spenatsallad/",
    "http://www.tasteline.com/recept/rapsgriskorv-med-vita-bonor-och-baconstrimlor/",
    "http://www.tasteline.com/recept/helstekt-gremolatafile-med-tomatrisotto/",
    "http://www.tasteline.com/recept/helstekt-ortkarre-med-fankal-och-appelsallad/",
    "http://www.tasteline.com/recept/pulled-pork-4/",
    "http://www.tasteline.com/recept/vitlok-och-rosmarinstekt-kotlett-med-ingefarsinlagd-cocktailtomat/",
    "http://www.tasteline.com/recept/grillad-karre-med-appelpotatissallad/",
    "http://www.tasteline.com/recept/baconlindad-zucchini-med-ugnsrostade-rodbetor-pinjenotter-och-dragoncreme/",
    "http://www.tasteline.com/recept/baconlindad-appelkyckling-med-ugnsrostade-rotsaker-och-citroncreme/",
    "http://www.tasteline.com/recept/mustig-falukorvsgryta-med-krossade-tomater-majs-och-bonor/",
    "http://www.tasteline.com/recept/falukorvsgratang-med-blomkal-broccoli-och-soltorkade-tomater/",
    "http://www.tasteline.com/recept/kokosapple-kaka/",
    "http://www.tasteline.com/recept/tomatsoppa-med-adelost/",
    "http://www.tasteline.com/recept/sotpotatischips-med-pilgrimsmussla/",
    "http://www.tasteline.com/recept/quesadillas-med-bonor-och-tomatsalsa/",
    "http://www.tasteline.com/recept/den-perfekta-saffranspanncottan/",
    "http://www.tasteline.com/recept/mangosalsa-9-2/",
    "http://www.tasteline.com/recept/frisk-sommarbal-med-jordgubbssirap/",
    "http://www.tasteline.com/recept/jordgubbslemonad/",
    "http://www.tasteline.com/recept/hallonsas-till-grillat/",
    "http://www.tasteline.com/recept/muscovadomarinad/",
    "http://www.tasteline.com/recept/eton-mess-2/",
    "http://www.tasteline.com/recept/harliga-chokladvafflor/",
    "http://www.tasteline.com/recept/brownietarta-med-fluffig-marang/",
    "http://www.tasteline.com/recept/basrecept-sylt-smakvariationer/",
    "http://www.tasteline.com/recept/graddbullar/",
    "http://www.tasteline.com/recept/krispiga-blabarbars/",
    "http://www.tasteline.com/recept/choklad-och-havrekakor-med-jordnotsfrosting/",
    "http://www.tasteline.com/recept/cheesecakeglass-med-svarta-vinbar/",
    "http://www.tasteline.com/recept/bjornbarscobbler-i-portionsformar/",
    "http://www.tasteline.com/recept/bjornbarssylt-med-gin/",
    "http://www.tasteline.com/recept/muscovadokakor/",
    "http://www.tasteline.com/recept/lasange-ala-djungelhyddans-tropical-lounge/",
    "http://www.tasteline.com/recept/chokladmuffins-7/",
    "http://www.tasteline.com/recept/islatte-hasselnot/",
    "http://www.tasteline.com/recept/sojaccino/",
    "http://www.tasteline.com/recept/gronkalspaj-2/",
    "http://www.tasteline.com/recept/lax-och-spenatpaj-2/",
    "http://www.tasteline.com/recept/gnocchi-2/",
    "http://www.tasteline.com/recept/kikartspasta-2/",
    "http://www.tasteline.com/recept/chocolate-mocha-haze/",
    "http://www.tasteline.com/recept/tomatsoppa-med-halloumi/",
    "http://www.tasteline.com/recept/forbranningsdrink/",
    "http://www.tasteline.com/recept/chocolate-cardamon-mocha/",
    "http://www.tasteline.com/recept/stinsens-kraftsoppa/",
    "http://www.tasteline.com/recept/caramel-ice-coffee/",
    "http://www.tasteline.com/recept/rabarber-serverad-med-kazaar-glass/",
    "http://www.tasteline.com/recept/lammpolpette-med-spaghetti-och-vitlosbrod/",
    "http://www.tasteline.com/recept/lattlagad-fisksoppa/",
    "http://www.tasteline.com/recept/torskrygg-i-pepparrotsas-med-parmesandoftande-potatispure/",
    "http://www.tasteline.com/recept/spenatrisotto-3/",
    "http://www.tasteline.com/recept/saftig-tacopaj/",
    "http://www.tasteline.com/recept/gronkalschips-3/",
    "http://www.tasteline.com/recept/knapriga-muslibars/",
    "http://www.tasteline.com/recept/granolabars-med-notter/",
    "http://www.tasteline.com/recept/halloumi-och-gronsaksburgare/",
    "http://www.tasteline.com/recept/kladdkaka-grande/",
    "http://www.tasteline.com/recept/en-ekologisk-sommartarta/",
    "http://www.tasteline.com/recept/kycklingkorv-2/",
    "http://www.tasteline.com/recept/chilikorv/",
    "http://www.tasteline.com/recept/rostad-paronsallad-med-adelost-och-valnotter/",
    "http://www.tasteline.com/recept/arepas/",
    "http://www.tasteline.com/recept/oxfile-med-kantarellsas-och-wokade-gronsaker/",
    "http://www.tasteline.com/recept/fisksoppa-med-vitlokscreme/",
    "http://www.tasteline.com/recept/avokadosmoothie-med-superingredienser/",
    "http://www.tasteline.com/recept/sauterad-gronkal-med-bacon-och-mandlar/",
    "http://www.tasteline.com/recept/linssoppa-med-cirry/",
    "http://www.tasteline.com/recept/tonfiskpasta-8/",
    "http://www.tasteline.com/recept/tonfiskpasta-7-2/",
    "http://www.tasteline.com/recept/spaghetti-carbonara-med-touch-av-citron-och-chili-2/",
    "http://www.tasteline.com/recept/scones-3-2/",
    "http://www.tasteline.com/recept/spelande-oscar/",
    "http://www.tasteline.com/recept/jordnot-chokladkaka/",
    "http://www.tasteline.com/recept/mustig-korvgryta-med-senapsaioli/",
    "http://www.tasteline.com/recept/karleksmums-3-2/",
    "http://www.tasteline.com/recept/getosttarteletter-med-tomatsalsa/",
    "http://www.tasteline.com/recept/cheesecake-11/",
    "http://www.tasteline.com/recept/lingonparfait-2/",
    "http://www.tasteline.com/recept/svart-bonpasta-med-chorizosas/",
    "http://www.tasteline.com/recept/mjukt-tunnbrod-3/",
    "http://www.tasteline.com/recept/mustig-vintergryta/",
    "http://www.tasteline.com/recept/italiensk-potatissallad-3/",
    "http://www.tasteline.com/recept/jordnotschoklad/",
    "http://www.tasteline.com/recept/ingrids-enbarsgravade-lax/",
    "http://www.tasteline.com/recept/nyarsfile-med-rotsakskaka-och-rodvinssas/",
    "http://www.tasteline.com/recept/honokaka-3/",
    "http://www.tasteline.com/recept/lollos-lojromssill/",
    "http://www.tasteline.com/recept/leffes-lax/",
    "http://www.tasteline.com/recept/mozartkulor-4/",
    "http://www.tasteline.com/recept/sallad-pa-fikon-och-getost-med-en-ljummen-vinagrett/",
    "http://www.tasteline.com/recept/son-kyckling/",
    "http://www.tasteline.com/recept/asdfadsfds/",
    "http://www.tasteline.com/recept/harligt-valnotsbrod/",
    "http://www.tasteline.com/recept/nutellafudge/",
    "http://www.tasteline.com/recept/saffransbullar-med-vaniljkram/",
    "http://www.tasteline.com/recept/gron-artsoppa-med-mer-lok/",
    "http://www.tasteline.com/recept/gulaschsoppa-med-bulgur/",
    "http://www.tasteline.com/recept/indisk-vegetarisk-farssas-med-garam-masala/",
    "http://www.tasteline.com/recept/miia-s-suutarinlohta-skomakarlax/",
    "http://www.tasteline.com/recept/potatissoppa-med-parmesan/",
    "http://www.tasteline.com/recept/zereshkpolo-persisk-matratt-med-kyckling/",
    "http://www.tasteline.com/recept/torsk-i-hummersas/",
    "http://www.tasteline.com/recept/chiapudding-med-hallon/",
    "http://www.tasteline.com/recept/flaskfile-med-ugnsrostade-morotter-med-getostcreme-och-pinjenotter/",
    "http://www.tasteline.com/recept/dadlar-med-taleggio-och-tapenade/",
    "http://www.tasteline.com/recept/smordegspuffar-med-getost/",
    "http://www.tasteline.com/recept/kebabtarta/",
    "http://www.tasteline.com/recept/fyllda-dadlar/",
    "http://www.tasteline.com/recept/varm-chokladbakelse-med-apelsinsallad-och-frysta-lingon/",
    "http://www.tasteline.com/recept/julsnittar/",
    "http://www.tasteline.com/recept/glutenfri-prinsesstarta/",
    "http://www.tasteline.com/recept/ljust-matbrod-med-honung-i-cloche/",
    "http://www.tasteline.com/recept/ljust-matbrod-i-cloche/",
    "http://www.tasteline.com/recept/godaste-kycklingpajen/",
    "http://www.tasteline.com/recept/godaste-banan-muffins/",
    "http://www.tasteline.com/recept/julens-godaste-smorgastarta/",
    "http://www.tasteline.com/recept/aggsoppa/",
    "http://www.tasteline.com/recept/falukorv-deluxe/",
    "http://www.tasteline.com/recept/hotshot-mousse/",
    "http://www.tasteline.com/recept/mexikansk-salamimacka/",
    "http://www.tasteline.com/recept/kalkonrulle-med-coleslaw/",
    "http://www.tasteline.com/recept/regnbagsmacka-med-prickig-korv/",
    "http://www.tasteline.com/recept/het-pizzamacka-med-cool-keso/",
    "http://www.tasteline.com/recept/currynamnam-baguette/",
    "http://www.tasteline.com/recept/kladdkaka-med-toscatacke/",
    "http://www.tasteline.com/recept/kladdkaka-med-daimtacke-2-2/",
    "http://www.tasteline.com/recept/flygande-jakob/",
    "http://www.tasteline.com/recept/sillsallad-5/",
    "http://www.tasteline.com/recept/glutenfri-kladdkaka-5/",
    "http://www.tasteline.com/recept/dumlecheesecake/",
    "http://www.tasteline.com/recept/korvlada/",
    "http://www.tasteline.com/recept/mjolkchokladsittar/",
    "http://www.tasteline.com/recept/kladdig-citronkaka/",
    "http://www.tasteline.com/recept/banankaka-med-mjolkchokladglasyr/",
    "http://www.tasteline.com/recept/mjuk-kladdkaka-med-mjolkchoklad/",
    "http://www.tasteline.com/recept/staffans-lyxiga-tonic-water/",
    "http://www.tasteline.com/recept/staffans-tonic-water-citrus-tonic/",
    "http://www.tasteline.com/recept/tonic-water-staffans-enkla-essens/",
    "http://www.tasteline.com/recept/stockholmare-kallt-tilltugg/",
    "http://www.tasteline.com/recept/vita-kladdkakepajer/",
    "http://www.tasteline.com/recept/arroz-con-leche/",
    "http://www.tasteline.com/recept/amerikanska-pannkakor-8/",
    "http://www.tasteline.com/recept/enchiladas-med-kyckling/",
    "http://www.tasteline.com/recept/snickerskakor/",
    "http://www.tasteline.com/recept/gorgonzola-och-flaskfilegryta/",
    "http://www.tasteline.com/recept/chokladiga-kladdkakemuffins/",
    "http://www.tasteline.com/recept/kallarfranska/",
    "http://www.tasteline.com/recept/algkottbullar/",
    "http://www.tasteline.com/recept/avokado-och-ortdressing/",
    "http://www.tasteline.com/recept/tobleronemousse-2/",
    "http://www.tasteline.com/recept/peters-slottsstek/",
    "http://www.tasteline.com/recept/kladdkaka-med-center/",
    "http://www.tasteline.com/recept/knackig-och-seg-blabarspaj/",
    "http://www.tasteline.com/recept/triple-chocolate-cookies/",
    "http://www.tasteline.com/recept/latt-kalpudding/",
    "http://www.tasteline.com/recept/marias-lyxiga-kottfarssas/",
    "http://www.tasteline.com/recept/biff-med-ugnsbakade-gronsaker-och-gron-parmesancreme/",
    "http://www.tasteline.com/recept/linsoppa-med-curry-och-saffran/",
    "http://www.tasteline.com/recept/raktacos-med-en-fruktig-het-salsa/",
    "http://www.tasteline.com/recept/ortspackad-vildsvinsstek-med-senapssky-och-saltrostad-potatis/",
    "http://www.tasteline.com/recept/vildsvinschili-med-choklad-jalapeno-och-gurksalsa/",
    "http://www.tasteline.com/recept/torskburgare-med-citron-och-pepparrot/",
    "http://www.tasteline.com/recept/kottbulls-och-tomatsoppa/",
    "http://www.tasteline.com/recept/smulpaj-med-paron-choklad-mint/",
    "http://www.tasteline.com/recept/musli-med-choklad-notter-gryn/",
    "http://www.tasteline.com/recept/kladdkaka-med-brynt-smor/",
    "http://www.tasteline.com/recept/cupcakes-5/",
    "http://www.tasteline.com/recept/chokladsnittar/",
    "http://www.tasteline.com/recept/chokladskedar/",
    "http://www.tasteline.com/recept/chokladsas-med-pancakes/",
    "http://www.tasteline.com/recept/churros-med-chokladsas/",
    "http://www.tasteline.com/recept/chokladpudding-med-rostade-hasselnotter/",
    "http://www.tasteline.com/recept/chokladfudge/",
    "http://www.tasteline.com/recept/chokladdoppade-glasspinnar/",
    "http://www.tasteline.com/recept/chokladcreme/",
    "http://www.tasteline.com/recept/chokladbiskvier/",
    "http://www.tasteline.com/recept/chiligryta-med-choklad/",
    "http://www.tasteline.com/recept/wasabi-lax-med-wokade-gronsaker/",
    "http://www.tasteline.com/recept/kycklinggryta-med-chili/",
    "http://www.tasteline.com/recept/kycklingcurry/",
    "http://www.tasteline.com/recept/flaskfile-a-la-solvik/",
    "http://www.tasteline.com/recept/rustikt-knackebrod/",
    "http://www.tasteline.com/recept/melanzane-parmigiana/",
    "http://www.tasteline.com/recept/chili-till-en-gast/",
    "http://www.tasteline.com/recept/honungslax-med-citron-och-ingefara/",
    "http://www.tasteline.com/recept/passionsfruktsglass/",
    "http://www.tasteline.com/recept/ugnsstekt-kyckling-med-glasnudlar-och-ananassalsa/",
    "http://www.tasteline.com/recept/lammsaute-med-tomat-och-blandade-gronsaker/",
    "http://www.tasteline.com/recept/rullader-med-aubergine/",
    "http://www.tasteline.com/recept/sicilianska-gnocchi/",
    "http://www.tasteline.com/recept/caponata-med-zucchini/",
    "http://www.tasteline.com/recept/timjankaramelliserad-lax-knaprig-polenta-och-finkrossad-tomat-med-basilika-och-lok/",
    "http://www.tasteline.com/recept/kryddstarka-kottbullar/",
    "http://www.tasteline.com/recept/nyttiga-glutenfria-frukostmuffins/",
    "http://www.tasteline.com/recept/tomatsoppa-med-crostini/",
    "http://www.tasteline.com/recept/flaskfile-pa-sydskanskt-vis/",
    "http://www.tasteline.com/recept/linguine-med-stora-rakor-och-mutti-finkrossade-tomater/",
    "http://www.tasteline.com/recept/avokadorora/",
    "http://www.tasteline.com/recept/cashewrora/",
    "http://www.tasteline.com/recept/fetaostrora/",
    "http://www.tasteline.com/recept/kalvkotletter-pa-planka-med-potatismos-och-ortsas/",
    "http://www.tasteline.com/recept/spenatcarbonara-med-bonpasta/",
    "http://www.tasteline.com/recept/smoked-pulled-pork/",
    "http://www.tasteline.com/recept/morotsjuice-med-ingefara-och-applen/",
    "http://www.tasteline.com/recept/chokladbrack/",
    "http://www.tasteline.com/recept/ljummen-potatissallad-med-farska-orter/",
    "http://www.tasteline.com/recept/bakad-potatis-med-chevre-farska-orter-och-apple/",
    "http://www.tasteline.com/recept/hemmagjorda-glutenfria-dammsugare/",
    "http://www.tasteline.com/recept/mustig-kycklinggratang/",
    "http://www.tasteline.com/recept/romansgrytan-med-avokado/",
    "http://www.tasteline.com/recept/lemon-vodka-grogg/",
    "http://www.tasteline.com/recept/persiko-och-portobelloburgare/",
    "http://www.tasteline.com/recept/marockansk-fisktagine-med-saffran-och-grona-oliver/",
    "http://www.tasteline.com/recept/pulled-beef-med-anchochili/",
    "http://www.tasteline.com/recept/saras-yoghurtglass-med-mango-hallon-och-lakrits/",
    "http://www.tasteline.com/recept/sashimi-med-ingefara-lime-och-chili-pa-salladsbadd/",
    "http://www.tasteline.com/recept/rosa-wraps-med-getost-och-rodbetor/",
    "http://www.tasteline.com/recept/melongazpacho/",
    "http://www.tasteline.com/recept/enkel-supergod-chokladkaka-3-ingredienser/",
    "http://www.tasteline.com/recept/nyttig-glass/",
    "http://www.tasteline.com/recept/rawfood-chokladmousse/",
    "http://www.tasteline.com/recept/nyttigare-chokladmousse/",
    "http://www.tasteline.com/recept/chokladig-granolamusli/",
    "http://www.tasteline.com/recept/sallad-med-avocado-mozzarella-och-rakor/",
    "http://www.tasteline.com/recept/svartvinbarssorbet-pa-saft/",
    "http://www.tasteline.com/recept/wraps-med-rostbiff/",
    "http://www.tasteline.com/recept/kryddig-gazpacho/",
    "http://www.tasteline.com/recept/korv-stroganoff/",
    "http://www.tasteline.com/recept/mangoquesadilla/",
    "http://www.tasteline.com/recept/miias-fiskrullader-pa-abborre/",
    "http://www.tasteline.com/recept/focaccia-med-soltorkad-tomatolja/",
    "http://www.tasteline.com/recept/punschglass/",
    "http://www.tasteline.com/recept/mini-chokladmuffins/",
    "http://www.tasteline.com/recept/bananglass-med-riven-choklad/",
    "http://www.tasteline.com/recept/glasstarta-med-hasselnotsmarang/",
    "http://www.tasteline.com/recept/jordgubbsmoussetarta-med-havresmulbotten/",
    "http://www.tasteline.com/recept/sallad-med-bacon-och-halloumi/",
    "http://www.tasteline.com/recept/pulled-pork-med-tacokrydda/",
    "http://www.tasteline.com/recept/noras-kladdtarta/",
    "http://www.tasteline.com/recept/flaskstek-med-rosmarin-arista/",
    "http://www.tasteline.com/recept/raita-med-gurka/",
    "http://www.tasteline.com/recept/chicken-tikka-masala-3/",
    "http://www.tasteline.com/recept/kokos-papadums/",
    "http://www.tasteline.com/recept/kramig-indisk-gryta/",
    "http://www.tasteline.com/recept/indisk-linssoppa/",
    "http://www.tasteline.com/recept/jordgubbstarta-2/",
    "http://www.tasteline.com/recept/medelhavspasta-med-aubergine/",
    "http://www.tasteline.com/recept/fisk-med-dijonsenapssas-och-farska-orter/",
    "http://www.tasteline.com/recept/gravlaxsas-5/",
    "http://www.tasteline.com/recept/lyxig-jordgubbs-och-passions-smoothie/",
    "http://www.tasteline.com/recept/chokladdoppade-jordgubbar-pa-pinne/",
    "http://www.tasteline.com/recept/lakritsglass-med-godis/",
    "http://www.tasteline.com/recept/rakpizza/",
    "http://www.tasteline.com/recept/hamburgare-med-cheddar-karamelliserad-lok-ugnsbakad-tomat-och-tryffelmajonnas/",
    "http://www.tasteline.com/recept/the-steak-grillad-hel-biff-med-vit-balsamvinagerdressing-och-grillad-citron/",
    "http://www.tasteline.com/recept/midsommartarta/",
    "http://www.tasteline.com/recept/kycklinggratang-med-klyftpotatis/",
    "http://www.tasteline.com/recept/kebab/",
    "http://www.tasteline.com/recept/sallad-med-chevre-jordgubbar-och-apple-med-kanel/",
    "http://www.tasteline.com/recept/flinkmans-citronmarangpaj/",
    "http://www.tasteline.com/recept/pannkakstarta/",
    "http://www.tasteline.com/recept/korsbarspaj-med-mandelsmul/",
    "http://www.tasteline.com/recept/no-bake-raw-citronpaj/",
    "http://www.tasteline.com/recept/falafelburgare-med-cashewtzatziki/",
    "http://www.tasteline.com/recept/tofuwok-teriyaki/",
    "http://www.tasteline.com/recept/tagliatelle-med-bonbollar-i-tomatsas/",
    "http://www.tasteline.com/recept/coleslaw-4/",
    "http://www.tasteline.com/recept/lokrelish/",
    "http://www.tasteline.com/recept/asiatisk-portobellosvamp-med-ingefara-chili-och-paksoi/",
    "http://www.tasteline.com/recept/scrambled-eggs-aggrora/",
    "http://www.tasteline.com/recept/rakor-och-portobello-svamp-med-vitloksfrast-kal/",
    "http://www.tasteline.com/recept/kramig-laxpasta-med-spenat/",
    "http://www.tasteline.com/recept/scrambledegg-med-kallrokt-lax-och-avokado-creme/",
    "http://www.tasteline.com/recept/morot-och-ingefarssoppa-med-fetaost/",
    "http://www.tasteline.com/recept/ginas-burgare-med-pulled-chicken-och-coleslaw/",
    "http://www.tasteline.com/recept/toscaglaserad-mazarintarta/",
    "http://www.tasteline.com/recept/tropisk-fruktsallad-med-romgradde/",
    "http://www.tasteline.com/recept/lamm-biff-rydberg-med-endiver/",
    "http://www.tasteline.com/recept/karamelliserade-endiver-underbart-tillbehor/",
    "http://www.tasteline.com/recept/fruktsmoothie-smoothietips/",
    "http://www.tasteline.com/recept/en-annorlunda-carbonara-pa-salami/",
    "http://www.tasteline.com/recept/chokladmousse-med-vuxensmak/",
    "http://www.tasteline.com/recept/tomatsalsa/",
    "http://www.tasteline.com/recept/philadelphia-med-citron-och-myntasparris/",
    "http://www.tasteline.com/recept/philadelphia-med-fikon-valnotter-och-serranoskinka/",
    "http://www.tasteline.com/recept/philadelphia-caprese-salad/",
    "http://www.tasteline.com/recept/philadelphia-med-kronartskocka-och-parmaskinka/",
    "http://www.tasteline.com/recept/butternutsquashsoppa/",
    "http://www.tasteline.com/recept/bacon-och-majsmuffins/",
    "http://www.tasteline.com/recept/kerstins-kottfarssoppa/",
    "http://www.tasteline.com/recept/salladsskal-med-cashew-och-farsfras/",
    "http://www.tasteline.com/recept/vietnamesisk-glasnudelsallad-med-grillad-rostbiff/",
    "http://www.tasteline.com/recept/vit-sparris-pa-tyska-med-skinka-och-smalt-smor-och-ev-persiljepotatis/",
    "http://www.tasteline.com/recept/risotto-milanese/",
    "http://www.tasteline.com/recept/pasta-puttanesca-med-sardeller-kapris-tomat-och-oliver/",
    "http://www.tasteline.com/recept/pasta-med-lattlagad-gronsas-pa-spenat/",
    "http://www.tasteline.com/recept/passionsfrukts-och-chokladmoussetarta-pa-mandelbotten/",
    "http://www.tasteline.com/recept/ost-och-skinkpaj-quiche-lorraine/",
    "http://www.tasteline.com/recept/insalata-caprese-mozzarella-och-tomatsallad-fran-capri/",
    "http://www.tasteline.com/recept/kinesisk-kycklinggryta-med-schezuanpeppar/",
    "http://www.tasteline.com/recept/janssons-frestelse-pa-farskpotatis/",
    "http://www.tasteline.com/recept/ugnsstekt-lax-med-broccolimousse-och-citronpotatis/",
    "http://www.tasteline.com/recept/rodvinssas-5/",
    "http://www.tasteline.com/recept/provencalsk-gronsaksrora-pa-paprika-fankal-och-lok/",
    "http://www.tasteline.com/recept/lyxig-rustik-lojromstoast/",
    "http://www.tasteline.com/recept/lyxig-paskbrunch/",
    "http://www.tasteline.com/recept/blomkalsmousse-med-tryffel/",
    "http://www.tasteline.com/recept/lattrimmad-torsk-med-beurre-blanc-och-broccolimousse/",
    "http://www.tasteline.com/recept/sallad-med-krispig-parmaskinka/",
    "http://www.tasteline.com/recept/vegetarisk-maki-med-svart-raris/",
    "http://www.tasteline.com/recept/spenatplattar-med-fetaost-och-grekisk-sallad/",
    "http://www.tasteline.com/recept/rotfruktsplattar-med-keso-och-rarorda-lingon/",
    "http://www.tasteline.com/recept/pasta-med-rostad-rodbetspesto/",
    "http://www.tasteline.com/recept/chorizo-gor-dina-egna-goda-korvar/",
    "http://www.tasteline.com/recept/vargron-nyttig-smoothie/",
    "http://www.tasteline.com/recept/tropisk-smoothie/",
    "http://www.tasteline.com/recept/solskenssmoothie-pa-apelsin-och-mango/",
    "http://www.tasteline.com/recept/potatisgratang-i-portionskokott-med-parmesan/",
    "http://www.tasteline.com/recept/pistagemaranger/",
    "http://www.tasteline.com/recept/kramig-citronpaj/",
    "http://www.tasteline.com/recept/kycklingkorv/",
    "http://www.tasteline.com/recept/katinkas-vaniljsmorbullar/",
    "http://www.tasteline.com/recept/kardemummabrulee/",
    "http://www.tasteline.com/recept/kaffemoussetarta-pa-mandelbotten/",
    "http://www.tasteline.com/recept/graddstuvad-purjolok-fantastiskt-enkelt-och-gott-tillbehor/",
    "http://www.tasteline.com/recept/graddstuvad-purjolok-med-lojrom-till-forratt/",
    "http://www.tasteline.com/recept/dekonstruerad-lammstek/",
    "http://www.tasteline.com/recept/broccolimousse-gott-tillbehor/",
    "http://www.tasteline.com/recept/brod-bakat-pa-vita-bonor/",
    "http://www.tasteline.com/recept/purjo-och-potatissoppa/",
    "http://www.tasteline.com/recept/treveckorssallad/",
    "http://www.tasteline.com/recept/goddig-smorgastarta/",
    "http://www.tasteline.com/recept/pilgrimsmusslor-pa-badd-av-juliennegronsaker-med-beurre-blanc/",
    "http://www.tasteline.com/recept/paskens-lammstek/",
    "http://www.tasteline.com/recept/matjessillrora/",
    "http://www.tasteline.com/recept/kramig-aggrora-med-rokt-lax/",
    "http://www.tasteline.com/recept/citronpotatis/",
    "http://www.tasteline.com/recept/ceviche-pa-lax-pa-svenskt-vis-med-forellrom/",
    "http://www.tasteline.com/recept/philadelphia-frukostmacka/",
    "http://www.tasteline.com/recept/philadelphiasmorgas-med-radisa/",
    "http://www.tasteline.com/recept/trines-snabba-nudelsoppa/",
    "http://www.tasteline.com/recept/thailandska-nudlar-pad-thai/",
    "http://www.tasteline.com/recept/thailandsk-kycklingbuljong/",
    "http://www.tasteline.com/recept/spicy-thai-tuna-snack/",
    "http://www.tasteline.com/recept/satayspett/",
    "http://www.tasteline.com/recept/het-och-syrlig-thaisoppa-med-kungsrakor/",
    "http://www.tasteline.com/recept/gron-thai-curry-med-kokosmjolk-och-kyckling/",
    "http://www.tasteline.com/recept/mjuk-citronkaka/",
    "http://www.tasteline.com/recept/kebabgryta/",
    "http://www.tasteline.com/recept/pasta-med-god-kott-blandning/",
    "http://www.tasteline.com/recept/kladdkaka-med-kokostosca-i-langpanna/",
    "http://www.tasteline.com/recept/spareribs/",
    "http://www.tasteline.com/recept/grapefruktmarmelad-med-jordgubbar/",
    "http://www.tasteline.com/recept/muscovadomousse/",
    "http://www.tasteline.com/recept/choklad-kolakram/",
    "http://www.tasteline.com/recept/kolakakor/",
    "http://www.tasteline.com/recept/glutenfritt-fullkornsbrod/",
    "http://www.tasteline.com/recept/kryddigt-ragknacke/",
    "http://www.tasteline.com/recept/apelsinmarmelad-med-vin-och-pistage/",
    "http://www.tasteline.com/recept/rabarbermarmelad/",
    "http://www.tasteline.com/recept/glutenfritt-knackebrod-2/",
    "http://www.tasteline.com/recept/emils-bbq-sas/",
    "http://www.tasteline.com/recept/muscovadocookies/",
    "http://www.tasteline.com/recept/apelsinclafouti/",
    "http://www.tasteline.com/recept/sma-blabarspajer-pa-pinne-pajpops/",
    "http://www.tasteline.com/recept/blabarspaj-6/",
    "http://www.tasteline.com/recept/falsk-mandelkaka/",
    "http://www.tasteline.com/recept/jordgubbsflan/",
    "http://www.tasteline.com/recept/het-flaskfile-med-bacon/",
    "http://www.tasteline.com/recept/texmexgratang/",
    "http://www.tasteline.com/recept/oppen-lasagne-med-spenat-ricotta-och-mandelpesto/",
    "http://www.tasteline.com/recept/skaldjurssas-med-cognac/",
    "http://www.tasteline.com/recept/vitvinsas/",
    "http://www.tasteline.com/recept/tacotarta/",
    "http://www.tasteline.com/recept/rodvinsas/",
    "http://www.tasteline.com/recept/pepparsas-stark/"];
let filename = "tasteline/tasteline-7.1-2017-11-12.json";

nightmare
    .goto('http://www.tasteline.com/recept/')
    .evaluate(function () {

    })
    .then(function (hrefs) {

        console.log("start");
        console.log("nr of urls: " + urls.length);
        uniqurls = [...new Set(urls)];
        console.log("uniq : " + uniqurls.length);
        return uniqurls.reduce(function (accumulator, href) {
            return accumulator.then(function (results) {
                return nightmare.goto(href)
                    .evaluate(function () {
                        if (!document.querySelector('.page-content .recipe-content')) {
                            return;
                        }
                        let recipe = {};
                        //title
                        recipe.title = document.querySelector('.page-content .recipe-description h1').innerHTML.trim();
                        //tags
                        let tags = {};
                        //cannot read property length of null
                        $('.page-content .recipe-description .category-list a').each(function () {
                            let t = $(this).text();
                            if (t.match(/^[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]*$/)) {
                                t = t + "FAILEDTAG";
                            }
                            tags[t.charAt(0).toUpperCase() + t.slice(1).replace(/\s*\([^()]*\)$/, '').split(",")[0].replace(/([/.#$])/g, '').trim()] = true;

                        })
                        recipe.tags = tags;
                        //source
                        recipe.source = window.location.href;

                        //votes rating
                        if (document.querySelector('.page-content .recipe-description .recipe-rating.voting-enabled i')) {
                            let ratingLine = document.querySelector('.page-content .recipe-description .recipe-rating.voting-enabled').getAttribute("title");
                            let parts = ratingLine.split("Antal röster:");
                            recipe.votes = parts[1].trim();
                            recipe.rating = parts[0].split(":")[1].trim();
                        }
                        //author
                        if (document.querySelector('.page-content .recipe-author-text-inner span')) {
                            recipe.author = document.querySelector('.page-content .recipe-author-text-inner span').innerText.trim();
                        } else {
                            recipe.author = "tasteline.com";
                        }

                        //createdFor

                        //portions
                        if (document.querySelector('.page-content .recipe-content .portions')) {
                            recipe.portions = document.querySelector('.page-content .recipe-content .portions').getAttribute('data-portions');
                        }
                        //created

                        //description
                        if (document.querySelector('.page-content .recipe-ingress')) {
                            recipe.description = document.querySelector('.page-content .recipe-ingress').innerHTML.replace(/(\r\n|\n|\r|<[^>]*>)/gm, "").replace(/  +/g, ' ').trim();
                        }

                        //time
                        if (document.querySelector('.page-content .recipe-description .fa-clock-o')) {
                            recipe.time = document.querySelector('.page-content .recipe-description .fa-clock-o').nextSibling.nodeValue.trim();
                            let parts = recipe.time.split(" ");
                            if (parts.length === 2 && (parts[1] === "min" || parts[1] === "minuter") && parts[0] < 30) {
                                if (!tags.hasOwnProperty('Snabbt')) {
                                    tags["Snabbt"] = true;
                                }
                            }
                        }
                        //denna är kvar att fixa till
                        //ingredients
                        if (document.querySelector('.page-content .ingredient-group li')) {
                            let ingredientgroups = document.querySelector('.page-content').getElementsByClassName('ingredient-group');
                            let ingredients = [];
                            let ingredientNames = [];
                            for (let i = 0; i < ingredientgroups.length; i++) {
                                let ingredientsDom = ingredientgroups[i].getElementsByTagName("li");
                                for (let j = 0; j < ingredientsDom.length; ++j) {
                                    let ingredient = {};
                                    ingredient.amount = ingredientsDom[j].getElementsByClassName("quantity")[0].getAttribute('data-quantity');
                                    ingredient.unit = ingredientsDom[j].getElementsByClassName("unit")[0].getAttribute('data-unit-name');
                                    if (!ingredientsDom[j].getElementsByClassName("ingredient")[0]) {
                                        return;
                                    }
                                    let namepart = ingredientsDom[j].getElementsByClassName("ingredient")[0].getElementsByTagName("span")[0].innerHTML.trim();
                                    ingredient.name = namepart.charAt(0).toUpperCase() + namepart.slice(1).replace(/\s*\([^()]*\)$/, '').split(",")[0].replace(/([/.#$])/g, '').trim();
                                    if (ingredientNames.indexOf(ingredient.name) > -1) {
                                        continue;
                                    }
                                    ingredientNames.push(ingredient.name);
                                    ingredients.push(ingredient);
                                    //måste göra om till innerHTML och ta ut det som ligger i spanet till amount 
                                    //och det andra får först trimmas och sen splitas på " " och ta ut [0] till unit

                                }
                            }
                            recipe.ingredients = ingredients;
                        }

                        if (!recipe.ingredients || recipe.ingredients.length === 0) {
                            return;
                        }

                        //difficulty
                        let instructionsList = document.querySelector('.page-content .recipe-content .steps').getElementsByTagName("li");
                        let nrOfIngredients = recipe.ingredients.length;
                        let instructionLength = 0;
                        for (let i = 0; i < instructionsList.length; i++) {
                            instructionLength = instructionLength + instructionsList[i].innerHTML.replace(/(\r\n|\n|\r|)/gm, "").trim().length;
                        }
                        instructionLength = instructionLength - instructionsList.length * 10;

                        let levelIndex = (nrOfIngredients * 8) + (instructionLength / 14);
                        if (recipe.tags.hasOwnProperty('Enkelt') || recipe.tags.hasOwnProperty('Lättlagat')) {
                            levelIndex = levelIndex - 100;
                        }
                        if (recipe.tags.hasOwnProperty('Snabbt')) {
                            levelIndex = levelIndex - 20;
                        }

                        if (levelIndex < 100) {
                            recipe.level = 1;
                        } else if (levelIndex < 200) {
                            recipe.level = 2;
                        } else {
                            recipe.level = 3;
                        }


                        return recipe;
                    })
                    .then(function (html) {
                        results.push(html);
                        return results;
                    })

            });
        }, Promise.resolve([]))
    })
    .then(function (resultArr) {
        console.log(resultArr.length);

        fs.writeFile("C:/react/" + filename, JSON.stringify(resultArr), function (err) {

            if (err) {
                return console.log(err);
            }

            console.log("The file was saved!");
        });
    });